<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0133.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<trees>
<LM id="T-wsj0133-001-p1s0">
<atree.rf>a#a-wsj0133-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj0133-001-p1s0a30">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>firma</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a36">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>3</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Allergan</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a37">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0133-001-p1s0a8">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s0W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obdržet</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>9</deepord>
<val_frame.rf>v#v41dnkA</val_frame.rf>
<children>
<LM id="T-wsj0133-001-p1s0a32">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0133-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0133-001-p1s0a9">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>souhlas</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s0W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úřad</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a13">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>13</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a14">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s0W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potravina</t_lemma>
<functor>BEN</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a15">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s0W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>léčivo</t_lemma>
<functor>BEN</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0133-001-p1s0a16">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodávat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>17</deepord>
<val_frame.rf>v#v41hblA</val_frame.rf>
<children>
<LM id="T-wsj0133-001-p1s0a35">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>15</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a34">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0133-001-p1s0a32</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0133-001-p1s0a20">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>21</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a17">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čočka</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a18">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nitrooční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a19">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>PhacoFlex</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0133-001-p1s0a21">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čočka</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a22">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>22</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a23">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ohebný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a24">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>silikonový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>24</deepord>
</LM>
<LM id="T-wsj0133-001-p1s0a25">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dostupný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>26</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a27">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s0W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>operace</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>27</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a28">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákal</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
<children>
<LM id="T-wsj0133-001-p1s0a29">
<a>
<lex.rf>a#a-wsj0133-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šedý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>28</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Allergan Inc. said it received Food and Drug Administration approval to sell the PhacoFlex intraocular lens, the first foldable silicone lens available for cataract surgery.</eng_sentence>
</LM>
<LM id="T-wsj0133-001-p1s1">
<atree.rf>a#a-wsj0133-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0133-001-p1s1a22">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>20</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj0133-001-p1s1a1">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dovolovat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41aitA</val_frame.rf>
<children>
<LM id="T-wsj0133-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ohebnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0133-001-p1s0a23</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0133-001-p1s1a3">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0133-001-p1s1a4">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čočka</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0133-001-p1s1a5">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0133-001-p1s1a4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0133-001-p1s1a8">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s1W8-Ta</LM>
<LM>a#a-wsj0133-001-p1s1W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vložit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41nnoA</val_frame.rf>
<children>
<LM id="T-wsj0133-001-p1s1a30">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0133-001-p1s1a5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0133-001-p1s1a36">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0133-001-p1s1a35">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR3</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0133-001-p1s1a10">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řez</t_lemma>
<functor>DIR2</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0133-001-p1s1a11">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>malý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0133-001-p1s1a14">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s1W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>CPR</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0133-001-p1s1a31">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0133-001-p1s1a10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0133-001-p1s1a15">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nyní</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>teď</proto_lemma>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<deepord>14</deepord>
</LM>
<LM id="T-wsj0133-001-p1s1a17">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s1W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>operace</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0133-001-p1s1a18">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákal</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj0133-001-p1s1a19">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šedý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0133-001-p1s1a20">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>možný</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0133-001-p1s1a33">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>19</deepord>
</LM>
<LM id="T-wsj0133-001-p1s1a23">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koncern</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0133-001-p1s0a34</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0133-001-p1s1a25">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s1W24-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>péče</t_lemma>
<functor>BEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj0133-001-p1s1a27">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W28-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>24</deepord>
<children>
<LM id="T-wsj0133-001-p1s1a28">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s1W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oko</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj0133-001-p1s1a29">
<a>
<lex.rf>a#a-wsj0133-001-p1s1W29-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s1W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kůže</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The len's foldability enables it to be inserted in smaller incisions than are now possible for cataract surgery, the eye care and skin care concern said.</eng_sentence>
</LM>
<LM id="T-wsj0133-001-p1s2">
<atree.rf>a#a-wsj0133-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0133-001-p1s2a1">
<a>
<lex.rf>a#a-wsj0133-001-p1s2W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0133-001-p1s2W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nazývat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41dilA</val_frame.rf>
<children>
<LM id="T-wsj0133-001-p1s2a2">
<a>
<lex.rf>a#a-wsj0133-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákal</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0133-001-p1s2a3">
<a>
<lex.rf>a#a-wsj0133-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šedý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0133-001-p1s2a5">
<a>
<lex.rf>a#a-wsj0133-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ztmavnutí</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj0133-001-p1s2a6">
<a>
<lex.rf>a#a-wsj0133-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čočka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0133-001-p1s2a7">
<a>
<lex.rf>a#a-wsj0133-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přirozený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0133-001-p1s2a8">
<a>
<lex.rf>a#a-wsj0133-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Cataracts refer to a clouding of the eye's natural lens.</eng_sentence>
</LM>
</trees>
</tdata>
