<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0069.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj0069-001-p1s0">
<atree.rf>a#a-wsj0069-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a15">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>19</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>3</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Henderson</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Michael</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0069-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a6">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skupinový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a7">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výkonný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a36">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W4-Ta-sw1-ia</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>letý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>51</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0069-001-p1s0a8">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výrobce</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a9">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a10">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>britský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>13</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a12">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kov</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a13">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>materiál</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a14">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průmyslový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0069-001-p1s0a16">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0069-001-p1s0W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>17</deepord>
<val_frame.rf>v#v41lioA</val_frame.rf>
<children>
<LM id="T-wsj0069-001-p1s0a20">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0069-001-p1s0W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>květen</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a21">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0069-001-p1s0a22">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vystřídat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>20</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0069-001-p1s0a16</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<comment>PHASE:3 TYPECHECKED; NO-INTRA-PDTB</comment>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj0069-001-p1s0a15</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41oyvB</val_frame.rf>
<children>
<LM id="T-wsj0069-001-p1s0a23">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>tak</t_lemma>
<functor>PREC</functor>
<deepord>21</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a25">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0069-001-p1s0W24-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>funkce</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a26">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Butler</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a27">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ian</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj0069-001-p1s0a29">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>26</deepord>
<children>
<LM id="T-wsj0069-001-p1s0a28">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>64</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0069-001-p1s0a30">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odcházet</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>28</deepord>
<val_frame.rf>v#v41ealC</val_frame.rf>
<children>
<LM id="T-wsj0069-001-p1s0a33">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W32-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>27</deepord>
<coref_gram.rf>
<LM>T-wsj0069-001-p1s0a26</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0069-001-p1s0a35">
<a>
<lex.rf>a#a-wsj0069-001-p1s0W35-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0069-001-p1s0W34-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>důchod</t_lemma>
<functor>DIR3</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Michael Henderson, 51-year-old group chief executive of this U.K. metals and industrial materials maker, will become chairman in May, succeeding Ian Butler, 64, who is retiring.</eng_sentence>
</LM>
<LM id="T-wsj0069-001-p1s1">
<atree.rf>a#a-wsj0069-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0069-001-p1s1a1">
<a>
<lex.rf>a#a-wsj0069-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zůstat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41sadA</val_frame.rf>
<children>
<LM id="T-wsj0069-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0069-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Butler</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0069-001-p1s0a33</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0069-001-p1s1a3">
<a>
<lex.rf>a#a-wsj0069-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>I</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0069-001-p1s1a5">
<a>
<lex.rf>a#a-wsj0069-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>člen</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj0069-001-p1s1a6">
<a>
<lex.rf>a#a-wsj0069-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představenstvo</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0069-001-p1s1a7">
<a>
<lex.rf>a#a-wsj0069-001-p1s1W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0069-001-p1s1W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>COMPL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<compl.rf>
<LM>T-wsj0069-001-p1s1a2</LM>
</compl.rf>
<children>
<LM id="T-wsj0069-001-p1s1a9">
<a>
<lex.rf>a#a-wsj0069-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výkonný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Mr. Butler will remain on the board as a nonexecutive director.</eng_sentence>
</LM>
</trees>
</tdata>
