<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0104.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<trees>
<LM id="T-wsj0104-001-p1s0">
<atree.rf>a#a-wsj0104-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0104-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0104-001-p1s0W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>identifikovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>12</deepord>
<val_frame.rf>v#v41bdgB</val_frame.rf>
<children>
<LM id="T-wsj0104-001-p1s0a21">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0104-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0104-001-p1s0W1-Ta</LM>
<LM>a#a-wsj0104-001-p1s0W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chyba</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj0104-001-p1s0a6">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ediční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0104-001-p1s0a8">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0104-001-p1s0W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vydání</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41nwsD</val_frame.rf>
<children>
<LM id="T-wsj0104-001-p1s0a9">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včerejší</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0104-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0104-001-p1s0W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>list</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0104-001-p1s0a12">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šéfredaktor</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj0104-001-p1s0a15">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0104-001-p1s0W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hallett</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0104-001-p1s0a14">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Frederick</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0104-001-p1s0a16">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>H</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0104-001-p1s0a18">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>špatně</t_lemma>
<functor>MANN</functor>
<proto_lemma>špatný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj0104-001-p1s0a19">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zkratka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj0104-001-p1s0a20">
<a>
<lex.rf>a#a-wsj0104-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>NRDC</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Due to an editing error, a letter to the editor in yesterday's edition from Frederick H. Hallett mistakenly identified the NRDC.</eng_sentence>
</LM>
<LM id="T-wsj0104-001-p1s1">
<atree.rf>a#a-wsj0104-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0104-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0104-001-p1s1W3-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0104-001-p1s1W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0104-001-p1s1a3">
<a>
<lex.rf>a#a-wsj0104-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0104-001-p1s0a19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0104-001-p1s1a9">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Idph</t_lemma>
<functor>PAT</functor>
<deepord>3</deepord>
<children>
<LM id="T-wsj0104-001-p1s1a4">
<a>
<lex.rf>a#a-wsj0104-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rada</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj0104-001-p1s1a6">
<a>
<lex.rf>a#a-wsj0104-001-p1s1W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0104-001-p1s1W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ochrana</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0104-001-p1s1a7">
<a>
<lex.rf>a#a-wsj0104-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdroj</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0104-001-p1s1a8">
<a>
<lex.rf>a#a-wsj0104-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přírodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>It should be the Natural Resources Defense Council.</eng_sentence>
</LM>
</trees>
</tdata>
