<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj2245.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj2245-001-p1s0">
<atree.rf>a#a-wsj2245-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a42">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W41-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oznámit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>37</deepord>
<val_frame.rf>v#v41fgeB</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s0a1">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>očekávat</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41dvcA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s0a2">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a63">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a4">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Allegheny</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a5">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Ludlum</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a3">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a6">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a9">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s0W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ohlásit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>12</deepord>
<val_frame.rf>v#v41eonA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s0a59">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a58">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s0a11">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s0W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a12">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetí</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a13">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a14">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čistý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a64">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W25-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>23</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a19">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>čili</t_lemma>
<functor>APPS</functor>
<is_member>1</is_member>
<deepord>19</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a17">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a16">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>34</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a15">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližně</t_lemma>
<functor>EXT</functor>
<proto_lemma>přibližný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a18">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a22">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>EXT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a21">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1.50</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>20</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a24">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s0W23-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a25">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>EXT</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>25</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s0a27">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>ACT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>24</deepord>
<coref_gram.rf>
<LM>T-wsj2245-001-p1s0a19</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2245-001-p1s0a28">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>27</deepord>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s0a60">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>26</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s0a58</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s0a67">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>28</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s0a13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s0a34">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W35-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>čili</t_lemma>
<functor>APPS</functor>
<deepord>33</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a31">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W32-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s0W29-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>ORIG</functor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>31</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a32">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>loňský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>29</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a30">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>38.4</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>30</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a33">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>32</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a37">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W37-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s0W29-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>ORIG</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>35</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a36">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W36-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1.70</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>34</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a39">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W39-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s0W38-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>36</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a43">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W43-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>investor</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>39</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a44">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W42-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>institucionální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>38</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a65">
<a>
<aux.rf>
<LM>a#a-wsj2245-001-p1s0W44-Ta</LM>
</aux.rf>
</a>
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>LOC</functor>
<deepord>40</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a47">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W45-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>New</t_lemma>
<functor>FPHR</functor>
<deepord>41</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a46">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W46-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Yorku</t_lemma>
<functor>FPHR</functor>
<deepord>42</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a66">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W51-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>46</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a48">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W50-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Simmons</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>45</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a49">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W47-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Richard</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>43</deepord>
</LM>
<LM id="T-wsj2245-001-p1s0a50">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W48-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>P</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>44</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a41">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W54-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>49</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a53">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W52-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>47</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a54">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W53-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představenstvo</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>48</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s0a55">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W56-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>51</deepord>
<children>
<LM id="T-wsj2245-001-p1s0a56">
<a>
<lex.rf>a#a-wsj2245-001-p1s0W55-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>generální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>50</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Allegheny Ludlum Corp. expects to report third-quarter net of about $34 million, or $1.50 a share, down from $38.4 million, or $1.70 a share, a year earlier, Richard P. Simmons, chairman and chief executive officer, told institutional investors in New York.</eng_sentence>
</LM>
<LM id="T-wsj2245-001-p1s1">
<atree.rf>a#a-wsj2245-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2245-001-p1s1a1">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s1a28">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s0a43</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s1a27">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s0a66</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s1a4">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s1W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klesnout</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>15</deepord>
<val_frame.rf>v#v41blkA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s1a5">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tržba</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj2245-001-p1s1a6">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>producent</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s0a60</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2245-001-p1s1a7">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj2245-001-p1s1a8">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pittsburský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2245-001-p1s1a9">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="T-wsj2245-001-p1s1a10">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ocel</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2245-001-p1s1a11">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>speciální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s1a12">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>materiál</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj2245-001-p1s1a13">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s1a15">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s1W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s0a11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2245-001-p1s1a16">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetí</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s1a19">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W20-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s1W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj2245-001-p1s1a20">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>loňský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj2245-001-p1s1a18">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>320.5</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>17</deepord>
</LM>
<LM id="T-wsj2245-001-p1s1a21">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s1a25">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s1W22-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj2245-001-p1s1a24">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>265</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj2245-001-p1s1a23">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližně</t_lemma>
<functor>EXT</functor>
<proto_lemma>přibližný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s1a26">
<a>
<lex.rf>a#a-wsj2245-001-p1s1W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Sales for the Pittsburgh-based producer of specialty steels and other materials fell to about $265 million in the third quarter from $320.5 million a year earlier, he said.</eng_sentence>
</LM>
<LM id="T-wsj2245-001-p1s2">
<atree.rf>a#a-wsj2245-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a1">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2245-001-p1s1a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_I_A</src>
<t-connectors.rf>
<LM>T-wsj2245-001-p1s2a2</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s2a43">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s1a28</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s2a42">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s1a27</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s2a2">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>též</t_lemma>
<functor>RHEM</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj2245-001-p1s2a5">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s2W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>naznačovat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41dhzA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s2a6">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odhad</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a8">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s2W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s1a15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2245-001-p1s2a9">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetí</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s2a44">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W18-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>15</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a10">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a13">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíc</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<coref_special>exoph</coref_special>
<children>
<LM id="T-wsj2245-001-p1s2a12">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s2W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>devět</t_lemma>
<functor>RSTR</functor>
<proto_lemma>devět</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s2a16">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a15">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>4.65</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj2245-001-p1s2a18">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s2W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s2a14">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W19-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>tedy</t_lemma>
<functor>CM</functor>
<deepord>16</deepord>
</LM>
<LM id="T-wsj2245-001-p1s2a45">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>zisk</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a21">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a22">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>téměř</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s2a46">
<a>
<aux.rf>
<LM>a#a-wsj2245-001-p1s2W23-Ta</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>CPR</functor>
<deepord>21</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a24">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příjem</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a26">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s2W25-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a27">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
<LM id="T-wsj2245-001-p1s2a28">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1988</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>24</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s2a30">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W32-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>činit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>26</deepord>
<val_frame.rf>v#v41noG</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s2a32">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>25</deepord>
<coref_gram.rf>
<LM>T-wsj2245-001-p1s2a24</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2245-001-p1s2a37">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W37-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>čili</t_lemma>
<functor>APPS</functor>
<deepord>30</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a34">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W34-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>28</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a33">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>108.6</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>27</deepord>
</LM>
<LM id="T-wsj2245-001-p1s2a35">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W35-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s2a39">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W39-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>EXT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>32</deepord>
<children>
<LM id="T-wsj2245-001-p1s2a38">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W38-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>4.81</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>31</deepord>
</LM>
<LM id="T-wsj2245-001-p1s2a41">
<a>
<lex.rf>a#a-wsj2245-001-p1s2W41-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s2W40-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>33</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>He said the third-quarter estimate indicates profit for the nine months of $4.65 a share, ``almost equal to the full-year 1988 earnings'' of $108.6 million, or $4.81 a share.</eng_sentence>
</LM>
<LM id="T-wsj2245-001-p1s3">
<atree.rf>a#a-wsj2245-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2245-001-p1s3a1">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s3a3">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s3W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíc</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj2245-001-p1s3a4">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2245-001-p1s3a5">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>devět</t_lemma>
<functor>RSTR</functor>
<proto_lemma>devět</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj2245-001-p1s3a6">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s2a26</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2245-001-p1s3a7">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1988</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s3a8">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj2245-001-p1s3a9">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čistý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s3a13">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W14-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>čili</t_lemma>
<functor>APPS</functor>
<deepord>12</deepord>
<children>
<LM id="T-wsj2245-001-p1s3a11">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj2245-001-p1s3a10">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>85</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj2245-001-p1s3a12">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s3a16">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2245-001-p1s3a15">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>3.76</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj2245-001-p1s3a18">
<a>
<lex.rf>a#a-wsj2245-001-p1s3W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s3W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>In the first nine months of 1988, net was $85 million, or $3.76 a share.</eng_sentence>
</LM>
<LM id="T-wsj2245-001-p1s4">
<atree.rf>a#a-wsj2245-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2245-001-p1s4a1">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s4a16">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s2a43</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s4a2">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Simmons</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s2a42</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s4a5">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s4W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odrážet</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41ehyB</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s4a6">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výsledek</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj2245-001-p1s4a8">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s4W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s2a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2245-001-p1s4a9">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetí</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s4a10">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zlepšování</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>10</deepord>
<val_frame.rf>v#v41rijA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s4a18">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s1a6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s4a11">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pokračující</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj2245-001-p1s4a12">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W13-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="T-wsj2245-001-p1s4a13">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produktivita</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj2245-001-p1s4a14">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rezerva</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2245-001-p1s4a15">
<a>
<lex.rf>a#a-wsj2245-001-p1s4W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provozní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Mr. Simmons said the third-quarter results reflect continued improvements in productivity and operating margins.</eng_sentence>
</LM>
<LM id="T-wsj2245-001-p1s5">
<atree.rf>a#a-wsj2245-001-p1s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2245-001-p1s5a1">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s5a22">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2245-001-p1s4a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2245-001-p1s5a4">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s5W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vzrůst</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41pnkA</val_frame.rf>
<children>
<LM id="T-wsj2245-001-p1s5a5">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výdaj</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj2245-001-p1s5a6">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitálový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s5a7">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj2245-001-p1s5a8">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příští</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s5a12">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s5W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj2245-001-p1s5a11">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>45</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2245-001-p1s5a10">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližně</t_lemma>
<functor>EXT</functor>
<proto_lemma>přibližný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s5a13">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s5a15">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s5W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2245-001-p1s5a16">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>35</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj2245-001-p1s5a17">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližně</t_lemma>
<functor>EXT</functor>
<proto_lemma>přibližný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2245-001-p1s5a21">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
<LM id="T-wsj2245-001-p1s5a19">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2245-001-p1s5W19-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj2245-001-p1s5a20">
<a>
<lex.rf>a#a-wsj2245-001-p1s5W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>letošní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>He said capital spending next year will rise to about $45 million from about $35 million this year.</eng_sentence>
</LM>
</trees>
</tdata>
