#!/bin/bash
set -eu -o pipefail
shopt -s extglob

target_dir=$PWD
mrp_dir=/net/work/people/zeman/mrp-data/mrp-pdtc20

dir=$(readlink -f "${0%/*}/..")
cd "$dir"

tmp=$(mktemp -d)
pdtc20="$tmp"/PDT-C-2.0
mkdir "$pdtc20"

find .  -name '*.[amtw]' \
     -o -name '*.[zwm]data' \
     -o -name '*.ogg' \
     -o -name 'pdtvallex-4.5.xml' \
    | while read file ; do
    path=${file%/*}
    if [[ ! -d $pdtc20/$path ]] ; then
        mkdir -p "$pdtc20/$path"
        mkdir -p "$pdtc20/${path/pml/treex}"
        if [[ $path != */pml/[am]* ]] ; then
            mkdir -p "$pdtc20/${path/pml/mrp}"
        fi
    fi
    cp "$file" "$pdtc20/$path"
    basename=${file##*/}
    ls "$pdtc20/$path/$basename"
    if [[ $file = *.m ]] ; then
        cp "${file%.m}".treex.gz "$pdtc20/${path/pml/treex}"
        ls "$pdtc20/${path/pml/treex}"/"${basename%.m}".treex.gz
    elif [[ $file = *.t ]] ; then
        if [[ $path = */PDT/* ]] ; then
            src="$mrp_dir"/"${path/\/pml\/tamw}"/"${basename%.t}".mrp
        else
            src="$mrp_dir"/"${path/\/pml*}"/"${basename%.t}".mrp
        fi
        cp  "$src" "$pdtc20/${path/pml/mrp}"
        ls "$pdtc20/${path/pml/mrp}"/"${basename%.t}".mrp
    fi
done

mkdir "$pdtc20/resources"
cp "$dir"/../tred-extension/pdtc10/resources/*schema.xml "$pdtc20"/resources/
ls "$pdtc20"/resources/

cp "$dir"/../publication/PDTSC-2.0/data/pdtsc_???.ogg "$pdtc20"/PDTSC/pml/
ls "$pdtc20"/PDTSC/pml/pdtsc_???.ogg

cp "$dir"/../vallex.changes "$pdtc20"/dictionaries/
ls "$pdtc20"/dictionaries/vallex.changes

cp "$dir"/../pdtsc.map "$pdtc20"/PDTSC/
ls "$pdtc20"/PDTSC/pdtsc.map

cd "$tmp"
tar -f "$target_dir"/pdtc20.tgz -cz PDT-C-2.0
rm -rf "$tmp"
