<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94202_11.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>collection</genre>
</meta>
<trees>
<LM id="t-ln94202-11-p1s1">
<atree.rf>a#a-ln94202-11-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-11-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<tfa>t</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln94202-11-p1s1w1">
<a>
<lex.rf>a#a-ln94202-11-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>krátce</t_lemma>
<functor>MANN</functor>
<proto_lemma>krátký</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s1">
<atree.rf>a#a-ln94202-11-p2s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-11-l1A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-11-p2s1w16</LM>
<LM>t-ln94202-11-p2s1w17</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-11-l2A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-11-p2s1w25</LM>
<LM>t-ln94202-11-p2s1w26</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-11-l12A">
<basic-form>osobní automobil</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-11-p2s1w4</LM>
<LM>t-ln94202-11-p2s1w5</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-11-p2s1w18">
<a>
<lex.rf>a#a-ln94202-11-p2s1w18</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>13</deepord>
<children>
<LM id="t-ln94202-11-p2s1w1">
<a>
<lex.rf>a#a-ln94202-11-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počet</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-11-p2s1w2">
<a>
<lex.rf>a#a-ln94202-11-p2s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>registrace</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94202-11-p2s1w5">
<a>
<lex.rf>a#a-ln94202-11-p2s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>automobil</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94202-11-p2s1w4">
<a>
<lex.rf>a#a-ln94202-11-p2s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osobní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94202-11-p2s1w3">
<a>
<lex.rf>a#a-ln94202-11-p2s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94202-11-p2s1w7">
<a>
<lex.rf>a#a-ln94202-11-p2s1w7</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Německo</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s1w14">
<a>
<lex.rf>a#a-ln94202-11-p2s1w14</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s1w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41kxmA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s1w10">
<a>
<lex.rf>a#a-ln94202-11-p2s1w10</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>červenec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94202-11-p2s1w13">
<a>
<lex.rf>a#a-ln94202-11-p2s1w13</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s1w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíc</t_lemma>
<functor>CPR</functor>
<subfunctor>wrt</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94202-11-p2s1w12">
<a>
<lex.rf>a#a-ln94202-11-p2s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předchozí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s1w17">
<a>
<lex.rf>a#a-ln94202-11-p2s1w17</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s1w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94202-11-p2s1w16">
<a>
<lex.rf>a#a-ln94202-11-p2s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>16.3</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s1w22">
<a>
<lex.rf>a#a-ln94202-11-p2s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94202-11-p2s1w14</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94202-11-p2s1w18</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s1w21">
<a>
<lex.rf>a#a-ln94202-11-p2s1w21</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s1w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>srovnání</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41lgnA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s1a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln94202-11-p2s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln94202-11-p2s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>EFF</functor>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln94202-11-p2s1w20">
<a>
<lex.rf>a#a-ln94202-11-p2s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>meziroční</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s1w23">
<a>
<lex.rf>a#a-ln94202-11-p2s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nízký</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>comp</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>20</deepord>
<children>
<LM id="t-ln94202-11-p2s1w26">
<a>
<lex.rf>a#a-ln94202-11-p2s1w26</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s1w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>21</deepord>
<children>
<LM id="t-ln94202-11-p2s1w25">
<a>
<lex.rf>a#a-ln94202-11-p2s1w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>4.9</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s2">
<atree.rf>a#a-ln94202-11-p2s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-11-p2s2w10">
<a>
<lex.rf>a#a-ln94202-11-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>činit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41noG</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s2w2">
<a>
<lex.rf>a#a-ln94202-11-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počet</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94202-11-p2s2w1">
<a>
<lex.rf>a#a-ln94202-11-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celkový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94202-11-p2s2w3">
<a>
<lex.rf>a#a-ln94202-11-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>registrace</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94202-11-p2s2w6">
<a>
<lex.rf>a#a-ln94202-11-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vozidlo</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94202-11-p2s2w5">
<a>
<lex.rf>a#a-ln94202-11-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94202-11-p2s2w4">
<a>
<lex.rf>a#a-ln94202-11-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s2w9">
<a>
<lex.rf>a#a-ln94202-11-p2s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s2w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíc</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s1w10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p2s2w8">
<a>
<lex.rf>a#a-ln94202-11-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s2w11">
<a>
<lex.rf>a#a-ln94202-11-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>299147</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s3">
<atree.rf>a#a-ln94202-11-p2s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-11-l3A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-11-p2s3w11</LM>
<LM>t-ln94202-11-p2s3w12</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-11-l4A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-11-p2s3w16</LM>
<LM>t-ln94202-11-p2s3w17</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-11-l13A">
<basic-form>osobní automobil</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-11-p2s3w6</LM>
<LM>t-ln94202-11-p2s3w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-11-p2s3w13">
<a>
<lex.rf>a#a-ln94202-11-p2s3w13</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-11-p2s3w4">
<a>
<lex.rf>a#a-ln94202-11-p2s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počet</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p2s3w5">
<a>
<lex.rf>a#a-ln94202-11-p2s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>registrace</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94202-11-p2s3w7">
<a>
<lex.rf>a#a-ln94202-11-p2s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>automobil</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p2s3w6">
<a>
<lex.rf>a#a-ln94202-11-p2s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osobní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s3w2">
<a>
<lex.rf>a#a-ln94202-11-p2s3w2</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s3w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>červen</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s1w13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-11-p2s3w8">
<a>
<lex.rf>a#a-ln94202-11-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41kxmA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s3w9">
<a>
<lex.rf>a#a-ln94202-11-p2s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíčně</t_lemma>
<functor>REG</functor>
<proto_lemma>měsíční</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94202-11-p2s3w12">
<a>
<lex.rf>a#a-ln94202-11-p2s3w12</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s3w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94202-11-p2s3w11">
<a>
<lex.rf>a#a-ln94202-11-p2s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jeden</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s3a0">
<a>
<lex.rf>a#a-ln94202-11-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>snížit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94202-11-p2s3w8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94202-11-p2s3w13</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41kxmA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s3w14">
<a>
<lex.rf>a#a-ln94202-11-p2s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>meziročně</t_lemma>
<functor>REG</functor>
<proto_lemma>meziroční</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln94202-11-p2s3w17">
<a>
<lex.rf>a#a-ln94202-11-p2s3w17</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s3w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94202-11-p2s3w16">
<a>
<lex.rf>a#a-ln94202-11-p2s3w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>5.5</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s4">
<atree.rf>a#a-ln94202-11-p2s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-11-l5A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-11-p2s4w18</LM>
<LM>t-ln94202-11-p2s4w19</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-11-p2s4w7">
<a>
<lex.rf>a#a-ln94202-11-p2s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosáhnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41afbA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s4w4">
<a>
<lex.rf>a#a-ln94202-11-p2s4w4</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s4w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíc</t_lemma>
<functor>TPAR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94202-11-p2s4w6">
<a>
<lex.rf>a#a-ln94202-11-p2s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_special>exoph</coref_special>
<children>
<LM id="t-ln94202-11-p2s4w5">
<a>
<lex.rf>a#a-ln94202-11-p2s4w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s4w2">
<a>
<lex.rf>a#a-ln94202-11-p2s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94202-11-p2s4w3">
<a>
<lex.rf>a#a-ln94202-11-p2s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sedm</t_lemma>
<functor>RSTR</functor>
<proto_lemma>sedm</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s4w8">
<a>
<lex.rf>a#a-ln94202-11-p2s4w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>registrace</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s1w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p2s4w11">
<a>
<lex.rf>a#a-ln94202-11-p2s4w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vůz</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s3w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p2s4w9">
<a>
<lex.rf>a#a-ln94202-11-p2s4w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94202-11-p2s4w10">
<a>
<lex.rf>a#a-ln94202-11-p2s4w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osobní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s4w14">
<a>
<lex.rf>a#a-ln94202-11-p2s4w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>13</deepord>
<children>
<LM id="t-ln94202-11-p2s4w12">
<a>
<lex.rf>a#a-ln94202-11-p2s4w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počet</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94202-11-p2s4w13">
<a>
<lex.rf>a#a-ln94202-11-p2s4w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2017474</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s4w16">
<a>
<lex.rf>a#a-ln94202-11-p2s4w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s4w15">
<a>
<lex.rf>a#a-ln94202-11-p2s4w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>ACT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_gram.rf>
<LM>t-ln94202-11-p2s4w12</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-11-p2s4w20">
<a>
<lex.rf>a#a-ln94202-11-p2s4w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln94202-11-p2s4w19">
<a>
<lex.rf>a#a-ln94202-11-p2s4w19</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s4w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln94202-11-p2s4w18">
<a>
<lex.rf>a#a-ln94202-11-p2s4w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>0.1</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s4a0">
<a>
<lex.rf>a#a-ln94202-11-p2s4w16</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s4w21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>být</t_lemma>
<functor>CPR</functor>
<proto_lemma>být</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>21</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s4a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s4w15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-11-p2s4a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Some</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-ln94202-11-p2s4w25">
<a>
<lex.rf>a#a-ln94202-11-p2s4w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>22</deepord>
</LM>
<LM id="t-ln94202-11-p2s4w24">
<a>
<lex.rf>a#a-ln94202-11-p2s4w24</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s4w22</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>období</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>23</deepord>
<children>
<LM id="t-ln94202-11-p2s4w23">
<a>
<lex.rf>a#a-ln94202-11-p2s4w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s5">
<atree.rf>a#a-ln94202-11-p2s5</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-11-l6A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-11-p2s5w9</LM>
<LM>t-ln94202-11-p2s5w10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-11-p2s5w7">
<a>
<lex.rf>a#a-ln94202-11-p2s5w7</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s5w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94202-11-p2s4w7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>confr</discourse_type>
<sense_PDTB3>Comparison.Contrast</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94202-11-p2s5w6</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41kxmA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p2s5w6">
<a>
<lex.rf>a#a-ln94202-11-p2s5w6</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>však</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94202-11-p2s5w1">
<a>
<lex.rf>a#a-ln94202-11-p2s5w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počet</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s2w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p2s5w2">
<a>
<lex.rf>a#a-ln94202-11-p2s5w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>registrace</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s2w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p2s5w4">
<a>
<lex.rf>a#a-ln94202-11-p2s5w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vozidlo</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p2s2w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p2s5w3">
<a>
<lex.rf>a#a-ln94202-11-p2s5w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s5w10">
<a>
<lex.rf>a#a-ln94202-11-p2s5w10</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s5w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-11-p2s5w9">
<a>
<lex.rf>a#a-ln94202-11-p2s5w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>0.3</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p2s5w13">
<a>
<lex.rf>a#a-ln94202-11-p2s5w13</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p2s5w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kus</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94202-11-p2s5w12">
<a>
<lex.rf>a#a-ln94202-11-p2s5w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2355628</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s1">
<atree.rf>a#a-ln94202-11-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-11-l7A">
<basic-form>Harley-Davidson</basic-form>
<type>object</type>
<tnode.rfs>
<LM>t-ln94202-11-p3s1w5</LM>
<LM>t-ln94202-11-p3s1w6</LM>
<LM>t-ln94202-11-p3s1w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-11-p3s1w13">
<a>
<lex.rf>a#a-ln94202-11-p3s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41chlO</val_frame.rf>
<children>
<LM id="t-ln94202-11-p3s1w1">
<a>
<lex.rf>a#a-ln94202-11-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sraz</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-11-p3s1w2">
<a>
<lex.rf>a#a-ln94202-11-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milovník</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94202-11-p3s1w4">
<a>
<lex.rf>a#a-ln94202-11-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>motocykl</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94202-11-p3s1a3">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94202-11-p3s1w5">
<a>
<lex.rf>a#a-ln94202-11-p3s1w5</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Harley</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="t-ln94202-11-p3s1w6">
<a>
<lex.rf>a#a-ln94202-11-p3s1w6</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>-</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="t-ln94202-11-p3s1w7">
<a>
<lex.rf>a#a-ln94202-11-p3s1w7</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Davidson</t_lemma>
<functor>FPHR</functor>
<is_name_of_person>1</is_name_of_person>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s1w3">
<a>
<lex.rf>a#a-ln94202-11-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>legendární</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s1w9">
<a>
<lex.rf>a#a-ln94202-11-p3s1w9</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s1w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Cunlhat</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94202-11-p3s1w12">
<a>
<lex.rf>a#a-ln94202-11-p3s1w12</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Francie</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-11-p3s1w9</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
<children>
<LM id="t-ln94202-11-p3s1w11">
<a>
<lex.rf>a#a-ln94202-11-p3s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s1w16">
<a>
<lex.rf>a#a-ln94202-11-p3s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>účast</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94202-11-p3s1w15">
<a>
<lex.rf>a#a-ln94202-11-p3s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vysoký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>comp</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln94202-11-p3s1w14">
<a>
<lex.rf>a#a-ln94202-11-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podstatně</t_lemma>
<functor>EXT</functor>
<proto_lemma>podstatný</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln94202-11-p3s1a0">
<a>
<lex.rf>a#a-ln94202-11-p3s1w13</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s1w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>mít</t_lemma>
<functor>CPR</functor>
<proto_lemma>mít</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41chlO</val_frame.rf>
<children>
<LM id="t-ln94202-11-p3s1a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p3s1w16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-11-p3s1w19">
<a>
<lex.rf>a#a-ln94202-11-p3s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>setkání</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-11-p3s1w1</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<val_frame.rf>v#v41klfA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p3s1a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>18</deepord>
<coref_gram.rf>
<LM>t-ln94202-11-p3s1w20</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-11-p3s1w18">
<a>
<lex.rf>a#a-ln94202-11-p3s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dávný</t_lemma>
<functor>TWHEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-ln94202-11-p3s1w20">
<a>
<lex.rf>a#a-ln94202-11-p3s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>majitel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<children>
<LM id="t-ln94202-11-p3s1w21">
<a>
<lex.rf>a#a-ln94202-11-p3s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stroj</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>23</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p3s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p3s1w23">
<a>
<lex.rf>a#a-ln94202-11-p3s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>značka</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>22</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p3s1a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p3s1w22">
<a>
<lex.rf>a#a-ln94202-11-p3s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s1w25">
<a>
<lex.rf>a#a-ln94202-11-p3s1w25</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s1w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s2">
<atree.rf>a#a-ln94202-11-p3s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-11-p3s2w3">
<a>
<lex.rf>a#a-ln94202-11-p3s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>navštívit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41dhlB</val_frame.rf>
<children>
<LM id="t-ln94202-11-p3s2w2">
<a>
<lex.rf>a#a-ln94202-11-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ročník</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p3s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p3s2w1">
<a>
<lex.rf>a#a-ln94202-11-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sedmý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>sedm</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s2w7">
<a>
<lex.rf>a#a-ln94202-11-p3s2w7</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-11-p3s2w6">
<a>
<lex.rf>a#a-ln94202-11-p3s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>motocyklista</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94202-11-p3s2w5">
<a>
<lex.rf>a#a-ln94202-11-p3s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>20000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94202-11-p3s2w4">
<a>
<lex.rf>a#a-ln94202-11-p3s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>téměř</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s2w11">
<a>
<lex.rf>a#a-ln94202-11-p3s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návštěvník</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94202-11-p3s2w10">
<a>
<lex.rf>a#a-ln94202-11-p3s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94202-11-p3s2w9">
<a>
<lex.rf>a#a-ln94202-11-p3s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>30000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-11-p3s2w8">
<a>
<lex.rf>a#a-ln94202-11-p3s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>asi</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s3">
<atree.rf>a#a-ln94202-11-p3s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-11-l8A">
<basic-form>Free Wheels</basic-form>
<type>object</type>
<tnode.rfs>
<LM>t-ln94202-11-p3s3w3</LM>
<LM>t-ln94202-11-p3s3w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-11-p3s3w5">
<a>
<lex.rf>a#a-ln94202-11-p3s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pobavit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41fojA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p3s3w1">
<a>
<lex.rf>a#a-ln94202-11-p3s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>účastník</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-11-p3s2w6</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>t-ln94202-11-p3s2w11</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln94202-11-p3s3w2">
<a>
<lex.rf>a#a-ln94202-11-p3s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akce</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p3s2w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p3s3a0">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94202-11-p3s3w3">
<a>
<lex.rf>a#a-ln94202-11-p3s3w3</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Free</t_lemma>
<functor>FPHR</functor>
<deepord>2</deepord>
</LM>
<LM id="t-ln94202-11-p3s3w4">
<a>
<lex.rf>a#a-ln94202-11-p3s3w4</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Wheels</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s3w9">
<a>
<lex.rf>a#a-ln94202-11-p3s3w9</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-11-p3s3w8">
<a>
<lex.rf>a#a-ln94202-11-p3s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koncert</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-11-p3s3w7">
<a>
<lex.rf>a#a-ln94202-11-p3s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rockový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln94202-11-p3s3w6">
<a>
<lex.rf>a#a-ln94202-11-p3s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s3w11">
<a>
<lex.rf>a#a-ln94202-11-p3s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soutěž</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94202-11-p3s3w10">
<a>
<lex.rf>a#a-ln94202-11-p3s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>motocyklový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln94202-11-p3s3w15">
<a>
<lex.rf>a#a-ln94202-11-p3s3w15</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>15</deepord>
<children>
<LM id="t-ln94202-11-p3s3w14">
<a>
<lex.rf>a#a-ln94202-11-p3s3w14</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s3w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jízda</t_lemma>
<functor>REG</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94202-11-p3s3w13">
<a>
<lex.rf>a#a-ln94202-11-p3s3w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pomalý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s3w16">
<a>
<lex.rf>a#a-ln94202-11-p3s3w16</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s3w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zručnost</t_lemma>
<functor>REG</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s4">
<atree.rf>a#a-ln94202-11-p3s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-11-p3s4w13">
<a>
<lex.rf>a#a-ln94202-11-p3s4w13</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s4w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvyknout_si</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41sdcA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p3s4w1">
<a>
<lex.rf>a#a-ln94202-11-p3s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obyvatel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-11-p3s4w3">
<a>
<lex.rf>a#a-ln94202-11-p3s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obec</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p3s1w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-11-p3s4w4">
<a>
<lex.rf>a#a-ln94202-11-p3s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Cunlhat</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94202-11-p3s4w7">
<a>
<lex.rf>a#a-ln94202-11-p3s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obyvatel</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94202-11-p3s4w6">
<a>
<lex.rf>a#a-ln94202-11-p3s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1500</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s4w2">
<a>
<lex.rf>a#a-ln94202-11-p3s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>malý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s4w12">
<a>
<lex.rf>a#a-ln94202-11-p3s4w12</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s4w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úřad</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-11-p3s4w11">
<a>
<lex.rf>a#a-ln94202-11-p3s4w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>místní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s4w16">
<a>
<lex.rf>a#a-ln94202-11-p3s4w16</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p3s4w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nájezd</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-11-p3s3w2</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln94202-11-p3s4w15">
<a>
<lex.rf>a#a-ln94202-11-p3s4w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>srpnový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94202-11-p3s4w24">
<a>
<lex.rf>a#a-ln94202-11-p3s4w24</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>19</deepord>
<children>
<LM id="t-ln94202-11-p3s4w18">
<a>
<lex.rf>a#a-ln94202-11-p3s4w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_gram.rf>
<LM>t-ln94202-11-p3s4w16</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-11-p3s4w20">
<a>
<lex.rf>a#a-ln94202-11-p3s4w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyvolat</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41phdC</val_frame.rf>
<children>
<LM id="t-ln94202-11-p3s4w19">
<a>
<lex.rf>a#a-ln94202-11-p3s4w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosud</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln94202-11-p3s4a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln94202-11-p3s4w23">
<a>
<lex.rf>a#a-ln94202-11-p3s4w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>incident</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln94202-11-p3s4w22">
<a>
<lex.rf>a#a-ln94202-11-p3s4w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vážný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-ln94202-11-p3s4w21">
<a>
<lex.rf>a#a-ln94202-11-p3s4w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žádný</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>negat</indeftype>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p3s4w26">
<a>
<lex.rf>a#a-ln94202-11-p3s4w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přinést</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94202-11-p3s4w20</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>grad</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94202-11-p3s4w25</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41iunA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p3s4w25">
<a>
<lex.rf>a#a-ln94202-11-p3s4w25</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>zato</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-ln94202-11-p3s4w27">
<a>
<lex.rf>a#a-ln94202-11-p3s4w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obec</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>21</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p3s4w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-11-p3s4w29">
<a>
<lex.rf>a#a-ln94202-11-p3s4w29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>peníze</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<children>
<LM id="t-ln94202-11-p3s4w28">
<a>
<lex.rf>a#a-ln94202-11-p3s4w28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>pos</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p4s1">
<atree.rf>a#a-ln94202-11-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-11-l11A">
<basic-form>Mercedes-Benz O 404</basic-form>
<type>object</type>
<tnode.rfs>
<LM>t-ln94202-11-p4s1w13</LM>
<LM>t-ln94202-11-p4s1w14</LM>
<LM>t-ln94202-11-p4s1w15</LM>
<LM>t-ln94202-11-p4s1w16</LM>
<LM>t-ln94202-11-p4s1w17</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-11-l14A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-11-p4s1w3</LM>
<LM>t-ln94202-11-p4s1w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-11-p4s1w6">
<a>
<lex.rf>a#a-ln94202-11-p4s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaplatit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41qfcB</val_frame.rf>
<children>
<LM id="t-ln94202-11-p4s1w1">
<a>
<lex.rf>a#a-ln94202-11-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-11-p4s1w4">
<a>
<lex.rf>a#a-ln94202-11-p4s1w4</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p4s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>CPR</functor>
<subfunctor>than</subfunctor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94202-11-p4s1w5">
<a>
<lex.rf>a#a-ln94202-11-p4s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>marka</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94202-11-p4s1w3">
<a>
<lex.rf>a#a-ln94202-11-p4s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>padesát</t_lemma>
<functor>RSTR</functor>
<proto_lemma>padesát</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p4s1w9">
<a>
<lex.rf>a#a-ln94202-11-p4s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94202-11-p4s1w8">
<a>
<lex.rf>a#a-ln94202-11-p4s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dopravní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94202-11-p4s1w7">
<a>
<lex.rf>a#a-ln94202-11-p4s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>saúdskoarabský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p4s1w11">
<a>
<lex.rf>a#a-ln94202-11-p4s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p4s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stovka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94202-11-p4s1w12">
<a>
<lex.rf>a#a-ln94202-11-p4s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>autobus</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-11-p4s1a0">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94202-11-p4s1w13">
<a>
<lex.rf>a#a-ln94202-11-p4s1w13</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Mercedes</t_lemma>
<functor>FPHR</functor>
<deepord>12</deepord>
</LM>
<LM id="t-ln94202-11-p4s1w14">
<a>
<lex.rf>a#a-ln94202-11-p4s1w14</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>-</t_lemma>
<functor>FPHR</functor>
<deepord>13</deepord>
</LM>
<LM id="t-ln94202-11-p4s1w15">
<a>
<lex.rf>a#a-ln94202-11-p4s1w15</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Benz</t_lemma>
<functor>FPHR</functor>
<deepord>14</deepord>
</LM>
<LM id="t-ln94202-11-p4s1w16">
<a>
<lex.rf>a#a-ln94202-11-p4s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>O</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>nr</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln94202-11-p4s1w17">
<a>
<lex.rf>a#a-ln94202-11-p4s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>404</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p4s2">
<atree.rf>a#a-ln94202-11-p4s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-11-p4s2w1">
<a>
<lex.rf>a#a-ln94202-11-p4s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94202-11-p4s1w6</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>restr</discourse_type>
<sense_PDTB3>Expansion.Exception.Arg2-as-excpt</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94202-11-p4s2w3</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94202-11-p4s2w3">
<a>
<lex.rf>a#a-ln94202-11-p4s2w3</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>ovšem</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94202-11-p4s2w2">
<a>
<lex.rf>a#a-ln94202-11-p4s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p4s1w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-11-p4s2w4">
<a>
<lex.rf>a#a-ln94202-11-p4s2w4</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>jen</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94202-11-p4s2w5">
<a>
<lex.rf>a#a-ln94202-11-p4s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetina</t_lemma>
<functor>PAT</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>frac</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94202-11-p4s2w7">
<a>
<lex.rf>a#a-ln94202-11-p4s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>objednávka</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94202-11-p4s2w6">
<a>
<lex.rf>a#a-ln94202-11-p4s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celkový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94202-11-p4s2w13">
<a>
<lex.rf>a#a-ln94202-11-p4s2w13</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p4s2w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodnout</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>deagent</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41jqhD</val_frame.rf>
<children>
<LM id="t-ln94202-11-p4s2w11">
<a>
<lex.rf>a#a-ln94202-11-p4s2w11</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p4s2w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>realizace</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94202-11-p4s2w10">
<a>
<lex.rf>a#a-ln94202-11-p4s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_gram.rf>
<LM>t-ln94202-11-p4s2w7</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p4s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln94202-11-p4s2w16">
<a>
<lex.rf>a#a-ln94202-11-p4s2w16</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p4s2w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provoz</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94202-11-p4s2w15">
<a>
<lex.rf>a#a-ln94202-11-p4s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zkušební</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-11-p4s3">
<atree.rf>a#a-ln94202-11-p4s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-11-p4s3w3">
<a>
<lex.rf>a#a-ln94202-11-p4s3w3</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p4s3w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vydržet</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>deb</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41nybA</val_frame.rf>
<children>
<LM id="t-ln94202-11-p4s3w1">
<a>
<lex.rf>a#a-ln94202-11-p4s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vůz</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-11-p4s1w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-11-p4s3w4">
<a>
<lex.rf>a#a-ln94202-11-p4s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>teplota</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94202-11-p4s3w7">
<a>
<lex.rf>a#a-ln94202-11-p4s3w7</lex.rf>
<aux.rf>
<LM>a#a-ln94202-11-p4s3w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stupeň</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94202-11-p4s3w6">
<a>
<lex.rf>a#a-ln94202-11-p4s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>50</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
