<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94202_84.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln94202-84-p1s1">
<atree.rf>a#a-ln94202-84-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-84-p1s1w2">
<a>
<lex.rf>a#a-ln94202-84-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>studna</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln94202-84-p1s1w1">
<a>
<lex.rf>a#a-ln94202-84-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bezpečný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s1">
<atree.rf>a#a-ln94202-84-p2s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-84-p2s1w6">
<a>
<lex.rf>a#a-ln94202-84-p2s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>začínat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41pqyA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s1w3">
<a>
<lex.rf>a#a-ln94202-84-p2s1w3</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s1w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_special>exoph</coref_special>
<children>
<LM id="t-ln94202-84-p2s1w2">
<a>
<lex.rf>a#a-ln94202-84-p2s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s1w4">
<a>
<lex.rf>a#a-ln94202-84-p2s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>člověk</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94202-84-p2s1w5">
<a>
<lex.rf>a#a-ln94202-84-p2s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znovu</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94202-84-p2s1w9">
<a>
<lex.rf>a#a-ln94202-84-p2s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>využívat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41pfnA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_gram.rf>
<LM>t-ln94202-84-p2s1w4</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-84-p2s1w7">
<a>
<lex.rf>a#a-ln94202-84-p2s1w7</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>stále</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln94202-84-p2s1w8">
<a>
<lex.rf>a#a-ln94202-84-p2s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94202-84-p2s1w10">
<a>
<lex.rf>a#a-ln94202-84-p2s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>voda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-84-p2s1w11">
<a>
<lex.rf>a#a-ln94202-84-p2s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čerpaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94202-84-p2s1w13">
<a>
<lex.rf>a#a-ln94202-84-p2s1w13</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s1w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>studna</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p1s1w2</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s2">
<atree.rf>a#a-ln94202-84-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-84-l2A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-84-p2s2w5</LM>
<LM>t-ln94202-84-p2s2w6</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-84-l3A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-84-p2s2w13</LM>
<LM>t-ln94202-84-p2s2w14</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-84-p2s2w4">
<a>
<lex.rf>a#a-ln94202-84-p2s2w4</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s2w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zásobovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41qlqA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s2w1">
<a>
<lex.rf>a#a-ln94202-84-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nyní</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>teď</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94202-84-p2s2w3">
<a>
<lex.rf>a#a-ln94202-84-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>takto</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p2s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-84-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94202-84-p2s2w9">
<a>
<lex.rf>a#a-ln94202-84-p2s2w9</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>9</deepord>
<children>
<LM id="t-ln94202-84-p2s2w6">
<a>
<lex.rf>a#a-ln94202-84-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>ADDR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94202-84-p2s2w5">
<a>
<lex.rf>a#a-ln94202-84-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1.7</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94202-84-p2s2w7">
<a>
<lex.rf>a#a-ln94202-84-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obyvatel</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94202-84-p2s2w8">
<a>
<lex.rf>a#a-ln94202-84-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČR</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s2w11">
<a>
<lex.rf>a#a-ln94202-84-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s2w10">
<a>
<lex.rf>a#a-ln94202-84-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>ACT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_gram.rf>
<LM>t-ln94202-84-p2s2w6</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-84-p2s2w14">
<a>
<lex.rf>a#a-ln94202-84-p2s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94202-84-p2s2w13">
<a>
<lex.rf>a#a-ln94202-84-p2s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>17</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94202-84-p2s2w12">
<a>
<lex.rf>a#a-ln94202-84-p2s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>téměř</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s3">
<atree.rf>a#a-ln94202-84-p2s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-84-p2s3w9">
<a>
<lex.rf>a#a-ln94202-84-p2s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyhovovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94202-84-p2s2w4</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94202-84-p2s3w5</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41oapA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s3w5">
<a>
<lex.rf>a#a-ln94202-84-p2s3w5</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>však</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94202-84-p2s3w4">
<a>
<lex.rf>a#a-ln94202-84-p2s3w4</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s3w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>případ</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>4</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-84-p2s2w3</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln94202-84-p2s3w3">
<a>
<lex.rf>a#a-ln94202-84-p2s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94202-84-p2s3w1">
<a>
<lex.rf>a#a-ln94202-84-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>téměř</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s3w6">
<a>
<lex.rf>a#a-ln94202-84-p2s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>voda</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p2s1w10</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-84-p2s3w8">
<a>
<lex.rf>a#a-ln94202-84-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s3w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>studna</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s3a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94202-84-p2s3w10">
<a>
<lex.rf>a#a-ln94202-84-p2s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hygienicky</t_lemma>
<functor>REG</functor>
<proto_lemma>hygienický</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94202-84-p2s3w12">
<a>
<lex.rf>a#a-ln94202-84-p2s3w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kritérium</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-84-p2s3w11">
<a>
<lex.rf>a#a-ln94202-84-p2s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>závažný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>sup</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s4">
<atree.rf>a#a-ln94202-84-p2s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-84-p2s4w5">
<a>
<lex.rf>a#a-ln94202-84-p2s4w5</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="t-ln94202-84-p2s4w3">
<a>
<lex.rf>a#a-ln94202-84-p2s4w3</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s4w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znečistit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41rnjA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s4w1">
<a>
<lex.rf>a#a-ln94202-84-p2s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>často</t_lemma>
<functor>THO</functor>
<gram>
<sempos>adv.denot.grad.neg</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-84-p2s3w4</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94202-84-p2s4a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p2s3w6</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-84-p2s4w4">
<a>
<lex.rf>a#a-ln94202-84-p2s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bakterie</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s4w6">
<a>
<lex.rf>a#a-ln94202-84-p2s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obsahovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41dsuA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s4a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p2s4a0</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-84-p2s4w8">
<a>
<lex.rf>a#a-ln94202-84-p2s4w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>množství</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94202-84-p2s4w7">
<a>
<lex.rf>a#a-ln94202-84-p2s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94202-84-p2s4w10">
<a>
<lex.rf>a#a-ln94202-84-p2s4w10</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>i</t_lemma>
<functor>CONJ</functor>
<deepord>11</deepord>
<children>
<LM id="t-ln94202-84-p2s4w9">
<a>
<lex.rf>a#a-ln94202-84-p2s4w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>radon</t_lemma>
<functor>MAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln94202-84-p2s4w11">
<a>
<lex.rf>a#a-ln94202-84-p2s4w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dusičnan</t_lemma>
<functor>MAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s5">
<atree.rf>a#a-ln94202-84-p2s5</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-84-l1A">
<basic-form>mimo jiné</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-84-p2s5w4</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-84-l4A">
<basic-form>ministerstvo zemědělství</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-84-p2s5w9</LM>
<LM>t-ln94202-84-p2s5w10</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-84-l5A">
<basic-form>ministerstvo zdravotnictví</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-84-p2s5w13</LM>
<LM>t-ln94202-84-p2s5w14</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-84-l6A">
<type>location</type>
<tnode.rfs>
<LM>t-ln94202-84-p2s5w17</LM>
<LM>t-ln94202-84-p2s5w19</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-84-p2s5w1">
<a>
<lex.rf>a#a-ln94202-84-p2s5w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potvrdit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41grtA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s5w2">
<a>
<lex.rf>a#a-ln94202-84-p2s5w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>PAT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p2s4w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-84-p2s5w4">
<a>
<lex.rf>a#a-ln94202-84-p2s5w4</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s5w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jiný</t_lemma>
<functor>RESTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94202-84-p2s5w5">
<a>
<lex.rf>a#a-ln94202-84-p2s5w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průzkum</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94202-84-p2s5w8">
<a>
<lex.rf>a#a-ln94202-84-p2s5w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uskutečnit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41mvpA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s5w7">
<a>
<lex.rf>a#a-ln94202-84-p2s5w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-ln94202-84-p2s5w5</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-84-p2s5w13">
<a>
<lex.rf>a#a-ln94202-84-p2s5w13</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s5w12</LM>
<LM>a#a-ln94202-84-p2s5w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-84-p2s5w14">
<a>
<lex.rf>a#a-ln94202-84-p2s5w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdravotnictví</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s5w9">
<a>
<lex.rf>a#a-ln94202-84-p2s5w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94202-84-p2s5w10">
<a>
<lex.rf>a#a-ln94202-84-p2s5w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zemědělství</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s5w16">
<a>
<lex.rf>a#a-ln94202-84-p2s5w16</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p2s5w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>okres</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94202-84-p2s5w17">
<a>
<lex.rf>a#a-ln94202-84-p2s5w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Plzeň</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94202-84-p2s5w19">
<a>
<lex.rf>a#a-ln94202-84-p2s5w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jih</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p2s6">
<atree.rf>a#a-ln94202-84-p2s6</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-84-l7A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-84-p2s6w4</LM>
<LM>t-ln94202-84-p2s6w5</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-84-p2s6w3">
<a>
<lex.rf>a#a-ln94202-84-p2s6w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odpovídat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41egyF</val_frame.rf>
<children>
<LM id="t-ln94202-84-p2s6w1">
<a>
<lex.rf>a#a-ln94202-84-p2s6w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>norma</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-84-p2s3w12</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94202-84-p2s6w2">
<a>
<lex.rf>a#a-ln94202-84-p2s6w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tu</t_lemma>
<functor>LOC</functor>
<proto_lemma>tady</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p2s5w16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-84-p2s6a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94202-84-p2s6w5">
<a>
<lex.rf>a#a-ln94202-84-p2s6w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94202-84-p2s6w4">
<a>
<lex.rf>a#a-ln94202-84-p2s6w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>97.6</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94202-84-p2s6w7">
<a>
<lex.rf>a#a-ln94202-84-p2s6w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vzorek</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-84-p2s6w6">
<a>
<lex.rf>a#a-ln94202-84-p2s6w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odebraný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p3s1">
<atree.rf>a#a-ln94202-84-p3s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-84-p3s1w18">
<a>
<lex.rf>a#a-ln94202-84-p3s1w18</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s1w14</LM>
<LM>a#a-ln94202-84-p3s1w15</LM>
<LM>a#a-ln94202-84-p3s1w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ověřit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41feqA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p3s1w1">
<a>
<lex.rf>a#a-ln94202-84-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>voda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p2s4a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-84-p3s1w4">
<a>
<lex.rf>a#a-ln94202-84-p3s1w4</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdroj</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p2s3w8</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94202-84-p3s1w3">
<a>
<lex.rf>a#a-ln94202-84-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94202-84-p3s1w11">
<a>
<lex.rf>a#a-ln94202-84-p3s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s1w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>používat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41gtdA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p3s1w6">
<a>
<lex.rf>a#a-ln94202-84-p3s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_gram.rf>
<LM>t-ln94202-84-p3s1w4</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-84-p3s1a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94202-84-p3s1w10">
<a>
<lex.rf>a#a-ln94202-84-p3s1w10</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s1w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doba</t_lemma>
<functor>TFHL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94202-84-p3s1w9">
<a>
<lex.rf>a#a-ln94202-84-p3s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dlouhý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p3s1a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p3s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln94202-84-p3s1w16">
<a>
<lex.rf>a#a-ln94202-84-p3s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>brzy</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.grad.nneg</sempos>
<degcmp>sup</degcmp>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94202-84-p3s1w17">
<a>
<lex.rf>a#a-ln94202-84-p3s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laboratorně</t_lemma>
<functor>MANN</functor>
<proto_lemma>laboratorní</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p3s2">
<atree.rf>a#a-ln94202-84-p3s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-84-l8A">
<basic-form>hygienická stanice</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-84-p3s2w8</LM>
<LM>t-ln94202-84-p3s2w9</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-84-l8B">
<basic-form>laboratorní vyšetření</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-84-p3s2w4</LM>
<LM>t-ln94202-84-p3s2w5</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-84-p3s2w6">
<a>
<lex.rf>a#a-ln94202-84-p3s2w6</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>objednat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41dpjA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p3s2w1">
<a>
<lex.rf>a#a-ln94202-84-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>občan</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94202-84-p3s2w5">
<a>
<lex.rf>a#a-ln94202-84-p3s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyšetření</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p3s1w18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41pakA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p3s2w4">
<a>
<lex.rf>a#a-ln94202-84-p3s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laboratorní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94202-84-p3s2a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94202-84-p3s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p3s2w2">
<a>
<lex.rf>a#a-ln94202-84-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>BEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_gram.rf>
<LM>t-ln94202-84-p3s2w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-84-p3s2w14">
<a>
<lex.rf>a#a-ln94202-84-p3s2w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>i</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln94202-84-p3s2w9">
<a>
<lex.rf>a#a-ln94202-84-p3s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s2w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stanice</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94202-84-p3s2w8">
<a>
<lex.rf>a#a-ln94202-84-p3s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hygienický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p3s2w12">
<a>
<lex.rf>a#a-ln94202-84-p3s2w12</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s2w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laboratoř</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-84-p3s2w13">
<a>
<lex.rf>a#a-ln94202-84-p3s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vodárna</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p3s2w17">
<a>
<lex.rf>a#a-ln94202-84-p3s2w17</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s2w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laboratoř</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94202-84-p3s2w15">
<a>
<lex.rf>a#a-ln94202-84-p3s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akreditovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln94202-84-p3s2w16">
<a>
<lex.rf>a#a-ln94202-84-p3s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soukromý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-84-p3s3">
<atree.rf>a#a-ln94202-84-p3s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-84-l9A">
<basic-form>technický stav</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-84-p3s3w6</LM>
<LM>t-ln94202-84-p3s3w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-84-p3s3w1">
<a>
<lex.rf>a#a-ln94202-84-p3s3w1</lex.rf>
<aux.rf>
<LM>a#a-ln94202-84-p3s3w3</LM>
<LM>a#a-ln94202-84-p3s3w2</LM>
<LM>a#a-ln94202-84-p3s3w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zkontrolovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41rggA</val_frame.rf>
<children>
<LM id="t-ln94202-84-p3s3a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94202-84-p3s3w7">
<a>
<lex.rf>a#a-ln94202-84-p3s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stav</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94202-84-p3s3w5">
<a>
<lex.rf>a#a-ln94202-84-p3s3w5</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94202-84-p3s3w6">
<a>
<lex.rf>a#a-ln94202-84-p3s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>technický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94202-84-p3s3w9">
<a>
<lex.rf>a#a-ln94202-84-p3s3w9</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-84-p3s3w8">
<a>
<lex.rf>a#a-ln94202-84-p3s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>studna</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p3s1w6</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-84-p3s3w11">
<a>
<lex.rf>a#a-ln94202-84-p3s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>okolí</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94202-84-p3s3w10">
<a>
<lex.rf>a#a-ln94202-84-p3s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-84-p3s3w8</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
