<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf930713_126.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>other</genre>
</meta>
<trees>
<LM id="t-mf930713-126-p1s1">
<atree.rf>a#a-mf930713-126-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930713-126-l2B">
<type>time</type>
<tnode.rfs>
<LM>t-mf930713-126-p1s1w5</LM>
<LM>t-mf930713-126-p1s1w7</LM>
<LM>t-mf930713-126-p1s1w9</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930713-126-l3B">
<basic-form>kurzovní lístek</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930713-126-p1s1w1</LM>
<LM>t-mf930713-126-p1s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930713-126-p1s1w2">
<a>
<lex.rf>a#a-mf930713-126-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lístek</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-mf930713-126-p1s1w1">
<a>
<lex.rf>a#a-mf930713-126-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kursovní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930713-126-p1s1w3">
<a>
<lex.rf>a#a-mf930713-126-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>platný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930713-126-p1s1w7">
<a>
<lex.rf>a#a-mf930713-126-p1s1w7</lex.rf>
<aux.rf>
<LM>a#a-mf930713-126-p1s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7</t_lemma>
<functor>TSIN</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930713-126-p1s1w9">
<a>
<lex.rf>a#a-mf930713-126-p1s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1993</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930713-126-p1s1w5">
<a>
<lex.rf>a#a-mf930713-126-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>13</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930713-126-p2s1">
<atree.rf>a#a-mf930713-126-p2s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930713-126-p2s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>2</deepord>
<children>
<LM id="t-mf930713-126-p2s1w1">
<a>
<lex.rf>a#a-mf930713-126-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>deviza</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930713-126-p2s1w2">
<a>
<lex.rf>a#a-mf930713-126-p2s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>valuta</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930713-126-p3s1">
<atree.rf>a#a-mf930713-126-p3s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930713-126-p3s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="t-mf930713-126-p3s1w1">
<a>
<lex.rf>a#a-mf930713-126-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>země</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930713-126-p3s1w2">
<a>
<lex.rf>a#a-mf930713-126-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kód</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930713-126-p3s1w3">
<a>
<lex.rf>a#a-mf930713-126-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nákup</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930713-126-p3s1w4">
<a>
<lex.rf>a#a-mf930713-126-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodej</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf930713-126-p3s1w5">
<a>
<lex.rf>a#a-mf930713-126-p3s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střed</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930713-126-p3s1w6">
<a>
<lex.rf>a#a-mf930713-126-p3s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nákup</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930713-126-p3s1w7">
<a>
<lex.rf>a#a-mf930713-126-p3s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodej</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930713-126-p3s1w8">
<a>
<lex.rf>a#a-mf930713-126-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střed</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
