<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf930709_054.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>person_interv</genre>
</meta>
<trees>
<LM id="t-mf930709-054-p1s1">
<atree.rf>a#a-mf930709-054-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-054-l34B">
<basic-form>Bylo nás pět</basic-form>
<type>object</type>
<tnode.rfs>
<LM>t-mf930709-054-p1s1w1</LM>
<LM>t-mf930709-054-p1s1w2</LM>
<LM>t-mf930709-054-p1s1w3</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l2A">
<basic-form>Indie v Kouřimi</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-mf930709-054-p1s1w5</LM>
<LM>t-mf930709-054-p1s1w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-054-p1s1w4">
<a>
<lex.rf>a#a-mf930709-054-p1s1w4</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Colon</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-mf930709-054-p1s1w1">
<a>
<lex.rf>a#a-mf930709-054-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-mf930709-054-p1s1w2">
<a>
<lex.rf>a#a-mf930709-054-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-054-p1s1w3">
<a>
<lex.rf>a#a-mf930709-054-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pět</t_lemma>
<functor>PAT</functor>
<proto_lemma>pět</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<tfa>t</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf930709-054-p1s1w5">
<a>
<lex.rf>a#a-mf930709-054-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Indie</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-054-p1s1w7">
<a>
<lex.rf>a#a-mf930709-054-p1s1w7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p1s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kouřim</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s1">
<atree.rf>a#a-mf930709-054-p2s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-054-l4B">
<basic-form>Karel Poláček</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s1w11</LM>
<LM>t-mf930709-054-p2s1w12</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l9B">
<basic-form>Karel Smyczek</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s1w19</LM>
<LM>t-mf930709-054-p2s1w20</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l11B">
<type>time</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s1w15</LM>
<LM>t-mf930709-054-p2s1w17</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l35B">
<basic-form>Bylo nás pět</basic-form>
<type>object</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s1w4</LM>
<LM>t-mf930709-054-p2s1w5</LM>
<LM>t-mf930709-054-p2s1w6</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l36A">
<basic-form>televizní seriál</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s1w2</LM>
<LM>t-mf930709-054-p2s1w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-054-p2s1w14">
<a>
<lex.rf>a#a-mf930709-054-p2s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zahájit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41psqB</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s1w1">
<a>
<lex.rf>a#a-mf930709-054-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>natáčení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41defA</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-054-p2s1w3">
<a>
<lex.rf>a#a-mf930709-054-p2s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>seriál</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-054-p2s1w2">
<a>
<lex.rf>a#a-mf930709-054-p2s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>televizní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf930709-054-p2s1w4">
<a>
<lex.rf>a#a-mf930709-054-p2s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>ID</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s1w5">
<a>
<lex.rf>a#a-mf930709-054-p2s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-054-p2s1w6">
<a>
<lex.rf>a#a-mf930709-054-p2s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pět</t_lemma>
<functor>PAT</functor>
<proto_lemma>pět</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s1w8">
<a>
<lex.rf>a#a-mf930709-054-p2s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>inspirovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf930709-054-p2s1w10">
<a>
<lex.rf>a#a-mf930709-054-p2s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>román</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-054-p2s1w9">
<a>
<lex.rf>a#a-mf930709-054-p2s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stejnojmenný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-mf930709-054-p2s1w12">
<a>
<lex.rf>a#a-mf930709-054-p2s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Poláček</t_lemma>
<functor>AUTH</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-mf930709-054-p2s1w11">
<a>
<lex.rf>a#a-mf930709-054-p2s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Karel</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s1w17">
<a>
<lex.rf>a#a-mf930709-054-p2s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>červenec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-mf930709-054-p2s1w15">
<a>
<lex.rf>a#a-mf930709-054-p2s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>20</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s1w20">
<a>
<lex.rf>a#a-mf930709-054-p2s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Smyczek</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf930709-054-p2s1w19">
<a>
<lex.rf>a#a-mf930709-054-p2s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Karel</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-mf930709-054-p2s1w18">
<a>
<lex.rf>a#a-mf930709-054-p2s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>režisér</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-054-p2s1w1</target_node.rf>
<type>REST</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s2">
<atree.rf>a#a-mf930709-054-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-054-l32B">
<basic-form>podle mého názoru</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s2w24</LM>
<LM>t-mf930709-054-p2s2w25</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l33B">
<basic-form>převážná část</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s2w14</LM>
<LM>t-mf930709-054-p2s2w15</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-054-p2s2w12">
<a>
<lex.rf>a#a-mf930709-054-p2s2w12</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Colon</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-054-p2s2w1">
<a>
<lex.rf>a#a-mf930709-054-p2s2w1</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s2w2</LM>
<LM>a#a-mf930709-054-p2s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zeptat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41raoA</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s2a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-054-p2s2w4">
<a>
<lex.rf>a#a-mf930709-054-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s1w20</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s2w9">
<a>
<lex.rf>a#a-mf930709-054-p2s2w9</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s2w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vybrat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41nusB</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s2a2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s2w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s2w7">
<a>
<lex.rf>a#a-mf930709-054-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>BEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-mf930709-054-p2s2a2</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-054-p2s2w8">
<a>
<lex.rf>a#a-mf930709-054-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>už</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930709-054-p2s2w11">
<a>
<lex.rf>a#a-mf930709-054-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lokalita</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf930709-054-p2s2w10">
<a>
<lex.rf>a#a-mf930709-054-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vhodný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s2w17">
<a>
<lex.rf>a#a-mf930709-054-p2s2w17</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s2w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>točit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-054-p2s2w1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>spec</discourse_type>
<sense_PDTB3>Expansion.Level-of-detail.Arg2-as-detail</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf930709-054-p2s2w12</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41lzsC</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s2w15">
<a>
<lex.rf>a#a-mf930709-054-p2s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>část</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-054-p2s1w3</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-054-p2s2w14">
<a>
<lex.rf>a#a-mf930709-054-p2s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>převážný</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s2a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-054-p2s2a2</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
</LM>
<LM id="t-mf930709-054-p2s2w19">
<a>
<lex.rf>a#a-mf930709-054-p2s2w19</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s2w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>městečko</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p1s1w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-054-p2s2w20">
<a>
<lex.rf>a#a-mf930709-054-p2s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kouřim</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-mf930709-054-p2s2w26">
<a>
<lex.rf>a#a-mf930709-054-p2s2w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odpovídat</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<val_frame.rf>v#v41egyF</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s2w22">
<a>
<lex.rf>a#a-mf930709-054-p2s2w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_gram.rf>
<LM>t-mf930709-054-p2s2w19</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-054-p2s2w25">
<a>
<lex.rf>a#a-mf930709-054-p2s2w25</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s2w23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>názor</t_lemma>
<functor>CRIT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<children>
<LM id="t-mf930709-054-p2s2w24">
<a>
<lex.rf>a#a-mf930709-054-p2s2w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s2w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s2w29">
<a>
<lex.rf>a#a-mf930709-054-p2s2w29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>atmosféra</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<children>
<LM id="t-mf930709-054-p2s2w28">
<a>
<lex.rf>a#a-mf930709-054-p2s2w28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poláčkovský</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
<LM id="t-mf930709-054-p2s2w27">
<a>
<lex.rf>a#a-mf930709-054-p2s2w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laskavý</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s3">
<atree.rf>a#a-mf930709-054-p2s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-054-p2s3w4">
<a>
<lex.rf>a#a-mf930709-054-p2s3w4</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41chlQ</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s3a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s2a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s3w1">
<a>
<lex.rf>a#a-mf930709-054-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trocha</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-054-p2s3w2">
<a>
<lex.rf>a#a-mf930709-054-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>problém</t_lemma>
<functor>MAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-054-p2s3w7">
<a>
<lex.rf>a#a-mf930709-054-p2s3w7</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<deepord>6</deepord>
<children>
<LM id="t-mf930709-054-p2s3w6">
<a>
<lex.rf>a#a-mf930709-054-p2s3w6</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s3w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přepis</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-054-p2s3w8">
<a>
<lex.rf>a#a-mf930709-054-p2s3w8</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>respektive</t_lemma>
<functor>CM</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-054-p2s3w9">
<a>
<lex.rf>a#a-mf930709-054-p2s3w9</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s3w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zjednodušení</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41reqA</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s3w11">
<a>
<lex.rf>a#a-mf930709-054-p2s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pasáž</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-054-p2s3w10">
<a>
<lex.rf>a#a-mf930709-054-p2s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snový</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf930709-054-p2s3w17">
<a>
<lex.rf>a#a-mf930709-054-p2s3w17</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s3w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ocitat_se</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<val_frame.rf>v#v41duwA</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s3w16">
<a>
<lex.rf>a#a-mf930709-054-p2s3w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hrdina</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-mf930709-054-p2s3w14">
<a>
<lex.rf>a#a-mf930709-054-p2s3w14</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s3w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>LOC</functor>
<proto_lemma>který</proto_lemma>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<coref_gram.rf>
<LM>t-mf930709-054-p2s3w11</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-054-p2s3w20">
<a>
<lex.rf>a#a-mf930709-054-p2s3w20</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s3w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>reálie</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-mf930709-054-p2s3w19">
<a>
<lex.rf>a#a-mf930709-054-p2s3w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>indický</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s2w17</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p1s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s4">
<atree.rf>a#a-mf930709-054-p2s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-054-p2s4w2">
<a>
<lex.rf>a#a-mf930709-054-p2s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>inter</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s4w4">
<a>
<lex.rf>a#a-mf930709-054-p2s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obsazení</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41dswC</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s4w3">
<a>
<lex.rf>a#a-mf930709-054-p2s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>herecký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s4w1">
<a>
<lex.rf>a#a-mf930709-054-p2s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jaký</t_lemma>
<functor>PAT</functor>
<proto_lemma>jaký</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>inter</indeftype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s5">
<atree.rf>a#a-mf930709-054-p2s5</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-054-l17B">
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s5w12</LM>
<LM>t-mf930709-054-p2s5w13</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l20B">
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s5w15</LM>
<LM>t-mf930709-054-p2s5w16</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l23B">
<basic-form>Jiřina Jirásková</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s5w21</LM>
<LM>t-mf930709-054-p2s5w22</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l27B">
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s5w31</LM>
<LM>t-mf930709-054-p2s5w32</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-054-l29B">
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-054-p2s5w9</LM>
<LM>t-mf930709-054-p2s5w10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-054-p2s5w23">
<a>
<lex.rf>a#a-mf930709-054-p2s5w23</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<deepord>18</deepord>
<children>
<LM id="t-mf930709-054-p2s5w11">
<a>
<lex.rf>a#a-mf930709-054-p2s5w11</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s5w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>objevit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41dpuA</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s5w4">
<a>
<lex.rf>a#a-mf930709-054-p2s5w4</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s5w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představitel</t_lemma>
<functor>RESTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-054-p2s4w4</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-054-p2s5w3">
<a>
<lex.rf>a#a-mf930709-054-p2s5w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dětský</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s5w7">
<a>
<lex.rf>a#a-mf930709-054-p2s5w7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s5w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>role</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-054-p2s5w8">
<a>
<lex.rf>a#a-mf930709-054-p2s5w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rodič</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>group</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-054-p2s5w10">
<a>
<lex.rf>a#a-mf930709-054-p2s5w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bajza</t_lemma>
<functor>APP</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-054-p2s5w9">
<a>
<lex.rf>a#a-mf930709-054-p2s5w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Petr</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s5w14">
<a>
<lex.rf>a#a-mf930709-054-p2s5w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-054-p2s5w13">
<a>
<lex.rf>a#a-mf930709-054-p2s5w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Navrátil</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-054-p2s4w4</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-054-p2s5w12">
<a>
<lex.rf>a#a-mf930709-054-p2s5w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Oldřich</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s5w16">
<a>
<lex.rf>a#a-mf930709-054-p2s5w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Veškrnová</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-054-p2s4w4</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-054-p2s5w15">
<a>
<lex.rf>a#a-mf930709-054-p2s5w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Dagmar</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s5w20">
<a>
<lex.rf>a#a-mf930709-054-p2s5w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ztvárnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41rzsA</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s5w19">
<a>
<lex.rf>a#a-mf930709-054-p2s5w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>postava</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>13</deepord>
<children>
<LM id="t-mf930709-054-p2s5w18">
<a>
<lex.rf>a#a-mf930709-054-p2s5w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zajímavý</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s5w22">
<a>
<lex.rf>a#a-mf930709-054-p2s5w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jirásková</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-054-p2s4w4</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-054-p2s5w21">
<a>
<lex.rf>a#a-mf930709-054-p2s5w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jiřina</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s5w30">
<a>
<lex.rf>a#a-mf930709-054-p2s5w30</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s5w29</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hrát</t_lemma>
<functor>PRED</functor>
<proto_lemma>hrát</proto_lemma>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<val_frame.rf>v#v41aypD</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s5w26">
<a>
<lex.rf>a#a-mf930709-054-p2s5w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Zilvar</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>19</deepord>
<children>
<LM id="t-mf930709-054-p2s5w25">
<a>
<lex.rf>a#a-mf930709-054-p2s5w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pan</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-mf930709-054-p2s5w28">
<a>
<lex.rf>a#a-mf930709-054-p2s5w28</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s5w27</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chudobinec</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
<LM id="t-mf930709-054-p2s5w24">
<a>
<lex.rf>a#a-mf930709-054-p2s5w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>legendární</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s5w32">
<a>
<lex.rf>a#a-mf930709-054-p2s5w32</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pecha</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-054-p2s4w4</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-054-p2s5w31">
<a>
<lex.rf>a#a-mf930709-054-p2s5w31</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jiří</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s6">
<atree.rf>a#a-mf930709-054-p2s6</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-054-p2s6w9">
<a>
<lex.rf>a#a-mf930709-054-p2s6w9</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>nicméně</t_lemma>
<functor>ADVS</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<deepord>7</deepord>
<children>
<LM id="t-mf930709-054-p2s6w1">
<a>
<lex.rf>a#a-mf930709-054-p2s6w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>myslit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-054-p2s6w14</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conc</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf930709-054-p2s6w9</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41cklC</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s6a2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s2w24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s6w5">
<a>
<lex.rf>a#a-mf930709-054-p2s6w5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s6w3</LM>
<LM>a#a-mf930709-054-p2s6w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>získat</t_lemma>
<functor>EFF</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41reiB</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s6a3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s6a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s6w7">
<a>
<lex.rf>a#a-mf930709-054-p2s6w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představitel</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s4w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-054-p2s6w6">
<a>
<lex.rf>a#a-mf930709-054-p2s6w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>optimální</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s6w14">
<a>
<lex.rf>a#a-mf930709-054-p2s6w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zjišťovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<val_frame.rf>v#v41rfcB</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s6w13">
<a>
<lex.rf>a#a-mf930709-054-p2s6w13</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s6w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>natáčení</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41defA</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s6a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-054-p2s6a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-mf930709-054-p2s6w12">
<a>
<lex.rf>a#a-mf930709-054-p2s6w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf930709-054-p2s6w11">
<a>
<lex.rf>a#a-mf930709-054-p2s6w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>každý</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>který</proto_lemma>
<subfunctor>nr</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.indef</sempos>
<gender>neut</gender>
<number>sg</number>
<indeftype>total2</indeftype>
<person>3</person>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s6a4">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s6a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s6w20">
<a>
<lex.rf>a#a-mf930709-054-p2s6w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chybět</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41bcpB</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s6w17">
<a>
<lex.rf>a#a-mf930709-054-p2s6w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s6a4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s6w16">
<a>
<lex.rf>a#a-mf930709-054-p2s6w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jak</t_lemma>
<functor>EXT</functor>
<proto_lemma>jak</proto_lemma>
<subfunctor>nr</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>adv.pron.indef</sempos>
<indeftype>inter</indeftype>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-mf930709-054-p2s6w21">
<a>
<lex.rf>a#a-mf930709-054-p2s6w21</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Colon</t_lemma>
<functor>APPS</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<deepord>20</deepord>
<children>
<LM id="t-mf930709-054-p2s6w19">
<a>
<lex.rf>a#a-mf930709-054-p2s6w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>člověk</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-mf930709-054-p2s6w18">
<a>
<lex.rf>a#a-mf930709-054-p2s6w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>některý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>indef1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s6w24">
<a>
<lex.rf>a#a-mf930709-054-p2s6w24</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<deepord>23</deepord>
<children>
<LM id="t-mf930709-054-p2s6w23">
<a>
<lex.rf>a#a-mf930709-054-p2s6w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jegorov</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
<LM id="t-mf930709-054-p2s6w25">
<a>
<lex.rf>a#a-mf930709-054-p2s6w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Štibich</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
<LM id="t-mf930709-054-p2s6w22">
<a>
<lex.rf>a#a-mf930709-054-p2s6w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pán</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s7">
<atree.rf>a#a-mf930709-054-p2s7</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-054-p2s7w3">
<a>
<lex.rf>a#a-mf930709-054-p2s7w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znamenat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41rmoB</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s7a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s6w21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s7w2">
<a>
<lex.rf>a#a-mf930709-054-p2s7w2</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s7w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s6w17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s7w6">
<a>
<lex.rf>a#a-mf930709-054-p2s7w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>maskot</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
<LM>
<type>other</type>
<set_id>mf930709-054-p2s7w6</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-054-p2s7w4">
<a>
<lex.rf>a#a-mf930709-054-p2s7w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osobní</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
<LM>
<type>other</type>
<set_id>mf930709-054-p2s7w6</set_id>
</LM>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-054-p2s8">
<atree.rf>a#a-mf930709-054-p2s8</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-054-p2s8w1">
<a>
<lex.rf>a#a-mf930709-054-p2s8w1</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s8w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stýskat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41loiA</val_frame.rf>
<children>
<LM id="t-mf930709-054-p2s8w3">
<a>
<lex.rf>a#a-mf930709-054-p2s8w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s7w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-054-p2s8w5">
<a>
<lex.rf>a#a-mf930709-054-p2s8w5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-054-p2s8w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>mf930709-054-p2s5w23</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-054-p2s7a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
