<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="tdata_c2_schema.xml" />
  <references>
   <reffile id="a" name="adata" href="pdtsc_034_2.06.a" />
   <reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
  </references>
 </head>
 <meta/>
 <trees>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x5-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1786-x5-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x5-roota1">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d-id119669</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>#Comma</t_lemma>
     <functor>CONJ</functor>
     <deepord>5</deepord>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x5-n7">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_special>exoph</coref_special>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1819-10">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1819-10</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1819-7</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>jet</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>1</person>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <val_frame.rf>v#v41bhuF</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1819-9">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1819-9</lex.rf>
          <aux.rf>
           <LM>a#hg-25819_01.06-SCzechA-m-d1t1819-8</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>MEANS</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>fem</gender>
          <number>sg</number>
          <person>3</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>2</deepord>
         <coref_special>exoph</coref_special>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x5-roota2">
         <nodetype>qcomplex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Oblfm</t_lemma>
         <functor>DIR3</functor>
         <deepord>4</deepord>
        </LM>
       </children>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1819-18">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1819-18</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1819-14</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>učesat</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>1</person>
        <negation>neg0</negation>
       </gram>
       <deepord>7</deepord>
       <val_frame.rf>v#v41mguA</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1819-13">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1819-13</lex.rf>
          <aux.rf>
           <LM>a#hg-25819_01.06-SCzechA-m-d1t1819-12</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>ten</t_lemma>
         <functor>CRIT</functor>
         <proto_lemma>ten</proto_lemma>
         <gram>
          <sempos>n.pron.def.demon</sempos>
          <gender>neut</gender>
          <number>sg</number>
         </gram>
         <deepord>6</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1819-10</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x5-roota3">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1819-15</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>8</deepord>
         <coref_gram.rf>
          <LM>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x5-n7</LM>
         </coref_gram.rf>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1819-17">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1819-17</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>jinak</t_lemma>
         <functor>MANN</functor>
         <gram>
          <sempos>adv.denot.ngrad.neg</sempos>
          <negation>neg0</negation>
         </gram>
         <deepord>9</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-19751-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-19751-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1823-7">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1823-7</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>a</t_lemma>
     <functor>CONJ</functor>
     <deepord>6</deepord>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1823-4">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1823-4</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1823-3</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>jet</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>pl</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>1</person>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <val_frame.rf>v#v41bhuF</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1823-2">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1823-2</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>jednou</t_lemma>
         <functor>TWHEN</functor>
         <gram>
          <sempos>adj.quant.def</sempos>
          <numertype>basic</numertype>
          <negation>neg0</negation>
         </gram>
         <deepord>1</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-19751-n11">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>2</deepord>
         <coref_special>exoph</coref_special>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-19751-roota1">
         <nodetype>qcomplex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Oblfm</t_lemma>
         <functor>DIR3</functor>
         <deepord>4</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1823-6">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1823-6</lex.rf>
          <aux.rf>
           <LM>a#hg-25819_01.06-SCzechA-m-d1t1823-5</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>vlak</t_lemma>
         <functor>MEANS</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>inan</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>5</deepord>
        </LM>
       </children>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1823-8">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1823-8</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>přijít</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>cpl</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>8</deepord>
       <discourse>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1823-4</target_node.rf>
         <type>discourse</type>
         <start_range>0</start_range>
         <target_range>0</target_range>
         <discourse_type>conj</discourse_type>
         <sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
         <comment>PHASE:1</comment>
         <src>A_H_A</src>
         <t-connectors.rf>
          <LM>hg-25819_01.06-SCzechT-m-d1t1823-7</LM>
         </t-connectors.rf>
        </LM>
       </discourse>
       <val_frame.rf>v#v41isgP</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1823-9">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1823-9</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>tam</t_lemma>
         <functor>DIR3</functor>
         <proto_lemma>tam</proto_lemma>
         <gram>
          <sempos>adv.pron.def</sempos>
         </gram>
         <deepord>7</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1823-6</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1823-10">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1823-10</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>gestapák</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>9</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1823-11">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1823-11</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>kontrolovat</t_lemma>
         <functor>INTT</functor>
         <gram>
          <sempos>v</sempos>
          <deontmod>decl</deontmod>
          <tense>nil</tense>
          <aspect>proc</aspect>
          <iterativeness>it0</iterativeness>
          <negation>neg0</negation>
         </gram>
         <deepord>11</deepord>
         <val_frame.rf>v#v41brjB</val_frame.rf>
         <children>
          <LM id="hg-25819_01.06-SCzechT-hg-25819_01-19751-roota2">
           <nodetype>qcomplex</nodetype>
           <is_generated>1</is_generated>
           <t_lemma>#Cor</t_lemma>
           <functor>ACT</functor>
           <deepord>10</deepord>
           <coref_gram.rf>
            <LM>hg-25819_01.06-SCzechT-m-d1t1823-10</LM>
           </coref_gram.rf>
          </LM>
          <LM id="hg-25819_01.06-SCzechT-m-d1t1832-2">
           <a>
            <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1832-2</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>legitimace</t_lemma>
           <functor>PAT</functor>
           <gram>
            <sempos>n.denot</sempos>
            <gender>fem</gender>
            <number>pl</number>
            <negation>neg0</negation>
           </gram>
           <deepord>12</deepord>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x6-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1786-x6-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1836-11">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1836-11</lex.rf>
      <aux.rf>
       <LM>a#hg-25819_01.06-SCzechA-m-d1t1836-9</LM>
      </aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>mít</t_lemma>
     <functor>PRED</functor>
     <proto_lemma>mít</proto_lemma>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>1</person>
      <negation>neg0</negation>
     </gram>
     <deepord>3</deepord>
     <val_frame.rf>v#v41chlAH</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1836-10">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1836-10</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>už</t_lemma>
       <functor>TWHEN</functor>
       <gram>
        <sempos>adv.denot.ngrad.nneg</sempos>
        <negation>neg0</negation>
       </gram>
       <deepord>1</deepord>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x6-n5">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x5-roota3</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1836-12">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1836-12</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>strach</t_lemma>
       <functor>CPHR</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>4</deepord>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1786-x7-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-roota4">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d-id120565</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>#Comma</t_lemma>
     <functor>CONJ</functor>
     <deepord>8</deepord>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1841-1">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>tenkrát</t_lemma>
       <functor>TWHEN</functor>
       <proto_lemma>tenkrát</proto_lemma>
       <gram>
        <sempos>adv.pron.def</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1823-2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1841-3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-3</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1841-2</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>mít</t_lemma>
       <functor>PRED</functor>
       <proto_lemma>mít</proto_lemma>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <negation>neg1</negation>
       </gram>
       <deepord>4</deepord>
       <val_frame.rf>v#v41chlF</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-n12">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>2</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x6-n5</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-roota1">
         <nodetype>atom</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Neg</t_lemma>
         <functor>RHEM</functor>
         <deepord>3</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-roota5">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1832-2</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>legitimace</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>n.denot</sempos>
         </gram>
         <deepord>5</deepord>
         <children>
          <LM id="hg-25819_01.06-SCzechT-m-d1t1841-4">
           <a>
            <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-4</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>žádný</t_lemma>
           <functor>RSTR</functor>
           <gram>
            <sempos>n.pron.indef</sempos>
            <gender>fem</gender>
            <number>sg</number>
            <indeftype>negat</indeftype>
            <person>3</person>
           </gram>
           <deepord>6</deepord>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1841-11">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-11</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1841-7</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>vzít</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>poss</deontmod>
        <tense>ant</tense>
        <aspect>cpl</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg1</negation>
       </gram>
       <deepord>10</deepord>
       <val_frame.rf>v#v41pmaA</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1841-8">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-8</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>nějak</t_lemma>
         <functor>MANN</functor>
         <gram>
          <sempos>adv.pron.indef</sempos>
          <indeftype>indef1</indeftype>
         </gram>
         <deepord>7</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1841-6">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-6</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>ten</t_lemma>
         <functor>PAT</functor>
         <proto_lemma>ten</proto_lemma>
         <gram>
          <sempos>n.pron.def.demon</sempos>
          <gender>neut</gender>
          <number>sg</number>
         </gram>
         <deepord>9</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-roota5</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1841-10">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-10</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>žena</t_lemma>
         <functor>ADDR</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>fem</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>11</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-n14">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>12</deepord>
         <coref_special>exoph</coref_special>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-roota2">
         <nodetype>atom</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Neg</t_lemma>
         <functor>RHEM</functor>
         <deepord>13</deepord>
        </LM>
       </children>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1841-13">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-13</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>jít</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>pl</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>1</person>
        <negation>neg1</negation>
       </gram>
       <deepord>15</deepord>
       <val_frame.rf>v#v41bikAT</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-roota3">
         <nodetype>atom</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Neg</t_lemma>
         <functor>RHEM</functor>
         <deepord>14</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1841-14">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1841-14</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>ten</t_lemma>
         <functor>ACT</functor>
         <proto_lemma>ten</proto_lemma>
         <gram>
          <sempos>n.pron.def.demon</sempos>
          <gender>neut</gender>
          <number>sg</number>
         </gram>
         <deepord>16</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1841-11</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3034-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-3034-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1843-6">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1843-6</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>a</t_lemma>
     <functor>CONJ</functor>
     <deepord>5</deepord>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1843-3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1843-3</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>mít</t_lemma>
       <functor>PRED</functor>
       <proto_lemma>mít</proto_lemma>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <val_frame.rf>v#v41chlJ</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3034-n9">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>1</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1841-10</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1843-2">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1843-2</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>fem</gender>
          <number>sg</number>
          <person>3</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>2</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1841-6</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1843-5">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1843-5</lex.rf>
          <aux.rf>
           <LM>a#hg-25819_01.06-SCzechA-m-d1t1843-4</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>LOC</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>inher</gender>
          <number>inher</number>
          <person>inher</person>
          <politeness>inher</politeness>
         </gram>
         <deepord>4</deepord>
         <coref_gram.rf>
          <LM>hg-25819_01.06-SCzechT-hg-25819_01-3034-n9</LM>
         </coref_gram.rf>
        </LM>
       </children>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1843-8">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1843-8</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-3034-3035</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>jet</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>1</person>
        <negation>neg0</negation>
       </gram>
       <deepord>7</deepord>
       <discourse>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1843-3</target_node.rf>
         <type>discourse</type>
         <start_range>0</start_range>
         <target_range>0</target_range>
         <discourse_type>conj</discourse_type>
         <sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
         <comment>PHASE:1</comment>
         <src>A_H_A</src>
         <t-connectors.rf>
          <LM>hg-25819_01.06-SCzechT-m-d1t1843-6</LM>
         </t-connectors.rf>
        </LM>
       </discourse>
       <val_frame.rf>v#v41bhuF</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1843-7">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1843-7</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>nr</gender>
          <number>sg</number>
          <person>1</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>6</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x7-n12</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3034-roota2">
         <nodetype>qcomplex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Oblfm</t_lemma>
         <functor>DIR3</functor>
         <deepord>8</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3034-roota1">
         <a>
          <aux.rf>
           <LM>a#hg-25819_01.06-SCzechA-m-d1t1843-9</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#EmpNoun</t_lemma>
         <functor>ACMP</functor>
         <gram>
          <sempos>n.pron.def.demon</sempos>
         </gram>
         <deepord>9</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x8-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1786-x8-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1847-7">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-7</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>a</t_lemma>
     <functor>CONJ</functor>
     <deepord>5</deepord>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x8-n9">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-19751-roota2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1847-5">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-5</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>prohlížet</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <val_frame.rf>v#v41hdpA</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1847-3">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-3</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>ten</t_lemma>
         <functor>PAT</functor>
         <proto_lemma>ten</proto_lemma>
         <gram>
          <sempos>n.pron.def.demon</sempos>
          <gender>neut</gender>
          <number>sg</number>
         </gram>
         <deepord>2</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1832-2</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1847-4">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-4</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>tam</t_lemma>
         <functor>LOC</functor>
         <proto_lemma>tam</proto_lemma>
         <gram>
          <sempos>adv.pron.def</sempos>
         </gram>
         <deepord>4</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1823-9</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
       </children>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1847-9">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-9</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>jít</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>7</deepord>
       <discourse>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1847-5</target_node.rf>
         <type>discourse</type>
         <start_range>0</start_range>
         <target_range>0</target_range>
         <discourse_type>conj</discourse_type>
         <sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
         <comment>PHASE:1</comment>
         <src>A_H_A</src>
         <t-connectors.rf>
          <LM>hg-25819_01.06-SCzechT-m-d1t1847-7</LM>
         </t-connectors.rf>
        </LM>
       </discourse>
       <val_frame.rf>v#v41bikAI</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1847-8">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-8</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>prvně</t_lemma>
         <functor>TWHEN</functor>
         <gram>
          <sempos>adv.denot.grad.neg</sempos>
          <degcmp>pos</degcmp>
          <negation>neg0</negation>
         </gram>
         <deepord>6</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1847-11">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-11</lex.rf>
          <aux.rf>
           <LM>a#hg-25819_01.06-SCzechA-m-d1t1847-10</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>Fídler</t_lemma>
         <functor>DIR3</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>anim</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>8</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3042-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-3042-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1847-14">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-14</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>říkat</t_lemma>
     <functor>PRED</functor>
     <proto_lemma>říkat</proto_lemma>
     <sentmod>inter</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>4</deepord>
     <val_frame.rf>v#v41kejB</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3042-n7">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x8-n9</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3042-roota1">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ADDR</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1847-11</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3042-roota2">
       <nodetype>list</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#Forn</t_lemma>
       <functor>EFF</functor>
       <sentmod>enunc</sentmod>
       <is_dsp_root>1</is_dsp_root>
       <deepord>5</deepord>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1847-17">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-17</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>Das</t_lemma>
         <functor>FPHR</functor>
         <deepord>3</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1847-18">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-18</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>ist</t_lemma>
         <functor>FPHR</functor>
         <deepord>6</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1847-19">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-19</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>Ihre</t_lemma>
         <functor>FPHR</functor>
         <deepord>7</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1847-20">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1847-20</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>Frau</t_lemma>
         <functor>FPHR</functor>
         <deepord>8</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x9-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1786-x9-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1852-3">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1852-3</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>říci</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>pl</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>cpl</aspect>
      <iterativeness>it0</iterativeness>
      <person>1</person>
      <negation>neg0</negation>
     </gram>
     <deepord>2</deepord>
     <val_frame.rf>v#v41kebA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x9-n10">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-3042-roota1</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x9-roota1">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ADDR</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>3</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-3042-n7</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x9-roota2">
       <nodetype>list</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#Forn</t_lemma>
       <functor>EFF</functor>
       <sentmod>enunc</sentmod>
       <is_dsp_root>1</is_dsp_root>
       <deepord>5</deepord>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1852-6">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1852-6</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>Ja</t_lemma>
         <functor>FPHR</functor>
         <deepord>4</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1e1786-x9-20079">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1e1786-x9-20079</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>,</t_lemma>
         <functor>FPHR</functor>
         <deepord>6</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1852-7">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1852-7</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>das</t_lemma>
         <functor>FPHR</functor>
         <deepord>7</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1852-8">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1852-8</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>ist</t_lemma>
         <functor>FPHR</functor>
         <deepord>8</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1852-9">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1852-9</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>meine</t_lemma>
         <functor>FPHR</functor>
         <deepord>9</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1852-10">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1852-10</lex.rf>
         </a>
         <nodetype>fphr</nodetype>
         <t_lemma>Frau</t_lemma>
         <functor>FPHR</functor>
         <deepord>10</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3047-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-3047-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1854-3">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1854-3</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>riskovat</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>nr</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>2</deepord>
     <val_frame.rf>v#v41jkvA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3047-n3">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x9-n10</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x10-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1786-x10-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1858-4">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1858-4</lex.rf>
      <aux.rf>
       <LM>a#hg-25819_01.06-SCzechA-m-d1t1856-3</LM>
      </aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>vyváznout</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>cpl</aspect>
      <iterativeness>it0</iterativeness>
      <person>1</person>
      <negation>neg0</negation>
     </gram>
     <deepord>4</deepord>
     <discourse>
      <LM>
       <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1860-9</target_node.rf>
       <type>discourse</type>
       <start_range>0</start_range>
       <target_range>0</target_range>
       <discourse_type>preced</discourse_type>
       <sense_PDTB3>Temporal.Asynchronous.Precedence</sense_PDTB3>
       <comment>PHASE:2 MANUAL</comment>
       <src>A_I_A</src>
       <t-connectors.rf>
        <LM>hg-25819_01.06-SCzechT-m-d1t1860-7</LM>
       </t-connectors.rf>
      </LM>
     </discourse>
     <val_frame.rf>v#v41pgaB</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1856-2">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1856-2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>tenkrát</t_lemma>
       <functor>TWHEN</functor>
       <proto_lemma>tenkrát</proto_lemma>
       <gram>
        <sempos>adv.pron.def</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1841-1</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1858-3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1858-3</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1858-2</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>ten</t_lemma>
       <functor>DIR1</functor>
       <proto_lemma>ten</proto_lemma>
       <gram>
        <sempos>n.pron.def.demon</sempos>
        <gender>neut</gender>
        <number>sg</number>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1823-11</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x10-n8">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>3</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1843-7</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1856-5">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1856-5</lex.rf>
       </a>
       <nodetype>atom</nodetype>
       <t_lemma>jen</t_lemma>
       <functor>RHEM</functor>
       <deepord>5</deepord>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1856-6">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1856-6</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>tak</t_lemma>
       <functor>MANN</functor>
       <proto_lemma>tak</proto_lemma>
       <gram>
        <sempos>adv.pron.def</sempos>
       </gram>
       <deepord>6</deepord>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1856-7">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1856-7</lex.rf>
         </a>
         <nodetype>dphr</nodetype>
         <t_lemma>tak</t_lemma>
         <functor>DPHR</functor>
         <deepord>7</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-20236-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-20236-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-hg-25819_01-20236-roota1">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d-id121639</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>#Comma</t_lemma>
     <functor>CONJ</functor>
     <deepord>5</deepord>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1860-9">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1860-9</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>být</t_lemma>
       <functor>PRED</functor>
       <proto_lemma>být</proto_lemma>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <val_frame.rf>v#v41jsM</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1860-7">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1860-7</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>potom</t_lemma>
         <functor>TWHEN</functor>
         <proto_lemma>potom</proto_lemma>
         <gram>
          <sempos>adv.pron.def</sempos>
         </gram>
         <deepord>1</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1860-8">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1860-8</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>ten</t_lemma>
         <functor>ACT</functor>
         <proto_lemma>ten</proto_lemma>
         <gram>
          <sempos>n.pron.def.demon</sempos>
          <gender>neut</gender>
          <number>sg</number>
         </gram>
         <deepord>2</deepord>
         <coref_special>exoph</coref_special>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1860-10">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1860-10</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>zavřený</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>adj.denot</sempos>
          <degcmp>pos</degcmp>
          <negation>neg0</negation>
         </gram>
         <deepord>4</deepord>
        </LM>
       </children>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1862-5">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1862-5</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1862-2</LM>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1862-3</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>dostat_se</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>pl</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>cpl</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>8</deepord>
       <val_frame.rf>v#v41afyI</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1860-12">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1860-12</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>už</t_lemma>
         <functor>TWHEN</functor>
         <gram>
          <sempos>adv.denot.ngrad.nneg</sempos>
          <negation>neg0</negation>
         </gram>
         <deepord>6</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1862-4">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1862-4</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>tam</t_lemma>
         <functor>DIR3</functor>
         <proto_lemma>tam</proto_lemma>
         <gram>
          <sempos>adv.pron.def</sempos>
         </gram>
         <deepord>7</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1860-8</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-20236-roota2">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>9</deepord>
         <bridging>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x10-n8</target_node.rf>
           <type>SUB_SET</type>
          </LM>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-3047-n3</target_node.rf>
           <type>SUB_SET</type>
          </LM>
         </bridging>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1862-6">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1862-6</lex.rf>
         </a>
         <nodetype>atom</nodetype>
         <t_lemma>jenom</t_lemma>
         <functor>RHEM</functor>
         <deepord>10</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1871-1">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1871-1</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>pěšky</t_lemma>
         <functor>MANN</functor>
         <gram>
          <sempos>adv.denot.ngrad.nneg</sempos>
          <negation>neg0</negation>
         </gram>
         <deepord>11</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1873-2">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1873-2</lex.rf>
          <aux.rf>
           <LM>a#hg-25819_01.06-SCzechA-m-d1t1873-1</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>hvězda</t_lemma>
         <functor>ACMP</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>fem</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>12</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3065-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-3065-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1867-3">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1867-3</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>stát</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>4</deepord>
     <val_frame.rf>v#v41lilA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1867-1">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1867-1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>ten</t_lemma>
       <functor>ACT</functor>
       <proto_lemma>ten</proto_lemma>
       <gram>
        <sempos>n.pron.def.demon</sempos>
        <gender>neut</gender>
        <number>sg</number>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1862-5</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1867-2">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1867-2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>ADDR</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>sg</number>
        <person>1</person>
        <politeness>basic</politeness>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1786-x10-n8</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1867-4">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1867-4</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>tenkrát</t_lemma>
       <functor>TWHEN</functor>
       <proto_lemma>tenkrát</proto_lemma>
       <gram>
        <sempos>adv.pron.def</sempos>
       </gram>
       <deepord>3</deepord>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-20236-20247">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-20236-20247</lex.rf>
       </a>
       <nodetype>coap</nodetype>
       <t_lemma>a</t_lemma>
       <functor>CONJ</functor>
       <deepord>8</deepord>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1867-6">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1867-6</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>stroj</t_lemma>
         <functor>PAT</functor>
         <is_member>1</is_member>
         <gram>
          <sempos>n.denot</sempos>
          <gender>inan</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>6</deepord>
         <children>
          <LM id="hg-25819_01.06-SCzechT-m-d1t1867-5">
           <a>
            <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1867-5</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>psací</t_lemma>
           <functor>RSTR</functor>
           <gram>
            <sempos>adj.denot</sempos>
            <degcmp>pos</degcmp>
            <negation>neg0</negation>
           </gram>
           <deepord>5</deepord>
          </LM>
          <LM id="hg-25819_01.06-SCzechT-m-d1t1869-2">
           <a>
            <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1869-2</lex.rf>
            <aux.rf>
             <LM>a#hg-25819_01.06-SCzechA-m-d1t1869-1</LM>
            </aux.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>tatínek</t_lemma>
           <functor>RSTR</functor>
           <gram>
            <sempos>n.denot</sempos>
            <gender>anim</gender>
            <number>sg</number>
            <negation>neg0</negation>
           </gram>
           <deepord>7</deepord>
          </LM>
         </children>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1869-6">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1869-6</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>věc</t_lemma>
         <functor>PAT</functor>
         <is_member>1</is_member>
         <gram>
          <sempos>n.denot</sempos>
          <gender>fem</gender>
          <number>pl</number>
          <negation>neg0</negation>
         </gram>
         <deepord>10</deepord>
         <children>
          <LM id="hg-25819_01.06-SCzechT-m-d1t1869-5">
           <a>
            <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1869-5</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>různý</t_lemma>
           <functor>RSTR</functor>
           <gram>
            <sempos>adj.denot</sempos>
            <degcmp>pos</degcmp>
            <negation>neg0</negation>
           </gram>
           <deepord>9</deepord>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3067-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-3067-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1875-2">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1875-2</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>převést</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>cpl</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>4</deepord>
     <val_frame.rf>v#v41imqE</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1873-5">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1873-5</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1873-4</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>Bohušovice</t_lemma>
       <functor>DIR1</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>pl</number>
        <negation>neg0</negation>
       </gram>
       <deepord>1</deepord>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1873-8">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1873-8</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>PAT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>pl</number>
        <person>1</person>
        <politeness>basic</politeness>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-20236-roota2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1873-9">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1873-9</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>tam</t_lemma>
       <functor>DIR3</functor>
       <proto_lemma>tam</proto_lemma>
       <gram>
        <sempos>adv.pron.def</sempos>
       </gram>
       <deepord>3</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1862-4</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3067-roota1">
       <nodetype>qcomplex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#Oblfm</t_lemma>
       <functor>DIR2</functor>
       <deepord>5</deepord>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1875-4">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1875-4</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>četník</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>6</deepord>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1876-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1876-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1881-3">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1881-3</lex.rf>
      <aux.rf>
       <LM>a#hg-25819_01.06-SCzechA-m-d1t1881-2</LM>
      </aux.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>jmenovat_se</t_lemma>
     <functor>PRED</functor>
     <sentmod>inter</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>2</deepord>
     <val_frame.rf>v#v41birA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1876-x2-roota1">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1875-4</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1881-4">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1881-4</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>Hvězda</t_lemma>
       <functor>PAT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3085-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-3085-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1891-1">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1891-1</lex.rf>
     </a>
     <nodetype>atom</nodetype>
     <t_lemma>prosím</t_lemma>
     <functor>PARTL</functor>
     <sentmod>inter</sentmod>
     <deepord>1</deepord>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1882-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1882-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1882-x2-roota1">
     <nodetype>qcomplex</nodetype>
     <is_generated>1</is_generated>
     <t_lemma>#EmpVerb</t_lemma>
     <functor>PRED</functor>
     <sentmod>inter</sentmod>
     <deepord>3</deepord>
     <discourse>
      <LM>
       <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1881-3</target_node.rf>
       <type>discourse</type>
       <start_range>0</start_range>
       <target_range>0</target_range>
       <discourse_type>disjalt</discourse_type>
       <sense_PDTB3>Expansion.Disjunction</sense_PDTB3>
       <comment>PHASE:3 RETYPED conjalt->disjalt; RETARGETED</comment>
       <src>A_I_A</src>
       <t-connectors.rf>
        <LM>hg-25819_01.06-SCzechT-m-d1e1882-x2-20358</LM>
       </t-connectors.rf>
      </LM>
     </discourse>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1e1882-x2-20358">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1e1882-x2-20358</lex.rf>
       </a>
       <nodetype>atom</nodetype>
       <t_lemma>nebo</t_lemma>
       <functor>PREC</functor>
       <deepord>1</deepord>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1e1882-x2-20359">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1e1882-x2-20359</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>jak</t_lemma>
       <functor>MANN</functor>
       <proto_lemma>jak</proto_lemma>
       <gram>
        <sempos>adv.pron.indef</sempos>
        <indeftype>inter</indeftype>
       </gram>
       <deepord>2</deepord>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1889-2">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1889-2</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1889-1</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>hvězda</t_lemma>
       <functor>ACMP</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>4</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1873-2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1893-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1893-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1896-2">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1896-2</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>připnout</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>pl</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>3</deepord>
     <val_frame.rf>v#v41ivvA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1896-1">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1896-1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>BEN</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>sg</number>
        <person>1</person>
        <politeness>basic</politeness>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1867-2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1893-x2-n5">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>2</deepord>
       <coref_special>exoph</coref_special>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1896-3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1896-3</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>hvězda</t_lemma>
       <functor>PAT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>4</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1889-2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1897-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1897-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1900-3">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1900-3</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>připnout</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>pl</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>3</deepord>
     <val_frame.rf>v#v41ivvA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1900-2">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1900-2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>BEN</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>pl</number>
        <person>2</person>
        <politeness>basic</politeness>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1896-1</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1897-x2-n5">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1893-x2-n5</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1900-4">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1900-4</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>hvězda</t_lemma>
       <functor>PAT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>4</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1896-3</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1901-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1901-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1906-4">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1906-4</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>mít</t_lemma>
     <functor>PRED</functor>
     <proto_lemma>mít</proto_lemma>
     <sentmod>inter</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>2</deepord>
     <val_frame.rf>v#v41chlBS</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1906-3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1906-3</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>ten</t_lemma>
       <functor>ACT</functor>
       <proto_lemma>ten</proto_lemma>
       <gram>
        <sempos>n.pron.def.demon</sempos>
        <gender>neut</gender>
        <number>sg</number>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1900-3</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1906-5">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1906-5</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>smysl</t_lemma>
       <functor>CPHR</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>4</deepord>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1906-2">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1906-2</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>jaký</t_lemma>
         <functor>RSTR</functor>
         <proto_lemma>jaký</proto_lemma>
         <gram>
          <sempos>n.pron.indef</sempos>
          <gender>inan</gender>
          <number>sg</number>
          <indeftype>inter</indeftype>
          <person>3</person>
         </gram>
         <deepord>3</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1901-x4-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1901-x4-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1901-x4-roota1">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1900-3</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <is_generated>1</is_generated>
     <t_lemma>připnout</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
     </gram>
     <deepord>3</deepord>
     <val_frame.rf>v#v41ivvA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1901-x4-roota2">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1897-x2-n5</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1901-x4-roota4">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>PAT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1900-4</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1908-2">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1908-2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>BEN</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>sg</number>
        <person>3</person>
        <politeness>basic</politeness>
       </gram>
       <deepord>4</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-3047-n3</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1908-3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1908-3</lex.rf>
       </a>
       <nodetype>atom</nodetype>
       <t_lemma>taky</t_lemma>
       <functor>RHEM</functor>
       <deepord>5</deepord>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1909-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1909-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1909-x2-roota1">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1906-4</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <is_generated>1</is_generated>
     <t_lemma>mít</t_lemma>
     <functor>PRED</functor>
     <proto_lemma>mít</proto_lemma>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
     </gram>
     <deepord>2</deepord>
     <val_frame.rf>v#v41chlBS</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1909-x2-roota2">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <bridging>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1906-3</target_node.rf>
         <type>SUB_SET</type>
        </LM>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1901-x4-roota1</target_node.rf>
         <type>SUB_SET</type>
        </LM>
       </bridging>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1909-x2-roota3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1906-5</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>smysl</t_lemma>
       <functor>CPHR</functor>
       <gram>
        <sempos>n.denot</sempos>
       </gram>
       <deepord>4</deepord>
       <children>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1909-x2-roota4">
         <nodetype>qcomplex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Equal</t_lemma>
         <functor>RSTR</functor>
         <deepord>6</deepord>
         <children>
          <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1909-x2-roota5">
           <a>
            <lex.rf>a#hg-25819_01.06-SCzechA-m-d-id123033</lex.rf>
           </a>
           <nodetype>coap</nodetype>
           <t_lemma>#Comma</t_lemma>
           <functor>APPS</functor>
           <deepord>8</deepord>
           <children>
            <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1909-x2-n7">
             <nodetype>complex</nodetype>
             <is_generated>1</is_generated>
             <t_lemma>#PersPron</t_lemma>
             <functor>ACT</functor>
             <gram>
              <sempos>n.pron.def.pers</sempos>
             </gram>
             <deepord>3</deepord>
             <bridging>
              <LM>
               <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1908-2</target_node.rf>
               <type>SUB_SET</type>
              </LM>
              <LM>
               <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1900-2</target_node.rf>
               <type>SUB_SET</type>
              </LM>
             </bridging>
            </LM>
            <LM id="hg-25819_01.06-SCzechT-m-d1t1912-3">
             <a>
              <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1912-3</lex.rf>
              <aux.rf>
               <LM>a#hg-25819_01.06-SCzechA-m-d1t1912-2</LM>
               <LM>a#hg-25819_01.06-SCzechA-m-d1e1909-x2-3091</LM>
              </aux.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>být</t_lemma>
             <functor>CPR</functor>
             <proto_lemma>být</proto_lemma>
             <is_member>1</is_member>
             <gram>
              <sempos>v</sempos>
              <number>pl</number>
              <deontmod>decl</deontmod>
              <tense>sim</tense>
              <aspect>proc</aspect>
              <iterativeness>it0</iterativeness>
              <person>1</person>
              <negation>neg0</negation>
             </gram>
             <deepord>5</deepord>
             <val_frame.rf>v#v41jsU</val_frame.rf>
             <children>
              <LM id="hg-25819_01.06-SCzechT-m-d1t1912-4">
               <a>
                <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1912-4</lex.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>odtamtud</t_lemma>
               <functor>DIR1</functor>
               <gram>
                <sempos>adv.pron.def</sempos>
                <degcmp>pos</degcmp>
                <negation>neg0</negation>
               </gram>
               <deepord>7</deepord>
               <coref_text>
                <LM>
                 <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1873-9</target_node.rf>
                 <type>SPEC</type>
                </LM>
               </coref_text>
              </LM>
             </children>
            </LM>
            <LM id="hg-25819_01.06-SCzechT-m-d1t1912-7">
             <a>
              <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1912-7</lex.rf>
              <aux.rf>
               <LM>a#hg-25819_01.06-SCzechA-m-d1t1912-6</LM>
               <LM>a#hg-25819_01.06-SCzechA-m-d1e1909-x2-3091</LM>
               <LM>a#hg-25819_01.06-SCzechA-m-d1t1912-2</LM>
              </aux.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>být</t_lemma>
             <functor>CPR</functor>
             <proto_lemma>být</proto_lemma>
             <is_member>1</is_member>
             <gram>
              <sempos>v</sempos>
              <number>pl</number>
              <deontmod>decl</deontmod>
              <tense>sim</tense>
              <aspect>proc</aspect>
              <iterativeness>it0</iterativeness>
              <person>1</person>
              <negation>neg0</negation>
             </gram>
             <deepord>9</deepord>
             <val_frame.rf>v#v41jsU</val_frame.rf>
             <children>
              <LM id="hg-25819_01.06-SCzechT-m-d1t1912-9">
               <a>
                <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1912-9</lex.rf>
                <aux.rf>
                 <LM>a#hg-25819_01.06-SCzechA-m-d1t1912-8</LM>
                </aux.rf>
               </a>
               <nodetype>complex</nodetype>
               <t_lemma>Terezín</t_lemma>
               <functor>DIR1</functor>
               <gram>
                <sempos>n.denot</sempos>
                <gender>inan</gender>
                <number>sg</number>
                <negation>neg0</negation>
               </gram>
               <deepord>10</deepord>
               <coref_text>
                <LM>
                 <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1912-4</target_node.rf>
                 <type>SPEC</type>
                </LM>
               </coref_text>
              </LM>
             </children>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1913-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1913-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1916-1">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1916-1</lex.rf>
     </a>
     <nodetype>atom</nodetype>
     <t_lemma>aha</t_lemma>
     <functor>PARTL</functor>
     <sentmod>enunc</sentmod>
     <deepord>1</deepord>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1917-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1917-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1917-x2-roota1">
     <nodetype>qcomplex</nodetype>
     <is_generated>1</is_generated>
     <t_lemma>#EmpVerb</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <deepord>2</deepord>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1920-3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1920-3</lex.rf>
        <aux.rf>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1920-2</LM>
         <LM>a#hg-25819_01.06-SCzechA-m-d1t1920-1</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>být</t_lemma>
       <functor>PAT</functor>
       <proto_lemma>být</proto_lemma>
       <gram>
        <sempos>v</sempos>
        <number>pl</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>1</person>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <val_frame.rf>v#v41jsU</val_frame.rf>
       <children>
        <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1917-x2-n5">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>1</deepord>
         <coref_text>
          <LM>
           <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1909-x2-n7</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1920-6">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1920-6</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>někde</t_lemma>
         <functor>LOC</functor>
         <gram>
          <sempos>adv.pron.indef</sempos>
          <indeftype>indef1</indeftype>
         </gram>
         <deepord>4</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1920-5">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1920-5</lex.rf>
          <aux.rf>
           <LM>a#hg-25819_01.06-SCzechA-m-d1t1920-4</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>práce</t_lemma>
         <functor>AIM</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>fem</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>5</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1921-x2-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1921-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1924-1">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1924-1</lex.rf>
     </a>
     <nodetype>atom</nodetype>
     <t_lemma>ano</t_lemma>
     <functor>PARTL</functor>
     <sentmod>enunc</sentmod>
     <deepord>1</deepord>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1925-x3-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1925-x3-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1932-4">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1932-4</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>připnout</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>pl</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>3</deepord>
     <val_frame.rf>v#v41ivvA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1932-2">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1932-2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>Fídler</t_lemma>
       <functor>BEN</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>anim</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1908-2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1925-x3-n6">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1901-x4-roota4</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1925-x3-roota1">
       <nodetype>qcomplex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#Oblfm</t_lemma>
       <functor>DIR3</functor>
       <deepord>4</deepord>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1932-5">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1932-5</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>hvězda</t_lemma>
       <functor>PAT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>5</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1925-x3-n6</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1932-3">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1932-3</lex.rf>
       </a>
       <nodetype>atom</nodetype>
       <t_lemma>taky</t_lemma>
       <functor>RHEM</functor>
       <deepord>6</deepord>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1925-x4-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-d1e1925-x4-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1936-1">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1936-1</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>děkovat</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>sim</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>1</person>
      <negation>neg0</negation>
     </gram>
     <deepord>2</deepord>
     <val_frame.rf>v#v41rbA</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1925-x4-n3">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_special>exoph</coref_special>
      </LM>
      <LM id="hg-25819_01.06-SCzechT-hg-25819_01-d1e1925-x4-roota1">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ADDR</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>3</deepord>
       <coref_text>
        <LM>
         <target_node.rf>hg-25819_01.06-SCzechT-m-d1t1900-2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="hg-25819_01.06-SCzechT-hg-25819_01-3099-root">
   <atree.rf>a#hg-25819_01.06-SCzechA-hg-25819_01-3099-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="hg-25819_01.06-SCzechT-m-d1t1936-5">
     <a>
      <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1936-5</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>končit</t_lemma>
     <functor>PRED</functor>
     <proto_lemma>končit</proto_lemma>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>sim</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>1</deepord>
     <val_frame.rf>v#v41bplF</val_frame.rf>
     <children>
      <LM id="hg-25819_01.06-SCzechT-m-d1t1936-8">
       <a>
        <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1936-8</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>kazeta</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>fem</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <children>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1936-7">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1936-7</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>první</t_lemma>
         <functor>RSTR</functor>
         <gram>
          <sempos>adj.quant.def</sempos>
          <gender>fem</gender>
          <number>sg</number>
          <numertype>ord</numertype>
         </gram>
         <deepord>2</deepord>
        </LM>
        <LM id="hg-25819_01.06-SCzechT-m-d1t1945-1">
         <a>
          <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1945-1</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>rozhovor</t_lemma>
         <functor>RSTR</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>inan</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>4</deepord>
         <children>
          <LM id="hg-25819_01.06-SCzechT-m-d1t1945-5">
           <a>
            <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1945-5</lex.rf>
            <aux.rf>
             <LM>a#hg-25819_01.06-SCzechA-m-d1t1945-2</LM>
            </aux.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>Šelerová</t_lemma>
           <functor>RSTR</functor>
           <gram>
            <sempos>n.denot</sempos>
            <gender>nr</gender>
            <number>nr</number>
            <negation>neg0</negation>
           </gram>
           <deepord>6</deepord>
           <coref_text>
            <LM>
             <target_node.rf>hg-25819_01.06-SCzechT-hg-25819_01-d1e1925-x4-roota1</target_node.rf>
             <type>SPEC</type>
            </LM>
           </coref_text>
           <children>
            <LM id="hg-25819_01.06-SCzechT-m-d1t1945-3">
             <a>
              <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1945-3</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>paní</t_lemma>
             <functor>RSTR</functor>
             <gram>
              <sempos>n.denot</sempos>
              <gender>fem</gender>
              <number>sg</number>
              <negation>neg0</negation>
             </gram>
             <deepord>5</deepord>
            </LM>
            <LM id="hg-25819_01.06-SCzechT-m-d1t1945-4">
             <a>
              <lex.rf>a#hg-25819_01.06-SCzechA-m-d1t1945-4</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>Marie</t_lemma>
             <functor>RSTR</functor>
             <gram>
              <sempos>n.denot</sempos>
              <gender>fem</gender>
              <number>sg</number>
              <negation>neg0</negation>
             </gram>
             <deepord>7</deepord>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
 </trees>
</tdata>
