<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="tdata_c2_schema.xml" />
  <references>
   <reffile id="a" name="adata" href="pdtsc_013_2.06.a" />
   <reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
  </references>
 </head>
 <meta/>
 <trees>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-642-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-642-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-m-d1t1256-17">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-17</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>a</t_lemma>
     <functor>CONJ</functor>
     <deepord>11</deepord>
     <discourse>
      <LM>
       <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1258-4</target_node.rf>
       <type>discourse</type>
       <start_range>0</start_range>
       <target_range>0</target_range>
       <discourse_type>preced</discourse_type>
       <sense_PDTB3>Temporal.Asynchronous.Precedence</sense_PDTB3>
       <comment>PHASE:2 MANUAL</comment>
       <src>A_I_A</src>
       <t-connectors.rf>
        <LM>ml-16379_05.06-SCzechT-m-d1t1258-2</LM>
       </t-connectors.rf>
      </LM>
     </discourse>
     <children>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1256-2">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>ten</t_lemma>
       <functor>ACT</functor>
       <proto_lemma>ten</proto_lemma>
       <gram>
        <sempos>n.pron.def.demon</sempos>
        <gender>nr</gender>
        <number>sg</number>
       </gram>
       <deepord>1</deepord>
       <coref_special>exoph</coref_special>
       <children>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1256-4">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-4</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>mít</t_lemma>
         <functor>RSTR</functor>
         <proto_lemma>mít</proto_lemma>
         <gram>
          <sempos>v</sempos>
          <number>sg</number>
          <deontmod>decl</deontmod>
          <tense>ant</tense>
          <aspect>proc</aspect>
          <iterativeness>it0</iterativeness>
          <person>3</person>
          <negation>neg0</negation>
         </gram>
         <deepord>2</deepord>
         <val_frame.rf>v#v41chlO</val_frame.rf>
         <children>
          <LM id="ml-16379_05.06-SCzechT-ml-16379_05-642-roota1">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-3</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>co</t_lemma>
           <functor>ACT</functor>
           <proto_lemma>co</proto_lemma>
           <gram>
            <sempos>n.pron.indef</sempos>
           </gram>
           <deepord>3</deepord>
           <coref_gram.rf>
            <LM>ml-16379_05.06-SCzechT-m-d1t1256-2</LM>
           </coref_gram.rf>
          </LM>
          <LM id="ml-16379_05.06-SCzechT-m-d1t1256-7">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-7</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>obličej</t_lemma>
           <functor>PAT</functor>
           <gram>
            <sempos>n.denot</sempos>
            <gender>inan</gender>
            <number>sg</number>
            <negation>neg0</negation>
           </gram>
           <deepord>5</deepord>
           <children>
            <LM id="ml-16379_05.06-SCzechT-m-d1t1256-6">
             <a>
              <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-6</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>umělý</t_lemma>
             <functor>RSTR</functor>
             <gram>
              <sempos>adj.denot</sempos>
              <degcmp>pos</degcmp>
              <negation>neg0</negation>
             </gram>
             <deepord>4</deepord>
            </LM>
           </children>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1256-16">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-16</lex.rf>
        <aux.rf>
         <LM>a#ml-16379_05.06-SCzechA-m-d1t1256-10</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>vypůjčit_si</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>cpl</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>10</deepord>
       <val_frame.rf>v#v41ossA</val_frame.rf>
       <children>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1256-12">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-12</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>kolo</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>neut</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>7</deepord>
         <coref_special>exoph</coref_special>
         <children>
          <LM id="ml-16379_05.06-SCzechT-m-d1t1256-11">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-11</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>ten</t_lemma>
           <functor>RSTR</functor>
           <proto_lemma>ten</proto_lemma>
           <gram>
            <sempos>n.pron.def.demon</sempos>
            <gender>neut</gender>
            <number>sg</number>
           </gram>
           <deepord>6</deepord>
          </LM>
         </children>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1256-14">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-14</lex.rf>
          <aux.rf>
           <LM>a#ml-16379_05.06-SCzechA-m-d1t1256-13</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>ORIG</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>nr</gender>
          <number>sg</number>
          <person>3</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>8</deepord>
         <coref_special>exoph</coref_special>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1256-15">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-15</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>jednou</t_lemma>
         <functor>TWHEN</functor>
         <gram>
          <sempos>adj.quant.def</sempos>
          <numertype>basic</numertype>
         </gram>
         <deepord>9</deepord>
        </LM>
       </children>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1256-22">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-22</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>udělat</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>cpl</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>15</deepord>
       <discourse>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1256-16</target_node.rf>
         <type>discourse</type>
         <start_range>0</start_range>
         <target_range>0</target_range>
         <discourse_type>conj</discourse_type>
         <sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
         <comment>PHASE:1</comment>
         <src>A_H_A</src>
         <t-connectors.rf>
          <LM>ml-16379_05.06-SCzechT-m-d1t1256-17</LM>
         </t-connectors.rf>
        </LM>
       </discourse>
       <val_frame.rf>v#v41mhqI</val_frame.rf>
       <children>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1256-18">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-18</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>něco</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>n.pron.indef</sempos>
          <gender>neut</gender>
          <number>sg</number>
          <indeftype>indef1</indeftype>
          <person>3</person>
         </gram>
         <deepord>12</deepord>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1256-19">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-19</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>BEN</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>nr</gender>
          <number>sg</number>
          <person>3</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>13</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1256-14</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1256-21">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1256-21</lex.rf>
          <aux.rf>
           <LM>a#ml-16379_05.06-SCzechA-m-d1t1256-20</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>LOC</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>nr</gender>
          <number>sg</number>
          <person>3</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>14</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1256-12</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2783-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-2783-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-m-d1t1258-4">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1258-4</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>přijít</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>cpl</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>4</deepord>
     <val_frame.rf>v#v41isgP</val_frame.rf>
     <children>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1258-2">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1258-2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>potom</t_lemma>
       <functor>TWHEN</functor>
       <proto_lemma>potom</proto_lemma>
       <gram>
        <sempos>adv.pron.def</sempos>
       </gram>
       <deepord>1</deepord>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1258-7">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1258-7</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>zase</t_lemma>
       <functor>TWHEN</functor>
       <gram>
        <sempos>adv.denot.ngrad.nneg</sempos>
        <negation>neg0</negation>
       </gram>
       <deepord>2</deepord>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2783-n5">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>3</deepord>
       <coref_text>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-ml-16379_05-642-roota1</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2783-roota1">
       <nodetype>qcomplex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#Oblfm</t_lemma>
       <functor>DIR3</functor>
       <deepord>5</deepord>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2798-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-2798-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-m-d1t1258-15">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1258-15</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>říkat</t_lemma>
     <functor>PRED</functor>
     <proto_lemma>říkat</proto_lemma>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>4</deepord>
     <val_frame.rf>v#v41kejB</val_frame.rf>
     <children>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1258-14">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1258-14</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>Kleemann</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>nr</gender>
        <number>nr</number>
        <negation>neg0</negation>
       </gram>
       <deepord>1</deepord>
       <coref_text>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1256-19</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1258-11">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1258-11</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>ADDR</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>sg</number>
        <person>1</person>
        <politeness>basic</politeness>
       </gram>
       <deepord>2</deepord>
       <coref_special>exoph</coref_special>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1258-12">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1258-12</lex.rf>
       </a>
       <nodetype>atom</nodetype>
       <t_lemma>ještě</t_lemma>
       <functor>RHEM</functor>
       <deepord>3</deepord>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1260-1">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>půjčovat</t_lemma>
       <functor>EFF</functor>
       <sentmod>imper</sentmod>
       <is_dsp_root>1</is_dsp_root>
       <gram>
        <sempos>v</sempos>
        <deontmod>decl</deontmod>
        <tense>nil</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>2</person>
        <negation>neg1</negation>
       </gram>
       <deepord>6</deepord>
       <val_frame.rf>v#v41jdpA</val_frame.rf>
       <children>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2798-roota2">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>5</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1258-11</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2798-roota1">
         <nodetype>atom</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Neg</t_lemma>
         <functor>RHEM</functor>
         <deepord>7</deepord>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1260-2">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-2</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>nr</gender>
          <number>sg</number>
          <person>3</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>8</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1256-21</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1260-3">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-3</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>nikdo</t_lemma>
         <functor>ADDR</functor>
         <gram>
          <sempos>n.pron.indef</sempos>
          <gender>anim</gender>
          <number>sg</number>
          <indeftype>negat</indeftype>
          <person>3</person>
         </gram>
         <deepord>9</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2310-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-2310-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-m-d1t1260-7">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-7</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>mít</t_lemma>
     <functor>PRED</functor>
     <proto_lemma>mít</proto_lemma>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>sim</tense>
      <aspect>proc</aspect>
      <iterativeness>it0</iterativeness>
      <person>2</person>
      <negation>neg0</negation>
     </gram>
     <deepord>3</deepord>
     <discourse>
      <LM>
       <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1260-17</target_node.rf>
       <type>discourse</type>
       <start_range>0</start_range>
       <target_range>0</target_range>
       <discourse_type>preced</discourse_type>
       <sense_PDTB3>Temporal.Asynchronous.Precedence</sense_PDTB3>
       <comment>PHASE:3 TYPECHECKED</comment>
       <src>A_I_A</src>
       <t-connectors.rf>
        <LM>ml-16379_05.06-SCzechT-m-2321-2524</LM>
       </t-connectors.rf>
      </LM>
     </discourse>
     <val_frame.rf>v#v41chlF</val_frame.rf>
     <children>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1260-6">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-6</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>tady</t_lemma>
       <functor>LOC</functor>
       <proto_lemma>tady</proto_lemma>
       <gram>
        <sempos>adv.pron.def</sempos>
       </gram>
       <deepord>1</deepord>
       <coref_special>exoph</coref_special>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2310-n5">
       <nodetype>complex</nodetype>
       <is_generated>1</is_generated>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-ml-16379_05-2798-roota2</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1260-8">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-8</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>klíč</t_lemma>
       <functor>PAT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>4</deepord>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2321-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-2321-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2321-roota1">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-2321-2525</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>#Comma</t_lemma>
     <functor>CONJ</functor>
     <deepord>5</deepord>
     <children>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1260-17">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-17</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>přijít</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>cpl</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <val_frame.rf>v#v41isgP</val_frame.rf>
       <children>
        <LM id="ml-16379_05.06-SCzechT-m-2321-2524">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-2321-2524</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>pak</t_lemma>
         <functor>TWHEN</functor>
         <gram>
          <sempos>adv.pron.def</sempos>
         </gram>
         <deepord>1</deepord>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2321-n14">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>2</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1258-14</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2321-roota2">
         <nodetype>qcomplex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Oblfm</t_lemma>
         <functor>DIR3</functor>
         <deepord>4</deepord>
        </LM>
       </children>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d-id123768">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d-id123768</lex.rf>
       </a>
       <nodetype>coap</nodetype>
       <t_lemma>#Comma</t_lemma>
       <functor>CONJ</functor>
       <is_member>1</is_member>
       <deepord>13</deepord>
       <children>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1260-18">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-18</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>nr</gender>
          <number>sg</number>
          <person>1</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>6</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-ml-16379_05-2310-n5</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1260-22">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-22</lex.rf>
          <aux.rf>
           <LM>a#ml-16379_05.06-SCzechA-m-d1t1260-19</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>skočit</t_lemma>
         <functor>PRED</functor>
         <sentmod>enunc</sentmod>
         <is_member>1</is_member>
         <gram>
          <sempos>v</sempos>
          <number>sg</number>
          <deontmod>decl</deontmod>
          <tense>ant</tense>
          <aspect>cpl</aspect>
          <iterativeness>it0</iterativeness>
          <person>1</person>
          <negation>neg0</negation>
         </gram>
         <deepord>11</deepord>
         <val_frame.rf>v#v41kraF</val_frame.rf>
         <children>
          <LM id="ml-16379_05.06-SCzechT-m-d1t1260-20">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-20</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>#PersPron</t_lemma>
           <functor>BEN</functor>
           <gram>
            <sempos>n.pron.def.pers</sempos>
            <gender>nr</gender>
            <number>sg</number>
            <person>3</person>
            <politeness>basic</politeness>
           </gram>
           <deepord>7</deepord>
           <coref_text>
            <LM>
             <target_node.rf>ml-16379_05.06-SCzechT-ml-16379_05-2321-n14</target_node.rf>
             <type>SPEC</type>
            </LM>
           </coref_text>
          </LM>
          <LM id="ml-16379_05.06-SCzechT-m-d1t1260-21">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-21</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>vždycky</t_lemma>
           <functor>THO</functor>
           <gram>
            <sempos>adv.pron.indef</sempos>
            <degcmp>pos</degcmp>
            <indeftype>total1</indeftype>
            <negation>neg0</negation>
           </gram>
           <deepord>8</deepord>
          </LM>
          <LM id="ml-16379_05.06-SCzechT-m-d1t1260-25">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-25</lex.rf>
            <aux.rf>
             <LM>a#ml-16379_05.06-SCzechA-m-d1t1260-23</LM>
            </aux.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>klíč</t_lemma>
           <functor>INTT</functor>
           <gram>
            <sempos>n.denot</sempos>
            <gender>inan</gender>
            <number>sg</number>
            <negation>neg0</negation>
           </gram>
           <deepord>10</deepord>
           <coref_text>
            <LM>
             <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1260-8</target_node.rf>
             <type>SPEC</type>
            </LM>
           </coref_text>
           <children>
            <LM id="ml-16379_05.06-SCzechT-m-d1t1260-24">
             <a>
              <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-24</lex.rf>
             </a>
             <nodetype>complex</nodetype>
             <t_lemma>ten</t_lemma>
             <functor>RSTR</functor>
             <proto_lemma>ten</proto_lemma>
             <gram>
              <sempos>n.pron.def.demon</sempos>
              <gender>inan</gender>
              <number>sg</number>
             </gram>
             <deepord>9</deepord>
            </LM>
           </children>
          </LM>
          <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2321-roota4">
           <nodetype>qcomplex</nodetype>
           <is_generated>1</is_generated>
           <t_lemma>#Oblfm</t_lemma>
           <functor>DIR3</functor>
           <deepord>12</deepord>
          </LM>
         </children>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1260-27">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-27</lex.rf>
          <aux.rf>
           <LM>a#ml-16379_05.06-SCzechA-m-d1t1260-28</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>donést</t_lemma>
         <functor>PRED</functor>
         <sentmod>enunc</sentmod>
         <is_member>1</is_member>
         <gram>
          <sempos>v</sempos>
          <number>sg</number>
          <deontmod>decl</deontmod>
          <tense>ant</tense>
          <aspect>cpl</aspect>
          <iterativeness>it0</iterativeness>
          <person>1</person>
          <negation>neg0</negation>
         </gram>
         <deepord>14</deepord>
         <val_frame.rf>v#v41aboA</val_frame.rf>
         <children>
          <LM id="ml-16379_05.06-SCzechT-m-d1t1260-29">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-29</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>#PersPron</t_lemma>
           <functor>ADDR</functor>
           <gram>
            <sempos>n.pron.def.pers</sempos>
            <gender>nr</gender>
            <number>sg</number>
            <person>3</person>
            <politeness>basic</politeness>
           </gram>
           <deepord>15</deepord>
           <coref_text>
            <LM>
             <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1260-20</target_node.rf>
             <type>SPEC</type>
            </LM>
           </coref_text>
          </LM>
          <LM id="ml-16379_05.06-SCzechT-m-2321-2528">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-2321-2528</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>#PersPron</t_lemma>
           <functor>PAT</functor>
           <gram>
            <sempos>n.pron.def.pers</sempos>
            <gender>nr</gender>
            <number>sg</number>
            <person>3</person>
            <politeness>basic</politeness>
           </gram>
           <deepord>16</deepord>
           <coref_text>
            <LM>
             <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1260-25</target_node.rf>
             <type>SPEC</type>
            </LM>
           </coref_text>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2532-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-2532-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-m-d1t1262-3">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-3</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>dát</t_lemma>
     <functor>PRED</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>v</sempos>
      <number>sg</number>
      <deontmod>decl</deontmod>
      <tense>ant</tense>
      <aspect>cpl</aspect>
      <iterativeness>it0</iterativeness>
      <person>3</person>
      <negation>neg0</negation>
     </gram>
     <deepord>4</deepord>
     <discourse>
      <LM>
       <target_node.rf>ml-16379_05.06-SCzechT-ml-16379_05-2321-roota1</target_node.rf>
       <type>discourse</type>
       <start_range>0</start_range>
       <target_range>0</target_range>
       <discourse_type>corr</discourse_type>
       <sense_PDTB3>Expansion.Substitution.Arg2-as-subst</sense_PDTB3>
       <comment>PHASE:2 MANUAL</comment>
       <src>A_I_A</src>
       <t-connectors.rf>
        <LM>ml-16379_05.06-SCzechT-m-d1t1260-30</LM>
       </t-connectors.rf>
      </LM>
     </discourse>
     <val_frame.rf>v#v41plI</val_frame.rf>
     <children>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1260-30">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1260-30</lex.rf>
       </a>
       <nodetype>atom</nodetype>
       <t_lemma>vlastně</t_lemma>
       <functor>ATT</functor>
       <deepord>1</deepord>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1262-1">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-1</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>ACT</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>sg</number>
        <person>3</person>
        <politeness>basic</politeness>
       </gram>
       <deepord>2</deepord>
       <coref_text>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1260-29</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1262-2">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-2</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>#PersPron</t_lemma>
       <functor>ADDR</functor>
       <gram>
        <sempos>n.pron.def.pers</sempos>
        <gender>nr</gender>
        <number>sg</number>
        <person>1</person>
        <politeness>basic</politeness>
       </gram>
       <deepord>3</deepord>
       <coref_text>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1260-18</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1262-4">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-4</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>klíč</t_lemma>
       <functor>PAT</functor>
       <gram>
        <sempos>n.denot</sempos>
        <gender>inan</gender>
        <number>sg</number>
        <negation>neg0</negation>
       </gram>
       <deepord>5</deepord>
       <coref_text>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-m-2321-2528</target_node.rf>
         <type>SPEC</type>
        </LM>
       </coref_text>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2442-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-2442-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-m-d1t1262-18">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-18</lex.rf>
      <aux.rf>
       <LM>a#ml-16379_05.06-SCzechA-m-d1t1262-13</LM>
      </aux.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>buď_nebo</t_lemma>
     <functor>DISJ</functor>
     <deepord>5</deepord>
     <children>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1262-15">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-15</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>mít</t_lemma>
       <functor>PRED</functor>
       <proto_lemma>mít</proto_lemma>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>3</deepord>
       <val_frame.rf>v#v41chlJ</val_frame.rf>
       <children>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1262-14">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-14</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>nr</gender>
          <number>sg</number>
          <person>3</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>1</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1262-4</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2442-n10">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>2</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1262-1</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1262-17">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-17</lex.rf>
          <aux.rf>
           <LM>a#ml-16379_05.06-SCzechA-m-d1t1262-16</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>LOC</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>inher</gender>
          <number>inher</number>
          <person>inher</person>
          <politeness>inher</politeness>
         </gram>
         <deepord>4</deepord>
         <coref_gram.rf>
          <LM>ml-16379_05.06-SCzechT-ml-16379_05-2442-n10</LM>
         </coref_gram.rf>
        </LM>
       </children>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1262-19">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-19</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>viset</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>7</deepord>
       <discourse>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1262-15</target_node.rf>
         <type>discourse</type>
         <start_range>0</start_range>
         <target_range>0</target_range>
         <discourse_type>disjalt</discourse_type>
         <sense_PDTB3>Expansion.Disjunction</sense_PDTB3>
         <comment>PHASE:2 MANUAL</comment>
         <src>A_H_A</src>
         <t-connectors.rf>
          <LM>ml-16379_05.06-SCzechT-m-d1t1262-18</LM>
         </t-connectors.rf>
        </LM>
       </discourse>
       <val_frame.rf>v#v41nlsC</val_frame.rf>
       <children>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-2442-n12">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>6</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1262-14</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1262-22">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-22</lex.rf>
          <aux.rf>
           <LM>a#ml-16379_05.06-SCzechA-m-d1t1262-20</LM>
          </aux.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>místo</t_lemma>
         <functor>LOC</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>neut</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>9</deepord>
         <children>
          <LM id="ml-16379_05.06-SCzechT-m-d1t1262-21">
           <a>
            <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1262-21</lex.rf>
           </a>
           <nodetype>complex</nodetype>
           <t_lemma>určitý</t_lemma>
           <functor>RSTR</functor>
           <gram>
            <sempos>adj.denot</sempos>
            <degcmp>pos</degcmp>
            <negation>neg0</negation>
           </gram>
           <deepord>8</deepord>
          </LM>
         </children>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-660-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-660-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-m-d1t1265-7">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1265-7</lex.rf>
     </a>
     <nodetype>coap</nodetype>
     <t_lemma>a</t_lemma>
     <functor>CONJ</functor>
     <deepord>5</deepord>
     <children>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1265-6">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1265-6</lex.rf>
        <aux.rf>
         <LM>a#ml-16379_05.06-SCzechA-m-d1t1265-2</LM>
        </aux.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>dovézt</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>cpl</aspect>
        <iterativeness>it0</iterativeness>
        <person>1</person>
        <negation>neg0</negation>
       </gram>
       <deepord>2</deepord>
       <val_frame.rf>v#v41ailA</val_frame.rf>
       <children>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-660-n7">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>1</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1262-2</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1265-3">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1265-3</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>#PersPron</t_lemma>
         <functor>ADDR</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
          <gender>nr</gender>
          <number>sg</number>
          <person>3</person>
          <politeness>basic</politeness>
         </gram>
         <deepord>3</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1262-17</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-m-d1t1265-5">
         <a>
          <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1265-5</lex.rf>
         </a>
         <nodetype>complex</nodetype>
         <t_lemma>kolo</t_lemma>
         <functor>PAT</functor>
         <gram>
          <sempos>n.denot</sempos>
          <gender>neut</gender>
          <number>sg</number>
          <negation>neg0</negation>
         </gram>
         <deepord>4</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1260-2</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
       </children>
      </LM>
      <LM id="ml-16379_05.06-SCzechT-m-d1t1265-9">
       <a>
        <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1265-9</lex.rf>
       </a>
       <nodetype>complex</nodetype>
       <t_lemma>jet</t_lemma>
       <functor>PRED</functor>
       <sentmod>enunc</sentmod>
       <is_member>1</is_member>
       <gram>
        <sempos>v</sempos>
        <number>sg</number>
        <deontmod>decl</deontmod>
        <tense>ant</tense>
        <aspect>proc</aspect>
        <iterativeness>it0</iterativeness>
        <person>3</person>
        <negation>neg0</negation>
       </gram>
       <deepord>7</deepord>
       <discourse>
        <LM>
         <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1265-6</target_node.rf>
         <type>discourse</type>
         <start_range>0</start_range>
         <target_range>0</target_range>
         <discourse_type>conj</discourse_type>
         <sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
         <comment>PHASE:1</comment>
         <src>A_H_A</src>
         <t-connectors.rf>
          <LM>ml-16379_05.06-SCzechT-m-d1t1265-7</LM>
         </t-connectors.rf>
        </LM>
       </discourse>
       <val_frame.rf>v#v41bhuF</val_frame.rf>
       <children>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-660-n9">
         <nodetype>complex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#PersPron</t_lemma>
         <functor>ACT</functor>
         <gram>
          <sempos>n.pron.def.pers</sempos>
         </gram>
         <deepord>6</deepord>
         <coref_text>
          <LM>
           <target_node.rf>ml-16379_05.06-SCzechT-m-d1t1265-3</target_node.rf>
           <type>SPEC</type>
          </LM>
         </coref_text>
        </LM>
        <LM id="ml-16379_05.06-SCzechT-ml-16379_05-660-roota1">
         <nodetype>qcomplex</nodetype>
         <is_generated>1</is_generated>
         <t_lemma>#Oblfm</t_lemma>
         <functor>DIR3</functor>
         <deepord>8</deepord>
        </LM>
       </children>
      </LM>
     </children>
    </LM>
   </children>
  </LM>
  <LM id="ml-16379_05.06-SCzechT-ml-16379_05-d1e1268-x2-root">
   <atree.rf>a#ml-16379_05.06-SCzechA-ml-16379_05-d1e1268-x2-root</atree.rf>
   <deepord>0</deepord>
   <children>
    <LM id="ml-16379_05.06-SCzechT-m-d1t1271-1">
     <a>
      <lex.rf>a#ml-16379_05.06-SCzechA-m-d1t1271-1</lex.rf>
     </a>
     <nodetype>complex</nodetype>
     <t_lemma>stop</t_lemma>
     <functor>DENOM</functor>
     <sentmod>enunc</sentmod>
     <gram>
      <sempos>n.denot</sempos>
      <gender>inan</gender>
      <number>sg</number>
      <negation>neg0</negation>
     </gram>
     <deepord>1</deepord>
    </LM>
   </children>
  </LM>
 </trees>
</tdata>
