<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94203_30.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln94203-30-p1s1">
<atree.rf>a#a-ln94203-30-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94203-30-p1s1w1">
<a>
<lex.rf>a#a-ln94203-30-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>archeolog</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln94203-30-p1s1w3">
<a>
<lex.rf>a#a-ln94203-30-p1s1w3</lex.rf>
<aux.rf>
<LM>a#a-ln94203-30-p1s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zámek</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94203-30-p1s1w5">
<a>
<lex.rf>a#a-ln94203-30-p1s1w5</lex.rf>
<aux.rf>
<LM>a#a-ln94203-30-p1s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Plumlov</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94203-30-p2s1A">
<atree.rf>a#a-ln94203-30-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94203-30-p2s1Aw1">
<a>
<lex.rf>a#a-ln94203-30-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Plumlov</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94203-30-p1s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94203-30-p2s1Aw3">
<a>
<lex.rf>a#a-ln94203-30-p2s1Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pet</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>nr</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94203-30-p2s1B">
<atree.rf>a#a-ln94203-30-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94203-30-l1A">
<type>time</type>
<tnode.rfs>
<LM>t-ln94203-30-p2s1Bw6</LM>
<LM>t-ln94203-30-p2s1Bw8</LM>
<LM>t-ln94203-30-p2s1Bw9</LM>
<LM>t-ln94203-30-p2s1Bw11</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94203-30-p2s1Bw12">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94203-30-p2s1Bw2">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>objev</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94203-30-p2s1Bw1">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>četný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94203-30-p2s1Bw4">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střep</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94203-30-p2s1Bw3">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>keramický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94203-30-p2s1Bw11">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw11</lex.rf>
<aux.rf>
<LM>a#a-ln94203-30-p2s1Bw5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>století</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94203-30-p2s1Bw8">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw8</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>až</t_lemma>
<functor>OPER</functor>
<deepord>7</deepord>
<children>
<LM id="t-ln94203-30-p2s1Bw6">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>15</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94203-30-p2s1Bw9">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>17</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94203-30-p2s1Bw13">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výsledek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94203-30-p2s1Bw15">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výzkum</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94203-30-p2s1Bw14">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>archeologický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln94203-30-p2s1Bw16">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovník</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94203-30-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94203-30-p2s1Bw18">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>muzeum</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln94203-30-p2s1Bw17">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prostějovský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94203-30-p2s1Bw20">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw20</lex.rf>
<aux.rf>
<LM>a#a-ln94203-30-p2s1Bw19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zámek</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94203-30-p1s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94203-30-p2s1Bw22">
<a>
<lex.rf>a#a-ln94203-30-p2s1Bw22</lex.rf>
<aux.rf>
<LM>a#a-ln94203-30-p2s1Bw21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Plumlov</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94203-30-p2s1Aw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94203-30-p2s2">
<atree.rf>a#a-ln94203-30-p2s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94203-30-p2s2w5">
<a>
<lex.rf>a#a-ln94203-30-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41jsU</val_frame.rf>
<children>
<LM id="t-ln94203-30-p2s2w4">
<a>
<lex.rf>a#a-ln94203-30-p2s2w4</lex.rf>
<aux.rf>
<LM>a#a-ln94203-30-p2s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skvost</t_lemma>
<functor>LOC</functor>
<subfunctor>betw</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94203-30-p2s2w2">
<a>
<lex.rf>a#a-ln94203-30-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nalezený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94203-30-p2s2w3">
<a>
<lex.rf>a#a-ln94203-30-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>archeologický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94203-30-p2s2w6">
<a>
<lex.rf>a#a-ln94203-30-p2s2w6</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94203-30-p2s2w10">
<a>
<lex.rf>a#a-ln94203-30-p2s2w10</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>9</deepord>
<children>
<LM id="t-ln94203-30-p2s2w9">
<a>
<lex.rf>a#a-ln94203-30-p2s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nádoba</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94203-30-p2s2w8">
<a>
<lex.rf>a#a-ln94203-30-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skleněný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94203-30-p2s2w7">
<a>
<lex.rf>a#a-ln94203-30-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>několik</t_lemma>
<functor>RSTR</functor>
<proto_lemma>kolik</proto_lemma>
<gram>
<sempos>adj.quant.indef</sempos>
<indeftype>indef1</indeftype>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94203-30-p2s2w11">
<a>
<lex.rf>a#a-ln94203-30-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kus</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94203-30-p2s2w13">
<a>
<lex.rf>a#a-ln94203-30-p2s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střela</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94203-30-p2s2w12">
<a>
<lex.rf>a#a-ln94203-30-p2s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>středověký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln94203-30-p2s2w14">
<a>
<lex.rf>a#a-ln94203-30-p2s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svědčící</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94203-30-p2s2w17">
<a>
<lex.rf>a#a-ln94203-30-p2s2w17</lex.rf>
<aux.rf>
<LM>a#a-ln94203-30-p2s2w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obléhání</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41dqlA</val_frame.rf>
<children>
<LM id="t-ln94203-30-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln94203-30-p2s2a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln94203-30-p2s2w16">
<a>
<lex.rf>a#a-ln94203-30-p2s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>někdejší</t_lemma>
<functor>TWHEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
