<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln95047_028.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>sport</genre>
</meta>
<trees>
<LM id="t-ln95047-028-p1s1">
<atree.rf>a#a-ln95047-028-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p1s1w2">
<a>
<lex.rf>a#a-ln95047-028-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>problém</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln95047-028-p1s1w1">
<a>
<lex.rf>a#a-ln95047-028-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vítkovický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95047-028-p1s1w4">
<a>
<lex.rf>a#a-ln95047-028-p1s1w4</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p1s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sestava</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1A">
<atree.rf>a#a-ln95047-028-p2s1A</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95047-028-l1A">
<basic-form>hokejová extraliga</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95047-028-p2s1Aw5</LM>
<LM>t-ln95047-028-p2s1Aw6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95047-028-p2s1Aw7">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s1Aw1">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šlágr</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95047-028-p2s1Aw4">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kolo</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95047-028-p2s1Aw6">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>extraliga</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95047-028-p2s1Aw5">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hokejový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Aw2">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>42</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Aw8">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zápas</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95047-028-p2s1Aw10">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tým</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95047-028-p2s1Aw9">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ostravský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Aw12">
<a>
<lex.rf>a#a-ln95047-028-p2s1Aw12</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Aw11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sparta</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1B">
<atree.rf>a#a-ln95047-028-p2s1B</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p2s1Bw1">
<a>
<lex.rf>a#a-ln95047-028-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw12</target_node.rf>
<type>REST</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1C">
<atree.rf>a#a-ln95047-028-p2s1C</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95047-028-l2A">
<basic-form>hokejová extraliga</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95047-028-p2s1Cw6</LM>
<LM>t-ln95047-028-p2s1Cw7</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95047-028-l3A">
<basic-form>play off</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95047-028-p2s1Cw26</LM>
<LM>t-ln95047-028-p2s1Cw27</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95047-028-p2s1Cw42">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw42</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jít</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>33</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p2s1Cw28</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>confr</discourse_type>
<sense_PDTB3>Comparison.Contrast</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-ln95047-028-p2s1Cw1</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41bikX</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s1Cw28">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw28</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>21</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw18">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw18</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw11</LM>
<LM>a#a-ln95047-028-p2s1Cw1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>myslet</t_lemma>
<functor>CONTRD</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41ckjD</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s1Cw4">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mužstvo</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw5">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tabulka</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw8">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw8</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Bracket</t_lemma>
<functor>APPS</functor>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95047-028-p2s1Cw7">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>extraliga</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw6">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hokejový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Cw9">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ELH</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Cw3">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šest</t_lemma>
<functor>RSTR</functor>
<proto_lemma>šest</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95047-028-p2s1Cw2">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Cw14">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw14</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zápas</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw8</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln95047-028-p2s1Cw17">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kolo</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95047-028-p2s1Cw15">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>42</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Cw13">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dnešní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Cw19">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw19</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>především</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95047-028-p2s1Cw21">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw21</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vylepšení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41ohvA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s1Ca0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln95047-028-p2s1Cw22">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pozice</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw24">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw24</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vstup</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw26">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw26</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw25</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>play</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p2s1Cw8</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln95047-028-p2s1Cw27">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>off</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>nr</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Ca1">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw18</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw11</LM>
<LM>a#a-ln95047-028-p2s1Cw1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>myslet</t_lemma>
<functor>CONTRD</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>26</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p2s1Cw18</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95047-028-p2s1Cw28</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41ckjD</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s1Cw30">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pardubice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>22</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw29">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předposlední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
</LM>
<LM id="t-ln95047-028-p2s1Cw33">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw33</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw31</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jihlava</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw32">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw32</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Cw34">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw34</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>už</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>27</deepord>
</LM>
<LM id="t-ln95047-028-p2s1Cw35">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw35</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>jenom</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>28</deepord>
</LM>
<LM id="t-ln95047-028-p2s1Cw37">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw37</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw36</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prestiž</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>29</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Cw41">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw41</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tým</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>30</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw12</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw10</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln95047-028-p2s1Cw40">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw40</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>31</deepord>
<children>
<LM id="t-ln95047-028-p2s1Cw39">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw39</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>málo</t_lemma>
<functor>EXT</functor>
<proto_lemma>málo</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>sup</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>32</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s1Cw44">
<a>
<lex.rf>a#a-ln95047-028-p2s1Cw44</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s1Cw43</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>pos</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>34</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s2">
<atree.rf>a#a-ln95047-028-p2s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p2s2w7">
<a>
<lex.rf>a#a-ln95047-028-p2s2w7</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="t-ln95047-028-p2s2w5">
<a>
<lex.rf>a#a-ln95047-028-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s2w1">
<a>
<lex.rf>a#a-ln95047-028-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střetnutí</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41lngA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_gram.rf>
<LM>t-ln95047-028-p2s2w3</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95047-028-p2s2w3">
<a>
<lex.rf>a#a-ln95047-028-p2s2w3</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Dash</t_lemma>
<functor>CONTRA</functor>
<deepord>4</deepord>
<children>
<LM id="t-ln95047-028-p2s2w2">
<a>
<lex.rf>a#a-ln95047-028-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sparta</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p2s2w4">
<a>
<lex.rf>a#a-ln95047-028-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Vítkovice</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Aw10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s2w6">
<a>
<lex.rf>a#a-ln95047-028-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>existenční</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s2w11">
<a>
<lex.rf>a#a-ln95047-028-p2s2w11</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s2w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p2s2w5</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95047-028-p2s2w7</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41lilA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s2w8">
<a>
<lex.rf>a#a-ln95047-028-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohra</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln95047-028-p2s2w10">
<a>
<lex.rf>a#a-ln95047-028-p2s2w10</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>pravděpodobně</t_lemma>
<functor>MOD</functor>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln95047-028-p2s2w12">
<a>
<lex.rf>a#a-ln95047-028-p2s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>postup</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s3">
<atree.rf>a#a-ln95047-028-p2s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p2s3w10">
<a>
<lex.rf>a#a-ln95047-028-p2s3w10</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="t-ln95047-028-p2s3w1">
<a>
<lex.rf>a#a-ln95047-028-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Slavia</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p2s1Cw41</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-ln95047-028-p2s3w5">
<a>
<lex.rf>a#a-ln95047-028-p2s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zkomplikovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41rfwA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s3w4">
<a>
<lex.rf>a#a-ln95047-028-p2s3w4</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úterý</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95047-028-p2s3w2">
<a>
<lex.rf>a#a-ln95047-028-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>BEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_gram.rf>
<LM>t-ln95047-028-p2s3w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95047-028-p2s3w6">
<a>
<lex.rf>a#a-ln95047-028-p2s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>situace</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln95047-028-p2s3w7">
<a>
<lex.rf>a#a-ln95047-028-p2s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>remíza</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95047-028-p2s3w9">
<a>
<lex.rf>a#a-ln95047-028-p2s3w9</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s3w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Zlín</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s3w17">
<a>
<lex.rf>a#a-ln95047-028-p2s3w17</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s3w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyhrát</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>deb</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p2s3w5</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95047-028-p2s3w10</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41obaA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s3w12">
<a>
<lex.rf>a#a-ln95047-028-p2s3w12</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s3w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jihlava</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p2s1Cw33</target_node.rf>
<type>REST</type>
</LM>
</bridging>
</LM>
<LM id="t-ln95047-028-p2s3w14">
<a>
<lex.rf>a#a-ln95047-028-p2s3w14</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s3w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>udržení</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41mikA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s3w15">
<a>
<lex.rf>a#a-ln95047-028-p2s3w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>naděje</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln95047-028-p2s3a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s3w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s3a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s4">
<atree.rf>a#a-ln95047-028-p2s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p2s4w5">
<a>
<lex.rf>a#a-ln95047-028-p2s4w5</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s4w3</LM>
<LM>a#a-ln95047-028-p2s4w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podceňovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41fquA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s4w1">
<a>
<lex.rf>a#a-ln95047-028-p2s4w1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>ani</t_lemma>
<functor>RHEM</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95047-028-p2s4w2">
<a>
<lex.rf>a#a-ln95047-028-p2s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Litvínov</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95047-028-p2s4a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95047-028-p2s4w7">
<a>
<lex.rf>a#a-ln95047-028-p2s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pardubice</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Cw30</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95047-028-p2s4w6">
<a>
<lex.rf>a#a-ln95047-028-p2s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předposlední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln95047-028-p2s4a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<tfa>t</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95047-028-p2s4w9">
<a>
<lex.rf>a#a-ln95047-028-p2s4w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>již</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln95047-028-p2s4w12">
<a>
<lex.rf>a#a-ln95047-028-p2s4w12</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_parenthesis>1</is_parenthesis>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p2s4w7</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln95047-028-p2s4w11">
<a>
<lex.rf>a#a-ln95047-028-p2s4w11</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s4w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Biegl</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln95047-028-p2s4w13">
<a>
<lex.rf>a#a-ln95047-028-p2s4w13</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s4w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Šejba</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s4w27">
<a>
<lex.rf>a#a-ln95047-028-p2s4w27</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s4w16</LM>
<LM>a#a-ln95047-028-p2s4w26</LM>
<LM>a#a-ln95047-028-p2s4w19</LM>
<LM>a#a-ln95047-028-p2s4w20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyplatit_se</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>v</sempos>
<deontmod>deb</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p2s4w5</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Reason</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-ln95047-028-p2s4w16</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41oooA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p2s4w17">
<a>
<lex.rf>a#a-ln95047-028-p2s4w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ztráta</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln95047-028-p2s4w18">
<a>
<lex.rf>a#a-ln95047-028-p2s4w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bod</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s4w24">
<a>
<lex.rf>a#a-ln95047-028-p2s4w24</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p2s4w22</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konstelace</t_lemma>
<functor>COND</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln95047-028-p2s4w25">
<a>
<lex.rf>a#a-ln95047-028-p2s4w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výsledek</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln95047-028-p2s4w23">
<a>
<lex.rf>a#a-ln95047-028-p2s4w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>určitý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p2s4w21">
<a>
<lex.rf>a#a-ln95047-028-p2s4w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s4w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p2s4a1">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p3s1">
<atree.rf>a#a-ln95047-028-p3s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p3s1w2">
<a>
<lex.rf>a#a-ln95047-028-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41chlI</val_frame.rf>
<children>
<LM id="t-ln95047-028-p3s1w1">
<a>
<lex.rf>a#a-ln95047-028-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Slavia</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s3a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p3s1w5">
<a>
<lex.rf>a#a-ln95047-028-p3s1w5</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střetnutí</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41lngA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p3s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95047-028-p3s1w4">
<a>
<lex.rf>a#a-ln95047-028-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úterní</t_lemma>
<functor>TWHEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s3w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p3s1w7">
<a>
<lex.rf>a#a-ln95047-028-p3s1w7</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Zlín</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s3w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p3s1w8">
<a>
<lex.rf>a#a-ln95047-028-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zraněný</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95047-028-p3s1w11">
<a>
<lex.rf>a#a-ln95047-028-p3s1w11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p3s1w1</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln95047-028-p3s1w10">
<a>
<lex.rf>a#a-ln95047-028-p3s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tóth</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95047-028-p3s1w9">
<a>
<lex.rf>a#a-ln95047-028-p3s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>brankář</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p3s1w13">
<a>
<lex.rf>a#a-ln95047-028-p3s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hořava</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln95047-028-p3s1w12">
<a>
<lex.rf>a#a-ln95047-028-p3s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obránce</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p3s2">
<atree.rf>a#a-ln95047-028-p3s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p3s2w6">
<a>
<lex.rf>a#a-ln95047-028-p3s2w6</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>6</deepord>
<children>
<LM id="t-ln95047-028-p3s2w5">
<a>
<lex.rf>a#a-ln95047-028-p3s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chybět</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41bcpD</val_frame.rf>
<children>
<LM id="t-ln95047-028-p3s2w1">
<a>
<lex.rf>a#a-ln95047-028-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oba</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>anim</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p3s1w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p3s2a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>LOC</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95047-028-p3s2w4">
<a>
<lex.rf>a#a-ln95047-028-p3s2w4</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s2w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trénink</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95047-028-p3s2w3">
<a>
<lex.rf>a#a-ln95047-028-p3s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včerejší</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p3s2w11">
<a>
<lex.rf>a#a-ln95047-028-p3s2w11</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>deagent</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p3s2w5</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95047-028-p3s2w6</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jqhD</val_frame.rf>
<children>
<LM id="t-ln95047-028-p3s2w9">
<a>
<lex.rf>a#a-ln95047-028-p3s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s2w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>start</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95047-028-p3s2w8">
<a>
<lex.rf>a#a-ln95047-028-p3s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>případný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p3s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln95047-028-p3s2w12">
<a>
<lex.rf>a#a-ln95047-028-p3s2w12</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>až</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln95047-028-p3s2w14">
<a>
<lex.rf>a#a-ln95047-028-p3s2w14</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s2w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zápas</t_lemma>
<functor>TWHEN</functor>
<subfunctor>before</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p3s3">
<atree.rf>a#a-ln95047-028-p3s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p3s3w8">
<a>
<lex.rf>a#a-ln95047-028-p3s3w8</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s3w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vracet_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41npvB</val_frame.rf>
<children>
<LM id="t-ln95047-028-p3s3w2">
<a>
<lex.rf>a#a-ln95047-028-p3s3w2</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s3w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákaz</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95047-028-p3s3w3">
<a>
<lex.rf>a#a-ln95047-028-p3s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>start</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95047-028-p3s3w6">
<a>
<lex.rf>a#a-ln95047-028-p3s3w6</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p3s3w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střetnutí</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p3s1w5</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<val_frame.rf>v#v41lngA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p3s3a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95047-028-p3s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95047-028-p3s3w5">
<a>
<lex.rf>a#a-ln95047-028-p3s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jeden</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p3s3a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR3</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95047-028-p3s3w10">
<a>
<lex.rf>a#a-ln95047-028-p3s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jelínek</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p3s1w1</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln95047-028-p3s3w9">
<a>
<lex.rf>a#a-ln95047-028-p3s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitán</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p3s1w1</target_node.rf>
<type>P_FUNCT</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s1">
<atree.rf>a#a-ln95047-028-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95047-028-l5A">
<basic-form>čelní dutina</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95047-028-p4s1w23</LM>
<LM>t-ln95047-028-p4s1w24</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95047-028-p4s1w15">
<a>
<lex.rf>a#a-ln95047-028-p4s1w15</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>15</deepord>
<children>
<LM id="t-ln95047-028-p4s1w2">
<a>
<lex.rf>a#a-ln95047-028-p4s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nastoupit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41dcwC</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s1w1">
<a>
<lex.rf>a#a-ln95047-028-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sparta</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s2w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p4s1w5">
<a>
<lex.rf>a#a-ln95047-028-p4s1w5</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>utkání</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s2w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41naeB</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s1a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95047-028-p4s1a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95047-028-p4s1w6">
<a>
<lex.rf>a#a-ln95047-028-p4s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kolo</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Cw17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p4s1w4">
<a>
<lex.rf>a#a-ln95047-028-p4s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>důležitý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>sup</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s1w9">
<a>
<lex.rf>a#a-ln95047-028-p4s1w9</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s1w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sestava</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95047-028-p4s1w8">
<a>
<lex.rf>a#a-ln95047-028-p4s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln95047-028-p4s1a0">
<a>
<lex.rf>a#a-ln95047-028-p4s1w2</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>nastoupit</t_lemma>
<functor>CPR</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41dcwC</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s1a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p4s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p4s1a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>LOC</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln95047-028-p4s1w12">
<a>
<lex.rf>a#a-ln95047-028-p4s1w12</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s1w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úterý</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln95047-028-p4s1w14">
<a>
<lex.rf>a#a-ln95047-028-p4s1w14</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s1w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Vsetín</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s1w16">
<a>
<lex.rf>a#a-ln95047-028-p4s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s1w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chybět</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41bcpD</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s1a5">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>LOC</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln95047-028-p4s1w19">
<a>
<lex.rf>a#a-ln95047-028-p4s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Toužimský</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p4s1a1</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln95047-028-p4s1w18">
<a>
<lex.rf>a#a-ln95047-028-p4s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obránce</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
<LM id="t-ln95047-028-p4s1w22">
<a>
<lex.rf>a#a-ln95047-028-p4s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trápit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<val_frame.rf>v#v41mbgA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s1w21">
<a>
<lex.rf>a#a-ln95047-028-p4s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>20</deepord>
<coref_gram.rf>
<LM>t-ln95047-028-p4s1w19</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95047-028-p4s1w24">
<a>
<lex.rf>a#a-ln95047-028-p4s1w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dutina</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p4s1w21</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
<children>
<LM id="t-ln95047-028-p4s1w23">
<a>
<lex.rf>a#a-ln95047-028-p4s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čelní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s2">
<atree.rf>a#a-ln95047-028-p4s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p4s2w3">
<a>
<lex.rf>a#a-ln95047-028-p4s2w3</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s2w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41chlAE</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s2w1">
<a>
<lex.rf>a#a-ln95047-028-p4s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Vítkovice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s2w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p4s2w4">
<a>
<lex.rf>a#a-ln95047-028-p4s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>problém</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41hafA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_gram.rf>
<LM>t-ln95047-028-p4s2w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95047-028-p4s2w6">
<a>
<lex.rf>a#a-ln95047-028-p4s2w6</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s2w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sestava</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p1s1w4</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s3">
<atree.rf>a#a-ln95047-028-p4s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p4s3w11">
<a>
<lex.rf>a#a-ln95047-028-p4s3w11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln95047-028-p4s3w2">
<a>
<lex.rf>a#a-ln95047-028-p4s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41chlAE</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s3w1">
<a>
<lex.rf>a#a-ln95047-028-p4s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Folta</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p4s2a0</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-ln95047-028-p4s3w3">
<a>
<lex.rf>a#a-ln95047-028-p4s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potíž</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41gqpA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_gram.rf>
<LM>t-ln95047-028-p4s3w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95047-028-p4s3w5">
<a>
<lex.rf>a#a-ln95047-028-p4s3w5</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s3w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>záda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p4s3a1</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s3w8">
<a>
<lex.rf>a#a-ln95047-028-p4s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zlobit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41riwA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s3w7">
<a>
<lex.rf>a#a-ln95047-028-p4s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Škuta</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p4s2a0</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-ln95047-028-p4s3w9">
<a>
<lex.rf>a#a-ln95047-028-p4s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zánět</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95047-028-p4s3w10">
<a>
<lex.rf>a#a-ln95047-028-p4s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>noha</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p4s3w7</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s3a0">
<a>
<lex.rf>a#a-ln95047-028-p4s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>zlobit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p4s3w8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95047-028-p4s3w11</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41riwA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s3w12">
<a>
<lex.rf>a#a-ln95047-028-p4s3w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Chlubna</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p4s2a0</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-ln95047-028-p4s3w13">
<a>
<lex.rf>a#a-ln95047-028-p4s3w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>opět</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln95047-028-p4s3w14">
<a>
<lex.rf>a#a-ln95047-028-p4s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koleno</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95047-028-p4s3w12</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s4">
<atree.rf>a#a-ln95047-028-p4s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95047-028-l4A">
<basic-form>play off</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95047-028-p4s4w21</LM>
<LM>t-ln95047-028-p4s4w22</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95047-028-l6A">
<basic-form>Vladimír Stránský</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln95047-028-p4s4w3</LM>
<LM>t-ln95047-028-p4s4w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95047-028-p4s4w7">
<a>
<lex.rf>a#a-ln95047-028-p4s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s4w4">
<a>
<lex.rf>a#a-ln95047-028-p4s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Stránský</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95047-028-p4s4w3">
<a>
<lex.rf>a#a-ln95047-028-p4s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Vladimír</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95047-028-p4s4w1">
<a>
<lex.rf>a#a-ln95047-028-p4s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trenér</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95047-028-p4s4w2">
<a>
<lex.rf>a#a-ln95047-028-p4s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Vítkovice</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p4s2a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s4w6">
<a>
<lex.rf>a#a-ln95047-028-p4s4w6</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s4w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>utkání</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p4s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41naeB</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s4a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln95047-028-p4s4a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s4a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln95047-028-p4s4w14">
<a>
<lex.rf>a#a-ln95047-028-p4s4w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>EFF</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s4w10">
<a>
<lex.rf>a#a-ln95047-028-p4s4w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zápas</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p4s4w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95047-028-p4s4w13">
<a>
<lex.rf>a#a-ln95047-028-p4s4w13</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s4w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sparta</t_lemma>
<functor>ADDR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p4s1a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95047-028-p4s4w12">
<a>
<lex.rf>a#a-ln95047-028-p4s4w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pražský</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Bw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s4w15">
<a>
<lex.rf>a#a-ln95047-028-p4s4w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodující</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95047-028-p4s4w17">
<a>
<lex.rf>a#a-ln95047-028-p4s4w17</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s4w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>boj</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln95047-028-p4s4w19">
<a>
<lex.rf>a#a-ln95047-028-p4s4w19</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s4w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>účast</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln95047-028-p4s4w21">
<a>
<lex.rf>a#a-ln95047-028-p4s4w21</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s4w20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>play</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p2s1Cw26</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95047-028-p4s4w22">
<a>
<lex.rf>a#a-ln95047-028-p4s4w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>off</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>nr</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s5">
<atree.rf>a#a-ln95047-028-p4s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95047-028-p4s5w8">
<a>
<lex.rf>a#a-ln95047-028-p4s5w8</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ale</t_lemma>
<functor>ADVS</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<deepord>6</deepord>
<children>
<LM id="t-ln95047-028-p4s5w3">
<a>
<lex.rf>a#a-ln95047-028-p4s5w3</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s5w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41chlQ</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s5w1">
<a>
<lex.rf>a#a-ln95047-028-p4s5w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pražan</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p4s4w13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p4s5w4">
<a>
<lex.rf>a#a-ln95047-028-p4s5w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výhoda</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95047-028-p4s5w6">
<a>
<lex.rf>a#a-ln95047-028-p4s5w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prostředí</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95047-028-p4s5w5">
<a>
<lex.rf>a#a-ln95047-028-p4s5w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>domácí</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s5w19">
<a>
<lex.rf>a#a-ln95047-028-p4s5w19</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s5w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>získat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>deb</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p4s5w3</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95047-028-p4s5w8</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41reiD</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s5w11">
<a>
<lex.rf>a#a-ln95047-028-p4s5w11</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s5w9</LM>
<LM>a#a-ln95047-028-p4s5w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zůstat</t_lemma>
<functor>COND</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>v</sempos>
<deontmod>vol</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95047-028-p4s5w19</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>cond</discourse_type>
<sense_PDTB3>Contingency.Condition.Arg2-as-cond</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-ln95047-028-p4s5w9</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41sadF</val_frame.rf>
<children>
<LM id="t-ln95047-028-p4s5a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p4s4w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p4s5w13">
<a>
<lex.rf>a#a-ln95047-028-p4s5w13</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s5w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hra</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln95047-028-p4s5w16">
<a>
<lex.rf>a#a-ln95047-028-p4s5w16</lex.rf>
<aux.rf>
<LM>a#a-ln95047-028-p4s5w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>místo</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln95047-028-p4s5w15">
<a>
<lex.rf>a#a-ln95047-028-p4s5w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osmý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>osm</proto_lemma>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95047-028-p4s5a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95047-028-p4s5a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95047-028-p4s5w21">
<a>
<lex.rf>a#a-ln95047-028-p4s5w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bod</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln95047-028-p4s5w20">
<a>
<lex.rf>a#a-ln95047-028-p4s5w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>minimálně</t_lemma>
<functor>EXT</functor>
<proto_lemma>minimální</proto_lemma>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95047-028-p4s4w14</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
