#!/usr/bin/perl
use warnings;
use strict;
use feature qw{ say };

use FindBin;
use lib $FindBin::Bin;

use List;
use Path::Tiny qw{ path };

my $list = 'List::Builder::Config'->new->build;
$list->for_each(sub {
    my ($self, $file) = @_;
    return if $file->done || ! $file->sent;

    my $workdir = $self->workdir($file->annotator);
    return unless -d "$workdir";

    return if -e "$workdir/" . $file->name . '.cz.a';

    my @files = glob $self->bindir
              . "/../WorkData2.0/PCEDT-cz/pml/" . $file->name . ".cz.[amtw]";
    die 'Some of ', $file->name, ' not found' unless 4 == @files;

    for my $data (@files) {
        path($data)->copy($workdir);
    }
});
