<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln95049_012.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln95049-012-p1s1">
<atree.rf>a#a-ln95049-012-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l16A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95049-012-p1s1w1</LM>
<LM>t-ln95049-012-p1s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p1s1w3">
<a>
<lex.rf>a#a-ln95049-012-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>očekávat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41dvcA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p1s1w1">
<a>
<lex.rf>a#a-ln95049-012-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>op</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95049-012-p1s1w2">
<a>
<lex.rf>a#a-ln95049-012-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Prostějov</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p1s1w4">
<a>
<lex.rf>a#a-ln95049-012-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p2s1A">
<atree.rf>a#a-ln95049-012-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95049-012-p2s1Aw1">
<a>
<lex.rf>a#a-ln95049-012-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p2s1B">
<atree.rf>a#a-ln95049-012-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l15A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95049-012-p2s1Bw3</LM>
<LM>t-ln95049-012-p2s1Bw4</LM>
<LM>t-ln95049-012-p2s1Bw5</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l17A">
<basic-form>hrubý zisk</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95049-012-p2s1Bw1</LM>
<LM>t-ln95049-012-p2s1Bw2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l18A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95049-012-p2s1Bw11</LM>
<LM>t-ln95049-012-p2s1Bw12</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p2s1Bw9">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosáhnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41afbA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p2s1Bw2">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p1s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95049-012-p2s1Bw1">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hrubý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95049-012-p2s1Bw4">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95049-012-p2s1Bw3">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Oděvní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95049-012-p2s1Bw5">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Prostějov</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p1s1w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p2s1Bw8">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw8</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p2s1Bw6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95049-012-p2s1Bw7">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>loňský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p2s1Bw12">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln95049-012-p2s1Bw13">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln95049-012-p2s1Bw11">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>200</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln95049-012-p2s1Bw10">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližně</t_lemma>
<functor>EXT</functor>
<proto_lemma>přibližný</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p2s1Bw15">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stejně</t_lemma>
<functor>MANN</functor>
<proto_lemma>stejný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95049-012-p2s1Ba0">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw9</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p2s1Bw16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>dosáhnout</t_lemma>
<functor>CPR</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41afbA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p2s1Ba2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s1Bw2</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95049-012-p2s1Ba1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s1Bw12</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95049-012-p2s1Bw17">
<a>
<lex.rf>a#a-ln95049-012-p2s1Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předloni</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p2s2">
<atree.rf>a#a-ln95049-012-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l6A">
<basic-form>František Tuhý</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln95049-012-p2s2w8</LM>
<LM>t-ln95049-012-p2s2w9</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l19A">
<basic-form>generální ředitel</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95049-012-p2s2w5</LM>
<LM>t-ln95049-012-p2s2w6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p2s2w1">
<a>
<lex.rf>a#a-ln95049-012-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p2s2w2">
<a>
<lex.rf>a#a-ln95049-012-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>EFF</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s1Bw9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95049-012-p2s2w4">
<a>
<lex.rf>a#a-ln95049-012-p2s2w4</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p2s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sobota</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95049-012-p2s2w9">
<a>
<lex.rf>a#a-ln95049-012-p2s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tuhý</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95049-012-p2s2w8">
<a>
<lex.rf>a#a-ln95049-012-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>František</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln95049-012-p2s2w6">
<a>
<lex.rf>a#a-ln95049-012-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95049-012-p2s2w7">
<a>
<lex.rf>a#a-ln95049-012-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>firma</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s1Bw4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95049-012-p2s2w5">
<a>
<lex.rf>a#a-ln95049-012-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>generální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p2s2w12">
<a>
<lex.rf>a#a-ln95049-012-p2s2w12</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p2s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veletrh</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln95049-012-p2s2w13">
<a>
<lex.rf>a#a-ln95049-012-p2s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Elegance</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln95049-012-p2s2w11">
<a>
<lex.rf>a#a-ln95049-012-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pražský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s1Aw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s1">
<atree.rf>a#a-ln95049-012-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l20A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95049-012-p3s1w10</LM>
<LM>t-ln95049-012-p3s1w11</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l21A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95049-012-p3s1w15</LM>
<LM>t-ln95049-012-p3s1w16</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p3s1w4">
<a>
<lex.rf>a#a-ln95049-012-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vzrůst</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41pnkA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p3s1w1">
<a>
<lex.rf>a#a-ln95049-012-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obrat</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95049-012-p3s1w2">
<a>
<lex.rf>a#a-ln95049-012-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s2w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s1w7">
<a>
<lex.rf>a#a-ln95049-012-p3s1w7</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p3s1w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>slovo</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95049-012-p3s1w6">
<a>
<lex.rf>a#a-ln95049-012-p3s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s2w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s1w3">
<a>
<lex.rf>a#a-ln95049-012-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>letos</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln95049-012-p3s1w11">
<a>
<lex.rf>a#a-ln95049-012-p3s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p3s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95049-012-p3s1w10">
<a>
<lex.rf>a#a-ln95049-012-p3s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>20</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95049-012-p3s1w8">
<a>
<lex.rf>a#a-ln95049-012-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>málo</t_lemma>
<functor>EXT</functor>
<proto_lemma>málo</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>sup</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s1w16">
<a>
<lex.rf>a#a-ln95049-012-p3s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p3s1w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>miliarda</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95049-012-p3s1w11</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln95049-012-p3s1w14">
<a>
<lex.rf>a#a-ln95049-012-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>loňský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln95049-012-p3s1w17">
<a>
<lex.rf>a#a-ln95049-012-p3s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln95049-012-p3s1w15">
<a>
<lex.rf>a#a-ln95049-012-p3s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.5</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s2">
<atree.rf>a#a-ln95049-012-p3s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l10A">
<type>location</type>
<tnode.rfs>
<LM>t-ln95049-012-p3s2w24</LM>
<LM>t-ln95049-012-p3s2w25</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l22A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95049-012-p3s2w1</LM>
<LM>t-ln95049-012-p3s2w2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l25A">
<basic-form>Spojené státy americké</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-ln95049-012-p3s2w27</LM>
<LM>t-ln95049-012-p3s2w28</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p3s2a4">
<a>
<lex.rf>a#a-ln95049-012-p3s2w17</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>17</deepord>
<children>
<LM id="t-ln95049-012-p3s2w2">
<a>
<lex.rf>a#a-ln95049-012-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95049-012-p3s2w5">
<a>
<lex.rf>a#a-ln95049-012-p3s2w5</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-ln95049-012-p3s2a2">
<a>
<lex.rf>a#a-ln95049-012-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>konfekce</t_lemma>
<functor>MAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95049-012-p3s2w4">
<a>
<lex.rf>a#a-ln95049-012-p3s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pánský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s2w7">
<a>
<lex.rf>a#a-ln95049-012-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konfekce</t_lemma>
<functor>MAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95049-012-p3s2w6">
<a>
<lex.rf>a#a-ln95049-012-p3s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dámský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s2w3">
<a>
<lex.rf>a#a-ln95049-012-p3s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klasický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95049-012-p3s2w10">
<a>
<lex.rf>a#a-ln95049-012-p3s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>RSTR</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95049-012-p3s2w9">
<a>
<lex.rf>a#a-ln95049-012-p3s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_gram.rf>
<LM>t-ln95049-012-p3s2w5</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95049-012-p3s2w12">
<a>
<lex.rf>a#a-ln95049-012-p3s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln95049-012-p3s2w13">
<a>
<lex.rf>a#a-ln95049-012-p3s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>firma</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p3s1w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95049-012-p3s2w11">
<a>
<lex.rf>a#a-ln95049-012-p3s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlavní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s2w1">
<a>
<lex.rf>a#a-ln95049-012-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sedmdesát</t_lemma>
<functor>RSTR</functor>
<proto_lemma>sedmdesát</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s2a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95049-012-p3s2a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR1</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln95049-012-p3s2w16">
<a>
<lex.rf>a#a-ln95049-012-p3s2w16</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p3s2w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyvážet</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>deagent</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41pgbA</val_frame.rf>
</LM>
<LM id="t-ln95049-012-p3s2a5">
<a>
<lex.rf>a#a-ln95049-012-p3s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>vyvážet</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>deagent</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
<val_frame.rf>v#v41pgbA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p3s2w18">
<a>
<lex.rf>a#a-ln95049-012-p3s2w18</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>zejména</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
<LM id="t-ln95049-012-p3s2w26">
<a>
<lex.rf>a#a-ln95049-012-p3s2w26</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>23</deepord>
<children>
<LM id="t-ln95049-012-p3s2w22">
<a>
<lex.rf>a#a-ln95049-012-p3s2w22</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p3s2w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>země</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<children>
<LM id="t-ln95049-012-p3s2w21">
<a>
<lex.rf>a#a-ln95049-012-p3s2w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mluvící</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<children>
<LM id="t-ln95049-012-p3s2w20">
<a>
<lex.rf>a#a-ln95049-012-p3s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>německy</t_lemma>
<functor>MANN</functor>
<proto_lemma>německý</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s2w25">
<a>
<lex.rf>a#a-ln95049-012-p3s2w25</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p3s2w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Británie</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<children>
<LM id="t-ln95049-012-p3s2w24">
<a>
<lex.rf>a#a-ln95049-012-p3s2w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Velký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p3s2w28">
<a>
<lex.rf>a#a-ln95049-012-p3s2w28</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p3s2w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
<children>
<LM id="t-ln95049-012-p3s2w27">
<a>
<lex.rf>a#a-ln95049-012-p3s2w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Spojený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s1">
<atree.rf>a#a-ln95049-012-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l13A">
<type>person</type>
<tnode.rfs>
<LM>t-ln95049-012-p4s1w4</LM>
<LM>t-ln95049-012-p4s1w6</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l14A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95049-012-p4s1w12</LM>
<LM>t-ln95049-012-p4s1w13</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l26A">
<basic-form>obchodní vztah</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95049-012-p4s1w9</LM>
<LM>t-ln95049-012-p4s1w10</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l28A">
<basic-form>lhůta splatnosti</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95049-012-p4s1w20</LM>
<LM>t-ln95049-012-p4s1w21</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p4s1w17">
<a>
<lex.rf>a#a-ln95049-012-p4s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>narušovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95049-012-p3s2a4</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<comment>PHASE:2 RESTARTED; RETARGETED</comment>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95049-012-p4s1w2</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41czyA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p4s1w3">
<a>
<lex.rf>a#a-ln95049-012-p4s1w3</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s1w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41kebB</val_frame.rf>
<children>
<LM id="t-ln95049-012-p4s1w2">
<a>
<lex.rf>a#a-ln95049-012-p4s1w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>dále</t_lemma>
<functor>PREC</functor>
<is_parenthesis>1</is_parenthesis>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95049-012-p4s1w6">
<a>
<lex.rf>a#a-ln95049-012-p4s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tuhý</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p3s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95049-012-p4s1w4">
<a>
<lex.rf>a#a-ln95049-012-p4s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>F</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<is_parenthesis>1</is_parenthesis>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95049-012-p4s1a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>EFF</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p4s1w17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s1w10">
<a>
<lex.rf>a#a-ln95049-012-p4s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vztah</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95049-012-p4s1w9">
<a>
<lex.rf>a#a-ln95049-012-p4s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obchodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln95049-012-p4s1w8">
<a>
<lex.rf>a#a-ln95049-012-p4s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dobrý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln95049-012-p4s1w14">
<a>
<lex.rf>a#a-ln95049-012-p4s1w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln95049-012-p4s1w12">
<a>
<lex.rf>a#a-ln95049-012-p4s1w12</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s1w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>OP</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p3s2w13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95049-012-p4s1w13">
<a>
<lex.rf>a#a-ln95049-012-p4s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Prostějov</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s1Bw5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s1w16">
<a>
<lex.rf>a#a-ln95049-012-p4s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s1w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odběratel</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln95049-012-p4s1w15">
<a>
<lex.rf>a#a-ln95049-012-p4s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p4s1w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s1w18">
<a>
<lex.rf>a#a-ln95049-012-p4s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pohledávka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln95049-012-p4s1w20">
<a>
<lex.rf>a#a-ln95049-012-p4s1w20</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s1w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lhůta</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln95049-012-p4s1w21">
<a>
<lex.rf>a#a-ln95049-012-p4s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>splatnost</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s2">
<atree.rf>a#a-ln95049-012-p4s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l27A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95049-012-p4s2w7</LM>
<LM>t-ln95049-012-p4s2w8</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p4s2w5">
<a>
<lex.rf>a#a-ln95049-012-p4s2w5</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s2w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pohybovat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41fyhA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p4s2w1">
<a>
<lex.rf>a#a-ln95049-012-p4s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>fem</gender>
<number>pl</number>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p4s1w18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95049-012-p4s2w4">
<a>
<lex.rf>a#a-ln95049-012-p4s2w4</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>současnost</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95049-012-p4s2w8">
<a>
<lex.rf>a#a-ln95049-012-p4s2w8</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s2w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>LOC</functor>
<subfunctor>around</subfunctor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95049-012-p4s2w9">
<a>
<lex.rf>a#a-ln95049-012-p4s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95049-012-p4s2w7">
<a>
<lex.rf>a#a-ln95049-012-p4s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>100</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s3">
<atree.rf>a#a-ln95049-012-p4s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95049-012-p4s3w20">
<a>
<lex.rf>a#a-ln95049-012-p4s3w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdůraznit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41qzoA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p4s3w21">
<a>
<lex.rf>a#a-ln95049-012-p4s3w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p4s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95049-012-p4s3w2">
<a>
<lex.rf>a#a-ln95049-012-p4s3w2</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95049-012-p4s3w4">
<a>
<lex.rf>a#a-ln95049-012-p4s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dobrý</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95049-012-p4s3w10">
<a>
<lex.rf>a#a-ln95049-012-p4s3w10</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s3w9</LM>
<LM>a#a-ln95049-012-p4s3w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpořit</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41fuiB</val_frame.rf>
<children>
<LM id="t-ln95049-012-p4s3w8">
<a>
<lex.rf>a#a-ln95049-012-p4s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>banka</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln95049-012-p4s3w12">
<a>
<lex.rf>a#a-ln95049-012-p4s3w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95049-012-p4s1w15</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln95049-012-p4s3w15">
<a>
<lex.rf>a#a-ln95049-012-p4s3w15</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s3w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odvětví</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="t-ln95049-012-p4s3w14">
<a>
<lex.rf>a#a-ln95049-012-p4s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s3w11">
<a>
<lex.rf>a#a-ln95049-012-p4s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>perspektivní</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p4s3w17">
<a>
<lex.rf>a#a-ln95049-012-p4s3w17</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p4s3w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>půjčka</t_lemma>
<functor>MANN</functor>
<quot>
<LM>
<type>dsp</type>
<set_id>ln95049-012-p4s3w2</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p5s1">
<atree.rf>a#a-ln95049-012-p5s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l29A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95049-012-p5s1w1</LM>
<LM>t-ln95049-012-p5s1w2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l30A">
<basic-form>druhá vlna kupónové privatizace</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95049-012-p5s1w6</LM>
<LM>t-ln95049-012-p5s1w7</LM>
<LM>t-ln95049-012-p5s1w8</LM>
<LM>t-ln95049-012-p5s1w9</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p5s1w4">
<a>
<lex.rf>a#a-ln95049-012-p5s1w4</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p5s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>privatizovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41gztA</val_frame.rf>
<children>
<LM id="t-ln95049-012-p5s1w1">
<a>
<lex.rf>a#a-ln95049-012-p5s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>OP</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p4s1w15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95049-012-p5s1w2">
<a>
<lex.rf>a#a-ln95049-012-p5s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Prostějov</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p4s1w13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p5s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95049-012-p5s1w7">
<a>
<lex.rf>a#a-ln95049-012-p5s1w7</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p5s1w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vlna</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95049-012-p5s1w9">
<a>
<lex.rf>a#a-ln95049-012-p5s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>privatizace</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95049-012-p5s1w8">
<a>
<lex.rf>a#a-ln95049-012-p5s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kupónový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p5s1w6">
<a>
<lex.rf>a#a-ln95049-012-p5s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>druhý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>dva</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p5s2">
<atree.rf>a#a-ln95049-012-p5s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95049-012-l31A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95049-012-p5s2w15</LM>
<LM>t-ln95049-012-p5s2w17</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95049-012-l32A">
<basic-form>zaváděcí cena</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95049-012-p5s2w1</LM>
<LM>t-ln95049-012-p5s2w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95049-012-p5s2w13">
<a>
<lex.rf>a#a-ln95049-012-p5s2w13</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>11</deepord>
<children>
<LM id="t-ln95049-012-p5s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95049-012-p5s2w9">
<a>
<lex.rf>a#a-ln95049-012-p5s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p5s2w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stanovit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41lhzD</val_frame.rf>
<children>
<LM id="t-ln95049-012-p5s2w2">
<a>
<lex.rf>a#a-ln95049-012-p5s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cena</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95049-012-p5s2w1">
<a>
<lex.rf>a#a-ln95049-012-p5s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaváděcí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95049-012-p5s2w4">
<a>
<lex.rf>a#a-ln95049-012-p5s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95049-012-p5s2w3">
<a>
<lex.rf>a#a-ln95049-012-p5s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p5s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p5s2w7">
<a>
<lex.rf>a#a-ln95049-012-p5s2w7</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p5s2w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>burza</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95049-012-p5s2w6">
<a>
<lex.rf>a#a-ln95049-012-p5s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pražský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95049-012-p2s2w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p5s2w12">
<a>
<lex.rf>a#a-ln95049-012-p5s2w12</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p5s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln95049-012-p5s2w11">
<a>
<lex.rf>a#a-ln95049-012-p5s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>3330</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p5s2a1">
<a>
<lex.rf>a#a-ln95049-012-p5s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p5s2w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>stanovit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95049-012-p5s2w9</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95049-012-p5s2w13</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41lhzD</val_frame.rf>
<children>
<LM id="t-ln95049-012-p5s2a2">
<a>
<lex.rf>a#a-ln95049-012-p5s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>cena</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln95049-012-p5s2w17">
<a>
<lex.rf>a#a-ln95049-012-p5s2w17</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p5s2w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>S</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln95049-012-p5s2w15">
<a>
<lex.rf>a#a-ln95049-012-p5s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>RM</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95049-012-p5s2w20">
<a>
<lex.rf>a#a-ln95049-012-p5s2w20</lex.rf>
<aux.rf>
<LM>a#a-ln95049-012-p5s2w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln95049-012-p5s2w19">
<a>
<lex.rf>a#a-ln95049-012-p5s2w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1199</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
