<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln95046_080.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln95046-080-p1s1">
<atree.rf>a#a-ln95046-080-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95046-080-p1s1w3">
<a>
<lex.rf>a#a-ln95046-080-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibývat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41ipjC</val_frame.rf>
<children>
<LM id="t-ln95046-080-p1s1w2">
<a>
<lex.rf>a#a-ln95046-080-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řidič</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95046-080-p1s1w1">
<a>
<lex.rf>a#a-ln95046-080-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslušný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p2s1A">
<atree.rf>a#a-ln95046-080-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95046-080-p2s1Aw1">
<a>
<lex.rf>a#a-ln95046-080-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p2s1B">
<atree.rf>a#a-ln95046-080-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95046-080-l1A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95046-080-p2s1Bw2</LM>
<LM>t-ln95046-080-p2s1Bw3</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95046-080-l2A">
<basic-form>blokovací botička</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-080-p2s1Bw13</LM>
<LM>t-ln95046-080-p2s1Bw14</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95046-080-p2s1Bw15">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw15</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>13</deepord>
<children>
<LM id="t-ln95046-080-p2s1Bw1">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>strážník</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95046-080-p2s1Bw3">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>policie</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95046-080-p2s1Bw2">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>městský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95046-080-p2s1Bw5">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw5</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p2s1Bw4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-080-p2s1Aw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p2s1Bw6">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nasadit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41dalE</val_frame.rf>
<children>
<LM id="t-ln95046-080-p2s1Bw7">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln95046-080-p2s1Bw9">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw9</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p2s1Bw8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>auto</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95046-080-p2s1Bw11">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řidič</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-080-p1s1w2</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-080-p2s1Bw10">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslušný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p2s1Bw14">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>botička</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln95046-080-p2s1Bw13">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>blokovací</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln95046-080-p2s1Bw12">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>41779</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p2s1Bw18">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vybrat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95046-080-p2s1Bw6</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95046-080-p2s1Bw15</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41nusA</val_frame.rf>
<children>
<LM id="t-ln95046-080-p2s1Bw17">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw17</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p2s1Bw16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>CAUS</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-080-p2s1Bw6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-080-p2s1Bw20">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw20</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p2s1Bw19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pokuta</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln95046-080-p2s1Bw22">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln95046-080-p2s1Bw21">
<a>
<lex.rf>a#a-ln95046-080-p2s1Bw21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>5682000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s1">
<atree.rf>a#a-ln95046-080-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95046-080-l3A">
<type>time</type>
<tnode.rfs>
<LM>t-ln95046-080-p3s1w2</LM>
<LM>t-ln95046-080-p3s1w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95046-080-p3s1w5">
<a>
<lex.rf>a#a-ln95046-080-p3s1w5</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p3s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41sdjA</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s1w2">
<a>
<lex.rf>a#a-ln95046-080-p3s1w2</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p3s1w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>CPR</functor>
<subfunctor>wrt</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95046-080-p3s1w3">
<a>
<lex.rf>a#a-ln95046-080-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1993</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s1w6">
<a>
<lex.rf>a#a-ln95046-080-p3s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počet</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95046-080-p3s1w8">
<a>
<lex.rf>a#a-ln95046-080-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>botička</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-080-p2s1Bw14</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-080-p3s1w7">
<a>
<lex.rf>a#a-ln95046-080-p3s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nasazený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s1w11">
<a>
<lex.rf>a#a-ln95046-080-p3s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p3s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetina</t_lemma>
<functor>DIFF</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>frac</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95046-080-p3s1w10">
<a>
<lex.rf>a#a-ln95046-080-p3s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jeden</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s2">
<atree.rf>a#a-ln95046-080-p3s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95046-080-l4A">
<basic-form>zákaz stání</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-080-p3s2w7</LM>
<LM>t-ln95046-080-p3s2w8</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95046-080-l5A">
<basic-form>zákaz stání</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-080-p3s2a2</LM>
<LM>t-ln95046-080-p3s2w12</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95046-080-l6A">
<basic-form>vyhrazené parkoviště</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-080-p3s2w17</LM>
<LM>t-ln95046-080-p3s2w18</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95046-080-p3s2w2">
<a>
<lex.rf>a#a-ln95046-080-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>blokovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41geA</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s2w1">
<a>
<lex.rf>a#a-ln95046-080-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>strážník</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-080-p2s1Bw1</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-080-p3s2w3">
<a>
<lex.rf>a#a-ln95046-080-p3s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>automobil</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95046-080-p2s1Bw9</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln95046-080-p3s2w15">
<a>
<lex.rf>a#a-ln95046-080-p3s2w15</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>17</deepord>
<children>
<LM id="t-ln95046-080-p3s2w5">
<a>
<lex.rf>a#a-ln95046-080-p3s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_gram.rf>
<LM>t-ln95046-080-p3s2w3</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95046-080-p3s2w6">
<a>
<lex.rf>a#a-ln95046-080-p3s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>porušovat</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41gjxA</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s2w11">
<a>
<lex.rf>a#a-ln95046-080-p3s2w11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>či</t_lemma>
<functor>DISJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln95046-080-p3s2w7">
<a>
<lex.rf>a#a-ln95046-080-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákaz</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95046-080-p3s2w8">
<a>
<lex.rf>a#a-ln95046-080-p3s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stání</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41lhsA</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s2a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s2a1">
<a>
<lex.rf>a#a-ln95046-080-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>zákaz</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln95046-080-p3s2w10">
<a>
<lex.rf>a#a-ln95046-080-p3s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zastavení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41qmcB</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s2a5">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s2a2">
<a>
<lex.rf>a#a-ln95046-080-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>zákaz</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95046-080-p3s2w12">
<a>
<lex.rf>a#a-ln95046-080-p3s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stání</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41lhsA</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s2a6">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95046-080-p3s2w14">
<a>
<lex.rf>a#a-ln95046-080-p3s2w14</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p3s2w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trávník</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s2w16">
<a>
<lex.rf>a#a-ln95046-080-p3s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>respektovat</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95046-080-p3s2w6</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95046-080-p3s2w15</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jjhA</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s2a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
<LM id="t-ln95046-080-p3s2w18">
<a>
<lex.rf>a#a-ln95046-080-p3s2w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>parkoviště</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<children>
<LM id="t-ln95046-080-p3s2w17">
<a>
<lex.rf>a#a-ln95046-080-p3s2w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyhrazený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s3">
<atree.rf>a#a-ln95046-080-p3s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95046-080-l7A">
<basic-form>hlavní město</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-080-p3s3w7</LM>
<LM>t-ln95046-080-p3s3w8</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95046-080-p3s3w1">
<a>
<lex.rf>a#a-ln95046-080-p3s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kontrolovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41brjB</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s3a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-080-p3s2w1</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-080-p3s3w2">
<a>
<lex.rf>a#a-ln95046-080-p3s3w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>hlavně</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95046-080-p3s3w4">
<a>
<lex.rf>a#a-ln95046-080-p3s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ulice</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95046-080-p3s3w3">
<a>
<lex.rf>a#a-ln95046-080-p3s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rušný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln95046-080-p3s3w6">
<a>
<lex.rf>a#a-ln95046-080-p3s3w6</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p3s3w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>centrum</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95046-080-p3s3w4</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
<children>
<LM id="t-ln95046-080-p3s3w8">
<a>
<lex.rf>a#a-ln95046-080-p3s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-080-p2s1Bw5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-080-p3s3w7">
<a>
<lex.rf>a#a-ln95046-080-p3s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlavní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95046-080-p3s3w14">
<a>
<lex.rf>a#a-ln95046-080-p3s3w14</lex.rf>
<aux.rf>
<LM>a#a-ln95046-080-p3s3w11</LM>
<LM>a#a-ln95046-080-p3s3w12</LM>
<LM>a#a-ln95046-080-p3s3w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zajistit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41pvyD</val_frame.rf>
<children>
<LM id="t-ln95046-080-p3s3w10">
<a>
<lex.rf>a#a-ln95046-080-p3s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kde</t_lemma>
<functor>LOC</functor>
<proto_lemma>kde</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.indef</sempos>
<indeftype>relat</indeftype>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_gram.rf>
<LM>t-ln95046-080-p3s3w6</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95046-080-p3s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln95046-080-p3s3w16">
<a>
<lex.rf>a#a-ln95046-080-p3s3w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provoz</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln95046-080-p3s3w15">
<a>
<lex.rf>a#a-ln95046-080-p3s3w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>plynulý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
