<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln95045_125.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln95045-125-p1s1">
<atree.rf>a#a-ln95045-125-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-125-l1A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95045-125-p1s1w1</LM>
<LM>t-ln95045-125-p1s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-125-p1s1w3">
<a>
<lex.rf>a#a-ln95045-125-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vykázat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41oeoA</val_frame.rf>
<children>
<LM id="t-ln95045-125-p1s1w2">
<a>
<lex.rf>a#a-ln95045-125-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>banka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95045-125-p1s1w1">
<a>
<lex.rf>a#a-ln95045-125-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>COOP</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p1s1w4">
<a>
<lex.rf>a#a-ln95045-125-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ztráta</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s1A">
<atree.rf>a#a-ln95045-125-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95045-125-p2s1Aw1">
<a>
<lex.rf>a#a-ln95045-125-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s1B">
<atree.rf>a#a-ln95045-125-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-125-l2A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95045-125-p2s1Bw1</LM>
<LM>t-ln95045-125-p2s1Bw2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-125-l3A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-125-p2s1Bw15</LM>
<LM>t-ln95045-125-p2s1Bw16</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-125-l4A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-125-p2s1Bw25</LM>
<LM>t-ln95045-125-p2s1Bw27</LM>
<LM>t-ln95045-125-p2s1Bw28</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-125-p2s1Bw8">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uzavřít</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41nemH</val_frame.rf>
<children>
<LM id="t-ln95045-125-p2s1Bw2">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>banka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-125-p1s1w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-125-p2s1Bw1">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>COOP</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s1Bw7">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw7</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s1Bw3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výsledek</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95045-125-p2s1Bw5">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw5</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="t-ln95045-125-p2s1Bw4">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předběžný</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95045-125-p2s1Bw6">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>auditovaný</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s1Bw10">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95045-125-p2s1Bw9">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>loňský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s1Bw19">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw19</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ale</t_lemma>
<functor>ADVS</functor>
<deepord>16</deepord>
<children>
<LM id="t-ln95045-125-p2s1Bw11">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw11</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>sice</t_lemma>
<functor>CM</functor>
<deepord>10</deepord>
</LM>
<LM id="t-ln95045-125-p2s1Bw13">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw13</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s1Bw12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ztráta</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-125-p1s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-125-p2s1Bw16">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln95045-125-p2s1Bw17">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln95045-125-p2s1Bw15">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>25</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95045-125-p2s1Bw14">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s1Bw20">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw20</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>zato</t_lemma>
<functor>CM</functor>
<deepord>17</deepord>
</LM>
<LM id="t-ln95045-125-p2s1Bw22">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw22</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s1Bw21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rezerva</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln95045-125-p2s1Bw23">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln95045-125-p2s1Ba2">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw28</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s1Bw24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>milión</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<children>
<LM id="t-ln95045-125-p2s1Ba3">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw29</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>koruna</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-ln95045-125-p2s1Bw25">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>68</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s1Bw28">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw28</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s1Bw26</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>t</tfa>
<deepord>24</deepord>
<children>
<LM id="t-ln95045-125-p2s1Bw29">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>23</deepord>
</LM>
<LM id="t-ln95045-125-p2s1Bw27">
<a>
<lex.rf>a#a-ln95045-125-p2s1Bw27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>194</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s2">
<atree.rf>a#a-ln95045-125-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-125-l5A">
<basic-form>portfolio cenných papírů</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-125-p2s2w15</LM>
<LM>t-ln95045-125-p2s2w16</LM>
<LM>t-ln95045-125-p2s2w17</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-125-p2s2w4">
<a>
<lex.rf>a#a-ln95045-125-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vytvořit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41peoA</val_frame.rf>
<children>
<LM id="t-ln95045-125-p2s2w3">
<a>
<lex.rf>a#a-ln95045-125-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>banka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-125-p2s1Bw2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-125-p2s2w2">
<a>
<lex.rf>a#a-ln95045-125-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rezerva</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-125-p2s1Bw22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-125-p2s2w1">
<a>
<lex.rf>a#a-ln95045-125-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vysoký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>comp</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s2w12">
<a>
<lex.rf>a#a-ln95045-125-p2s2w12</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ale</t_lemma>
<functor>GRAD</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln95045-125-p2s2w5">
<a>
<lex.rf>a#a-ln95045-125-p2s2w5</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>nejen</t_lemma>
<functor>CM</functor>
<deepord>5</deepord>
</LM>
<LM id="t-ln95045-125-p2s2w7">
<a>
<lex.rf>a#a-ln95045-125-p2s2w7</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s2w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>důvod</t_lemma>
<functor>CAUS</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95045-125-p2s2w9">
<a>
<lex.rf>a#a-ln95045-125-p2s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klasifikace</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95045-125-p2s2w10">
<a>
<lex.rf>a#a-ln95045-125-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úvěr</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln95045-125-p2s2w8">
<a>
<lex.rf>a#a-ln95045-125-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přísný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>comp</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s2w13">
<a>
<lex.rf>a#a-ln95045-125-p2s2w13</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>CM</functor>
<deepord>11</deepord>
</LM>
<LM id="t-ln95045-125-p2s2w15">
<a>
<lex.rf>a#a-ln95045-125-p2s2w15</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s2w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>portfolio</t_lemma>
<functor>CAUS</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln95045-125-p2s2w17">
<a>
<lex.rf>a#a-ln95045-125-p2s2w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>papír</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95045-125-p2s2w16">
<a>
<lex.rf>a#a-ln95045-125-p2s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cenný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s2w23">
<a>
<lex.rf>a#a-ln95045-125-p2s2w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdvojnásobit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41qzzA</val_frame.rf>
<children>
<LM id="t-ln95045-125-p2s2w21">
<a>
<lex.rf>a#a-ln95045-125-p2s2w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>banka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-125-p2s2w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-125-p2s2w22">
<a>
<lex.rf>a#a-ln95045-125-p2s2w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-125-p2s1Bw10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-125-p2s2w20">
<a>
<lex.rf>a#a-ln95045-125-p2s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln95045-125-p2s2w19">
<a>
<lex.rf>a#a-ln95045-125-p2s2w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>APP</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
<coref_gram.rf>
<LM>t-ln95045-125-p2s2w15</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3">
<atree.rf>a#a-ln95045-125-p2s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-125-l6A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-125-p2s3w8</LM>
<LM>t-ln95045-125-p2s3w10</LM>
<LM>t-ln95045-125-p2s3w11</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-125-l7A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-125-p2s3w19</LM>
<LM>t-ln95045-125-p2s3w21</LM>
<LM>t-ln95045-125-p2s3w22</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-125-l8A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-125-p2s3w31</LM>
<LM>t-ln95045-125-p2s3w32</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-125-l9A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-125-p2s3w34</LM>
<LM>t-ln95045-125-p2s3w35</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-125-p2s3w24">
<a>
<lex.rf>a#a-ln95045-125-p2s3w24</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>18</deepord>
<children>
<LM id="t-ln95045-125-p2s3w4">
<a>
<lex.rf>a#a-ln95045-125-p2s3w4</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41sdjA</val_frame.rf>
<children>
<LM id="t-ln95045-125-p2s3w1">
<a>
<lex.rf>a#a-ln95045-125-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vklad</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95045-125-p2s3w2">
<a>
<lex.rf>a#a-ln95045-125-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klient</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-125-p2s2w21</target_node.rf>
<type>REST</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3w6">
<a>
<lex.rf>a#a-ln95045-125-p2s3w6</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtina</t_lemma>
<functor>DIFF</functor>
<proto_lemma>čtyři</proto_lemma>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>frac</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95045-125-p2s3a0">
<a>
<lex.rf>a#a-ln95045-125-p2s3w11</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>miliarda</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95045-125-p2s3w8">
<a>
<lex.rf>a#a-ln95045-125-p2s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.2</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3w11">
<a>
<lex.rf>a#a-ln95045-125-p2s3w11</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>miliarda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95045-125-p2s3w12">
<a>
<lex.rf>a#a-ln95045-125-p2s3w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95045-125-p2s3w10">
<a>
<lex.rf>a#a-ln95045-125-p2s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.7</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3w17">
<a>
<lex.rf>a#a-ln95045-125-p2s3w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vzrůst</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41pnkA</val_frame.rf>
<children>
<LM id="t-ln95045-125-p2s3w14">
<a>
<lex.rf>a#a-ln95045-125-p2s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>závazek</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln95045-125-p2s3w16">
<a>
<lex.rf>a#a-ln95045-125-p2s3w16</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>banka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3a1">
<a>
<lex.rf>a#a-ln95045-125-p2s3w22</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>miliarda</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95045-125-p2s3w19">
<a>
<lex.rf>a#a-ln95045-125-p2s3w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1.5</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3w22">
<a>
<lex.rf>a#a-ln95045-125-p2s3w22</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>miliarda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln95045-125-p2s3w23">
<a>
<lex.rf>a#a-ln95045-125-p2s3w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln95045-125-p2s3w21">
<a>
<lex.rf>a#a-ln95045-125-p2s3w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1.8</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3w29">
<a>
<lex.rf>a#a-ln95045-125-p2s3w29</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w28</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvětšit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>22</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95045-125-p2s3w17</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95045-125-p2s3w24</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41sbtA</val_frame.rf>
<children>
<LM id="t-ln95045-125-p2s3w25">
<a>
<lex.rf>a#a-ln95045-125-p2s3w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>objem</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln95045-125-p2s3w27">
<a>
<lex.rf>a#a-ln95045-125-p2s3w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úvěr</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<children>
<LM id="t-ln95045-125-p2s3w26">
<a>
<lex.rf>a#a-ln95045-125-p2s3w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klientský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3w32">
<a>
<lex.rf>a#a-ln95045-125-p2s3w32</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w30</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>DIFF</functor>
<tfa>f</tfa>
<deepord>23</deepord>
<children>
<LM id="t-ln95045-125-p2s3w31">
<a>
<lex.rf>a#a-ln95045-125-p2s3w31</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>15</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-125-p2s3w35">
<a>
<lex.rf>a#a-ln95045-125-p2s3w35</lex.rf>
<aux.rf>
<LM>a#a-ln95045-125-p2s3w33</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>miliarda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
<children>
<LM id="t-ln95045-125-p2s3w36">
<a>
<lex.rf>a#a-ln95045-125-p2s3w36</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>25</deepord>
</LM>
<LM id="t-ln95045-125-p2s3w34">
<a>
<lex.rf>a#a-ln95045-125-p2s3w34</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>4.1</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
