<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln95046_060.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln95046-060-p1s1">
<atree.rf>a#a-ln95046-060-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95046-060-p1s1w2">
<a>
<lex.rf>a#a-ln95046-060-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyhostit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41oaiA</val_frame.rf>
<children>
<LM id="t-ln95046-060-p1s1w1">
<a>
<lex.rf>a#a-ln95046-060-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Francie</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95046-060-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR1</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95046-060-p1s1w3">
<a>
<lex.rf>a#a-ln95046-060-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pětice</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95046-060-p1s1w4">
<a>
<lex.rf>a#a-ln95046-060-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>občan</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95046-060-p1s1w5">
<a>
<lex.rf>a#a-ln95046-060-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>USA</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s1A">
<atree.rf>a#a-ln95046-060-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95046-060-p2s1Aw1">
<a>
<lex.rf>a#a-ln95046-060-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Paříž</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95046-060-p1s1w1</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s1B">
<atree.rf>a#a-ln95046-060-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95046-060-l1A">
<basic-form>ministr vnitra</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-060-p2s1Bw2</LM>
<LM>t-ln95046-060-p2s1Bw3</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95046-060-l2A">
<basic-form>Charles Pasqua</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln95046-060-p2s1Bw4</LM>
<LM>t-ln95046-060-p2s1Bw5</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95046-060-l3A">
<basic-form>Spojené státy americké</basic-form>
<type>institution</type>
<tnode.rfs>
<LM>t-ln95046-060-p2s1Bw9</LM>
<LM>t-ln95046-060-p2s1Bw10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95046-060-p2s1Bw6">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>požádat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41gxkA</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s1Bw5">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pasqua</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95046-060-p2s1Bw4">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Charles</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95046-060-p2s1Bw2">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministr</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95046-060-p2s1Bw1">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>francouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-060-p2s1Bw3">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vnitro</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s1Bw8">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úřad</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95046-060-p2s1Bw7">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příslušný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln95046-060-p2s1Bw10">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p1s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-060-p2s1Bw9">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Spojený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s1Bw14">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw14</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s1Bw12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odvolat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41enfA</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s1Ba0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s1Bw8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-060-p2s1Bw16">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw16</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s1Bw15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Francie</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s1Bw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-060-p2s1Bw19">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>občan</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p1s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-060-p2s1Bw18">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>americký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s1Bw10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-060-p2s1Bw17">
<a>
<lex.rf>a#a-ln95046-060-p2s1Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pět</t_lemma>
<functor>RSTR</functor>
<proto_lemma>pět</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s2">
<atree.rf>a#a-ln95046-060-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95046-060-l4A">
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-060-p2s2w4</LM>
<LM>t-ln95046-060-p2s2w5</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95046-060-l5A">
<basic-form>diplomatické zastoupení</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-060-p2s2w13</LM>
<LM>t-ln95046-060-p2s2w14</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95046-060-p2s2w19">
<a>
<lex.rf>a#a-ln95046-060-p2s2w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyvíjet</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<val_frame.rf>v#v41pgpA</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s2w18">
<a>
<lex.rf>a#a-ln95046-060-p2s2w18</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>údajně</t_lemma>
<functor>ATT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95046-060-p2s2w2">
<a>
<lex.rf>a#a-ln95046-060-p2s2w2</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41ndjG</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s2a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s2w19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-060-p2s2w3">
<a>
<lex.rf>a#a-ln95046-060-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>deník</t_lemma>
<functor>ACT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95046-060-p2s2w5">
<a>
<lex.rf>a#a-ln95046-060-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Monde</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95046-060-p2s2w4">
<a>
<lex.rf>a#a-ln95046-060-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Le</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s2w9">
<a>
<lex.rf>a#a-ln95046-060-p2s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osoba</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s1Bw19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-060-p2s2w7">
<a>
<lex.rf>a#a-ln95046-060-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95046-060-p2s2w8">
<a>
<lex.rf>a#a-ln95046-060-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvedený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln95046-060-p2s2w12">
<a>
<lex.rf>a#a-ln95046-060-p2s2w12</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovník</t_lemma>
<functor>ACMP</functor>
<subfunctor>incl</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95046-060-p2s2w9</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln95046-060-p2s2w11">
<a>
<lex.rf>a#a-ln95046-060-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtyři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>čtyři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln95046-060-p2s2w14">
<a>
<lex.rf>a#a-ln95046-060-p2s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zastoupení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41qmpC</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s2w15">
<a>
<lex.rf>a#a-ln95046-060-p2s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>USA</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s1Bw18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-060-p2s2w13">
<a>
<lex.rf>a#a-ln95046-060-p2s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>diplomatický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95046-060-p2s2w17">
<a>
<lex.rf>a#a-ln95046-060-p2s2w17</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s2w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Francie</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s1Bw16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s2w22">
<a>
<lex.rf>a#a-ln95046-060-p2s2w22</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s2w20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>území</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln95046-060-p2s2w21">
<a>
<lex.rf>a#a-ln95046-060-p2s2w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>francouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s2w17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s2w24">
<a>
<lex.rf>a#a-ln95046-060-p2s2w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>aktivita</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln95046-060-p2s2w23">
<a>
<lex.rf>a#a-ln95046-060-p2s2w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyzvědačský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s3">
<atree.rf>a#a-ln95046-060-p2s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95046-060-l6A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95046-060-p2s3w13</LM>
<LM>t-ln95046-060-p2s3w14</LM>
<LM>t-ln95046-060-p2s3w15</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95046-060-p2s3w6">
<a>
<lex.rf>a#a-ln95046-060-p2s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zjistit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41rexB</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s3w5">
<a>
<lex.rf>a#a-ln95046-060-p2s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kontrašpionáž</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95046-060-p2s3w4">
<a>
<lex.rf>a#a-ln95046-060-p2s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>francouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s2w21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s3w3">
<a>
<lex.rf>a#a-ln95046-060-p2s3w3</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s3w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>informace</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="t-ln95046-060-p2s3w2">
<a>
<lex.rf>a#a-ln95046-060-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s3w9">
<a>
<lex.rf>a#a-ln95046-060-p2s3w9</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s3w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jít</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41bikAV</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s3w11">
<a>
<lex.rf>a#a-ln95046-060-p2s3w11</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s3w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovník</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s2w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-060-p2s3w16">
<a>
<lex.rf>a#a-ln95046-060-p2s3w16</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Bracket</t_lemma>
<functor>APPS</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln95046-060-p2s3w15">
<a>
<lex.rf>a#a-ln95046-060-p2s3w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>služba</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln95046-060-p2s3w12">
<a>
<lex.rf>a#a-ln95046-060-p2s3w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>americký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s2w15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-060-p2s3w14">
<a>
<lex.rf>a#a-ln95046-060-p2s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zpravodajský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln95046-060-p2s3w13">
<a>
<lex.rf>a#a-ln95046-060-p2s3w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ústřední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s3w17">
<a>
<lex.rf>a#a-ln95046-060-p2s3w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>CIA</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s3w22">
<a>
<lex.rf>a#a-ln95046-060-p2s3w22</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s3w21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snažit_se</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41kwuA</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s3w20">
<a>
<lex.rf>a#a-ln95046-060-p2s3w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_gram.rf>
<LM>t-ln95046-060-p2s3w11</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95046-060-p2s3w23">
<a>
<lex.rf>a#a-ln95046-060-p2s3w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>naverbovat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41dfzA</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s3a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_gram.rf>
<LM>t-ln95046-060-p2s3w20</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95046-060-p2s3w25">
<a>
<lex.rf>a#a-ln95046-060-p2s3w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaměstnanec</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln95046-060-p2s3w27">
<a>
<lex.rf>a#a-ln95046-060-p2s3w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln95046-060-p2s3w26">
<a>
<lex.rf>a#a-ln95046-060-p2s3w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>francouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s3w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s3w24">
<a>
<lex.rf>a#a-ln95046-060-p2s3w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>některý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>indef1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s4">
<atree.rf>a#a-ln95046-060-p2s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95046-060-l7A">
<basic-form>diplomatická mise</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95046-060-p2s4w14</LM>
<LM>t-ln95046-060-p2s4w15</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95046-060-p2s4w11">
<a>
<lex.rf>a#a-ln95046-060-p2s4w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sdělit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41kgjA</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s4w2">
<a>
<lex.rf>a#a-ln95046-060-p2s4w2</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s4w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dodávat</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<discourse_comment>one_arg</discourse_comment>
<val_frame.rf>v#v41wzD</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s4a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>EFF</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s4w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95046-060-p2s4w3">
<a>
<lex.rf>a#a-ln95046-060-p2s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>ACT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95046-060-p2s4w4">
<a>
<lex.rf>a#a-ln95046-060-p2s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Reuter</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s4w6">
<a>
<lex.rf>a#a-ln95046-060-p2s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mluvčí</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95046-060-p2s4w8">
<a>
<lex.rf>a#a-ln95046-060-p2s4w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>velvyslanectví</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s2w14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-060-p2s4w7">
<a>
<lex.rf>a#a-ln95046-060-p2s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>americký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s3w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s4w10">
<a>
<lex.rf>a#a-ln95046-060-p2s4w10</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s4w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>případ</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_special>segm</coref_special>
</LM>
<LM id="t-ln95046-060-p2s4a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln95046-060-p2s4w21">
<a>
<lex.rf>a#a-ln95046-060-p2s4w21</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s4w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaujímat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41qrgD</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s4w15">
<a>
<lex.rf>a#a-ln95046-060-p2s4w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mise</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95046-060-p2s4w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95046-060-p2s4w14">
<a>
<lex.rf>a#a-ln95046-060-p2s4w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>diplomatický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s4w20">
<a>
<lex.rf>a#a-ln95046-060-p2s4w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nikdy</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>kdy</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.indef</sempos>
<indeftype>negat</indeftype>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln95046-060-p2s4a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95046-060-p2s4w23">
<a>
<lex.rf>a#a-ln95046-060-p2s4w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stanovisko</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<val_frame.rf>v#v41lhyA</val_frame.rf>
<children>
<LM id="t-ln95046-060-p2s4w17">
<a>
<lex.rf>a#a-ln95046-060-p2s4w17</lex.rf>
<aux.rf>
<LM>a#a-ln95046-060-p2s4w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>záležitost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95046-060-p2s4w10</target_node.rf>
<type>ANAF</type>
</LM>
</bridging>
<children>
<LM id="t-ln95046-060-p2s4w19">
<a>
<lex.rf>a#a-ln95046-060-p2s4w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>charakter</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln95046-060-p2s4w18">
<a>
<lex.rf>a#a-ln95046-060-p2s4w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podobný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95046-060-p2s4a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>19</deepord>
<coref_gram.rf>
<LM>t-ln95046-060-p2s4w15</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95046-060-p2s4w22">
<a>
<lex.rf>a#a-ln95046-060-p2s4w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veřejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
