<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf930709_008.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-mf930709-008-p1s1">
<atree.rf>a#a-mf930709-008-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l5B">
<type>time</type>
<tnode.rfs>
<LM>t-mf930709-008-p1s1w9</LM>
<LM>t-mf930709-008-p1s1w11</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p1s1w2">
<a>
<lex.rf>a#a-mf930709-008-p1s1w2</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Colon</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<tfa>t</tfa>
<deepord>2</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-mf930709-008-p1s1w1">
<a>
<lex.rf>a#a-mf930709-008-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ruml</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-008-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>EFF</functor>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-008-p1s1w5">
<a>
<lex.rf>a#a-mf930709-008-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>režim</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-008-p1s1w4">
<a>
<lex.rf>a#a-mf930709-008-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hraniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-008-p1s1w7">
<a>
<lex.rf>a#a-mf930709-008-p1s1w7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p1s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>SR</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930709-008-p1s1w3">
<a>
<lex.rf>a#a-mf930709-008-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>běžný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-008-p1s1w11">
<a>
<lex.rf>a#a-mf930709-008-p1s1w11</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p1s1w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>červenec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf930709-008-p1s1w9">
<a>
<lex.rf>a#a-mf930709-008-p1s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>20</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s1A">
<atree.rf>a#a-mf930709-008-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-008-p2s1Aw1">
<a>
<lex.rf>a#a-mf930709-008-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-008-p2s1Aw4">
<a>
<lex.rf>a#a-mf930709-008-p2s1Aw4</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<is_parenthesis>1</is_parenthesis>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-008-p2s1Aw3">
<a>
<lex.rf>a#a-mf930709-008-p2s1Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>km</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>nr</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-008-p2s1Aw5">
<a>
<lex.rf>a#a-mf930709-008-p2s1Aw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČTK</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s1B">
<atree.rf>a#a-mf930709-008-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l11B">
<type>time</type>
<tnode.rfs>
<LM>t-mf930709-008-p2s1Bw12</LM>
<LM>t-mf930709-008-p2s1Bw14</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l8A">
<type>location</type>
<tnode.rfs>
<LM>t-mf930709-008-p2s1Bw7</LM>
<LM>t-mf930709-008-p2s1Bw9</LM>
<LM>t-mf930709-008-p2s1Bw10</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l37B">
<basic-form>běžný pohraniční režim</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p2s1Bw1</LM>
<LM>t-mf930709-008-p2s1Bw2</LM>
<LM>t-mf930709-008-p2s1Bw3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p2s1Bw8">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zavést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41qsnE</val_frame.rf>
<children>
<LM id="t-mf930709-008-p2s1Bw3">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>režim</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p1s1w5</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-008-p2s1Bw2">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pohraniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-008-p2s1Bw1">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>běžný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-008-p2s1Bw5">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p2s1Bw4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hranice</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-008-p2s1Bw7">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p2s1Bw6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Slovensko</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p1s1w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s1Bw10">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>republika</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p2s1Aw1</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-008-p2s1Bw9">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s1Bw14">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw14</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p2s1Bw11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>červenec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p1s1w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-008-p2s1Bw12">
<a>
<lex.rf>a#a-mf930709-008-p2s1Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>20</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s2">
<atree.rf>a#a-mf930709-008-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l13B">
<basic-form>Jan Ruml</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-008-p2s2w3</LM>
<LM>t-mf930709-008-p2s2w4</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l38B">
<basic-form>ministr vnitra</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p2s2w1</LM>
<LM>t-mf930709-008-p2s2w2</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l39B">
<basic-form>politická reprezentace</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p2s2w19</LM>
<LM>t-mf930709-008-p2s2w20</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p2s2w6">
<a>
<lex.rf>a#a-mf930709-008-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p2s2w4">
<a>
<lex.rf>a#a-mf930709-008-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ruml</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-008-p2s2w3">
<a>
<lex.rf>a#a-mf930709-008-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jan</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-008-p2s2w1">
<a>
<lex.rf>a#a-mf930709-008-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministr</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p2s1Bw10</target_node.rf>
<type>P_FUNCT</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-008-p2s2w2">
<a>
<lex.rf>a#a-mf930709-008-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vnitro</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s2a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-008-p2s2w5">
<a>
<lex.rf>a#a-mf930709-008-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930709-008-p2s2w13">
<a>
<lex.rf>a#a-mf930709-008-p2s2w13</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p2s2w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>začít</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41prbA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p2s2w10">
<a>
<lex.rf>a#a-mf930709-008-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>opatření</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p2s1Bw3</target_node.rf>
<type>REST</type>
</LM>
</bridging>
<val_frame.rf>v#v41euvB</val_frame.rf>
<children>
<LM id="t-mf930709-008-p2s2w9">
<a>
<lex.rf>a#a-mf930709-008-p2s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>připravený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-008-p2s2w12">
<a>
<lex.rf>a#a-mf930709-008-p2s2w12</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p2s2w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hranice</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p2s1Bw5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s2w14">
<a>
<lex.rf>a#a-mf930709-008-p2s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>platit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41fmtI</val_frame.rf>
<children>
<LM id="t-mf930709-008-p2s2a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_gram.rf>
<LM>t-mf930709-008-p2s2w10</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s2w22">
<a>
<lex.rf>a#a-mf930709-008-p2s2w22</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p2s2w16</LM>
</aux.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ať_nebo</t_lemma>
<functor>DISJ</functor>
<deepord>20</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-008-p2s2w13</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>cond</discourse_type>
<sense_PDTB3>Contingency.Condition.Arg2-as-cond</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-mf930709-008-p2s2w16</LM>
</a-connectors.rf>
<t-connectors.rf>
<LM>t-mf930709-008-p2s2w17</LM>
</t-connectors.rf>
</LM>
</discourse>
<children>
<LM id="t-mf930709-008-p2s2w20">
<a>
<lex.rf>a#a-mf930709-008-p2s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>reprezentace</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>14</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p2s1Bw7</target_node.rf>
<type>P_FUNCT</type>
</LM>
<LM>
<target_node.rf>t-mf930709-008-p2s1Bw10</target_node.rf>
<type>P_FUNCT</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-008-p2s2w19">
<a>
<lex.rf>a#a-mf930709-008-p2s2w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>politický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p2s2a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-mf930709-008-p2s2a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_gram.rf>
<LM>t-mf930709-008-p2s2w20</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-008-p2s2w17">
<a>
<lex.rf>a#a-mf930709-008-p2s2w17</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>už</t_lemma>
<functor>CM</functor>
<deepord>18</deepord>
</LM>
<LM id="t-mf930709-008-p2s2w21">
<a>
<lex.rf>a#a-mf930709-008-p2s2w21</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p2s2w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohodnout_se</t_lemma>
<functor>CNCS</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<val_frame.rf>v#v41yeA</val_frame.rf>
</LM>
<LM id="t-mf930709-008-p2s2w23">
<a>
<lex.rf>a#a-mf930709-008-p2s2w23</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p2s2w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohodnout_se</t_lemma>
<functor>CNCS</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>21</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-008-p2s2w21</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>disjalt</discourse_type>
<sense_PDTB3>Expansion.Disjunction</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-mf930709-008-p2s2w22</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41yeA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p2s2a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p3s1">
<atree.rf>a#a-mf930709-008-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l40B">
<basic-form>pohraniční policie</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p3s1w11</LM>
<LM>t-mf930709-008-p3s1w12</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l41B">
<basic-form>voják základní služby</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p3s1w16</LM>
<LM>t-mf930709-008-p3s1w17</LM>
<LM>t-mf930709-008-p3s1w18</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p3s1w2">
<a>
<lex.rf>a#a-mf930709-008-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p3s1w1">
<a>
<lex.rf>a#a-mf930709-008-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ruml</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p2s2w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p3s1w10">
<a>
<lex.rf>a#a-mf930709-008-p3s1w10</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s1w9</LM>
<LM>a#a-mf930709-008-p3s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlídkovat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41avuA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p3s1w7">
<a>
<lex.rf>a#a-mf930709-008-p3s1w7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s1w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>délka</t_lemma>
<functor>LOC</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-008-p3s1w6">
<a>
<lex.rf>a#a-mf930709-008-p3s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-008-p3s1w8">
<a>
<lex.rf>a#a-mf930709-008-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hranice</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p2s2w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p3s1w12">
<a>
<lex.rf>a#a-mf930709-008-p3s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>policie</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf930709-008-p3s1w11">
<a>
<lex.rf>a#a-mf930709-008-p3s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pohraniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-008-p3s1w14">
<a>
<lex.rf>a#a-mf930709-008-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>posílený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-008-p3s1w16">
<a>
<lex.rf>a#a-mf930709-008-p3s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>voják</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-008-p3s1w18">
<a>
<lex.rf>a#a-mf930709-008-p3s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>služba</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-mf930709-008-p3s1w17">
<a>
<lex.rf>a#a-mf930709-008-p3s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>základní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p3s1w15">
<a>
<lex.rf>a#a-mf930709-008-p3s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>290</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-mf930709-008-p3s1w20">
<a>
<lex.rf>a#a-mf930709-008-p3s1w20</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s1w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zbraň</t_lemma>
<functor>ACMP</functor>
<subfunctor>wout</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p3s2">
<atree.rf>a#a-mf930709-008-p3s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l32B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-008-p3s2w1</LM>
<LM>t-mf930709-008-p3s2w2</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l42B">
<basic-form>hraniční přechod</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p3s2w4</LM>
<LM>t-mf930709-008-p3s2w5</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l43B">
<basic-form>nežádoucí osoba</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p3s2w14</LM>
<LM>t-mf930709-008-p3s2w15</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l44B">
<basic-form>třetí země</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p3s2w11</LM>
<LM>t-mf930709-008-p3s2w12</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p3s2w7">
<a>
<lex.rf>a#a-mf930709-008-p3s2w7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s2w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sledovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41kslD</val_frame.rf>
<children>
<LM id="t-mf930709-008-p3s2w2">
<a>
<lex.rf>a#a-mf930709-008-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>policie</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-008-p3s2w1">
<a>
<lex.rf>a#a-mf930709-008-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cizinecký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-008-p3s2w5">
<a>
<lex.rf>a#a-mf930709-008-p3s2w5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přechod</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-008-p3s2w4">
<a>
<lex.rf>a#a-mf930709-008-p3s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hraniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p3s1w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p3s2w13">
<a>
<lex.rf>a#a-mf930709-008-p3s2w13</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-008-p3s2w8">
<a>
<lex.rf>a#a-mf930709-008-p3s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pohyb</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf930709-008-p3s2w9">
<a>
<lex.rf>a#a-mf930709-008-p3s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cizinec</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf930709-008-p3s2w12">
<a>
<lex.rf>a#a-mf930709-008-p3s2w12</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>země</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf930709-008-p3s2w11">
<a>
<lex.rf>a#a-mf930709-008-p3s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetí</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p3s2w15">
<a>
<lex.rf>a#a-mf930709-008-p3s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osoba</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-mf930709-008-p3s2w14">
<a>
<lex.rf>a#a-mf930709-008-p3s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žádoucí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p3s3">
<atree.rf>a#a-mf930709-008-p3s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-008-p3s3w21">
<a>
<lex.rf>a#a-mf930709-008-p3s3w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p3s3w22">
<a>
<lex.rf>a#a-mf930709-008-p3s3w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ruml</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p3s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p3s3a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-008-p3s3w3">
<a>
<lex.rf>a#a-mf930709-008-p3s3w3</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s3w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlídat</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-008-p3s2w7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf930709-008-p3s3w1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41avsA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p3s3a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p3s2w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p3s3w1">
<a>
<lex.rf>a#a-mf930709-008-p3s3w1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>rovněž</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930709-008-p3s3w11">
<a>
<lex.rf>a#a-mf930709-008-p3s3w11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-mf930709-008-p3s3w8">
<a>
<lex.rf>a#a-mf930709-008-p3s3w8</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s3w5</LM>
<LM>a#a-mf930709-008-p3s3w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vybavit</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>res1</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41ntgA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p3s3w7">
<a>
<lex.rf>a#a-mf930709-008-p3s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příchozí</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-008-p3s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-008-p3s3w10">
<a>
<lex.rf>a#a-mf930709-008-p3s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vízum</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-008-p3s3w9">
<a>
<lex.rf>a#a-mf930709-008-p3s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>platný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p3s3w13">
<a>
<lex.rf>a#a-mf930709-008-p3s3w13</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s3w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>splňovat</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-008-p3s3w8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf930709-008-p3s3w11</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41lcfA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p3s3a3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p3s3w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p3s3w14">
<a>
<lex.rf>a#a-mf930709-008-p3s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podmínka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-mf930709-008-p3s3w16">
<a>
<lex.rf>a#a-mf930709-008-p3s3w16</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s3w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vstup</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf930709-008-p3s3w19">
<a>
<lex.rf>a#a-mf930709-008-p3s3w19</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p3s3w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>území</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-mf930709-008-p3s3w18">
<a>
<lex.rf>a#a-mf930709-008-p3s3w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p2s1Bw10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s1">
<atree.rf>a#a-mf930709-008-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l33B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-008-p4s1w1</LM>
<LM>t-mf930709-008-p4s1w2</LM>
<LM>t-mf930709-008-p4s1w3</LM>
<LM>t-mf930709-008-p4s1w4</LM>
<LM>t-mf930709-008-p4s1w5</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l40A">
<basic-form>administrativní hranice</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p4s1w21</LM>
<LM>t-mf930709-008-p4s1w22</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p4s1w13">
<a>
<lex.rf>a#a-mf930709-008-p4s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpořit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41fuiB</val_frame.rf>
<children>
<LM id="t-mf930709-008-p4s1w5">
<a>
<lex.rf>a#a-mf930709-008-p4s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komise</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-008-p4s1w4">
<a>
<lex.rf>a#a-mf930709-008-p4s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhraničovací</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-008-p4s1w2">
<a>
<lex.rf>a#a-mf930709-008-p4s1w2</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Dash</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-008-p4s1w1">
<a>
<lex.rf>a#a-mf930709-008-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p3s3w18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p4s1w3">
<a>
<lex.rf>a#a-mf930709-008-p4s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>slovenský</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p2s1Bw7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s1w8">
<a>
<lex.rf>a#a-mf930709-008-p4s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41bhrA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p4s1w7">
<a>
<lex.rf>a#a-mf930709-008-p4s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_gram.rf>
<LM>t-mf930709-008-p4s1w5</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-008-p4s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-008-p4s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-008-p4s1w10">
<a>
<lex.rf>a#a-mf930709-008-p4s1w10</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p4s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p2s1Aw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s1w12">
<a>
<lex.rf>a#a-mf930709-008-p4s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf930709-008-p4s1w14">
<a>
<lex.rf>a#a-mf930709-008-p4s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-mf930709-008-p4s1w17">
<a>
<lex.rf>a#a-mf930709-008-p4s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předpokládat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41hxpB</val_frame.rf>
<children>
<LM id="t-mf930709-008-p4s1w16">
<a>
<lex.rf>a#a-mf930709-008-p4s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_gram.rf>
<LM>t-mf930709-008-p4s1w14</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-008-p4s1w18">
<a>
<lex.rf>a#a-mf930709-008-p4s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přeložení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<val_frame.rf>v#v41idvB</val_frame.rf>
<children>
<LM id="t-mf930709-008-p4s1a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-mf930709-008-p4s1a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR1</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-mf930709-008-p4s1w20">
<a>
<lex.rf>a#a-mf930709-008-p4s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průběh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-mf930709-008-p4s1w22">
<a>
<lex.rf>a#a-mf930709-008-p4s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hranice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p3s2w4</target_node.rf>
<type>REST</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-008-p4s1w21">
<a>
<lex.rf>a#a-mf930709-008-p4s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>administrativní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s1w19">
<a>
<lex.rf>a#a-mf930709-008-p4s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nynější</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s1w24">
<a>
<lex.rf>a#a-mf930709-008-p4s1w24</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p4s1w23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osa</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<children>
<LM id="t-mf930709-008-p4s1w26">
<a>
<lex.rf>a#a-mf930709-008-p4s1w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tok</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<children>
<LM id="t-mf930709-008-p4s1w25">
<a>
<lex.rf>a#a-mf930709-008-p4s1w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>regulovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
</LM>
<LM id="t-mf930709-008-p4s1w27">
<a>
<lex.rf>a#a-mf930709-008-p4s1w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Morava</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s2">
<atree.rf>a#a-mf930709-008-p4s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l22B">
<basic-form>Jiří Pešek</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-008-p4s2w6</LM>
<LM>t-mf930709-008-p4s2w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p4s2w8">
<a>
<lex.rf>a#a-mf930709-008-p4s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p4s2w7">
<a>
<lex.rf>a#a-mf930709-008-p4s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pešek</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-008-p4s2w6">
<a>
<lex.rf>a#a-mf930709-008-p4s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jiří</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-008-p4s2w1">
<a>
<lex.rf>a#a-mf930709-008-p4s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-008-p4s2w5">
<a>
<lex.rf>a#a-mf930709-008-p4s2w5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p4s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komise</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s1w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p4s2w3">
<a>
<lex.rf>a#a-mf930709-008-p4s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>delegace</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p4s2w5</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-008-p4s2w2">
<a>
<lex.rf>a#a-mf930709-008-p4s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s2w15">
<a>
<lex.rf>a#a-mf930709-008-p4s2w15</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p4s2w13</LM>
<LM>a#a-mf930709-008-p4s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>EFF</functor>
<proto_lemma>mít</proto_lemma>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41chlO</val_frame.rf>
<children>
<LM id="t-mf930709-008-p4s2w14">
<a>
<lex.rf>a#a-mf930709-008-p4s2w14</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>tak</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-008-p4s2w12">
<a>
<lex.rf>a#a-mf930709-008-p4s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>strana</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s1w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-008-p4s2w11">
<a>
<lex.rf>a#a-mf930709-008-p4s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oba</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s2w17">
<a>
<lex.rf>a#a-mf930709-008-p4s2w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přístup</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-mf930709-008-p4s2w19">
<a>
<lex.rf>a#a-mf930709-008-p4s2w19</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p4s2w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>voda</t_lemma>
<functor>DIR3</functor>
<subfunctor>to</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p4s1w27</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
<LM id="t-mf930709-008-p4s2w16">
<a>
<lex.rf>a#a-mf930709-008-p4s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rovnocenný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s3">
<atree.rf>a#a-mf930709-008-p4s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l25B">
<type>location</type>
<tnode.rfs>
<LM>t-mf930709-008-p4s3w8</LM>
<LM>t-mf930709-008-p4s3w9</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l41A">
<basic-form>administrativní hranice</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-008-p4s3w3</LM>
<LM>t-mf930709-008-p4s3w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p4s3w5">
<a>
<lex.rf>a#a-mf930709-008-p4s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>protékat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41hpiB</val_frame.rf>
<children>
<LM id="t-mf930709-008-p4s3w4">
<a>
<lex.rf>a#a-mf930709-008-p4s3w4</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p4s3w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hranice</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s1w22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-008-p4s3w2">
<a>
<lex.rf>a#a-mf930709-008-p4s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>současný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-008-p4s3w3">
<a>
<lex.rf>a#a-mf930709-008-p4s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>administrativní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s3w6">
<a>
<lex.rf>a#a-mf930709-008-p4s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Morava</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s1w27</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p4s3w7">
<a>
<lex.rf>a#a-mf930709-008-p4s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střídavě</t_lemma>
<functor>MANN</functor>
<proto_lemma>střídavý</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930709-008-p4s3w10">
<a>
<lex.rf>a#a-mf930709-008-p4s3w10</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>i</t_lemma>
<functor>CONJ</functor>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-008-p4s3w9">
<a>
<lex.rf>a#a-mf930709-008-p4s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>republika</t_lemma>
<functor>DIR2</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s2w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-008-p4s3w8">
<a>
<lex.rf>a#a-mf930709-008-p4s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p4s3w11">
<a>
<lex.rf>a#a-mf930709-008-p4s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Slovensko</t_lemma>
<functor>DIR2</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p5s1">
<atree.rf>a#a-mf930709-008-p5s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-008-l29B">
<basic-form>Ivica Brestovanská</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-008-p5s1w7</LM>
<LM>t-mf930709-008-p5s1w8</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-008-l36B">
<type>number</type>
<tnode.rfs>
<LM>t-mf930709-008-p5s1w20</LM>
<LM>t-mf930709-008-p5s1w21</LM>
<LM>t-mf930709-008-p5s1w22</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-008-p5s1w10">
<a>
<lex.rf>a#a-mf930709-008-p5s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p5s1w8">
<a>
<lex.rf>a#a-mf930709-008-p5s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Brestovanská</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-008-p5s1w7">
<a>
<lex.rf>a#a-mf930709-008-p5s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ivica</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-008-p5s1w1">
<a>
<lex.rf>a#a-mf930709-008-p5s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zástupkyně</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-008-p5s1w6">
<a>
<lex.rf>a#a-mf930709-008-p5s1w6</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p5s1w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komise</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s2w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p5s1w2">
<a>
<lex.rf>a#a-mf930709-008-p5s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-008-p5s1w4">
<a>
<lex.rf>a#a-mf930709-008-p5s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>delegace</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p5s1w6</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-008-p5s1w3">
<a>
<lex.rf>a#a-mf930709-008-p5s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>slovenský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s3w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p5s1w9">
<a>
<lex.rf>a#a-mf930709-008-p5s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-008-p2s1Aw3</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
</LM>
<LM id="t-mf930709-008-p5s1w18">
<a>
<lex.rf>a#a-mf930709-008-p5s1w18</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p5s1w17</LM>
<LM>a#a-mf930709-008-p5s1w15</LM>
<LM>a#a-mf930709-008-p5s1w12</LM>
<LM>a#a-mf930709-008-p5s1w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zkrátit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>deagent</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41rhcA</val_frame.rf>
<children>
<LM id="t-mf930709-008-p5s1w14">
<a>
<lex.rf>a#a-mf930709-008-p5s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hranice</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s3w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-008-p5s1w13">
<a>
<lex.rf>a#a-mf930709-008-p5s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosavadní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p5s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-mf930709-008-p5s1w23">
<a>
<lex.rf>a#a-mf930709-008-p5s1w23</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p5s1w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kilometr</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-mf930709-008-p5s1w21">
<a>
<lex.rf>a#a-mf930709-008-p5s1w21</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>až</t_lemma>
<functor>OPER</functor>
<deepord>16</deepord>
<children>
<LM id="t-mf930709-008-p5s1w20">
<a>
<lex.rf>a#a-mf930709-008-p5s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>230</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-mf930709-008-p5s1w22">
<a>
<lex.rf>a#a-mf930709-008-p5s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>250</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p5s2">
<atree.rf>a#a-mf930709-008-p5s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-008-p5s2w2">
<a>
<lex.rf>a#a-mf930709-008-p5s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvažovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41ncrB</val_frame.rf>
<children>
<LM id="t-mf930709-008-p5s2w1">
<a>
<lex.rf>a#a-mf930709-008-p5s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komise</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p5s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-008-p5s2w3">
<a>
<lex.rf>a#a-mf930709-008-p5s2w3</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>až</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-008-p5s2w6">
<a>
<lex.rf>a#a-mf930709-008-p5s2w6</lex.rf>
<aux.rf>
<LM>a#a-mf930709-008-p5s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>možnost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-008-p5s2w7">
<a>
<lex.rf>a#a-mf930709-008-p5s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>změna</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-008-p5s2w8">
<a>
<lex.rf>a#a-mf930709-008-p5s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průběh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p4s1w20</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-008-p5s2w9">
<a>
<lex.rf>a#a-mf930709-008-p5s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hranice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-008-p5s1w14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-008-p5s2w5">
<a>
<lex.rf>a#a-mf930709-008-p5s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>16</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
