<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf930709_018.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>description</genre>
</meta>
<trees>
<LM id="t-mf930709-018-p1s1">
<atree.rf>a#a-mf930709-018-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l11B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-018-p1s1w1</LM>
<LM>t-mf930709-018-p1s1w2</LM>
<LM>t-mf930709-018-p1s1w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p1s1w4">
<a>
<lex.rf>a#a-mf930709-018-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>začínat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41pqyA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p1s1w1">
<a>
<lex.rf>a#a-mf930709-018-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-018-p1s1w3">
<a>
<lex.rf>a#a-mf930709-018-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bratr</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf930709-018-p1s1w2">
<a>
<lex.rf>a#a-mf930709-018-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Milosrdný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p1s1w5">
<a>
<lex.rf>a#a-mf930709-018-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hospodařit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41axnB</val_frame.rf>
<children>
<LM id="t-mf930709-018-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-mf930709-018-p1s1w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-018-p1s1w6">
<a>
<lex.rf>a#a-mf930709-018-p1s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>samostatně</t_lemma>
<functor>MANN</functor>
<proto_lemma>samostatný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s1A">
<atree.rf>a#a-mf930709-018-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-018-p2s1Aw1">
<a>
<lex.rf>a#a-mf930709-018-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Brno</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-018-p2s1Aw3">
<a>
<lex.rf>a#a-mf930709-018-p2s1Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kar</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>nr</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s1B">
<atree.rf>a#a-mf930709-018-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l12B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s1Bw1</LM>
<LM>t-mf930709-018-p2s1Bw2</LM>
<LM>t-mf930709-018-p2s1Bw3</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-018-l23A">
<basic-form>právní subjektivita</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s1Bw9</LM>
<LM>t-mf930709-018-p2s1Bw10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s1Bw4">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41chlQ</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s1Bw1">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p1s1a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-018-p2s1Bw3">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bratr</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p1s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-018-p2s1Bw2">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milosrdný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s1Bw6">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw6</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s1Bw5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počátek</t_lemma>
<functor>TSIN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-018-p2s1Bw8">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíc</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_special>exoph</coref_special>
<children>
<LM id="t-mf930709-018-p2s1Bw7">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s1Bw10">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>subjektivita</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf930709-018-p2s1Bw9">
<a>
<lex.rf>a#a-mf930709-018-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>právní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s2A">
<atree.rf>a#a-mf930709-018-p2s2A</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l13B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s2Aw6</LM>
<LM>t-mf930709-018-p2s2Aw7</LM>
<LM>t-mf930709-018-p2s2Aw8</LM>
<LM>t-mf930709-018-p2s2Aw9</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s2Aw3">
<a>
<lex.rf>a#a-mf930709-018-p2s2Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fungovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41asiB</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s2Aw1">
<a>
<lex.rf>a#a-mf930709-018-p2s2Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosud</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-018-p2s2Aw2">
<a>
<lex.rf>a#a-mf930709-018-p2s2Aw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s1Bw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s2Aw5">
<a>
<lex.rf>a#a-mf930709-018-p2s2Aw5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s2Aw4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>součást</t_lemma>
<functor>COMPL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<compl.rf>
<LM>t-mf930709-018-p2s2Aw2</LM>
</compl.rf>
<children>
<LM id="t-mf930709-018-p2s2Aw6">
<a>
<lex.rf>a#a-mf930709-018-p2s2Aw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sdružení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41kgoB</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s2Aw8">
<a>
<lex.rf>a#a-mf930709-018-p2s2Aw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zařízení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41qjoC</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s2Aw7">
<a>
<lex.rf>a#a-mf930709-018-p2s2Aw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdravotnický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s2Aw9">
<a>
<lex.rf>a#a-mf930709-018-p2s2Aw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>I</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s2B">
<atree.rf>a#a-mf930709-018-p2s2B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l14B">
<type>number</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s2Bw5</LM>
<LM>t-mf930709-018-p2s2Bw6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s2Bw4">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přispívat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41iywC</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s2Bw3">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw3</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s2Bw1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozpočet</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf930709-018-p2s2Bw2">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s2Aw6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s2Ba0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s2Aw2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s2Bw6">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-018-p2s2Bw5">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>54</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s2Bw10">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw10</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s2Bw8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovat</t_lemma>
<functor>CNCS</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-018-p2s2Bw4</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conc</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg1-as-denier</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-mf930709-018-p2s2Bw8</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41gyaF</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s2Bw9">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zde</t_lemma>
<functor>LOC</functor>
<proto_lemma>tady</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s2Ba0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s2Bw11">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw11</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>pouze</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-mf930709-018-p2s2Bw12">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetina</t_lemma>
<functor>ACT</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>n.quant.def</sempos>
<gender>fem</gender>
<number>sg</number>
<numertype>frac</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-018-p2s2Bw13">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaměstnanec</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-mf930709-018-p2s2Bw14">
<a>
<lex.rf>a#a-mf930709-018-p2s2Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sdružení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s2Bw2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41kgoB</val_frame.rf>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s3">
<atree.rf>a#a-mf930709-018-p2s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l15B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s3w1</LM>
<LM>t-mf930709-018-p2s3w2</LM>
<LM>t-mf930709-018-p2s3w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s3w14">
<a>
<lex.rf>a#a-mf930709-018-p2s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>očekávat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41dvcD</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s3w1">
<a>
<lex.rf>a#a-mf930709-018-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řád</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s1Bw3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-018-p2s3w3">
<a>
<lex.rf>a#a-mf930709-018-p2s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bratr</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf930709-018-p2s3w2">
<a>
<lex.rf>a#a-mf930709-018-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milosrdný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s3w9">
<a>
<lex.rf>a#a-mf930709-018-p2s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>usilovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41mveA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s3w5">
<a>
<lex.rf>a#a-mf930709-018-p2s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_gram.rf>
<LM>t-mf930709-018-p2s3w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-018-p2s3w7">
<a>
<lex.rf>a#a-mf930709-018-p2s3w7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s3w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osamostatnění</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s1Bw4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41eyuB</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s3w8">
<a>
<lex.rf>a#a-mf930709-018-p2s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s2Bw9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s3w10">
<a>
<lex.rf>a#a-mf930709-018-p2s3w10</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>už</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-018-p2s3w12">
<a>
<lex.rf>a#a-mf930709-018-p2s3w12</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s3w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s3w20">
<a>
<lex.rf>a#a-mf930709-018-p2s3w20</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s3w16</LM>
<LM>a#a-mf930709-018-p2s3w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vrátit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>deagent</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<val_frame.rf>v#v41npzA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s3w19">
<a>
<lex.rf>a#a-mf930709-018-p2s3w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nyní</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>teď</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf930709-018-p2s3a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-mf930709-018-p2s3w18">
<a>
<lex.rf>a#a-mf930709-018-p2s3w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s3w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s3w21">
<a>
<lex.rf>a#a-mf930709-018-p2s3w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>většina</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-mf930709-018-p2s3w22">
<a>
<lex.rf>a#a-mf930709-018-p2s3w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budova</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf930709-018-p2s3w24">
<a>
<lex.rf>a#a-mf930709-018-p2s3w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komplex</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-mf930709-018-p2s3w23">
<a>
<lex.rf>a#a-mf930709-018-p2s3w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s3w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s5">
<atree.rf>a#a-mf930709-018-p2s5</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l16B">
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s5w7</LM>
<LM>t-mf930709-018-p2s5w9</LM>
<LM>t-mf930709-018-p2s5w10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s5w6">
<a>
<lex.rf>a#a-mf930709-018-p2s5w6</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s5w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyjmout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>res1</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-018-p2s3w14</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>restr</discourse_type>
<sense_PDTB3>Expansion.Exception.Arg2-as-excpt</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf930709-018-p2s5w4</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41oegB</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s5w4">
<a>
<lex.rf>a#a-mf930709-018-p2s5w4</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>však</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-018-p2s5a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-018-p2s5w2">
<a>
<lex.rf>a#a-mf930709-018-p2s5w2</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s5w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>restituce</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-018-p2s5w5">
<a>
<lex.rf>a#a-mf930709-018-p2s5w5</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>například</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf930709-018-p2s5w7">
<a>
<lex.rf>a#a-mf930709-018-p2s5w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>léčebna</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s3w24</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-018-p2s5w10">
<a>
<lex.rf>a#a-mf930709-018-p2s5w10</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s5w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocný</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf930709-018-p2s5w9">
<a>
<lex.rf>a#a-mf930709-018-p2s5w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dlouhodobě</t_lemma>
<functor>THL</functor>
<proto_lemma>dlouhodobý</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s5w18">
<a>
<lex.rf>a#a-mf930709-018-p2s5w18</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s5w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přistavět</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<val_frame.rf>v#v41izbA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s5w12">
<a>
<lex.rf>a#a-mf930709-018-p2s5w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_gram.rf>
<LM>t-mf930709-018-p2s5w7</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-018-p2s5a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-mf930709-018-p2s5w16">
<a>
<lex.rf>a#a-mf930709-018-p2s5w16</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s5w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budova</t_lemma>
<functor>DIR3</functor>
<subfunctor>to</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s3w22</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-018-p2s5w15">
<a>
<lex.rf>a#a-mf930709-018-p2s5w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>starý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf930709-018-p2s5w17">
<a>
<lex.rf>a#a-mf930709-018-p2s5w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s3w23</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s5w21">
<a>
<lex.rf>a#a-mf930709-018-p2s5w21</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s5w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-mf930709-018-p2s5w20">
<a>
<lex.rf>a#a-mf930709-018-p2s5w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osmdesátý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>osmdesát</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s6">
<atree.rf>a#a-mf930709-018-p2s6</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l17B">
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s6w1</LM>
<LM>t-mf930709-018-p2s6w2</LM>
<LM>t-mf930709-018-p2s6w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s6w8">
<a>
<lex.rf>a#a-mf930709-018-p2s6w8</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s6w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>financovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41aqmA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s6w4">
<a>
<lex.rf>a#a-mf930709-018-p2s6w4</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-018-p2s6w1">
<a>
<lex.rf>a#a-mf930709-018-p2s6w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>léčebna</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s5w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-018-p2s6w3">
<a>
<lex.rf>a#a-mf930709-018-p2s6w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocný</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf930709-018-p2s6w2">
<a>
<lex.rf>a#a-mf930709-018-p2s6w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dlouhodobě</t_lemma>
<functor>THL</functor>
<proto_lemma>dlouhodobý</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s6w5">
<a>
<lex.rf>a#a-mf930709-018-p2s6w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zbytek</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s6w1</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-018-p2s6w6">
<a>
<lex.rf>a#a-mf930709-018-p2s6w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>areál</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s3w24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s6a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-018-p2s6w11">
<a>
<lex.rf>a#a-mf930709-018-p2s6w11</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s6w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdroj</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-018-p2s6w10">
<a>
<lex.rf>a#a-mf930709-018-p2s6w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>různý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s7">
<atree.rf>a#a-mf930709-018-p2s7</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l23B">
<basic-form>zdravotní pojišťovna</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s7w9</LM>
<LM>t-mf930709-018-p2s7w10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s7w5">
<a>
<lex.rf>a#a-mf930709-018-p2s7w5</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-018-p2s7w3">
<a>
<lex.rf>a#a-mf930709-018-p2s7w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hradit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41ayjA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s7w1">
<a>
<lex.rf>a#a-mf930709-018-p2s7w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provoz</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-018-p2s7w2">
<a>
<lex.rf>a#a-mf930709-018-p2s7w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>léčebna</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s6w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s7w4">
<a>
<lex.rf>a#a-mf930709-018-p2s7w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s1Aw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s7w8">
<a>
<lex.rf>a#a-mf930709-018-p2s7w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s7w6">
<a>
<lex.rf>a#a-mf930709-018-p2s7w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>partner</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf930709-018-p2s7w7">
<a>
<lex.rf>a#a-mf930709-018-p2s7w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s5w17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s7w10">
<a>
<lex.rf>a#a-mf930709-018-p2s7w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pojišťovna</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-018-p2s7w9">
<a>
<lex.rf>a#a-mf930709-018-p2s7w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdravotní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s8">
<atree.rf>a#a-mf930709-018-p2s8</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l18B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s8w10</LM>
<LM>t-mf930709-018-p2s8w11</LM>
<LM>t-mf930709-018-p2s8w13</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-018-l19B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s8w16</LM>
<LM>t-mf930709-018-p2s8w17</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s8w8">
<a>
<lex.rf>a#a-mf930709-018-p2s8w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přispívat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41iywA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s8w2">
<a>
<lex.rf>a#a-mf930709-018-p2s8w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zařízení</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s7w7</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>t-mf930709-018-p2s7w2</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<val_frame.rf>v#v41qjoC</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s8w1">
<a>
<lex.rf>a#a-mf930709-018-p2s8w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oba</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-018-p2s8w5">
<a>
<lex.rf>a#a-mf930709-018-p2s8w5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s8w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapacita</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-018-p2s8w4">
<a>
<lex.rf>a#a-mf930709-018-p2s8w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celkový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf930709-018-p2s8w7">
<a>
<lex.rf>a#a-mf930709-018-p2s8w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lůžko</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-018-p2s8w6">
<a>
<lex.rf>a#a-mf930709-018-p2s8w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>490</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s8a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-018-p2s8w10">
<a>
<lex.rf>a#a-mf930709-018-p2s8w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Nadace</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-018-p2s8w9">
<a>
<lex.rf>a#a-mf930709-018-p2s8w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>církevní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-mf930709-018-p2s8w13">
<a>
<lex.rf>a#a-mf930709-018-p2s8w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Dobrovský</t_lemma>
<functor>APP</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-mf930709-018-p2s8w11">
<a>
<lex.rf>a#a-mf930709-018-p2s8w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>J</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s8w15">
<a>
<lex.rf>a#a-mf930709-018-p2s8w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podporovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-mf930709-018-p2s8w20">
<a>
<lex.rf>a#a-mf930709-018-p2s8w20</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>16</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s3w18</target_node.rf>
<type>REST</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-018-p2s8w17">
<a>
<lex.rf>a#a-mf930709-018-p2s8w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bratr</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-mf930709-018-p2s8w19">
<a>
<lex.rf>a#a-mf930709-018-p2s8w19</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s8w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Rakousko</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s8a1">
<a>
<lex.rf>a#a-mf930709-018-p2s8w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>bratr</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<children>
<LM id="t-mf930709-018-p2s8w21">
<a>
<lex.rf>a#a-mf930709-018-p2s8w21</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s8w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bavorsko</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s8w16">
<a>
<lex.rf>a#a-mf930709-018-p2s8w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milosrdný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s9">
<atree.rf>a#a-mf930709-018-p2s9</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l22B">
<type>number</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s9w7</LM>
<LM>t-mf930709-018-p2s9w8</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-018-l24B">
<basic-form>lékařský přístroj</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s9w11</LM>
<LM>t-mf930709-018-p2s9w12</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s9w6">
<a>
<lex.rf>a#a-mf930709-018-p2s9w6</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s9w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>investovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41bheA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s9w2">
<a>
<lex.rf>a#a-mf930709-018-p2s9w2</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s9w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konto</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf930709-018-p2s9w3">
<a>
<lex.rf>a#a-mf930709-018-p2s9w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nadace</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s8w10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s9a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-018-p2s9w5">
<a>
<lex.rf>a#a-mf930709-018-p2s9w5</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>už</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf930709-018-p2s9w8">
<a>
<lex.rf>a#a-mf930709-018-p2s9w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf930709-018-p2s9w7">
<a>
<lex.rf>a#a-mf930709-018-p2s9w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s9w10">
<a>
<lex.rf>a#a-mf930709-018-p2s9w10</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s9w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koupě</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf930709-018-p2s9w12">
<a>
<lex.rf>a#a-mf930709-018-p2s9w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přístroj</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-018-p2s9w11">
<a>
<lex.rf>a#a-mf930709-018-p2s9w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lékařský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s10">
<atree.rf>a#a-mf930709-018-p2s10</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l7B">
<basic-form>Stanislav Fiala</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s10w5</LM>
<LM>t-mf930709-018-p2s10w6</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-018-l20B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s10w3</LM>
<LM>t-mf930709-018-p2s10w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s10w12">
<a>
<lex.rf>a#a-mf930709-018-p2s10w12</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s10w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sloužit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41ktqD</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s10w6">
<a>
<lex.rf>a#a-mf930709-018-p2s10w6</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s10w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Fiala</t_lemma>
<functor>CRIT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-018-p2s10w5">
<a>
<lex.rf>a#a-mf930709-018-p2s10w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Stanislav</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-018-p2s10w2">
<a>
<lex.rf>a#a-mf930709-018-p2s10w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provinciál</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-018-p2s10w4">
<a>
<lex.rf>a#a-mf930709-018-p2s10w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bratr</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s3w18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-018-p2s10w3">
<a>
<lex.rf>a#a-mf930709-018-p2s10w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milosrdný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s10w8">
<a>
<lex.rf>a#a-mf930709-018-p2s10w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s7w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-018-p2s10w9">
<a>
<lex.rf>a#a-mf930709-018-p2s10w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spravovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf930709-018-p2s10w10">
<a>
<lex.rf>a#a-mf930709-018-p2s10w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řád</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s10w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s10w11">
<a>
<lex.rf>a#a-mf930709-018-p2s10w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nadále</t_lemma>
<functor>THL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-mf930709-018-p2s10w13">
<a>
<lex.rf>a#a-mf930709-018-p2s10w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s7w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s11">
<atree.rf>a#a-mf930709-018-p2s11</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l26B">
<basic-form>ošetřovatelská péče</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s11w13</LM>
<LM>t-mf930709-018-p2s11w14</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-018-l1A">
<basic-form>v duchu</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s11w6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s11w20">
<a>
<lex.rf>a#a-mf930709-018-p2s11w20</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>však</t_lemma>
<functor>ADVS</functor>
<deepord>15</deepord>
<children>
<LM id="t-mf930709-018-p2s11w1">
<a>
<lex.rf>a#a-mf930709-018-p2s11w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bratr</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s10w10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s11w12">
<a>
<lex.rf>a#a-mf930709-018-p2s11w12</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s11w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zlepšit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>vol</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41rihA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s11w6">
<a>
<lex.rf>a#a-mf930709-018-p2s11w6</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s11w4</LM>
<LM>a#a-mf930709-018-p2s11w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úroveň</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf930709-018-p2s11w5">
<a>
<lex.rf>a#a-mf930709-018-p2s11w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tradiční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-018-p2s11w8">
<a>
<lex.rf>a#a-mf930709-018-p2s11w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zařízení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s10w8</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<val_frame.rf>v#v41qjoC</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s11w7">
<a>
<lex.rf>a#a-mf930709-018-p2s11w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_gram.rf>
<LM>t-mf930709-018-p2s11w1</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s11w10">
<a>
<lex.rf>a#a-mf930709-018-p2s11w10</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s11w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>převzetí</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41intA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s11w11">
<a>
<lex.rf>a#a-mf930709-018-p2s11w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s10w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s11a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s11w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s11w15">
<a>
<lex.rf>a#a-mf930709-018-p2s11w15</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-mf930709-018-p2s11w14">
<a>
<lex.rf>a#a-mf930709-018-p2s11w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>péče</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-018-p2s11w13">
<a>
<lex.rf>a#a-mf930709-018-p2s11w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ošetřovatelský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s11w16">
<a>
<lex.rf>a#a-mf930709-018-p2s11w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odbornost</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-mf930709-018-p2s11w17">
<a>
<lex.rf>a#a-mf930709-018-p2s11w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>personál</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s11w11</target_node.rf>
<type>REST</type>
</LM>
<LM>
<target_node.rf>t-mf930709-018-p2s2Bw12</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s11w19">
<a>
<lex.rf>a#a-mf930709-018-p2s11w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mínit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-018-p2s11w12</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf930709-018-p2s11w20</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41cgvF</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s11a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-mf930709-018-p2s11w24">
<a>
<lex.rf>a#a-mf930709-018-p2s11w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>propouštět</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<val_frame.rf>v#v41hkyA</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s11w22">
<a>
<lex.rf>a#a-mf930709-018-p2s11w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaměstnanec</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s2Bw12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-018-p2s11w23">
<a>
<lex.rf>a#a-mf930709-018-p2s11w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s11w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s11w21">
<a>
<lex.rf>a#a-mf930709-018-p2s11w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>současný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s11a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>21</deepord>
<coref_gram.rf>
<LM>t-mf930709-018-p2s11w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-018-p2s11a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR1</functor>
<tfa>t</tfa>
<deepord>22</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s11w23</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-018-p2s13">
<atree.rf>a#a-mf930709-018-p2s13</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-018-l9B">
<type>location</type>
<tnode.rfs>
<LM>t-mf930709-018-p2s13w14</LM>
<LM>t-mf930709-018-p2s13w15</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-018-p2s13w3">
<a>
<lex.rf>a#a-mf930709-018-p2s13w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čekat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41mtC</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s13w1">
<a>
<lex.rf>a#a-mf930709-018-p2s13w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řád</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s11a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s13w2">
<a>
<lex.rf>a#a-mf930709-018-p2s13w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosud</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-018-p2s13w5">
<a>
<lex.rf>a#a-mf930709-018-p2s13w5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s13w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>restituce</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-018-p2s13w8">
<a>
<lex.rf>a#a-mf930709-018-p2s13w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s11w8</target_node.rf>
<type>SET_SUB</type>
</LM>
<LM>
<target_node.rf>t-mf930709-018-p2s11w23</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-018-p2s13w7">
<a>
<lex.rf>a#a-mf930709-018-p2s13w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sedm</t_lemma>
<functor>RSTR</functor>
<proto_lemma>sedm</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930709-018-p2s13w6">
<a>
<lex.rf>a#a-mf930709-018-p2s13w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-018-p2s13w11">
<a>
<lex.rf>a#a-mf930709-018-p2s13w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>RSTR</functor>
<proto_lemma>mít</proto_lemma>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41chlJ</val_frame.rf>
<children>
<LM id="t-mf930709-018-p2s13w10">
<a>
<lex.rf>a#a-mf930709-018-p2s13w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_gram.rf>
<LM>t-mf930709-018-p2s13w8</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-018-p2s13a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-018-p2s13w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-018-p2s13w13">
<a>
<lex.rf>a#a-mf930709-018-p2s13w13</lex.rf>
<aux.rf>
<LM>a#a-mf930709-018-p2s13w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>území</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-mf930709-018-p2s13w15">
<a>
<lex.rf>a#a-mf930709-018-p2s13w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>republika</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-018-p2s10w13</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-018-p2s13w14">
<a>
<lex.rf>a#a-mf930709-018-p2s13w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
