<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tanot_coref_schema.xml" />
<references>
<reffile id="a" name="adata" href="pdtsc_083_2.10.a" />
<reffile id="v" name="vallex" href="vallex3.xml" />
</references>
</head>
<trees>
<LM id="ep_114.10-SCzechT-ep_114-d1e2783-x3-root">
<atree.rf>a#ep_114.10-SCzechA-ep_114-d1e2783-x3-root</atree.rf>
<deepord>0</deepord>
<children id="ep_114.10-SCzechT-m-d1t2790-7">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2790-7</lex.rf>
<aux.rf>a#ep_114.10-SCzechA-m-d1t2790-3</aux.rf>
</a>
<val_frame.rf>v#v-w4157f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>povídat_si</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<negation>neg0</negation>
</gram>
<deepord>5</deepord>
<children>
<LM id="ep_114.10-SCzechT-m-d1t2790-2">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2790-2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hezky</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adv.denot.grad.neg</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children id="ep_114.10-SCzechT-m-d1t2790-1">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2790-1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>moc</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>pos</degcmp>
<numertype>basic</numertype>
</gram>
<deepord>1</deepord>
</children>
</LM>
<LM id="ep_114.10-SCzechT-m-d1t2790-4">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2790-4</lex.rf>
</a>
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<deepord>3</deepord>
</LM>
<LM id="ep_114.10-SCzechT-m-d1t2790-6">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2790-6</lex.rf>
<aux.rf>a#ep_114.10-SCzechA-m-d1t2790-5</aux.rf>
</a>
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>2</person>
<politeness>basic</politeness>
</gram>
<deepord>4</deepord>
</LM>
</children>
</children>
</LM>
<LM id="ep_114.10-SCzechT-ep_114-d1e2792-x2-root">
<atree.rf>a#ep_114.10-SCzechA-ep_114-d1e2792-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ep_114.10-SCzechT-m-d1t2795-3">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2795-3</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="ep_114.10-SCzechT-ep_114-d1e2792-x2-roota1">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2790-7</lex.rf>
<aux.rf>a#ep_114.10-SCzechA-m-d1t2790-3</aux.rf>
</a>
<val_frame.rf>v#v-w4157f1</val_frame.rf>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>povídat_si</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="ep_114.10-SCzechT-ep_114-d1e2792-x2-roota2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<target-node.rf>ep_114.10-SCzechT-m-d1t2790-4</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ep_114.10-SCzechT-m-d1t2795-1">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2795-1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<deepord>3</deepord>
<coref_text>
<target-node.rf>ep_114.10-SCzechT-m-d1t2790-6</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ep_114.10-SCzechT-m-d1t2795-2">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2795-2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>taky</t_lemma>
<functor>RHEM</functor>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="ep_114.10-SCzechT-m-d1t2795-4">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2795-4</lex.rf>
</a>
<val_frame.rf>v#v-w406f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>děkovat</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<negation>neg0</negation>
</gram>
<deepord>7</deepord>
<children>
<LM id="ep_114.10-SCzechT-m-d1t2795-4x3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<target-node.rf>ep_114.10-SCzechT-m-d1t2795-1</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ep_114.10-SCzechT-ep_114-d1e2792-x2-roota3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>8</deepord>
<coref_text>
<target-node.rf>ep_114.10-SCzechT-ep_114-d1e2792-x2-roota2</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
</children>
</LM>
</children>
</children>
</LM>
<LM id="ep_114.10-SCzechT-ep_114-d1e2796-x2-root">
<atree.rf>a#ep_114.10-SCzechA-ep_114-d1e2796-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ep_114.10-SCzechT-ep_114-d1e2796-x2-roota1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<deepord>1</deepord>
<children id="ep_114.10-SCzechT-m-d1t2799-1">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2799-1</lex.rf>
<aux.rf>a#ep_114.10-SCzechA-m-d1e2796-x2-1716</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>shledaná</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
</children>
</children>
</LM>
<LM id="ep_114.10-SCzechT-ep_114-d1e2800-x2-root">
<atree.rf>a#ep_114.10-SCzechA-ep_114-d1e2800-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ep_114.10-SCzechT-ep_114-d1e2800-x2-roota1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<deepord>1</deepord>
<children id="ep_114.10-SCzechT-m-d1t2803-1">
<a>
<lex.rf>a#ep_114.10-SCzechA-m-d1t2803-1</lex.rf>
<aux.rf>a#ep_114.10-SCzechA-m-d1e2800-x2-1717</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>shledaná</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
</children>
</children>
</LM>
</trees>
</tdata>
