<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tanot_coref_schema.xml" />
<references>
<reffile id="a" name="adata" href="pdtsc_082_2.14.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.0.xml" />
</references>
</head>
<trees>
<LM id="ps_033.14-SCzechT-ps_033-d1e4476-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4476-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-ps_033-d1e4476-x2-roota1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<deepord>1</deepord>
<children id="ps_033.14-SCzechT-m-d1t4481-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4481-1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dobře</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adv.denot.grad.neg</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-9-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-9-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1t4483-8">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4483-8</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ale</t_lemma>
<functor>ADVS</functor>
<deepord>7</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4483-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4483-1</lex.rf>
</a>
<val_frame.rf>v#v-w3088f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>omlouvat</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>sg</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>1</person>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4483-1x3">
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-9-roota1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4483-2</lex.rf>
</a>
<coref_gram.rf>ps_033.14-SCzechT-m-d1t4483-1x3</coref_gram.rf>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4483-6">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4483-6</lex.rf>
<aux.rf>a#ps_033.14-SCzechA-m-d1t4483-4</aux.rf>
</a>
<val_frame.rf>v#v-w10819f3_ZU</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>přerušovat</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>v</sempos>
<number>sg</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>1</person>
<negation>neg0</negation>
</gram>
<deepord>6</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4483-5">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4483-5</lex.rf>
</a>
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>2</person>
<politeness>basic</politeness>
</gram>
<deepord>4</deepord>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4483-6x3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>5</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-ps_033-9-roota1</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4483-11">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4483-11</lex.rf>
<aux.rf>a#ps_033.14-SCzechA-m-d1t4483-10</aux.rf>
</a>
<val_frame.rf>v#v-w1480f2</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>končit</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>pl</number>
<verbmod>ind</verbmod>
<deontmod>deb</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>1</person>
<negation>neg0</negation>
</gram>
<deepord>10</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4483-9">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4483-9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>už</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
<negation>neg0</negation>
</gram>
<deepord>8</deepord>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4483-11x3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>9</deepord>
<bridging>
<LM>
<target-node.rf>ps_033.14-SCzechT-m-d1t4483-6x3</target-node.rf>
<informal-type>SUB_SET</informal-type>
<src>coref</src>
</LM>
<LM>
<target-node.rf>ps_033.14-SCzechT-m-d1t4483-5</target-node.rf>
<informal-type>SUB_SET</informal-type>
<src>coref</src>
</LM>
</bridging>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-9-roota2">
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-890-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-890-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1t4485-3">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4485-3</lex.rf>
</a>
<val_frame.rf>v#v-w243f80_ZU</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>sg</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>3</person>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4485-2">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4485-2</lex.rf>
</a>
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<t_lemma>tenhle</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<deepord>1</deepord>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4485-5">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4485-5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fotka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>4</deepord>
<children id="ps_033.14-SCzechT-m-d1t4485-4">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4485-4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<deepord>3</deepord>
</children>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4486-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4486-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-ps_033-d1e4486-x2-roota1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d-id215066-punct</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="ps_033.14-SCzechT-ps_033-d1e4486-x2-roota2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<deepord>2</deepord>
<children id="ps_033.14-SCzechT-m-d1t4489-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4489-1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dobře</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adv.denot.grad.neg</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<deepord>1</deepord>
</children>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4489-4">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4489-4</lex.rf>
</a>
<val_frame.rf>v#v-w5804f3</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>rozumět</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>1</person>
<negation>neg0</negation>
</gram>
<deepord>5</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4489-4x3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4483-5</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4486-x2-roota4">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4483-11</target-node.rf>
<informal-type>SPEC</informal-type>
<src>lenk</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4486-x2-roota3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4483-6x3</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
</children>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-3-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-3-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1t4491-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4491-1</lex.rf>
<aux.rf>a#ps_033.14-SCzechA-m-d1t4491-2</aux.rf>
</a>
<val_frame.rf>v#v-w1856f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>mít_se</t_lemma>
<functor>PRED</functor>
<sentmod>imper</sentmod>
<gram>
<sempos>v</sempos>
<number>pl</number>
<verbmod>imp</verbmod>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>nil</dispmod>
<iterativeness>it0</iterativeness>
<person>2</person>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children>
<LM id="ps_033.14-SCzechT-ps_033-3-roota1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-ps_033-d1e4486-x2-roota3</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4491-3">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4491-3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hezky</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adv.denot.grad.neg</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<deepord>3</deepord>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4492-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4492-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1t4495-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4495-1</lex.rf>
</a>
<val_frame.rf>v#v-w406f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>děkovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>pl</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>1</person>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4495-1x3">
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4495-2">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4495-2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>2</person>
<politeness>basic</politeness>
</gram>
<deepord>3</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4489-4x3</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4495-5">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4495-5</lex.rf>
<aux.rf>a#ps_033.14-SCzechA-m-d1t4495-3</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čas</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>5</deepord>
<children id="ps_033.14-SCzechT-m-d1t4495-4">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4495-4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>2</person>
<politeness>basic</politeness>
</gram>
<deepord>4</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4495-2</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</children>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4496-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4496-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1t4499-3">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4499-3</lex.rf>
</a>
<val_frame.rf>v#v-w406f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>děkovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>sg</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>1</person>
<negation>neg0</negation>
</gram>
<deepord>3</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4499-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4499-1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<deepord>1</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4495-4</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4499-2">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4499-2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>taky</t_lemma>
<functor>RHEM</functor>
<deepord>2</deepord>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4496-x2-roota1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4495-1x3</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4500-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4500-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1t4503-7">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4503-7</lex.rf>
<aux.rf>a#ps_033.14-SCzechA-m-d1t4503-3</aux.rf>
</a>
<val_frame.rf>v#v-w4157f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>povídat_si</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>sg</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>3</person>
<negation>neg0</negation>
</gram>
<deepord>5</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4503-2">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4503-2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hezky</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adv.denot.grad.neg</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children id="ps_033.14-SCzechT-m-d1t4503-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4503-1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>moc</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>pos</degcmp>
<numertype>basic</numertype>
</gram>
<deepord>1</deepord>
</children>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4503-4">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4503-4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<deepord>3</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-ps_033-3-roota1</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4503-6">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4503-6</lex.rf>
<aux.rf>a#ps_033.14-SCzechA-m-d1t4503-5</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>2</person>
<politeness>basic</politeness>
</gram>
<deepord>4</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4499-1</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4504-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4504-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1t4507-3">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4507-3</lex.rf>
</a>
<val_frame.rf>v#v-w406f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>děkovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>sg</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>1</person>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4507-3x3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4503-6</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4507-2">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4507-2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>2</person>
<politeness>basic</politeness>
</gram>
<deepord>3</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4503-4</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4509-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4509-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1e4509-x2-0">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1e4509-x2-0</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4512-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4512-1</lex.rf>
</a>
<val_frame.rf>v#v-w3536f2_ZU</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>počkat</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<sentmod>imper</sentmod>
<gram>
<sempos>v</sempos>
<number>pl</number>
<verbmod>imp</verbmod>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<resultative>res0</resultative>
<dispmod>nil</dispmod>
<iterativeness>it0</iterativeness>
<person>2</person>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children>
<LM id="ps_033.14-SCzechT-ps_033-d1e4509-x2-roota1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4507-3x3</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4509-x2-roota2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-m-d1t4512-5</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4512-2">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4512-2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chvilka</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4512-5">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4512-5</lex.rf>
</a>
<val_frame.rf>v#v-w5158f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>přijít</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>pl</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>3</person>
<negation>neg0</negation>
</gram>
<deepord>8</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4512-3">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4512-3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kluk</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<negation>neg0</negation>
</gram>
<deepord>6</deepord>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4509-x2-roota3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR3</functor>
<deepord>9</deepord>
</LM>
<LM id="ps_033.14-SCzechT-m-d1t4512-6">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4512-6</lex.rf>
</a>
<val_frame.rf>v#v-w8426f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>vysvobodit</t_lemma>
<functor>INTT</functor>
<gram>
<sempos>v</sempos>
<verbmod>nil</verbmod>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<resultative>res0</resultative>
<dispmod>nil</dispmod>
<iterativeness>it0</iterativeness>
<negation>neg0</negation>
</gram>
<deepord>10</deepord>
<children>
<LM id="ps_033.14-SCzechT-m-d1t4512-4">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4512-4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>2</person>
<politeness>basic</politeness>
</gram>
<deepord>7</deepord>
<coref_text>
<target-node.rf>ps_033.14-SCzechT-ps_033-d1e4509-x2-roota1</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4509-x2-roota4">
<coref_gram.rf>ps_033.14-SCzechT-m-d1t4512-3</coref_gram.rf>
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4513-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4513-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-m-d1t4516-1">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4516-1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>ano</t_lemma>
<functor>PARTL</functor>
<sentmod>enunc</sentmod>
<deepord>1</deepord>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4517-x2-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4517-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-ps_033-d1e4517-x2-roota1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<deepord>1</deepord>
<children id="ps_033.14-SCzechT-m-d1t4522-2">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4522-2</lex.rf>
<aux.rf>a#ps_033.14-SCzechA-m-d1t4522-1</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>shledaná</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
</children>
</children>
</LM>
<LM id="ps_033.14-SCzechT-ps_033-d1e4517-x3-root">
<atree.rf>a#ps_033.14-SCzechA-ps_033-d1e4517-x3-root</atree.rf>
<deepord>0</deepord>
<children id="ps_033.14-SCzechT-ps_033-d1e4517-x3-roota1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<deepord>1</deepord>
<children id="ps_033.14-SCzechT-m-d1t4524-2">
<a>
<lex.rf>a#ps_033.14-SCzechA-m-d1t4524-2</lex.rf>
<aux.rf>a#ps_033.14-SCzechA-m-d1t4524-1</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>shledaná</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
</children>
</children>
</LM>
</trees>
</tdata>
