<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tanot_coref_schema.xml" />
<references>
<reffile id="a" name="adata" href="pdtsc_089_2.14.a" />
<reffile id="v" name="vallex" href="vallex3.xml" />
</references>
</head>
<trees>
<LM id="ak_042.14-SCzechT-ak_042-d1e3434-x2-root">
<atree.rf>a#ak_042.14-SCzechA-ak_042-d1e3434-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ak_042.14-SCzechT-m-d1t3437-1">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3437-1</lex.rf>
</a>
<val_frame.rf>v#v-w406f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>děkovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>sg</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>1</person>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
<children>
<LM id="ak_042.14-SCzechT-m-d1t3437-1x3">
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="ak_042.14-SCzechT-ak_042-d1e3434-x2-roota1">
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</children>
</LM>
<LM id="ak_042.14-SCzechT-ak_042-d1e3438-x2-root">
<atree.rf>a#ak_042.14-SCzechA-ak_042-d1e3438-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ak_042.14-SCzechT-m-d-id165682-punct">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d-id165682-punct</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="ak_042.14-SCzechT-m-d1t3441-1">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3441-1</lex.rf>
</a>
<val_frame.rf>v#v-w3536f2_ZU</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>počkat</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<sentmod>imper</sentmod>
<gram>
<sempos>v</sempos>
<number>pl</number>
<verbmod>imp</verbmod>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<resultative>res0</resultative>
<dispmod>nil</dispmod>
<iterativeness>it0</iterativeness>
<person>2</person>
<negation>neg0</negation>
</gram>
<deepord>1</deepord>
<children>
<LM id="ak_042.14-SCzechT-ak_042-d1e3438-x2-roota2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<target-node.rf>ak_042.14-SCzechT-m-d1t3441-6</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ak_042.14-SCzechT-ak_042-d1e3438-x2-roota1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<target-node.rf>ak_042.14-SCzechT-m-d1t3437-1x3</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
<LM id="ak_042.14-SCzechT-m-d1t3441-2">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3441-2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chvilka</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="ak_042.14-SCzechT-m-d1t3441-6">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3441-6</lex.rf>
</a>
<val_frame.rf>v#v-w5158f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>přijít</t_lemma>
<functor>PRED</functor>
<is_member>1</is_member>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<number>pl</number>
<verbmod>ind</verbmod>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<resultative>res0</resultative>
<dispmod>disp0</dispmod>
<iterativeness>it0</iterativeness>
<person>3</person>
<negation>neg0</negation>
</gram>
<deepord>7</deepord>
<children>
<LM id="ak_042.14-SCzechT-m-d1t3441-4">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3441-4</lex.rf>
</a>
<coref_special>exoph</coref_special>
<nodetype>complex</nodetype>
<t_lemma>kluk</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<negation>neg0</negation>
</gram>
<deepord>6</deepord>
</LM>
<LM id="ak_042.14-SCzechT-ak_042-d1e3438-x2-roota3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR3</functor>
<deepord>8</deepord>
</LM>
<LM id="ak_042.14-SCzechT-m-d1t3441-7">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3441-7</lex.rf>
</a>
<val_frame.rf>v#v-w8426f1</val_frame.rf>
<nodetype>complex</nodetype>
<t_lemma>vysvobodit</t_lemma>
<functor>INTT</functor>
<gram>
<sempos>v</sempos>
<verbmod>nil</verbmod>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<resultative>res0</resultative>
<dispmod>nil</dispmod>
<iterativeness>it0</iterativeness>
<negation>neg0</negation>
</gram>
<deepord>10</deepord>
<children>
<LM id="ak_042.14-SCzechT-ak_042-d1e3438-x2-roota4">
<coref_gram.rf>ak_042.14-SCzechT-m-d1t3441-4</coref_gram.rf>
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>9</deepord>
</LM>
<LM id="ak_042.14-SCzechT-m-d1t3441-5">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3441-5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>2</person>
<politeness>basic</politeness>
</gram>
<deepord>11</deepord>
<coref_text>
<target-node.rf>ak_042.14-SCzechT-ak_042-d1e3438-x2-roota1</target-node.rf>
<informal-type>SPEC</informal-type>
<src>coref</src>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</children>
</LM>
<LM id="ak_042.14-SCzechT-ak_042-d1e3442-x2-root">
<atree.rf>a#ak_042.14-SCzechA-ak_042-d1e3442-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ak_042.14-SCzechT-m-d1t3445-1">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3445-1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>ano</t_lemma>
<functor>PARTL</functor>
<sentmod>enunc</sentmod>
<deepord>1</deepord>
</children>
</LM>
<LM id="ak_042.14-SCzechT-ak_042-d1e3446-x2-root">
<atree.rf>a#ak_042.14-SCzechA-ak_042-d1e3446-x2-root</atree.rf>
<deepord>0</deepord>
<children id="ak_042.14-SCzechT-ak_042-d1e3446-x2-roota1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<deepord>1</deepord>
<children id="ak_042.14-SCzechT-m-d1t3451-1">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3451-1</lex.rf>
<aux.rf>a#ak_042.14-SCzechA-m-d1e3446-x2-300</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>shledaná</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
</children>
</children>
</LM>
<LM id="ak_042.14-SCzechT-ak_042-d1e3446-x3-root">
<atree.rf>a#ak_042.14-SCzechA-ak_042-d1e3446-x3-root</atree.rf>
<deepord>0</deepord>
<children id="ak_042.14-SCzechT-ak_042-d1e3446-x3-roota1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<deepord>1</deepord>
<children id="ak_042.14-SCzechT-m-d1t3453-1">
<a>
<lex.rf>a#ak_042.14-SCzechA-m-d1t3453-1</lex.rf>
<aux.rf>a#ak_042.14-SCzechA-m-d1e3446-x3-301</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>shledaná</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<negation>neg0</negation>
</gram>
<deepord>2</deepord>
</children>
</children>
</LM>
</trees>
</tdata>
