<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94200_73.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln94200-73-p1s1">
<atree.rf>a#a-ln94200-73-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94200-73-p1s1w1">
<a>
<lex.rf>a#a-ln94200-73-p1s1w1</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p1s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dočkat_se</t_lemma>
<functor>PRED</functor>
<sentmod>inter</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41wqB</val_frame.rf>
<children>
<LM id="t-ln94200-73-p1s1w3">
<a>
<lex.rf>a#a-ln94200-73-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>gen</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94200-73-p1s1w4">
<a>
<lex.rf>a#a-ln94200-73-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pokračování</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41gbjB</val_frame.rf>
<children>
<LM id="t-ln94200-73-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s1A">
<atree.rf>a#a-ln94200-73-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94200-73-p2s1Aw1">
<a>
<lex.rf>a#a-ln94200-73-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94200-73-p2s1Aw3">
<a>
<lex.rf>a#a-ln94200-73-p2s1Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jaf</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>nr</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s1B">
<atree.rf>a#a-ln94200-73-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94200-73-l3A">
<type>object</type>
<tnode.rfs>
<LM>t-ln94200-73-p2s1Bw12</LM>
<LM>t-ln94200-73-p2s1Bw13</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94200-73-l4A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94200-73-p2s1Bw21</LM>
<LM>t-ln94200-73-p2s1Bw22</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94200-73-p2s1Bw16">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw16</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s1Bw15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cítit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41lcA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s1Bw2">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94200-73-p2s1Bw1">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>závislý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94200-73-p2s1Bw3">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Febio</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94200-73-p2s1Bw5">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>populární</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94200-73-p2s1Bw7">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cyklus</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p1s1w3</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln94200-73-p2s1Bw6">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-ln94200-73-p2s1Bw2</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94200-73-p2s1Bw11">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>9</deepord>
<children>
<LM id="t-ln94200-73-p2s1Bw8">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>gen</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94200-73-p2s1Bw10">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oko</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln94200-73-p2s1Bw13">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soda</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94200-73-p2s1Bw12">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s1Aw1</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s1Bw17">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ohrozit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<val_frame.rf>v#v41eqbA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s1Ba1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>13</deepord>
<coref_gram.rf>
<LM>t-ln94200-73-p2s1Bw2</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94200-73-p2s1Bw18">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fakt</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln94200-73-p2s1Bw26">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw26</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s1Bw20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uzavřít</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<val_frame.rf>v#v41nemJ</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s1Bw22">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>televize</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln94200-73-p2s1Bw21">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s1Bw12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s1Bw25">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosud</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
</LM>
<LM id="t-ln94200-73-p2s1Ba2">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
<LM id="t-ln94200-73-p2s1Bw27">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>smlouva</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<val_frame.rf>v#v41kvrB</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s1Ba4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>21</deepord>
<coref_gram.rf>
<LM>t-ln94200-73-p2s1Bw22</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94200-73-p2s1Ba3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>22</deepord>
</LM>
<LM id="t-ln94200-73-p2s1Bw24">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw24</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s1Bw23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>23</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s1Ba1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s1Bw30">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw30</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s1Bw28</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TOWH</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
<children>
<LM id="t-ln94200-73-p2s1Bw29">
<a>
<lex.rf>a#a-ln94200-73-p2s1Bw29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příští</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s2">
<atree.rf>a#a-ln94200-73-p2s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94200-73-p2s2w10">
<a>
<lex.rf>a#a-ln94200-73-p2s2w10</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="t-ln94200-73-p2s2w6">
<a>
<lex.rf>a#a-ln94200-73-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vypršet</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41osgA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s2w1">
<a>
<lex.rf>a#a-ln94200-73-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>platnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94200-73-p2s2w2">
<a>
<lex.rf>a#a-ln94200-73-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>smlouva</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94200-73-p2s2w5">
<a>
<lex.rf>a#a-ln94200-73-p2s2w5</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pořad</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s1Bw7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s2w4">
<a>
<lex.rf>a#a-ln94200-73-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zmíněný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s2w7">
<a>
<lex.rf>a#a-ln94200-73-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>letos</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94200-73-p2s2w9">
<a>
<lex.rf>a#a-ln94200-73-p2s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s2w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prosinec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s2w7</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s2w20">
<a>
<lex.rf>a#a-ln94200-73-p2s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>považovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41gtiA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s2w13">
<a>
<lex.rf>a#a-ln94200-73-p2s2w13</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s2w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>termín</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94200-73-p2s2w16">
<a>
<lex.rf>a#a-ln94200-73-p2s2w16</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s2w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodnutí</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41jqjB</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s2w15">
<a>
<lex.rf>a#a-ln94200-73-p2s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příslušný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94200-73-p2s2w19">
<a>
<lex.rf>a#a-ln94200-73-p2s2w19</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s2w18</LM>
<LM>a#a-ln94200-73-p2s2w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČT</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s1Ba4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s2w12">
<a>
<lex.rf>a#a-ln94200-73-p2s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hraniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s2w21">
<a>
<lex.rf>a#a-ln94200-73-p2s2w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Febio</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s1Bw24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s2w22">
<a>
<lex.rf>a#a-ln94200-73-p2s2w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>polovina</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln94200-73-p2s2w23">
<a>
<lex.rf>a#a-ln94200-73-p2s2w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>září</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s2w7</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s3">
<atree.rf>a#a-ln94200-73-p2s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94200-73-p2s3w20">
<a>
<lex.rf>a#a-ln94200-73-p2s3w20</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s3w18</LM>
<LM>a#a-ln94200-73-p2s3w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>následovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41dboA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s3w2">
<a>
<lex.rf>a#a-ln94200-73-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>seriál</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p1s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s3w3">
<a>
<lex.rf>a#a-ln94200-73-p2s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>gen</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94200-73-p2s3w1">
<a>
<lex.rf>a#a-ln94200-73-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stodílný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94200-73-p2s3w9">
<a>
<lex.rf>a#a-ln94200-73-p2s3w9</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<is_parenthesis>1</is_parenthesis>
<deepord>8</deepord>
<children>
<LM id="t-ln94200-73-p2s3w5">
<a>
<lex.rf>a#a-ln94200-73-p2s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skončit</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41krfH</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s3a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s3w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s3w6">
<a>
<lex.rf>a#a-ln94200-73-p2s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>letos</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s2w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s3w8">
<a>
<lex.rf>a#a-ln94200-73-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s3w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>listopad</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s3w6</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s3w13">
<a>
<lex.rf>a#a-ln94200-73-p2s3w13</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s3w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>plánovat</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>deagent</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41fmmA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s3w11">
<a>
<lex.rf>a#a-ln94200-73-p2s3w11</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s3w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prosinec</t_lemma>
<functor>TOWH</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s2w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<is_parenthesis>1</is_parenthesis>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln94200-73-p2s3w14">
<a>
<lex.rf>a#a-ln94200-73-p2s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>repríza</t_lemma>
<functor>PAT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94200-73-p2s3w16">
<a>
<lex.rf>a#a-ln94200-73-p2s3w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>díl</t_lemma>
<functor>PAT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s3a0</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln94200-73-p2s3w15">
<a>
<lex.rf>a#a-ln94200-73-p2s3w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úspěšný</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.denot</sempos>
<degcmp>sup</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s3w22">
<a>
<lex.rf>a#a-ln94200-73-p2s3w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cyklus</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p1s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s3w23">
<a>
<lex.rf>a#a-ln94200-73-p2s3w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>genus</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-ln94200-73-p2s3w21">
<a>
<lex.rf>a#a-ln94200-73-p2s3w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s4">
<atree.rf>a#a-ln94200-73-p2s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94200-73-p2s4w12">
<a>
<lex.rf>a#a-ln94200-73-p2s4w12</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s4w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>navázat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>vol</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41dfrD</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s4w1">
<a>
<lex.rf>a#a-ln94200-73-p2s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Febio</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s2w21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s4w5">
<a>
<lex.rf>a#a-ln94200-73-p2s4w5</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s4w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>portrét</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s3a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s4w7">
<a>
<lex.rf>a#a-ln94200-73-p2s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>profesionál</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94200-73-p2s4w10">
<a>
<lex.rf>a#a-ln94200-73-p2s4w10</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s4w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obor</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94200-73-p2s4w9">
<a>
<lex.rf>a#a-ln94200-73-p2s4w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>různý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s4w6">
<a>
<lex.rf>a#a-ln94200-73-p2s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vynikající</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s4w3">
<a>
<lex.rf>a#a-ln94200-73-p2s4w3</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s4w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s3w22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s4w13">
<a>
<lex.rf>a#a-ln94200-73-p2s4w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svědectví</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94200-73-p2s4w18">
<a>
<lex.rf>a#a-ln94200-73-p2s4w18</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s4w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osud</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94200-73-p2s4w16">
<a>
<lex.rf>a#a-ln94200-73-p2s4w16</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln94200-73-p2s4w15">
<a>
<lex.rf>a#a-ln94200-73-p2s4w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pozoruhodný</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94200-73-p2s4w17">
<a>
<lex.rf>a#a-ln94200-73-p2s4w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příkladný</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s4w21">
<a>
<lex.rf>a#a-ln94200-73-p2s4w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potkat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41gqqC</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s4w20">
<a>
<lex.rf>a#a-ln94200-73-p2s4w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_gram.rf>
<LM>t-ln94200-73-p2s4w18</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94200-73-p2s4w23">
<a>
<lex.rf>a#a-ln94200-73-p2s4w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>člověk</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s4w7</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<children>
<LM id="t-ln94200-73-p2s4w22">
<a>
<lex.rf>a#a-ln94200-73-p2s4w22</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-ln94200-73-p2s4w25">
<a>
<lex.rf>a#a-ln94200-73-p2s4w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>známý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln94200-73-p2s4w24">
<a>
<lex.rf>a#a-ln94200-73-p2s4w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zcela</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s5">
<atree.rf>a#a-ln94200-73-p2s5</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94200-73-l2A">
<basic-form>Ivo Mathé</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94200-73-p2s5w5</LM>
<LM>t-ln94200-73-p2s5w6</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94200-73-l5A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94200-73-p2s5w3</LM>
<LM>t-ln94200-73-p2s5w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94200-73-p2s5w7">
<a>
<lex.rf>a#a-ln94200-73-p2s5w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>reagovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41jfoB</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s5w6">
<a>
<lex.rf>a#a-ln94200-73-p2s5w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Mathé</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94200-73-p2s5w5">
<a>
<lex.rf>a#a-ln94200-73-p2s5w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ivo</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94200-73-p2s5w2">
<a>
<lex.rf>a#a-ln94200-73-p2s5w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94200-73-p2s5w4">
<a>
<lex.rf>a#a-ln94200-73-p2s5w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>televize</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s2w19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s5w3">
<a>
<lex.rf>a#a-ln94200-73-p2s5w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s1Bw21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s5w1">
<a>
<lex.rf>a#a-ln94200-73-p2s5w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>generální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s5a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94200-73-p2s5w8">
<a>
<lex.rf>a#a-ln94200-73-p2s5w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ujištění</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41mlaA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s5a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s5w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s5w19">
<a>
<lex.rf>a#a-ln94200-73-p2s5w19</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s5w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trvat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41mdbC</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s5w11">
<a>
<lex.rf>a#a-ln94200-73-p2s5w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zájem</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln94200-73-p2s5w13">
<a>
<lex.rf>a#a-ln94200-73-p2s5w13</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s5w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spolupráce</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94200-73-p2s5w15">
<a>
<lex.rf>a#a-ln94200-73-p2s5w15</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s5w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Febio</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s4w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s5w17">
<a>
<lex.rf>a#a-ln94200-73-p2s5w17</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s5w18</LM>
<LM>a#a-ln94200-73-p2s5w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s5a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s6">
<atree.rf>a#a-ln94200-73-p2s6</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94200-73-l7A">
<basic-form>vysílací schéma</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94200-73-p2s6w6</LM>
<LM>t-ln94200-73-p2s6w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94200-73-p2s6w18">
<a>
<lex.rf>a#a-ln94200-73-p2s6w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>považovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94200-73-p2s5w19</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94200-73-p2s6w11</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41gtiA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s6w4">
<a>
<lex.rf>a#a-ln94200-73-p2s6w4</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s6w2</LM>
<LM>a#a-ln94200-73-p2s6w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednání</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41bhqA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s6w3">
<a>
<lex.rf>a#a-ln94200-73-p2s6w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>probíhající</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94200-73-p2s6a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94200-73-p2s6a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94200-73-p2s6w7">
<a>
<lex.rf>a#a-ln94200-73-p2s6w7</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s6w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>schéma</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94200-73-p2s6w6">
<a>
<lex.rf>a#a-ln94200-73-p2s6w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vysílací</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94200-73-p2s6w10">
<a>
<lex.rf>a#a-ln94200-73-p2s6w10</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s6w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TOWH</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s1Bw30</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s6w9">
<a>
<lex.rf>a#a-ln94200-73-p2s6w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příští</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s6w11">
<a>
<lex.rf>a#a-ln94200-73-p2s6w11</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>však</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94200-73-p2s6w12">
<a>
<lex.rf>a#a-ln94200-73-p2s6w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>termín</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s2w22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s6w13">
<a>
<lex.rf>a#a-ln94200-73-p2s6w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stanovený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94200-73-p2s6w14">
<a>
<lex.rf>a#a-ln94200-73-p2s6w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Febio</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s5w15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s6w17">
<a>
<lex.rf>a#a-ln94200-73-p2s6w17</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s6w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohoda</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s1Bw27</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s6w16">
<a>
<lex.rf>a#a-ln94200-73-p2s6w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>definitivní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s6a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s5w17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s6w21">
<a>
<lex.rf>a#a-ln94200-73-p2s6w21</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s6w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předčasný</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln94200-73-p2s6w20">
<a>
<lex.rf>a#a-ln94200-73-p2s6w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poněkud</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s7">
<atree.rf>a#a-ln94200-73-p2s7</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94200-73-p2s7w5">
<a>
<lex.rf>a#a-ln94200-73-p2s7w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>souviset</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41kzmA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s7w2">
<a>
<lex.rf>a#a-ln94200-73-p2s7w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednání</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41bhqA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s7a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94200-73-p2s7a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94200-73-p2s7w4">
<a>
<lex.rf>a#a-ln94200-73-p2s7w4</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s7w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nákup</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94200-73-p2s7w1">
<a>
<lex.rf>a#a-ln94200-73-p2s7w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veškerý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s7w6">
<a>
<lex.rf>a#a-ln94200-73-p2s7w6</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94200-73-p2s7w9">
<a>
<lex.rf>a#a-ln94200-73-p2s7w9</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s7w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předvídatelnost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94200-73-p2s7w12">
<a>
<lex.rf>a#a-ln94200-73-p2s7w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozpočet</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94200-73-p2s7w10">
<a>
<lex.rf>a#a-ln94200-73-p2s7w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s5w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s7w11">
<a>
<lex.rf>a#a-ln94200-73-p2s7w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budoucí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s7w8">
<a>
<lex.rf>a#a-ln94200-73-p2s7w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jistý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s8">
<atree.rf>a#a-ln94200-73-p2s8</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94200-73-p2s8w10">
<a>
<lex.rf>a#a-ln94200-73-p2s8w10</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s8w7</LM>
<LM>a#a-ln94200-73-p2s8w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dojít</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94200-73-p2s9w6</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Result</sense_PDTB3>
<src>pdit20</src>
<t-connectors.rf>
<LM>t-ln94200-73-p2s9w13</LM>
</t-connectors.rf>
<is_secondary>1</is_secondary>
</LM>
</discourse>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<val_frame.rf>v#v41zdL</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s8w4">
<a>
<lex.rf>a#a-ln94200-73-p2s8w4</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s8w1</LM>
<LM>a#a-ln94200-73-p2s8w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tlak</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<children>
<LM id="t-ln94200-73-p2s8w6">
<a>
<lex.rf>a#a-ln94200-73-p2s8w6</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s8w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>parlament</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s5w3</target_node.rf>
<type>P_FUNCT</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94200-73-p2s8w3">
<a>
<lex.rf>a#a-ln94200-73-p2s8w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>určitý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s8w8">
<a>
<lex.rf>a#a-ln94200-73-p2s8w8</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>totiž</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>4</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
<LM id="t-ln94200-73-p2s8w18">
<a>
<lex.rf>a#a-ln94200-73-p2s8w18</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>nebo</t_lemma>
<functor>GRAD</functor>
<deepord>11</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<children>
<LM id="t-ln94200-73-p2s8w13">
<a>
<lex.rf>a#a-ln94200-73-p2s8w13</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s8w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>omezení</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<val_frame.rf>v#v41etbA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s8a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>6</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
<LM id="t-ln94200-73-p2s8w14">
<a>
<lex.rf>a#a-ln94200-73-p2s8w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>plocha</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<children>
<LM id="t-ln94200-73-p2s8w16">
<a>
<lex.rf>a#a-ln94200-73-p2s8w16</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s8w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>reklama</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s8w12">
<a>
<lex.rf>a#a-ln94200-73-p2s8w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s8w19">
<a>
<lex.rf>a#a-ln94200-73-p2s8w19</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>dokonce</t_lemma>
<functor>CM</functor>
<deepord>12</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
<LM id="t-ln94200-73-p2s8w23">
<a>
<lex.rf>a#a-ln94200-73-p2s8w23</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s8w20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákaz</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<children>
<LM id="t-ln94200-73-p2s8w21">
<a>
<lex.rf>a#a-ln94200-73-p2s8w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s8w16</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s8w26">
<a>
<lex.rf>a#a-ln94200-73-p2s8w26</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s8w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>okruh</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s5w4</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln94200-73-p2s8w25">
<a>
<lex.rf>a#a-ln94200-73-p2s8w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s7w10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s8w22">
<a>
<lex.rf>a#a-ln94200-73-p2s8w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úplný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s9">
<atree.rf>a#a-ln94200-73-p2s9</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94200-73-l6A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94200-73-p2s9w1</LM>
<LM>t-ln94200-73-p2s9w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94200-73-p2s9w13">
<a>
<lex.rf>a#a-ln94200-73-p2s9w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>upřesnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41mteA</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s9w14">
<a>
<lex.rf>a#a-ln94200-73-p2s9w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Mathé</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s6a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94200-73-p2s9w16">
<a>
<lex.rf>a#a-ln94200-73-p2s9w16</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s9w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>LN</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94200-73-p2s9w6">
<a>
<lex.rf>a#a-ln94200-73-p2s9w6</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s9w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přijít</t_lemma>
<functor>PAT</functor>
<sentmod>enunc</sentmod>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<val_frame.rf>v#v41isgK</val_frame.rf>
<children>
<LM id="t-ln94200-73-p2s9w2">
<a>
<lex.rf>a#a-ln94200-73-p2s9w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>televize</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s8w25</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94200-73-p2s9w1">
<a>
<lex.rf>a#a-ln94200-73-p2s9w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<coref_text>
<LM>
<target_node.rf>t-ln94200-73-p2s5w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94200-73-p2s9w4">
<a>
<lex.rf>a#a-ln94200-73-p2s9w4</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>tak</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>6</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
<LM id="t-ln94200-73-p2s9w5">
<a>
<lex.rf>a#a-ln94200-73-p2s9w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ráz</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
<LM id="t-ln94200-73-p2s9w10">
<a>
<lex.rf>a#a-ln94200-73-p2s9w10</lex.rf>
<aux.rf>
<LM>a#a-ln94200-73-p2s9w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
<bridging>
<LM>
<target_node.rf>t-ln94200-73-p2s7w12</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln94200-73-p2s9w11">
<a>
<lex.rf>a#a-ln94200-73-p2s9w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příjem</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
<LM id="t-ln94200-73-p2s9w9">
<a>
<lex.rf>a#a-ln94200-73-p2s9w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sto</t_lemma>
<functor>RSTR</functor>
<proto_lemma>sto</proto_lemma>
<gram>
<sempos>n.quant.def</sempos>
<gender>neut</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
<LM id="t-ln94200-73-p2s9w8">
<a>
<lex.rf>a#a-ln94200-73-p2s9w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>několik</t_lemma>
<functor>RSTR</functor>
<proto_lemma>kolik</proto_lemma>
<gram>
<sempos>adj.quant.indef</sempos>
<indeftype>indef1</indeftype>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<discourse_groups>
<LM>
<id>1</id>
</LM>
</discourse_groups>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
