<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94205_37.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln94205-37-p1s1">
<atree.rf>a#a-ln94205-37-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94205-37-l6A">
<basic-form>provozní budova</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94205-37-p1s1w2</LM>
<LM>t-ln94205-37-p1s1w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94205-37-p1s1w5">
<a>
<lex.rf>a#a-ln94205-37-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>patřit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41fjzB</val_frame.rf>
<children>
<LM id="t-ln94205-37-p1s1w1">
<a>
<lex.rf>a#a-ln94205-37-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>voršilka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94205-37-p1s1w3">
<a>
<lex.rf>a#a-ln94205-37-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budova</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94205-37-p1s1w4">
<a>
<lex.rf>a#a-ln94205-37-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ND</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94205-37-p1s1w2">
<a>
<lex.rf>a#a-ln94205-37-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provozní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1A">
<atree.rf>a#a-ln94205-37-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94205-37-p2s1Aw1">
<a>
<lex.rf>a#a-ln94205-37-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1B">
<atree.rf>a#a-ln94205-37-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94205-37-l1A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s1Bw4</LM>
<LM>t-ln94205-37-p2s1Bw5</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94205-37-l4A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s1Bw14</LM>
<LM>t-ln94205-37-p2s1Bw15</LM>
<LM>t-ln94205-37-p2s1Bw16</LM>
<LM>t-ln94205-37-p2s1Bw17</LM>
<LM>t-ln94205-37-p2s1Bw18</LM>
<LM>t-ln94205-37-p2s1Bw19</LM>
<LM>t-ln94205-37-p2s1Bw20</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94205-37-l5A">
<type>object</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s1Bw37</LM>
<LM>t-ln94205-37-p2s1Bw38</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94205-37-l7A">
<basic-form>provozní budova</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s1Bw35</LM>
<LM>t-ln94205-37-p2s1Bw36</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94205-37-l9A">
<basic-form>obvodní soud</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s1Bw1</LM>
<LM>t-ln94205-37-p2s1Bw2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94205-37-l10A">
<basic-form>ministerstvo financí</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s1Bw9</LM>
<LM>t-ln94205-37-p2s1Bw10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94205-37-p2s1Bw6">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zamítnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41qbvA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s1Bw2">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soud</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw1">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obvodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94205-37-p2s1Bw4">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw4</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s1Bw3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94205-37-p2s1Aw1</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
<children>
<LM id="t-ln94205-37-p2s1Bw5">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1Bw7">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94205-37-p2s1Bw8">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žaloba</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw9">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw10">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>finance</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1Bw12">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw12</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s1Bw11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spor</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw21">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw21</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>18</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw15">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw15</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s1Bw13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provincie</t_lemma>
<functor>ADDR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw17">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>unie</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw16">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>římský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln94205-37-p2s1Bw18">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řád</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94205-37-p2s1Bw20">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Voršila</t_lemma>
<functor>APP</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw19">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svatý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1Bw14">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Českomoravský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1Bw23">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw23</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s1Bw22</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ADDR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln94205-37-p2s1Bw24">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Themos</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1Bw29">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žádat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<val_frame.rf>v#v41sdqA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s1Bw27">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw27</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s1Bw26</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>LOC</functor>
<proto_lemma>který</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>21</deepord>
<coref_gram.rf>
<LM>t-ln94205-37-p2s1Bw8</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94205-37-p2s1Bw28">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>22</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s1Bw9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94205-37-p2s1Bw30">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soud</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>23</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s1Bw2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94205-37-p2s1Bw32">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw32</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s1Bw31</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>určení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
<val_frame.rf>v#v41mtpA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s1Ba1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>25</deepord>
<coref_gram.rf>
<LM>t-ln94205-37-p2s1Bw30</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94205-37-p2s1Bw39">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw39</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s1Bw34</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vlastnit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>31</deepord>
<val_frame.rf>v#v41nmxA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s1Bw36">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw36</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budova</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>27</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94205-37-p1s1w3</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln94205-37-p2s1Bw38">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw38</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>divadlo</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>28</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p1s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94205-37-p2s1Bw37">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw37</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Národní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>29</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1Bw35">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw35</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provozní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>30</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s1Bw40">
<a>
<lex.rf>a#a-ln94205-37-p2s1Bw40</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>32</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94205-37-p2s1Bw28</target_node.rf>
<type>FUNCT_P</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s2">
<atree.rf>a#a-ln94205-37-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94205-37-l11A">
<basic-form>majetkový vztah</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s2w9</LM>
<LM>t-ln94205-37-p2s2w10</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94205-37-l12A">
<basic-form>řeholní řád</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s2w11</LM>
<LM>t-ln94205-37-p2s2w12</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94205-37-p2s2w3">
<a>
<lex.rf>a#a-ln94205-37-p2s2w3</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s2w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odvolat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41engA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s2w1">
<a>
<lex.rf>a#a-ln94205-37-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soud</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s1Ba1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94205-37-p2s2w5">
<a>
<lex.rf>a#a-ln94205-37-p2s2w5</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94205-37-p2s2w7">
<a>
<lex.rf>a#a-ln94205-37-p2s2w7</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s2w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úprava</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94205-37-p2s2w10">
<a>
<lex.rf>a#a-ln94205-37-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vztah</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94205-37-p2s2w9">
<a>
<lex.rf>a#a-ln94205-37-p2s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>majetkový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94205-37-p2s2w8">
<a>
<lex.rf>a#a-ln94205-37-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>některý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>indef1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94205-37-p2s2w15">
<a>
<lex.rf>a#a-ln94205-37-p2s2w15</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln94205-37-p2s2w13">
<a>
<lex.rf>a#a-ln94205-37-p2s2w13</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>9</deepord>
<children>
<LM id="t-ln94205-37-p2s2w12">
<a>
<lex.rf>a#a-ln94205-37-p2s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řád</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94205-37-p2s1Bw18</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94205-37-p2s2w14">
<a>
<lex.rf>a#a-ln94205-37-p2s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kongregace</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln94205-37-p2s2w11">
<a>
<lex.rf>a#a-ln94205-37-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řeholní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s2w16">
<a>
<lex.rf>a#a-ln94205-37-p2s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>arcibiskupství</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94205-37-p2s2w17">
<a>
<lex.rf>a#a-ln94205-37-p2s2w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>olomoucký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s2w19">
<a>
<lex.rf>a#a-ln94205-37-p2s2w19</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s2w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TFRWH</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln94205-37-p2s2w20">
<a>
<lex.rf>a#a-ln94205-37-p2s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1990</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s2w24">
<a>
<lex.rf>a#a-ln94205-37-p2s2w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stanovit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<val_frame.rf>v#v41lhzD</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s2w22">
<a>
<lex.rf>a#a-ln94205-37-p2s2w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_gram.rf>
<LM>t-ln94205-37-p2s2w5</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94205-37-p2s2w23">
<a>
<lex.rf>a#a-ln94205-37-p2s2w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výčet</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
<LM id="t-ln94205-37-p2s2w31">
<a>
<lex.rf>a#a-ln94205-37-p2s2w31</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s2w28</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>navrátit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
<val_frame.rf>v#v41dgsA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s2w27">
<a>
<lex.rf>a#a-ln94205-37-p2s2w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>majetek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>20</deepord>
<children>
<LM id="t-ln94205-37-p2s2w26">
<a>
<lex.rf>a#a-ln94205-37-p2s2w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jaký</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jaký</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>inter</indeftype>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s2w30">
<a>
<lex.rf>a#a-ln94205-37-p2s2w30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řád</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>22</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s2w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94205-37-p2s2w29">
<a>
<lex.rf>a#a-ln94205-37-p2s2w29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednotlivý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s3">
<atree.rf>a#a-ln94205-37-p2s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94205-37-l13A">
<basic-form>číslo popisné</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s3w1</LM>
<LM>t-ln94205-37-p2s3w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94205-37-p2s3w8">
<a>
<lex.rf>a#a-ln94205-37-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s3w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>res1</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41ndjB</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s3w1">
<a>
<lex.rf>a#a-ln94205-37-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>číslo</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94205-37-p2s3w4">
<a>
<lex.rf>a#a-ln94205-37-p2s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budova</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p1s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94205-37-p2s3w3">
<a>
<lex.rf>a#a-ln94205-37-p2s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sporný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s3w2">
<a>
<lex.rf>a#a-ln94205-37-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>popisný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s3a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94205-37-p2s3w7">
<a>
<lex.rf>a#a-ln94205-37-p2s3w7</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s3w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s2w22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s4">
<atree.rf>a#a-ln94205-37-p2s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94205-37-l8A">
<basic-form>provozní budova</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94205-37-p2s4w6</LM>
<LM>t-ln94205-37-p2s4w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94205-37-p2s4w2">
<a>
<lex.rf>a#a-ln94205-37-p2s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>argumentovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41ceA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s4w1">
<a>
<lex.rf>a#a-ln94205-37-p2s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s1Bw28</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94205-37-p2s4w8">
<a>
<lex.rf>a#a-ln94205-37-p2s4w8</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s4w3</LM>
<LM>a#a-ln94205-37-p2s4w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s4w7">
<a>
<lex.rf>a#a-ln94205-37-p2s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budova</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s3w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94205-37-p2s4w6">
<a>
<lex.rf>a#a-ln94205-37-p2s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provozní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s4w9">
<a>
<lex.rf>a#a-ln94205-37-p2s4w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budova</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94205-37-p2s4w11">
<a>
<lex.rf>a#a-ln94205-37-p2s4w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jiný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94205-37-p2s4w10">
<a>
<lex.rf>a#a-ln94205-37-p2s4w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zcela</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s5">
<atree.rf>a#a-ln94205-37-p2s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94205-37-p2s5w8">
<a>
<lex.rf>a#a-ln94205-37-p2s5w8</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s5w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94205-37-p2s4w2</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94205-37-p2s5w1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41hbiA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s5w3">
<a>
<lex.rf>a#a-ln94205-37-p2s5w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>objekt</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94205-37-p2s4w9</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<children>
<LM id="t-ln94205-37-p2s5w2">
<a>
<lex.rf>a#a-ln94205-37-p2s5w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>původní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s5w1">
<a>
<lex.rf>a#a-ln94205-37-p2s5w1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>navíc</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94205-37-p2s5a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94205-37-p2s5w6">
<a>
<lex.rf>a#a-ln94205-37-p2s5w6</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s5w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94205-37-p2s5w7">
<a>
<lex.rf>a#a-ln94205-37-p2s5w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1931</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s5w9">
<a>
<lex.rf>a#a-ln94205-37-p2s5w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s1Bw40</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-37-p2s6">
<atree.rf>a#a-ln94205-37-p2s6</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94205-37-p2s6w4">
<a>
<lex.rf>a#a-ln94205-37-p2s6w4</lex.rf>
<aux.rf>
<LM>a#a-ln94205-37-p2s6w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odejmout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94205-37-p2s5w8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>equiv</discourse_type>
<sense_PDTB3>Expansion.Equivalence</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94205-37-p2s6w2</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41dysA</val_frame.rf>
<children>
<LM id="t-ln94205-37-p2s6w1">
<a>
<lex.rf>a#a-ln94205-37-p2s6w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řád</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s1Bw18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94205-37-p2s6w2">
<a>
<lex.rf>a#a-ln94205-37-p2s6w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>tedy</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94205-37-p2s6a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94205-37-p2s6a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94205-37-p2s5w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
