<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj2304.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<trees>
<LM id="T-wsj2304-001-p1s0">
<atree.rf>a#a-wsj2304-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a1">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>24</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj2304-001-p1s0a7">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosáhnout</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41afbA</val_frame.rf>
<children>
<LM id="T-wsj2304-001-p1s0a8">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produkce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a9">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kanadský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2304-001-p1s0a10">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ingot</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a11">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ocelový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s0a16">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s0W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>týden</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a17">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>končící</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a3">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říjen</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a4">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s0W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s0a35">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>15</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a13">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tuna</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a12">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>291890</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2304-001-p1s0a14">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>metrický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s0a2">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2304-001-p1s0a18">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>ACT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>13</deepord>
<coref_gram.rf>
<LM>T-wsj2304-001-p1s0a13</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2304-001-p1s0a19">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nárůst</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a36">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s0W19-Ta</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>DIFF</functor>
<deepord>17</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a21">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>14.8</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s0a24">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s0W22-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výkon</t_lemma>
<functor>CPR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a25">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předchozí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
<LM id="T-wsj2304-001-p1s0a26">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>týdenní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
<LM id="T-wsj2304-001-p1s0a28">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tuna</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a27">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>254280</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s0a30">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>26</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a31">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>federální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
<LM id="T-wsj2304-001-p1s0a34">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>27</deepord>
<children>
<LM id="T-wsj2304-001-p1s0a32">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W32-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Statistika</t_lemma>
<functor>FPHR</functor>
<deepord>28</deepord>
</LM>
<LM id="T-wsj2304-001-p1s0a33">
<a>
<lex.rf>a#a-wsj2304-001-p1s0W33-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Kanada</t_lemma>
<functor>FPHR</functor>
<deepord>29</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Canadian steel-ingot production totaled 291,890 metric tons in the week ended Oct. 7, up 14.8% from the preceding week's total of 254,280 tons, Statistics Canada, a federal agency, said.</eng_sentence>
</LM>
<LM id="T-wsj2304-001-p1s1">
<atree.rf>a#a-wsj2304-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2304-001-p1s1a1">
<a>
<lex.rf>a#a-wsj2304-001-p1s1W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s1W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41sdjA</val_frame.rf>
<children>
<LM id="T-wsj2304-001-p1s1a2">
<a>
<lex.rf>a#a-wsj2304-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úhrn</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj2304-001-p1s1a3">
<a>
<lex.rf>a#a-wsj2304-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>týdenní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s1a7">
<a>
<lex.rf>a#a-wsj2304-001-p1s1W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s1W5-Ta</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>DIFF</functor>
<deepord>5</deepord>
<children>
<LM id="T-wsj2304-001-p1s1a6">
<a>
<lex.rf>a#a-wsj2304-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>6.2</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s1a9">
<a>
<lex.rf>a#a-wsj2304-001-p1s1W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s1W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tuna</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj2304-001-p1s1a10">
<a>
<lex.rf>a#a-wsj2304-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>274963</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2304-001-p1s1a12">
<a>
<lex.rf>a#a-wsj2304-001-p1s1W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s1W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The week's total was up 6.2% from 274,963 tons a year earlier.</eng_sentence>
</LM>
<LM id="T-wsj2304-001-p1s2">
<atree.rf>a#a-wsj2304-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2304-001-p1s2a1">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="T-wsj2304-001-p1s2a2">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2304-001-p1s2a3">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úhrn</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj2304-001-p1s2a4">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>roční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s2a6">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s2W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>datum</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj2304-001-p1s2a7">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dnešní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s2a9">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tuna</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj2304-001-p1s2a8">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>12006883</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s2a19">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>9</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2304-001-p1s2a10">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nárůst</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj2304-001-p1s2a20">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W12-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>PAT</functor>
<deepord>11</deepord>
<children>
<LM id="T-wsj2304-001-p1s2a11">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7.8</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2304-001-p1s2a15">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s2W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tuna</t_lemma>
<functor>CPR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2304-001-p1s2a16">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>11141711</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj2304-001-p1s2a18">
<a>
<lex.rf>a#a-wsj2304-001-p1s2W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2304-001-p1s2W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2304-001-p1s1a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The year-to-date total was 12,006,883 tons, up 7.8% from 11,141,711 tons a year earlier.</eng_sentence>
</LM>
</trees>
</tdata>
