<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94210_133.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln94210-133-p1s1">
<atree.rf>a#a-ln94210-133-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94210-133-l2A">
<basic-form>černý šerif</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p1s1w1</LM>
<LM>t-ln94210-133-p1s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94210-133-p1s1w3">
<a>
<lex.rf>a#a-ln94210-133-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chtít</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41bcdA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p1s1w2">
<a>
<lex.rf>a#a-ln94210-133-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šerif</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94210-133-p1s1w1">
<a>
<lex.rf>a#a-ln94210-133-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>černý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p1s1w5">
<a>
<lex.rf>a#a-ln94210-133-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>volnost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94210-133-p1s1w4">
<a>
<lex.rf>a#a-ln94210-133-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1A">
<atree.rf>a#a-ln94210-133-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94210-133-p2s1Aw1">
<a>
<lex.rf>a#a-ln94210-133-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94210-133-p2s1Aw3">
<a>
<lex.rf>a#a-ln94210-133-p2s1Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>js</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>nr</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1B">
<atree.rf>a#a-ln94210-133-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94210-133-l5A">
<basic-form>bezpečnostní agentura</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p2s1Bw8</LM>
<LM>t-ln94210-133-p2s1Bw9</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l6A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94210-133-p2s1Bw20</LM>
<LM>t-ln94210-133-p2s1Bw21</LM>
<LM>t-ln94210-133-p2s1Bw22</LM>
<LM>t-ln94210-133-p2s1Bw23</LM>
<LM>t-ln94210-133-p2s1Bw24</LM>
<LM>t-ln94210-133-p2s1Bw25</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l7A">
<basic-form>Oldřich Dajbych</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94210-133-p2s1Bw26</LM>
<LM>t-ln94210-133-p2s1Bw27</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l8A">
<basic-form>ministerstvo vnitra</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p2s1Bw4</LM>
<LM>t-ln94210-133-p2s1Bw5</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94210-133-p2s1Bw11">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vadit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41nfwA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p2s1Bw2">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tendence</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94210-133-p2s1Ba1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94210-133-p2s1Bw3">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podřídit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41fuzA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p2s1Ba0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_gram.rf>
<LM>t-ln94210-133-p2s1Ba1</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94210-133-p2s1Bw4">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94210-133-p2s1Bw5">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vnitro</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1Bw9">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p1s1w2</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p2s1Bw8">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bezpečnostní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94210-133-p2s1Bw7">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>civilně</t_lemma>
<functor>REG</functor>
<proto_lemma>civilní</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1Bw6">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komerční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1Bw1">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>absolutní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1Bw10">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw10</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>hlavně</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln94210-133-p2s1Bw14">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw14</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p2s1Bw12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln94210-133-p2s1Bw15">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln94210-133-p2s1Bw18">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw18</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p2s1Bw16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s1Bw9</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p2s1Bw17">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1Bw13">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1Bw27">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Dajbych</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln94210-133-p2s1Bw26">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Oldřich</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-ln94210-133-p2s1Bw19">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<children>
<LM id="t-ln94210-133-p2s1Bw20">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sdružení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94210-133-p2s1Bw18</target_node.rf>
<type>REST</type>
</LM>
</bridging>
<val_frame.rf>v#v41kgoB</val_frame.rf>
<children>
<LM id="t-ln94210-133-p2s1Bw25">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>služba</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<children>
<LM id="t-ln94210-133-p2s1Bw23">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw23</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>25</deepord>
<children>
<LM id="t-ln94210-133-p2s1Bw22">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bezpečnostní</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
<LM id="t-ln94210-133-p2s1Bw24">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>detektivní</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s1Bw21">
<a>
<lex.rf>a#a-ln94210-133-p2s1Bw21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>civilní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s2">
<atree.rf>a#a-ln94210-133-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94210-133-l9A">
<basic-form>ministerstvo vnitra</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p2s2w14</LM>
<LM>t-ln94210-133-p2s2w15</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l10A">
<basic-form>Květoslav Kramář</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94210-133-p2s2w16</LM>
<LM>t-ln94210-133-p2s2w17</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l11A">
<basic-form>Tomáš Svoboda</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94210-133-p2s2w21</LM>
<LM>t-ln94210-133-p2s2w22</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l12A">
<basic-form>poslanec parlamentu</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p2s2w19</LM>
<LM>t-ln94210-133-p2s2w20</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94210-133-p2s2w1">
<a>
<lex.rf>a#a-ln94210-133-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odpovědět</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41egtB</val_frame.rf>
<children>
<LM id="t-ln94210-133-p2s2w2">
<a>
<lex.rf>a#a-ln94210-133-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tak</t_lemma>
<functor>MANN</functor>
<proto_lemma>tak</proto_lemma>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s1Bw11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94210-133-p2s2a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s1Bw27</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94210-133-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94210-133-p2s2w3">
<a>
<lex.rf>a#a-ln94210-133-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94210-133-p2s2w5">
<a>
<lex.rf>a#a-ln94210-133-p2s2w5</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p2s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dotaz</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94210-133-p2s2w6">
<a>
<lex.rf>a#a-ln94210-133-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>LN</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94210-133-p2s2w8">
<a>
<lex.rf>a#a-ln94210-133-p2s2w8</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p2s2w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>setkání</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41klfA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p2s2w9">
<a>
<lex.rf>a#a-ln94210-133-p2s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zástupce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94210-133-p2s2a1</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln94210-133-p2s2w11">
<a>
<lex.rf>a#a-ln94210-133-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s1Bw18</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p2s2w10">
<a>
<lex.rf>a#a-ln94210-133-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s2w27">
<a>
<lex.rf>a#a-ln94210-133-p2s2w27</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>21</deepord>
<children>
<LM id="t-ln94210-133-p2s2w17">
<a>
<lex.rf>a#a-ln94210-133-p2s2w17</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p2s2w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kramář</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94210-133-p2s2w16">
<a>
<lex.rf>a#a-ln94210-133-p2s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Květoslav</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln94210-133-p2s2w13">
<a>
<lex.rf>a#a-ln94210-133-p2s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zástupce</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln94210-133-p2s2w14">
<a>
<lex.rf>a#a-ln94210-133-p2s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s1Bw4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p2s2w15">
<a>
<lex.rf>a#a-ln94210-133-p2s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vnitro</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s2w22">
<a>
<lex.rf>a#a-ln94210-133-p2s2w22</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p2s2w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Svoboda</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln94210-133-p2s2w21">
<a>
<lex.rf>a#a-ln94210-133-p2s2w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tomáš</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
<LM id="t-ln94210-133-p2s2w19">
<a>
<lex.rf>a#a-ln94210-133-p2s2w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslanec</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln94210-133-p2s2w20">
<a>
<lex.rf>a#a-ln94210-133-p2s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>parlament</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s2w24">
<a>
<lex.rf>a#a-ln94210-133-p2s2w24</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p2s2w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představitel</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<children>
<LM id="t-ln94210-133-p2s2w26">
<a>
<lex.rf>a#a-ln94210-133-p2s2w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>magistrát</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<children>
<LM id="t-ln94210-133-p2s2w25">
<a>
<lex.rf>a#a-ln94210-133-p2s2w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pražský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s1Aw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p2s2w30">
<a>
<lex.rf>a#a-ln94210-133-p2s2w30</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p2s2w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osoba</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
<children>
<LM id="t-ln94210-133-p2s2w29">
<a>
<lex.rf>a#a-ln94210-133-p2s2w29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zainteresovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
</LM>
<LM id="t-ln94210-133-p2s2w28">
<a>
<lex.rf>a#a-ln94210-133-p2s2w28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jiný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s1">
<atree.rf>a#a-ln94210-133-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94210-133-l13A">
<basic-form>legislativní odbor</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p3s1w2</LM>
<LM>t-ln94210-133-p3s1w3</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l14A">
<basic-form>bezpečnostní agentura</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p3s1w20</LM>
<LM>t-ln94210-133-p3s1w21</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l15A">
<basic-form>bezpečnostní systém</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p3s1w29</LM>
<LM>t-ln94210-133-p3s1w30</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l18A">
<basic-form>veřejné právo</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p3s1w56</LM>
<LM>t-ln94210-133-p3s1w57</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94210-133-p3s1w8">
<a>
<lex.rf>a#a-ln94210-133-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdůraznit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41qzoA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p3s1w5">
<a>
<lex.rf>a#a-ln94210-133-p3s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kramář</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s2w17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p3s1w1">
<a>
<lex.rf>a#a-ln94210-133-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vedoucí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94210-133-p3s1w3">
<a>
<lex.rf>a#a-ln94210-133-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odbor</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94210-133-p3s1w4">
<a>
<lex.rf>a#a-ln94210-133-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>MV</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s2w14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94210-133-p3s1w2">
<a>
<lex.rf>a#a-ln94210-133-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>legislativní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s1w7">
<a>
<lex.rf>a#a-ln94210-133-p3s1w7</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p3s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>debata</t_lemma>
<functor>TPAR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94210-133-p2s2w8</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94210-133-p3s1w32">
<a>
<lex.rf>a#a-ln94210-133-p3s1w32</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ale</t_lemma>
<functor>ADVS</functor>
<deepord>24</deepord>
<children>
<LM id="t-ln94210-133-p3s1w22">
<a>
<lex.rf>a#a-ln94210-133-p3s1w22</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>sice</t_lemma>
<functor>CM</functor>
<deepord>8</deepord>
</LM>
<LM id="t-ln94210-133-p3s1w24">
<a>
<lex.rf>a#a-ln94210-133-p3s1w24</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p3s1w23</LM>
<LM>a#a-ln94210-133-p3s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94210-133-p3s1w12">
<a>
<lex.rf>a#a-ln94210-133-p3s1w12</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p3s1w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s1Bw14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p3s1w13">
<a>
<lex.rf>a#a-ln94210-133-p3s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s1Bw15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94210-133-p3s1w18">
<a>
<lex.rf>a#a-ln94210-133-p3s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>končit</t_lemma>
<functor>RSTR</functor>
<proto_lemma>končit</proto_lemma>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<val_frame.rf>v#v41bplF</val_frame.rf>
<children>
<LM id="t-ln94210-133-p3s1w17">
<a>
<lex.rf>a#a-ln94210-133-p3s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fáze</t_lemma>
<functor>ACT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94210-133-p3s1w15">
<a>
<lex.rf>a#a-ln94210-133-p3s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>APP</functor>
<proto_lemma>který</proto_lemma>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_gram.rf>
<LM>t-ln94210-133-p3s1w12</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94210-133-p3s1w16">
<a>
<lex.rf>a#a-ln94210-133-p3s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>připomínkový</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s1w21">
<a>
<lex.rf>a#a-ln94210-133-p3s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s2w11</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p3s1w20">
<a>
<lex.rf>a#a-ln94210-133-p3s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bezpečnostní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s1w25">
<a>
<lex.rf>a#a-ln94210-133-p3s1w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>součást</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln94210-133-p3s1w30">
<a>
<lex.rf>a#a-ln94210-133-p3s1w30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>systém</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln94210-133-p3s1w29">
<a>
<lex.rf>a#a-ln94210-133-p3s1w29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bezpečnostní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-ln94210-133-p3s1w28">
<a>
<lex.rf>a#a-ln94210-133-p3s1w28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>integrovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
<LM id="t-ln94210-133-p3s1w27">
<a>
<lex.rf>a#a-ln94210-133-p3s1w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chápaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<children>
<LM id="t-ln94210-133-p3s1w26">
<a>
<lex.rf>a#a-ln94210-133-p3s1w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>široko</t_lemma>
<functor>EXT</functor>
<proto_lemma>široký</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>acomp</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s1w49">
<a>
<lex.rf>a#a-ln94210-133-p3s1w49</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>35</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94210-133-p3s1w24</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94210-133-p3s1w32</LM>
<LM>t-ln94210-133-p3s1w22</LM>
</t-connectors.rf>
</LM>
</discourse>
<children>
<LM id="t-ln94210-133-p3s1w33">
<a>
<lex.rf>a#a-ln94210-133-p3s1w33</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p3s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jít</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
<val_frame.rf>v#v41bikAV</val_frame.rf>
<children>
<LM id="t-ln94210-133-p3s1w34">
<a>
<lex.rf>a#a-ln94210-133-p3s1w34</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>především</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>26</deepord>
</LM>
<LM id="t-ln94210-133-p3s1w45">
<a>
<lex.rf>a#a-ln94210-133-p3s1w45</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p3s1w35</LM>
<LM>a#a-ln94210-133-p3s1w36</LM>
<LM>a#a-ln94210-133-p3s1w38</LM>
<LM>a#a-ln94210-133-p3s1w44</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>působit</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>31</deepord>
<val_frame.rf>v#v41jebA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p3s1w41">
<a>
<lex.rf>a#a-ln94210-133-p3s1w41</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>práce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>28</deepord>
<children>
<LM id="t-ln94210-133-p3s1w40">
<a>
<lex.rf>a#a-ln94210-133-p3s1w40</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>27</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p3s1w21</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94210-133-p3s1w43">
<a>
<lex.rf>a#a-ln94210-133-p3s1w43</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p3s1w42</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákazník</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>29</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s1a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>30</deepord>
</LM>
<LM id="t-ln94210-133-p3s1w46">
<a>
<lex.rf>a#a-ln94210-133-p3s1w46</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>újma</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>32</deepord>
</LM>
<LM id="t-ln94210-133-p3s1w48">
<a>
<lex.rf>a#a-ln94210-133-p3s1w48</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osoba</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>33</deepord>
<children>
<LM id="t-ln94210-133-p3s1w47">
<a>
<lex.rf>a#a-ln94210-133-p3s1w47</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetí</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>34</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s1w51">
<a>
<lex.rf>a#a-ln94210-133-p3s1w51</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p3s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jít</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>38</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94210-133-p3s1w33</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94210-133-p3s1w49</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41bikAV</val_frame.rf>
<children>
<LM id="t-ln94210-133-p3s1w50">
<a>
<lex.rf>a#a-ln94210-133-p3s1w50</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>rozhodně</t_lemma>
<functor>ATT</functor>
<tfa>t</tfa>
<deepord>36</deepord>
</LM>
<LM id="t-ln94210-133-p3s1a1">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>37</deepord>
</LM>
<LM id="t-ln94210-133-p3s1w53">
<a>
<lex.rf>a#a-ln94210-133-p3s1w53</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p3s1w52</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střet</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>40</deepord>
<children>
<LM id="t-ln94210-133-p3s1a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>39</deepord>
<coref_gram.rf>
<LM>t-ln94210-133-p3s1w55</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94210-133-p3s1w55">
<a>
<lex.rf>a#a-ln94210-133-p3s1w55</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>43</deepord>
<children>
<LM id="t-ln94210-133-p3s1a2">
<a>
<lex.rf>a#a-ln94210-133-p3s1w57</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>právo</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>41</deepord>
<children>
<LM id="t-ln94210-133-p3s1w54">
<a>
<lex.rf>a#a-ln94210-133-p3s1w54</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soukromý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>42</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s1w57">
<a>
<lex.rf>a#a-ln94210-133-p3s1w57</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>právo</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>44</deepord>
<children>
<LM id="t-ln94210-133-p3s1w56">
<a>
<lex.rf>a#a-ln94210-133-p3s1w56</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veřejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>45</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s2">
<atree.rf>a#a-ln94210-133-p3s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94210-133-p3s2w10">
<a>
<lex.rf>a#a-ln94210-133-p3s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p3s2w11">
<a>
<lex.rf>a#a-ln94210-133-p3s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kramář</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p3s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94210-133-p3s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94210-133-p3s2w6">
<a>
<lex.rf>a#a-ln94210-133-p3s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>otevřít</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41fdfA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p3s2w2">
<a>
<lex.rf>a#a-ln94210-133-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p3s1w40</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p3s2w1">
<a>
<lex.rf>a#a-ln94210-133-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s2w5">
<a>
<lex.rf>a#a-ln94210-133-p3s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sám</t_lemma>
<functor>COMPL</functor>
<proto_lemma>sám</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<compl.rf>
<LM>t-ln94210-133-p3s2w2</LM>
</compl.rf>
</LM>
<LM id="t-ln94210-133-p3s2w4">
<a>
<lex.rf>a#a-ln94210-133-p3s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>exces</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94210-133-p3s2w3">
<a>
<lex.rf>a#a-ln94210-133-p3s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_gram.rf>
<LM>t-ln94210-133-p3s2w2</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p3s2w8">
<a>
<lex.rf>a#a-ln94210-133-p3s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>problém</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="t-ln94210-133-p3s2w7">
<a>
<lex.rf>a#a-ln94210-133-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p4s1">
<atree.rf>a#a-ln94210-133-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94210-133-l1A">
<basic-form>prodloužená ruka</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p4s1w11</LM>
<LM>t-ln94210-133-p4s1w12</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94210-133-p4s1w15">
<a>
<lex.rf>a#a-ln94210-133-p4s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyjádřit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41oczC</val_frame.rf>
<children>
<LM id="t-ln94210-133-p4s1w1">
<a>
<lex.rf>a#a-ln94210-133-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přesvědčení</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41ikcA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p4s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_gram.rf>
<LM>t-ln94210-133-p4s1w16</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94210-133-p4s1w8">
<a>
<lex.rf>a#a-ln94210-133-p4s1w8</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p4s1w7</LM>
<LM>a#a-ln94210-133-p4s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>udělat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41mhqC</val_frame.rf>
<children>
<LM id="t-ln94210-133-p4s1w5">
<a>
<lex.rf>a#a-ln94210-133-p4s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p3s1w15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p4s1w6">
<a>
<lex.rf>a#a-ln94210-133-p4s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p3s1w13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94210-133-p4s1w4">
<a>
<lex.rf>a#a-ln94210-133-p4s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přijatý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p4s1w10">
<a>
<lex.rf>a#a-ln94210-133-p4s1w10</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p4s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p3s2w3</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94210-133-p4s1w12">
<a>
<lex.rf>a#a-ln94210-133-p4s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ruka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94210-133-p4s1w13">
<a>
<lex.rf>a#a-ln94210-133-p4s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>policie</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94210-133-p4s1w11">
<a>
<lex.rf>a#a-ln94210-133-p4s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodloužený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p4s1w16">
<a>
<lex.rf>a#a-ln94210-133-p4s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zástupce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94210-133-p4s1w18">
<a>
<lex.rf>a#a-ln94210-133-p4s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sdružení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41kgoB</val_frame.rf>
<children>
<LM id="t-ln94210-133-p4s1w20">
<a>
<lex.rf>a#a-ln94210-133-p4s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>agentura</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p4s1w10</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p4s1w19">
<a>
<lex.rf>a#a-ln94210-133-p4s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p4s1w17">
<a>
<lex.rf>a#a-ln94210-133-p4s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>moravský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p4s2">
<atree.rf>a#a-ln94210-133-p4s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94210-133-l16A">
<basic-form>poslanec parlamentu</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94210-133-p4s2w1</LM>
<LM>t-ln94210-133-p4s2w2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94210-133-l17A">
<basic-form>Tomáš Svoboda</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94210-133-p4s2w3</LM>
<LM>t-ln94210-133-p4s2w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94210-133-p4s2w8">
<a>
<lex.rf>a#a-ln94210-133-p4s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>označit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41ffxA</val_frame.rf>
<children>
<LM id="t-ln94210-133-p4s2w4">
<a>
<lex.rf>a#a-ln94210-133-p4s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Svoboda</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s2w22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p4s2w1">
<a>
<lex.rf>a#a-ln94210-133-p4s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslanec</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94210-133-p4s2w2">
<a>
<lex.rf>a#a-ln94210-133-p4s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>parlament</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p2s2w20</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p4s2w3">
<a>
<lex.rf>a#a-ln94210-133-p4s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tomáš</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94210-133-p4s2w6">
<a>
<lex.rf>a#a-ln94210-133-p4s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>KDS</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p4s2w10">
<a>
<lex.rf>a#a-ln94210-133-p4s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94210-133-p4s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94210-133-p4s2w9">
<a>
<lex.rf>a#a-ln94210-133-p4s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výsledný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94210-133-p4s2w12">
<a>
<lex.rf>a#a-ln94210-133-p4s2w12</lex.rf>
<aux.rf>
<LM>a#a-ln94210-133-p4s2w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šťastný</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
