<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94205_116.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>caption</genre>
</meta>
<trees>
<LM id="t-ln94205-116-p1s1A">
<atree.rf>a#a-ln94205-116-p1s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94205-116-p1s1Aw8">
<a>
<lex.rf>a#a-ln94205-116-p1s1Aw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sledovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<discourse_feature>heading</discourse_feature>
<discourse_comment>is_photo description</discourse_comment>
<val_frame.rf>v#v41kslE</val_frame.rf>
<children>
<LM id="t-ln94205-116-p1s1Aw1">
<a>
<lex.rf>a#a-ln94205-116-p1s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>souboj</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94205-116-p1s1Aw3">
<a>
<lex.rf>a#a-ln94205-116-p1s1Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bejbl</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94205-116-p1s1Aw2">
<a>
<lex.rf>a#a-ln94205-116-p1s1Aw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>slávista</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94205-116-p1s1Aw5">
<a>
<lex.rf>a#a-ln94205-116-p1s1Aw5</lex.rf>
<aux.rf>
<LM>a#a-ln94205-116-p1s1Aw4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jeden</t_lemma>
<functor>ADDR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94205-116-p1s1Aw7">
<a>
<lex.rf>a#a-ln94205-116-p1s1Aw7</lex.rf>
<aux.rf>
<LM>a#a-ln94205-116-p1s1Aw6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jihočech</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-116-p1s1Aw10">
<a>
<lex.rf>a#a-ln94205-116-p1s1Aw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bohuněk</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94205-116-p1s1Aw9">
<a>
<lex.rf>a#a-ln94205-116-p1s1Aw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodčí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94205-116-p1s1B">
<atree.rf>a#a-ln94205-116-p1s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94205-116-l1A">
<basic-form>Robert Zlatohlávek</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94205-116-p1s1Bw2</LM>
<LM>t-ln94205-116-p1s1Bw3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94205-116-p1s1Ba0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94205-116-p1s1Bw1">
<a>
<lex.rf>a#a-ln94205-116-p1s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>foto</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94205-116-p1s1Bw3">
<a>
<lex.rf>a#a-ln94205-116-p1s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Zlatohlávek</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94205-116-p1s1Bw2">
<a>
<lex.rf>a#a-ln94205-116-p1s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Robert</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94205-116-p1s1Bw5">
<a>
<lex.rf>a#a-ln94205-116-p1s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>LN</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
