<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln95048_055.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>letter</genre>
</meta>
<trees>
<LM id="t-ln95048-055-p1s1">
<atree.rf>a#a-ln95048-055-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95048-055-p1s1w4">
<a>
<lex.rf>a#a-ln95048-055-p1s1w4</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln95048-055-p1s1w2">
<a>
<lex.rf>a#a-ln95048-055-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>srdce</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95048-055-p1s1w3">
<a>
<lex.rf>a#a-ln95048-055-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ptačí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95048-055-p1s1w1">
<a>
<lex.rf>a#a-ln95048-055-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jeden</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p1s1w6">
<a>
<lex.rf>a#a-ln95048-055-p1s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapka</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95048-055-p1s1w7">
<a>
<lex.rf>a#a-ln95048-055-p1s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žluč</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln95048-055-p1s1w5">
<a>
<lex.rf>a#a-ln95048-055-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtyři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>čtyři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s1A">
<atree.rf>a#a-ln95048-055-p2s1A</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95048-055-l2A">
<type>time</type>
<tnode.rfs>
<LM>t-ln95048-055-p2s1Aw3</LM>
<LM>t-ln95048-055-p2s1Aw5</LM>
<LM>t-ln95048-055-p2s1Aw7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95048-055-p2s1Aw2">
<a>
<lex.rf>a#a-ln95048-055-p2s1Aw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>NLN</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95048-055-p2s1Aw5">
<a>
<lex.rf>a#a-ln95048-055-p2s1Aw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95048-055-p2s1Aw3">
<a>
<lex.rf>a#a-ln95048-055-p2s1Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>28</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95048-055-p2s1Aw7">
<a>
<lex.rf>a#a-ln95048-055-p2s1Aw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1995</t_lemma>
<functor>APP</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s1B">
<atree.rf>a#a-ln95048-055-p2s1B</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95048-055-p2s1Bw4">
<a>
<lex.rf>a#a-ln95048-055-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s1Bw1">
<a>
<lex.rf>a#a-ln95048-055-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uveřejňování</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41ndgA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s1Ba0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95048-055-p2s1Bw3">
<a>
<lex.rf>a#a-ln95048-055-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>článek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_special>exoph</coref_special>
<children>
<LM id="t-ln95048-055-p2s1Bw2">
<a>
<lex.rf>a#a-ln95048-055-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>takový</t_lemma>
<functor>RSTR</functor>
<proto_lemma>takový</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s1Bw6">
<a>
<lex.rf>a#a-ln95048-055-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>důležitý</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95048-055-p2s1Bw5">
<a>
<lex.rf>a#a-ln95048-055-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nesmírně</t_lemma>
<functor>EXT</functor>
<proto_lemma>nesmírný</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s2">
<atree.rf>a#a-ln95048-055-p2s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95048-055-p2s2a8">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="t-ln95048-055-p2s2w9">
<a>
<lex.rf>a#a-ln95048-055-p2s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>roztrhnout_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41kaeA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s2w2">
<a>
<lex.rf>a#a-ln95048-055-p2s2w2</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>revoluce</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w10">
<a>
<lex.rf>a#a-ln95048-055-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pytel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95048-055-p2s2w7">
<a>
<lex.rf>a#a-ln95048-055-p2s2w7</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="t-ln95048-055-p2s2w6">
<a>
<lex.rf>a#a-ln95048-055-p2s2w6</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pavěda</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95048-055-p2s2w5">
<a>
<lex.rf>a#a-ln95048-055-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>různý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s2w8">
<a>
<lex.rf>a#a-ln95048-055-p2s2w8</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šarlatánství</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s2w13">
<a>
<lex.rf>a#a-ln95048-055-p2s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chápat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s2w9</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95048-055-p2s2w12</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41bamD</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s2w12">
<a>
<lex.rf>a#a-ln95048-055-p2s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>PAT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_gram.rf>
<LM>t-ln95048-055-p2s2w9</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95048-055-p2s2a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w27">
<a>
<lex.rf>a#a-ln95048-055-p2s2w27</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>22</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s2a8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Reason</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-ln95048-055-p2s2w15</LM>
</a-connectors.rf>
</LM>
</discourse>
<children>
<LM id="t-ln95048-055-p2s2w16">
<a>
<lex.rf>a#a-ln95048-055-p2s2w16</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>jednak</t_lemma>
<functor>CM</functor>
<deepord>12</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w22">
<a>
<lex.rf>a#a-ln95048-055-p2s2w22</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CSQ</functor>
<is_member>1</is_member>
<deepord>17</deepord>
<children>
<LM id="t-ln95048-055-p2s2a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p2s2w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95048-055-p2s2w17">
<a>
<lex.rf>a#a-ln95048-055-p2s2w17</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>CAUS</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s2w25</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Result</sense_PDTB3>
<src>pdt30</src>
<t-connectors.rf>
<LM>t-ln95048-055-p2s2w22</LM>
<LM>t-ln95048-055-p2s2w23</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s2w19">
<a>
<lex.rf>a#a-ln95048-055-p2s2w19</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komunismus</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w20">
<a>
<lex.rf>a#a-ln95048-055-p2s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zakázaný</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s2w23">
<a>
<lex.rf>a#a-ln95048-055-p2s2w23</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>tak</t_lemma>
<functor>CM</functor>
<deepord>18</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w25">
<a>
<lex.rf>a#a-ln95048-055-p2s2w25</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přitahovat</t_lemma>
<functor>CAUS</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<val_frame.rf>v#v41izzA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s2w24">
<a>
<lex.rf>a#a-ln95048-055-p2s2w24</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>logicky</t_lemma>
<functor>ATT</functor>
<tfa>t</tfa>
<deepord>19</deepord>
</LM>
<LM id="t-ln95048-055-p2s2a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s2w29">
<a>
<lex.rf>a#a-ln95048-055-p2s2w29</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w28</LM>
</aux.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>druhý</t_lemma>
<functor>CM</functor>
<deepord>23</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w37">
<a>
<lex.rf>a#a-ln95048-055-p2s2w37</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>35</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s2w22</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95048-055-p2s2w27</LM>
<LM>t-ln95048-055-p2s2w16</LM>
<LM>t-ln95048-055-p2s2w29</LM>
</t-connectors.rf>
</LM>
</discourse>
<children>
<LM id="t-ln95048-055-p2s2w30">
<a>
<lex.rf>a#a-ln95048-055-p2s2w30</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nabízet</t_lemma>
<functor>CAUS</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
<val_frame.rf>v#v41clwA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s2a7">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>24</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p2s2a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95048-055-p2s2a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>25</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w35">
<a>
<lex.rf>a#a-ln95048-055-p2s2w35</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>30</deepord>
<children>
<LM id="t-ln95048-055-p2s2a6">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>27</deepord>
</LM>
<LM id="t-ln95048-055-p2s2a5">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>28</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w34">
<a>
<lex.rf>a#a-ln95048-055-p2s2w34</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řešení</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>29</deepord>
<val_frame.rf>v#v41kdvA</val_frame.rf>
</LM>
<LM id="t-ln95048-055-p2s2w36">
<a>
<lex.rf>a#a-ln95048-055-p2s2w36</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vysvětlení</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>31</deepord>
<val_frame.rf>v#v41ozoA</val_frame.rf>
</LM>
<LM id="t-ln95048-055-p2s2w32">
<a>
<lex.rf>a#a-ln95048-055-p2s2w32</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>33</deepord>
<children>
<LM id="t-ln95048-055-p2s2w31">
<a>
<lex.rf>a#a-ln95048-055-p2s2w31</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rychlý</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>32</deepord>
</LM>
<LM id="t-ln95048-055-p2s2w33">
<a>
<lex.rf>a#a-ln95048-055-p2s2w33</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snadný</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>34</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s2w41">
<a>
<lex.rf>a#a-ln95048-055-p2s2w41</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s2w39</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>líbit_se</t_lemma>
<functor>CAUS</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>37</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s2w30</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95048-055-p2s2w38</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41calA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s2w38">
<a>
<lex.rf>a#a-ln95048-055-p2s2w38</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>PAT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>36</deepord>
<coref_gram.rf>
<LM>t-ln95048-055-p2s2w30</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95048-055-p2s2w42">
<a>
<lex.rf>a#a-ln95048-055-p2s2w42</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>nr</gender>
<number>pl</number>
</gram>
<tfa>t</tfa>
<deepord>38</deepord>
<children>
<LM id="t-ln95048-055-p2s2w46">
<a>
<lex.rf>a#a-ln95048-055-p2s2w46</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>myslit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>40</deepord>
<val_frame.rf>v#v41cklE</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s2w44">
<a>
<lex.rf>a#a-ln95048-055-p2s2w44</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>39</deepord>
<coref_gram.rf>
<LM>t-ln95048-055-p2s2w42</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95048-055-p2s2w45">
<a>
<lex.rf>a#a-ln95048-055-p2s2w45</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rád</t_lemma>
<functor>COMPL</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>41</deepord>
<compl.rf>
<LM>t-ln95048-055-p2s2w44</LM>
</compl.rf>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s2w40">
<a>
<lex.rf>a#a-ln95048-055-p2s2w40</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hrozně</t_lemma>
<functor>MANN</functor>
<proto_lemma>hrozný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>42</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s3">
<atree.rf>a#a-ln95048-055-p2s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95048-055-p2s3w3">
<a>
<lex.rf>a#a-ln95048-055-p2s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chápat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s2a8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>confr</discourse_type>
<sense_PDTB3>Comparison.Contrast</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95048-055-p2s3w2</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41bamD</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s3w2">
<a>
<lex.rf>a#a-ln95048-055-p2s3w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>ale</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95048-055-p2s3w1">
<a>
<lex.rf>a#a-ln95048-055-p2s3w1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>co</t_lemma>
<functor>INTF</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95048-055-p2s3a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p2s2a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95048-055-p2s3a1">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95048-055-p2s3w14">
<a>
<lex.rf>a#a-ln95048-055-p2s3w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>13</deepord>
<children>
<LM id="t-ln95048-055-p2s3w10">
<a>
<lex.rf>a#a-ln95048-055-p2s3w10</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>7</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95048-055-p2s2a7</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<children>
<LM id="t-ln95048-055-p2s3w9">
<a>
<lex.rf>a#a-ln95048-055-p2s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>věda</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln95048-055-p2s3w11">
<a>
<lex.rf>a#a-ln95048-055-p2s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osvěta</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s3w8">
<a>
<lex.rf>a#a-ln95048-055-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s3w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doba</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p2s2w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95048-055-p2s3w7">
<a>
<lex.rf>a#a-ln95048-055-p2s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s3w12">
<a>
<lex.rf>a#a-ln95048-055-p2s3w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyklidit</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41ofbB</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s3w13">
<a>
<lex.rf>a#a-ln95048-055-p2s3w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pole</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s3w15">
<a>
<lex.rf>a#a-ln95048-055-p2s3w15</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>přesněji</t_lemma>
<functor>CM</functor>
<deepord>14</deepord>
</LM>
<LM id="t-ln95048-055-p2s3w21">
<a>
<lex.rf>a#a-ln95048-055-p2s3w21</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>20</deepord>
<children>
<LM id="t-ln95048-055-p2s3w16">
<a>
<lex.rf>a#a-ln95048-055-p2s3w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyklidit</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s3w12</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>corr</discourse_type>
<sense_PDTB3>Expansion.Substitution.Arg2-as-subst</sense_PDTB3>
<src>pdit20</src>
<t-connectors.rf>
<LM>t-ln95048-055-p2s3w15</LM>
</t-connectors.rf>
<is_secondary>1</is_secondary>
</LM>
</discourse>
<val_frame.rf>v#v41ofbB</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s3w17">
<a>
<lex.rf>a#a-ln95048-055-p2s3w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stránka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln95048-055-p2s3w19">
<a>
<lex.rf>a#a-ln95048-055-p2s3w19</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>18</deepord>
<children>
<LM id="t-ln95048-055-p2s3w18">
<a>
<lex.rf>a#a-ln95048-055-p2s3w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>noviny</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-ln95048-055-p2s3w20">
<a>
<lex.rf>a#a-ln95048-055-p2s3w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>časopis</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s3w22">
<a>
<lex.rf>a#a-ln95048-055-p2s3w22</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s3w23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stáhnout_se</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s3w16</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95048-055-p2s3w21</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41lhkA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s3a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR1</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>21</deepord>
</LM>
<LM id="t-ln95048-055-p2s3w25">
<a>
<lex.rf>a#a-ln95048-055-p2s3w25</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s3w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ústraní</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s3w5">
<a>
<lex.rf>a#a-ln95048-055-p2s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>proč</t_lemma>
<functor>CAUS</functor>
<proto_lemma>proč</proto_lemma>
<gram>
<sempos>adv.pron.indef</sempos>
<indeftype>inter</indeftype>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s4">
<atree.rf>a#a-ln95048-055-p2s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95048-055-p2s4w2">
<a>
<lex.rf>a#a-ln95048-055-p2s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p3s1w7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Result</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95048-055-p3s1w1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s4w1">
<a>
<lex.rf>a#a-ln95048-055-p2s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p2s3w14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95048-055-p2s4w4">
<a>
<lex.rf>a#a-ln95048-055-p2s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zhoubný</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95048-055-p2s4w3">
<a>
<lex.rf>a#a-ln95048-055-p2s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společensky</t_lemma>
<functor>REG</functor>
<proto_lemma>společenský</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s4w26">
<a>
<lex.rf>a#a-ln95048-055-p2s4w26</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s4w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>začít</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p2s4w2</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Reason</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-ln95048-055-p2s4w6</LM>
</a-connectors.rf>
</LM>
<LM>
<target_node.rf>t-ln95048-055-p2s4w31</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>preced</discourse_type>
<sense_PDTB3>Temporal.Asynchronous.Precedence</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-ln95048-055-p2s4w29</LM>
</a-connectors.rf>
<t-connectors.rf>
<LM>t-ln95048-055-p2s4w30</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41prbA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s4w9">
<a>
<lex.rf>a#a-ln95048-055-p2s4w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtenář</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95048-055-p2s4w7">
<a>
<lex.rf>a#a-ln95048-055-p2s4w7</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w8">
<a>
<lex.rf>a#a-ln95048-055-p2s4w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soudný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w10">
<a>
<lex.rf>a#a-ln95048-055-p2s4w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zasypávaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95048-055-p2s4w11">
<a>
<lex.rf>a#a-ln95048-055-p2s4w11</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>jen</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w13">
<a>
<lex.rf>a#a-ln95048-055-p2s4w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zpráva</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln95048-055-p2s4w16">
<a>
<lex.rf>a#a-ln95048-055-p2s4w16</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln95048-055-p2s4w15">
<a>
<lex.rf>a#a-ln95048-055-p2s4w15</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s4w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>záhada</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w18">
<a>
<lex.rf>a#a-ln95048-055-p2s4w18</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s4w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jev</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95048-055-p2s4w17">
<a>
<lex.rf>a#a-ln95048-055-p2s4w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vysvětlitelný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s4w12">
<a>
<lex.rf>a#a-ln95048-055-p2s4w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>senzační</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s4w20">
<a>
<lex.rf>a#a-ln95048-055-p2s4w20</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s4w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>možnost</t_lemma>
<functor>ACMP</functor>
<subfunctor>wout</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln95048-055-p2s4a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w21">
<a>
<lex.rf>a#a-ln95048-055-p2s4w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přečíst</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<val_frame.rf>v#v41huvB</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s4a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>18</deepord>
<coref_gram.rf>
<LM>t-ln95048-055-p2s4a1</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95048-055-p2s4w22">
<a>
<lex.rf>a#a-ln95048-055-p2s4w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<coref_gram.rf>
<LM>t-ln95048-055-p2s4a2</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95048-055-p2s4w24">
<a>
<lex.rf>a#a-ln95048-055-p2s4w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vysvětlení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<val_frame.rf>v#v41ozoA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s4a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>21</deepord>
</LM>
<LM id="t-ln95048-055-p2s4a5">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>22</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w23">
<a>
<lex.rf>a#a-ln95048-055-p2s4w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vědecký</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s4w25">
<a>
<lex.rf>a#a-ln95048-055-p2s4w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čas</t_lemma>
<functor>TWHEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>25</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w27">
<a>
<lex.rf>a#a-ln95048-055-p2s4w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pochybovat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>t</tfa>
<deepord>29</deepord>
<val_frame.rf>v#v41fzeA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s4a6">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>27</deepord>
<coref_gram.rf>
<LM>t-ln95048-055-p2s4w9</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95048-055-p2s4a7">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>28</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w31">
<a>
<lex.rf>a#a-ln95048-055-p2s4w31</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s4w29</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvěřit</t_lemma>
<functor>THL</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>32</deepord>
<val_frame.rf>v#v41ndiB</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s4w30">
<a>
<lex.rf>a#a-ln95048-055-p2s4w30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nakonec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>30</deepord>
</LM>
<LM id="t-ln95048-055-p2s4a8">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>31</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p2s4a6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95048-055-p2s4w40">
<a>
<lex.rf>a#a-ln95048-055-p2s4w40</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p2s4w33</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fungovat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>38</deepord>
<val_frame.rf>v#v41asiB</val_frame.rf>
<children>
<LM id="t-ln95048-055-p2s4w35">
<a>
<lex.rf>a#a-ln95048-055-p2s4w35</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>35</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95048-055-p2s2w6</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln95048-055-p2s4w34">
<a>
<lex.rf>a#a-ln95048-055-p2s4w34</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>parapsychologie</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>33</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w36">
<a>
<lex.rf>a#a-ln95048-055-p2s4w36</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>biotronika</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>34</deepord>
</LM>
<LM id="t-ln95048-055-p2s4w37">
<a>
<lex.rf>a#a-ln95048-055-p2s4w37</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>apod</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>adv.denot.grad.neg</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>36</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p2s4w39">
<a>
<lex.rf>a#a-ln95048-055-p2s4w39</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>opravdu</t_lemma>
<functor>ATT</functor>
<tfa>t</tfa>
<deepord>37</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p3s1">
<atree.rf>a#a-ln95048-055-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95048-055-l1A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95048-055-p3s1w19</LM>
<LM>t-ln95048-055-p3s1w20</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95048-055-p3s1w7">
<a>
<lex.rf>a#a-ln95048-055-p3s1w7</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln95048-055-p3s1w1">
<a>
<lex.rf>a#a-ln95048-055-p3s1w1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>proto</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95048-055-p3s1w2">
<a>
<lex.rf>a#a-ln95048-055-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95048-055-p3s1w4">
<a>
<lex.rf>a#a-ln95048-055-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>důležitý</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95048-055-p3s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>BEN</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95048-055-p3s1w3">
<a>
<lex.rf>a#a-ln95048-055-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tak</t_lemma>
<functor>EXT</functor>
<proto_lemma>tak</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p3s1w5">
<a>
<lex.rf>a#a-ln95048-055-p3s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>působit</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41jebE</val_frame.rf>
<children>
<LM id="t-ln95048-055-p3s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_gram.rf>
<LM>t-ln95048-055-p3s1a0</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95048-055-p3s1a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95048-055-p3s1w6">
<a>
<lex.rf>a#a-ln95048-055-p3s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osvěta</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p2s3w11</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95048-055-p3s1w8">
<a>
<lex.rf>a#a-ln95048-055-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95048-055-p3s1w2</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95048-055-p3s1w7</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95048-055-p3s1a2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p2s3a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95048-055-p3s1w10">
<a>
<lex.rf>a#a-ln95048-055-p3s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rád</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95048-055-p3s1w9">
<a>
<lex.rf>a#a-ln95048-055-p3s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hrozně</t_lemma>
<functor>MANN</functor>
<proto_lemma>hrozný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95048-055-p3s1w16">
<a>
<lex.rf>a#a-ln95048-055-p3s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p3s1w13</LM>
<LM>a#a-ln95048-055-p3s1w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>začít</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41prbA</val_frame.rf>
<children>
<LM id="t-ln95048-055-p3s1w15">
<a>
<lex.rf>a#a-ln95048-055-p3s1w15</lex.rf>
<aux.rf>
<LM>a#a-ln95048-055-p3s1w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>PAT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p3s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95048-055-p3s1a3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>2</person>
<politeness>polite</politeness>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln95048-055-p3s1w20">
<a>
<lex.rf>a#a-ln95048-055-p3s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>noviny</t_lemma>
<functor>VOCAT</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95048-055-p3s1a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95048-055-p3s1w19">
<a>
<lex.rf>a#a-ln95048-055-p3s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lidový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
<LM id="t-ln95048-055-p3s1w18">
<a>
<lex.rf>a#a-ln95048-055-p3s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
