<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln95045_023.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>overview</genre>
</meta>
<trees>
<LM id="t-ln95045-023-p1s1">
<atree.rf>a#a-ln95045-023-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95045-023-p1s1w3">
<a>
<lex.rf>a#a-ln95045-023-p1s1w3</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p1s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přijít_si</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41ishB</val_frame.rf>
<children>
<LM id="t-ln95045-023-p1s1w1">
<a>
<lex.rf>a#a-ln95045-023-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lodník</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95045-023-p1s1w6">
<a>
<lex.rf>a#a-ln95045-023-p1s1w6</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p1s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>peníze</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95045-023-p1s1w5">
<a>
<lex.rf>a#a-ln95045-023-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>pos</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95045-023-p1s1a0">
<a>
<lex.rf>a#a-ln95045-023-p1s1w3</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p1s1w2</LM>
<LM>a#a-ln95045-023-p1s1w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>přijít_si</t_lemma>
<functor>CPR</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41ishB</val_frame.rf>
<children>
<LM id="t-ln95045-023-p1s1a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inan</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p1s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p1s1w8">
<a>
<lex.rf>a#a-ln95045-023-p1s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>železničář</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p2s1A">
<atree.rf>a#a-ln95045-023-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95045-023-p2s1Aw1">
<a>
<lex.rf>a#a-ln95045-023-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p2s1B">
<atree.rf>a#a-ln95045-023-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l1A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-023-p2s1Bw16</LM>
<LM>t-ln95045-023-p2s1Bw17</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l2A">
<basic-form>měsíční mzda</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p2s1Bw2</LM>
<LM>t-ln95045-023-p2s1Bw3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p2s1Bw6">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosáhnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41afbA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p2s1Bw3">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mzda</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95045-023-p2s1Bw2">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95045-023-p2s1Bw1">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průměrný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95045-023-p2s1Bw5">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw5</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p2s1Bw4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doprava</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p2s1Bw7">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln95045-023-p2s1Bw9">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw9</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p2s1Bw8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prosinec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln95045-023-p2s1Bw12">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw12</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln95045-023-p2s1Bw11">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95045-023-p2s1Bw10">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7777</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p2s1Bw14">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95045-023-p2s1Bw13">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>ACT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_gram.rf>
<LM>t-ln95045-023-p2s1Bw11</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95045-023-p2s1Bw18">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95045-023-p2s1Ba0">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw14</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p2s1Bw19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>být</t_lemma>
<functor>CPR</functor>
<proto_lemma>být</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln95045-023-p2s1Ba1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p2s1Bw13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p2s1Ba2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Some</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln95045-023-p2s1Bw22">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>brzy</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.grad.nneg</sempos>
<degcmp>comp</degcmp>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p2s1Bw7</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<children>
<LM id="t-ln95045-023-p2s1Bw21">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw21</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p2s1Bw20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p2s1Bw17">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw17</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p2s1Bw15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln95045-023-p2s1Bw16">
<a>
<lex.rf>a#a-ln95045-023-p2s1Bw16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>19.1</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p2s2">
<atree.rf>a#a-ln95045-023-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l4A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95045-023-p2s2w3</LM>
<LM>t-ln95045-023-p2s2w4</LM>
<LM>t-ln95045-023-p2s2w5</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p2s2w1">
<a>
<lex.rf>a#a-ln95045-023-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p2s2w2">
<a>
<lex.rf>a#a-ln95045-023-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>EFF</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p2s1Bw12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p2s2w5">
<a>
<lex.rf>a#a-ln95045-023-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úřad</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95045-023-p2s2w4">
<a>
<lex.rf>a#a-ln95045-023-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>statistický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95045-023-p2s2w3">
<a>
<lex.rf>a#a-ln95045-023-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p2s1Aw1</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s1">
<atree.rf>a#a-ln95045-023-p3s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln95045-023-p3s1w11">
<a>
<lex.rf>a#a-ln95045-023-p3s1w11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>9</deepord>
<children>
<LM id="t-ln95045-023-p3s1w3">
<a>
<lex.rf>a#a-ln95045-023-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vydělat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41nxgA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p3s1w1">
<a>
<lex.rf>a#a-ln95045-023-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>sup</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95045-023-p3s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95045-023-p3s1w2">
<a>
<lex.rf>a#a-ln95045-023-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>BEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_gram.rf>
<LM>t-ln95045-023-p3s1w4</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95045-023-p3s1w4">
<a>
<lex.rf>a#a-ln95045-023-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lodník</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p3s1w6">
<a>
<lex.rf>a#a-ln95045-023-p3s1w6</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p3s1w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řeka</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s1w9">
<a>
<lex.rf>a#a-ln95045-023-p3s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95045-023-p3s1w8">
<a>
<lex.rf>a#a-ln95045-023-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>8504</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s1w20">
<a>
<lex.rf>a#a-ln95045-023-p3s1w20</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>15</deepord>
<children>
<LM id="t-ln95045-023-p3s1w14">
<a>
<lex.rf>a#a-ln95045-023-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>následovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41dboB</val_frame.rf>
<children>
<LM id="t-ln95045-023-p3s1w13">
<a>
<lex.rf>a#a-ln95045-023-p3s1w13</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p3s1w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>TWHEN</functor>
<subfunctor>after</subfunctor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p3s1w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p3s1w15">
<a>
<lex.rf>a#a-ln95045-023-p3s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>železničář</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p1s1w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p3s1w18">
<a>
<lex.rf>a#a-ln95045-023-p3s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95045-023-p3s1w17">
<a>
<lex.rf>a#a-ln95045-023-p3s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7973</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s1a0">
<a>
<lex.rf>a#a-ln95045-023-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>následovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95045-023-p3s1w14</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95045-023-p3s1w20</LM>
<LM>t-ln95045-023-p3s1w21</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41dboC</val_frame.rf>
<children>
<LM id="t-ln95045-023-p3s1w21">
<a>
<lex.rf>a#a-ln95045-023-p3s1w21</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>dále</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln95045-023-p3s1w22">
<a>
<lex.rf>a#a-ln95045-023-p3s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>člověk</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln95045-023-p3s1w25">
<a>
<lex.rf>a#a-ln95045-023-p3s1w25</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p3s1w23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČSAD</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln95045-023-p3s1w24">
<a>
<lex.rf>a#a-ln95045-023-p3s1w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>silniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s1w28">
<a>
<lex.rf>a#a-ln95045-023-p3s1w28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>21</deepord>
<children>
<LM id="t-ln95045-023-p3s1w27">
<a>
<lex.rf>a#a-ln95045-023-p3s1w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7277</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s2">
<atree.rf>a#a-ln95045-023-p3s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l6A">
<basic-form>soukromý sektor</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p3s2w3</LM>
<LM>t-ln95045-023-p3s2w4</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l7A">
<basic-form>státní podnik</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p3s2w20</LM>
<LM>t-ln95045-023-p3s2w21</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p3s2w5">
<a>
<lex.rf>a#a-ln95045-023-p3s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>brát</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41hsD</val_frame.rf>
<children>
<LM id="t-ln95045-023-p3s2w1">
<a>
<lex.rf>a#a-ln95045-023-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dopravák</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95045-023-p3s2w4">
<a>
<lex.rf>a#a-ln95045-023-p3s2w4</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p3s2w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sektor</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95045-023-p3s2w3">
<a>
<lex.rf>a#a-ln95045-023-p3s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soukromý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s2w7">
<a>
<lex.rf>a#a-ln95045-023-p3s2w7</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p3s2w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průměr</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln95045-023-p3s2a3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpNoun</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>nr</gender>
<number>nr</number>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95045-023-p3s2w11">
<a>
<lex.rf>a#a-ln95045-023-p3s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95045-023-p3s2w9">
<a>
<lex.rf>a#a-ln95045-023-p3s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p3s2w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>něco</t_lemma>
<functor>DIFF</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>neut</gender>
<number>sg</number>
<indeftype>indef1</indeftype>
<person>3</person>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95045-023-p3s2w10">
<a>
<lex.rf>a#a-ln95045-023-p3s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>málo</t_lemma>
<functor>RSTR</functor>
<proto_lemma>málo</proto_lemma>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>pos</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s2w14">
<a>
<lex.rf>a#a-ln95045-023-p3s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln95045-023-p3s2w13">
<a>
<lex.rf>a#a-ln95045-023-p3s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7344</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s2a0">
<a>
<lex.rf>a#a-ln95045-023-p3s2w5</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p3s2w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>brát</t_lemma>
<functor>CPR</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41hsD</val_frame.rf>
<children>
<LM id="t-ln95045-023-p3s2a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln95045-023-p3s2w18">
<a>
<lex.rf>a#a-ln95045-023-p3s2w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kolega</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln95045-023-p3s2w17">
<a>
<lex.rf>a#a-ln95045-023-p3s2w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p3s2w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p3s2w21">
<a>
<lex.rf>a#a-ln95045-023-p3s2w21</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p3s2w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln95045-023-p3s2w20">
<a>
<lex.rf>a#a-ln95045-023-p3s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>státní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p3s2w24">
<a>
<lex.rf>a#a-ln95045-023-p3s2w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln95045-023-p3s2w23">
<a>
<lex.rf>a#a-ln95045-023-p3s2w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7296</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p4s1">
<atree.rf>a#a-ln95045-023-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l3A">
<basic-form>měsíční mzda</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p4s1w4</LM>
<LM>t-ln95045-023-p4s1w5</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p4s1w14">
<a>
<lex.rf>a#a-ln95045-023-p4s1w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln95045-023-p4s1w5">
<a>
<lex.rf>a#a-ln95045-023-p4s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mzda</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95045-023-p4s1w2">
<a>
<lex.rf>a#a-ln95045-023-p4s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sledovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln95045-023-p4s1w1">
<a>
<lex.rf>a#a-ln95045-023-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>statisticky</t_lemma>
<functor>MANN</functor>
<proto_lemma>statistický</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p4s1w3">
<a>
<lex.rf>a#a-ln95045-023-p4s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průměrný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95045-023-p4s1w4">
<a>
<lex.rf>a#a-ln95045-023-p4s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95045-023-p4s1w7">
<a>
<lex.rf>a#a-ln95045-023-p4s1w7</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průmysl</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p4s1w8">
<a>
<lex.rf>a#a-ln95045-023-p4s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>činit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41noG</val_frame.rf>
<children>
<LM id="t-ln95045-023-p4s1w9">
<a>
<lex.rf>a#a-ln95045-023-p4s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p2s1Bw7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p4s1w11">
<a>
<lex.rf>a#a-ln95045-023-p4s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prosinec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln95045-023-p4s1w13">
<a>
<lex.rf>a#a-ln95045-023-p4s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln95045-023-p4s1w12">
<a>
<lex.rf>a#a-ln95045-023-p4s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7781</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p4s1a0">
<a>
<lex.rf>a#a-ln95045-023-p4s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>činit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95045-023-p4s1w8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95045-023-p4s1w14</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41noG</val_frame.rf>
<children>
<LM id="t-ln95045-023-p4s1w16">
<a>
<lex.rf>a#a-ln95045-023-p4s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s1w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stavebnictví</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln95045-023-p4s1w18">
<a>
<lex.rf>a#a-ln95045-023-p4s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kč</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln95045-023-p4s1w17">
<a>
<lex.rf>a#a-ln95045-023-p4s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>8925</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p4s2">
<atree.rf>a#a-ln95045-023-p4s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l8A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-023-p4s2w9</LM>
<LM>t-ln95045-023-p4s2w10</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l9A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-023-p4s2w15</LM>
<LM>t-ln95045-023-p4s2w16</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l10B">
<basic-form>meziroční růst</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p4s2w6</LM>
<LM>t-ln95045-023-p4s2w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p4s2w11">
<a>
<lex.rf>a#a-ln95045-023-p4s2w11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="t-ln95045-023-p4s2w4">
<a>
<lex.rf>a#a-ln95045-023-p4s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jít</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41bikAV</val_frame.rf>
<children>
<LM id="t-ln95045-023-p4s2w3">
<a>
<lex.rf>a#a-ln95045-023-p4s2w3</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>případ</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p4s1w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p4s2w2">
<a>
<lex.rf>a#a-ln95045-023-p4s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p4s2w7">
<a>
<lex.rf>a#a-ln95045-023-p4s2w7</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s2w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nárůst</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95045-023-p4s2w6">
<a>
<lex.rf>a#a-ln95045-023-p4s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>meziroční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln95045-023-p4s2w10">
<a>
<lex.rf>a#a-ln95045-023-p4s2w10</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s2w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95045-023-p4s2w9">
<a>
<lex.rf>a#a-ln95045-023-p4s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>16.5</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p4s2a1">
<a>
<lex.rf>a#a-ln95045-023-p4s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>jít</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95045-023-p4s2w4</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95045-023-p4s2w11</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41bikAV</val_frame.rf>
<children>
<LM id="t-ln95045-023-p4s2a0">
<a>
<lex.rf>a#a-ln95045-023-p4s2w3</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s2w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>případ</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p4s1w16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p4s2w13">
<a>
<lex.rf>a#a-ln95045-023-p4s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>druhý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>dva</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>c</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p4s2a2">
<a>
<lex.rf>a#a-ln95045-023-p4s2w7</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s2w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>nárůst</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln95045-023-p4s2w16">
<a>
<lex.rf>a#a-ln95045-023-p4s2w16</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p4s2w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95045-023-p4s2w15">
<a>
<lex.rf>a#a-ln95045-023-p4s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>15.8</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s1">
<atree.rf>a#a-ln95045-023-p5s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l11B">
<basic-form>tuna krát kilometr</basic-form>
<type>object</type>
<tnode.rfs>
<LM>t-ln95045-023-p5s1w15</LM>
<LM>t-ln95045-023-p5s1w16</LM>
<LM>t-ln95045-023-p5s1w17</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p5s1w12">
<a>
<lex.rf>a#a-ln95045-023-p5s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odpovídat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95045-023-p5s4w16</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conc</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit20</src>
<t-connectors.rf>
<LM>t-ln95045-023-p5s4w3</LM>
<LM>t-ln95045-023-p5s4w2</LM>
</t-connectors.rf>
<a-connectors_ext.rf>
<LM>a#a-ln95045-023-p5s4w4</LM>
<LM>a#a-ln95045-023-p5s4w5</LM>
</a-connectors_ext.rf>
<t-connectors_ext.rf>
<LM>t-ln95045-023-p5s4w1</LM>
<LM>t-ln95045-023-p5s4w2</LM>
<LM>t-ln95045-023-p5s4w3</LM>
</t-connectors_ext.rf>
<is_secondary>1</is_secondary>
</LM>
</discourse>
<val_frame.rf>v#v41egyF</val_frame.rf>
<children>
<LM id="t-ln95045-023-p5s1w3">
<a>
<lex.rf>a#a-ln95045-023-p5s1w3</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s1w1</LM>
<LM>a#a-ln95045-023-p5s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zjistit</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41rexB</val_frame.rf>
<children>
<LM id="t-ln95045-023-p5s1a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95045-023-p5s1a2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p5s1w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p5s1w5">
<a>
<lex.rf>a#a-ln95045-023-p5s1w5</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>porovnání</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41gjgA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p5s1a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<is_parenthesis>1</is_parenthesis>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln95045-023-p5s1a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>EFF</functor>
<is_parenthesis>1</is_parenthesis>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-ln95045-023-p5s1w6</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln95045-023-p5s1w6">
<a>
<lex.rf>a#a-ln95045-023-p5s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ukazatel</t_lemma>
<functor>PAT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s1w8">
<a>
<lex.rf>a#a-ln95045-023-p5s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vývoj</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95045-023-p5s1w9">
<a>
<lex.rf>a#a-ln95045-023-p5s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mzda</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p2s1Bw3</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p5s1w11">
<a>
<lex.rf>a#a-ln95045-023-p5s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doprava</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p2s1Bw5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s1a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln95045-023-p5s1w13">
<a>
<lex.rf>a#a-ln95045-023-p5s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výkon</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln95045-023-p5s1w16">
<a>
<lex.rf>a#a-ln95045-023-p5s1w16</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>krát</t_lemma>
<functor>OPER</functor>
<is_parenthesis>1</is_parenthesis>
<deepord>15</deepord>
<children>
<LM id="t-ln95045-023-p5s1w15">
<a>
<lex.rf>a#a-ln95045-023-p5s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tuna</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln95045-023-p5s1w17">
<a>
<lex.rf>a#a-ln95045-023-p5s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kilometr</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s1w20">
<a>
<lex.rf>a#a-ln95045-023-p5s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obor</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p3s1w13</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>t-ln95045-023-p3s1w15</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>t-ln95045-023-p3s1w25</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln95045-023-p5s1w19">
<a>
<lex.rf>a#a-ln95045-023-p5s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednotlivý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s2">
<atree.rf>a#a-ln95045-023-p5s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l10A">
<basic-form>říční doprava</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p5s2w2</LM>
<LM>t-ln95045-023-p5s2w3</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l11A">
<type>time</type>
<tnode.rfs>
<LM>t-ln95045-023-p5s2w6</LM>
<LM>t-ln95045-023-p5s2w7</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l12A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-023-p5s2w16</LM>
<LM>t-ln95045-023-p5s2w17</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l13A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-023-p5s2w22</LM>
<LM>t-ln95045-023-p5s2w23</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p5s2w18">
<a>
<lex.rf>a#a-ln95045-023-p5s2w18</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>11</deepord>
<children>
<LM id="t-ln95045-023-p5s2w9">
<a>
<lex.rf>a#a-ln95045-023-p5s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výkon</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p5s1w13</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-ln95045-023-p5s2w8">
<a>
<lex.rf>a#a-ln95045-023-p5s2w8</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41kxmA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p5s2w3">
<a>
<lex.rf>a#a-ln95045-023-p5s2w3</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doprava</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p3s1w13</target_node.rf>
<type>REST</type>
</LM>
</bridging>
<children>
<LM id="t-ln95045-023-p5s2w2">
<a>
<lex.rf>a#a-ln95045-023-p5s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s2w6">
<a>
<lex.rf>a#a-ln95045-023-p5s2w6</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s2w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p4s1w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p5s2w7">
<a>
<lex.rf>a#a-ln95045-023-p5s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1994</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s2w14">
<a>
<lex.rf>a#a-ln95045-023-p5s2w14</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s2w11</LM>
<LM>a#a-ln95045-023-p5s2w12</LM>
<LM>a#a-ln95045-023-p5s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>CPR</functor>
<subfunctor>wrt</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95045-023-p5s2w13">
<a>
<lex.rf>a#a-ln95045-023-p5s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předchozí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s2w17">
<a>
<lex.rf>a#a-ln95045-023-p5s2w17</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s2w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln95045-023-p5s2w16">
<a>
<lex.rf>a#a-ln95045-023-p5s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>6.1</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s2a0">
<a>
<lex.rf>a#a-ln95045-023-p5s2w8</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>snížit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95045-023-p5s2w8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95045-023-p5s2w18</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41kxmA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p5s2w20">
<a>
<lex.rf>a#a-ln95045-023-p5s2w20</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s2w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>železnice</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>12</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p3s1w15</target_node.rf>
<type>REST</type>
</LM>
</bridging>
</LM>
<LM id="t-ln95045-023-p5s2w23">
<a>
<lex.rf>a#a-ln95045-023-p5s2w23</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s2w21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln95045-023-p5s2w22">
<a>
<lex.rf>a#a-ln95045-023-p5s2w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>4.7</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s3">
<atree.rf>a#a-ln95045-023-p5s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l14A">
<basic-form>silniční doprava</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p5s3w3</LM>
<LM>t-ln95045-023-p5s3w4</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l15A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-023-p5s3w9</LM>
<LM>t-ln95045-023-p5s3w10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p5s3w7">
<a>
<lex.rf>a#a-ln95045-023-p5s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vzrůst</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95045-023-p5s2w18</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>confr</discourse_type>
<sense_PDTB3>Comparison.Contrast</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln95045-023-p5s3w5</LM>
</t-connectors.rf>
</LM>
</discourse>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p5s2w18</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<val_frame.rf>v#v41pnkA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p5s3w5">
<a>
<lex.rf>a#a-ln95045-023-p5s3w5</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>naopak</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95045-023-p5s3w4">
<a>
<lex.rf>a#a-ln95045-023-p5s3w4</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s3w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doprava</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p3s1w25</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p5s3w3">
<a>
<lex.rf>a#a-ln95045-023-p5s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>silniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95045-023-p5s3w2">
<a>
<lex.rf>a#a-ln95045-023-p5s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veřejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s3w6">
<a>
<lex.rf>a#a-ln95045-023-p5s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výkon</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p5s1w13</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-ln95045-023-p5s3w10">
<a>
<lex.rf>a#a-ln95045-023-p5s3w10</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s3w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95045-023-p5s3w9">
<a>
<lex.rf>a#a-ln95045-023-p5s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>30.7</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s4">
<atree.rf>a#a-ln95045-023-p5s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l18B">
<basic-form>růst cen</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p5s4w14</LM>
<LM>t-ln95045-023-p5s4w15</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p5s4w3">
<a>
<lex.rf>a#a-ln95045-023-p5s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znamenat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41rmoB</val_frame.rf>
<children>
<LM id="t-ln95045-023-p5s4w2">
<a>
<lex.rf>a#a-ln95045-023-p5s4w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>ovšem</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln95045-023-p5s4w1">
<a>
<lex.rf>a#a-ln95045-023-p5s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_special>segm</coref_special>
</LM>
<LM id="t-ln95045-023-p5s4a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95045-023-p5s4w16">
<a>
<lex.rf>a#a-ln95045-023-p5s4w16</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s4w8</LM>
<LM>a#a-ln95045-023-p5s4w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvyšovat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41sdlA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p5s4w7">
<a>
<lex.rf>a#a-ln95045-023-p5s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln95045-023-p5s4w6">
<a>
<lex.rf>a#a-ln95045-023-p5s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příslušný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s4w13">
<a>
<lex.rf>a#a-ln95045-023-p5s4w13</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>nebo</t_lemma>
<functor>DISJ</functor>
<deepord>9</deepord>
<children>
<LM id="t-ln95045-023-p5s4w11">
<a>
<lex.rf>a#a-ln95045-023-p5s4w11</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s4w9</LM>
<LM>a#a-ln95045-023-p5s4w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úspora</t_lemma>
<functor>CAUS</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln95045-023-p5s4w12">
<a>
<lex.rf>a#a-ln95045-023-p5s4w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>náklad</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s4w14">
<a>
<lex.rf>a#a-ln95045-023-p5s4w14</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p5s4w9</LM>
<LM>a#a-ln95045-023-p5s4w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>růst</t_lemma>
<functor>CAUS</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln95045-023-p5s4w15">
<a>
<lex.rf>a#a-ln95045-023-p5s4w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cena</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p5s4a1">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln95045-023-p5s4w17">
<a>
<lex.rf>a#a-ln95045-023-p5s4w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mzda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p5s1w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p5s4w19">
<a>
<lex.rf>a#a-ln95045-023-p5s4w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovník</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p3s2w17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p5s4w18">
<a>
<lex.rf>a#a-ln95045-023-p5s4w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_gram.rf>
<LM>t-ln95045-023-p5s4w7</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s1">
<atree.rf>a#a-ln95045-023-p6s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l5A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln95045-023-p6s1w12</LM>
<LM>t-ln95045-023-p6s1w13</LM>
<LM>t-ln95045-023-p6s1w14</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l16A">
<basic-form>malý podnik</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p6s1w5</LM>
<LM>t-ln95045-023-p6s1w6</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l17A">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-023-p6s1w18</LM>
<LM>t-ln95045-023-p6s1w19</LM>
</tnode.rfs>
</LM>
<LM id="s-ln95045-023-l21B">
<basic-form>průmyslová produkce</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln95045-023-p6s1w2</LM>
<LM>t-ln95045-023-p6s1w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p6s1w16">
<a>
<lex.rf>a#a-ln95045-023-p6s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41sdjA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p6s1w3">
<a>
<lex.rf>a#a-ln95045-023-p6s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produkce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln95045-023-p6s1w2">
<a>
<lex.rf>a#a-ln95045-023-p6s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průmyslový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln95045-023-p6s1w1">
<a>
<lex.rf>a#a-ln95045-023-p6s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celkový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln95045-023-p6s1w7">
<a>
<lex.rf>a#a-ln95045-023-p6s1w7</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>6</deepord>
<children>
<LM id="t-ln95045-023-p6s1w6">
<a>
<lex.rf>a#a-ln95045-023-p6s1w6</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>ACMP</functor>
<subfunctor>incl</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln95045-023-p6s1w5">
<a>
<lex.rf>a#a-ln95045-023-p6s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>malý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s1w8">
<a>
<lex.rf>a#a-ln95045-023-p6s1w8</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>živnostník</t_lemma>
<functor>ACMP</functor>
<subfunctor>incl</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s1w11">
<a>
<lex.rf>a#a-ln95045-023-p6s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odhad</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln95045-023-p6s1w14">
<a>
<lex.rf>a#a-ln95045-023-p6s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úřad</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p2s2w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln95045-023-p6s1w12">
<a>
<lex.rf>a#a-ln95045-023-p6s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p2s2w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p6s1w13">
<a>
<lex.rf>a#a-ln95045-023-p6s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>statistický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s1w15">
<a>
<lex.rf>a#a-ln95045-023-p6s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p5s2w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p6s1w19">
<a>
<lex.rf>a#a-ln95045-023-p6s1w19</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln95045-023-p6s1w18">
<a>
<lex.rf>a#a-ln95045-023-p6s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.3</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s1w29">
<a>
<lex.rf>a#a-ln95045-023-p6s1w29</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stagnovat</t_lemma>
<functor>CONTRD</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<discourse>
<LM>
<target_node.rf>t-ln95045-023-p6s1w16</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>confr</discourse_type>
<sense_PDTB3>Comparison.Contrast</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-ln95045-023-p6s1w21</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41lhiA</val_frame.rf>
<children>
<LM id="t-ln95045-023-p6s1a0">
<a>
<lex.rf>a#a-ln95045-023-p6s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>produkce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>22</deepord>
<children>
<LM id="t-ln95045-023-p6s1w23">
<a>
<lex.rf>a#a-ln95045-023-p6s1w23</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w22</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>16</deepord>
<bridging>
<LM>
<target_node.rf>t-ln95045-023-p6s1w7</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<children>
<LM id="t-ln95045-023-p6s1w26">
<a>
<lex.rf>a#a-ln95045-023-p6s1w26</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>19</deepord>
<children>
<LM id="t-ln95045-023-p6s1a1">
<a>
<lex.rf>a#a-ln95045-023-p6s1w28</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>zaměstnanec</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-ln95045-023-p6s1w25">
<a>
<lex.rf>a#a-ln95045-023-p6s1w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>25</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s1w28">
<a>
<lex.rf>a#a-ln95045-023-p6s1w28</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s1w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaměstnanec</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>20</deepord>
<children>
<LM id="t-ln95045-023-p6s1w27">
<a>
<lex.rf>a#a-ln95045-023-p6s1w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s2">
<atree.rf>a#a-ln95045-023-p6s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln95045-023-l20B">
<type>number</type>
<tnode.rfs>
<LM>t-ln95045-023-p6s2w6</LM>
<LM>t-ln95045-023-p6s2w7</LM>
<LM>t-ln95045-023-p6s2w8</LM>
<LM>t-ln95045-023-p6s2w9</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln95045-023-p6s2w3">
<a>
<lex.rf>a#a-ln95045-023-p6s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>činit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41noG</val_frame.rf>
<children>
<LM id="t-ln95045-023-p6s2w2">
<a>
<lex.rf>a#a-ln95045-023-p6s2w2</lex.rf>
<aux.rf>
<LM>a#a-ln95045-023-p6s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stavebnictví</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln95045-023-p4s2a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln95045-023-p6s2w5">
<a>
<lex.rf>a#a-ln95045-023-p6s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ukazatel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln95045-023-p6s2w4">
<a>
<lex.rf>a#a-ln95045-023-p6s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obdobný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s2w7">
<a>
<lex.rf>a#a-ln95045-023-p6s2w7</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>7</deepord>
<children>
<LM id="t-ln95045-023-p6s2a0">
<a>
<lex.rf>a#a-ln95045-023-p6s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>procento</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln95045-023-p6s2w6">
<a>
<lex.rf>a#a-ln95045-023-p6s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7.5</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln95045-023-p6s2w9">
<a>
<lex.rf>a#a-ln95045-023-p6s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln95045-023-p6s2w8">
<a>
<lex.rf>a#a-ln95045-023-p6s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>6</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
