<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf920925_079.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-mf920925-079-p1s1">
<atree.rf>a#a-mf920925-079-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920925-079-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<tfa>t</tfa>
<deepord>2</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-mf920925-079-p1s1w1">
<a>
<lex.rf>a#a-mf920925-079-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>památka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920925-079-p1s1w4">
<a>
<lex.rf>a#a-mf920925-079-p1s1w4</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p1s1w3</LM>
<LM>a#a-mf920925-079-p1s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zloděj</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s1">
<atree.rf>a#a-mf920925-079-p2s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920925-079-p2s1w1">
<a>
<lex.rf>a#a-mf920925-079-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Klatovy</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920925-079-p2s1w3">
<a>
<lex.rf>a#a-mf920925-079-p2s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hč</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>nr</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s2">
<atree.rf>a#a-mf920925-079-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920925-079-l9A">
<type>number</type>
<tnode.rfs>
<LM>t-mf920925-079-p2s2w5</LM>
<LM>t-mf920925-079-p2s2w6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920925-079-p2s2w10">
<a>
<lex.rf>a#a-mf920925-079-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>způsobit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41rvuB</val_frame.rf>
<children>
<LM id="t-mf920925-079-p2s2w1">
<a>
<lex.rf>a#a-mf920925-079-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>škoda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920925-079-p2s2w3">
<a>
<lex.rf>a#a-mf920925-079-p2s2w3</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p2s2w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf920925-079-p2s2w6">
<a>
<lex.rf>a#a-mf920925-079-p2s2w6</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p2s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>CPR</functor>
<subfunctor>than</subfunctor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf920925-079-p2s2w7">
<a>
<lex.rf>a#a-mf920925-079-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920925-079-p2s2w5">
<a>
<lex.rf>a#a-mf920925-079-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.2</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s2w8">
<a>
<lex.rf>a#a-mf920925-079-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>už</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf920925-079-p2s2w9">
<a>
<lex.rf>a#a-mf920925-079-p2s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>letos</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf920925-079-p2s2w13">
<a>
<lex.rf>a#a-mf920925-079-p2s2w13</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p2s2w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>památka</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920925-079-p1s1w1</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf920925-079-p2s2w12">
<a>
<lex.rf>a#a-mf920925-079-p2s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>církevní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s2w14">
<a>
<lex.rf>a#a-mf920925-079-p2s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zloděj</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920925-079-p1s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920925-079-p2s2w17">
<a>
<lex.rf>a#a-mf920925-079-p2s2w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vykrást</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41ogmA</val_frame.rf>
<children>
<LM id="t-mf920925-079-p2s2w16">
<a>
<lex.rf>a#a-mf920925-079-p2s2w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_gram.rf>
<LM>t-mf920925-079-p2s2w14</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf920925-079-p2s2w20">
<a>
<lex.rf>a#a-mf920925-079-p2s2w20</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>15</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920925-079-p2s2w13</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf920925-079-p2s2w19">
<a>
<lex.rf>a#a-mf920925-079-p2s2w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kostel</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-mf920925-079-p2s2w21">
<a>
<lex.rf>a#a-mf920925-079-p2s2w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kaple</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-mf920925-079-p2s2w18">
<a>
<lex.rf>a#a-mf920925-079-p2s2w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>63</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-mf920925-079-p2s2w24">
<a>
<lex.rf>a#a-mf920925-079-p2s2w24</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p2s2w22</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Čechy</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920925-079-p2s1w1</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
<children>
<LM id="t-mf920925-079-p2s2w23">
<a>
<lex.rf>a#a-mf920925-079-p2s2w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>západní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s3">
<atree.rf>a#a-mf920925-079-p2s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920925-079-l5A">
<basic-form>Vřeskovice na Klatovsku</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-mf920925-079-p2s3w8</LM>
<LM>t-mf920925-079-p2s3w10</LM>
</tnode.rfs>
</LM>
<LM id="s-mf920925-079-l10A">
<basic-form>kostelík sv. Jana Křtitele</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-mf920925-079-p2s3w14</LM>
<LM>t-mf920925-079-p2s3w15</LM>
<LM>t-mf920925-079-p2s3w17</LM>
<LM>t-mf920925-079-p2s3w18</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920925-079-p2s3w6">
<a>
<lex.rf>a#a-mf920925-079-p2s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlásit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41avfC</val_frame.rf>
<children>
<LM id="t-mf920925-079-p2s3w4">
<a>
<lex.rf>a#a-mf920925-079-p2s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>případ</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920925-079-p2s2w17</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf920925-079-p2s3w3">
<a>
<lex.rf>a#a-mf920925-079-p2s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>takový</t_lemma>
<functor>RSTR</functor>
<proto_lemma>takový</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920925-079-p2s3w2">
<a>
<lex.rf>a#a-mf920925-079-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf920925-079-p2s3w1">
<a>
<lex.rf>a#a-mf920925-079-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zatím</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s3w5">
<a>
<lex.rf>a#a-mf920925-079-p2s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>policie</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf920925-079-p2s3w8">
<a>
<lex.rf>a#a-mf920925-079-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p2s3w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Vřeskovice</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf920925-079-p2s3w10">
<a>
<lex.rf>a#a-mf920925-079-p2s3w10</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p2s3w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Klatovsko</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920925-079-p2s2w24</target_node.rf>
<type>WHOLE_PART</type>
</LM>
<LM>
<target_node.rf>t-mf920925-079-p2s1w1</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
<LM id="t-mf920925-079-p2s3w22">
<a>
<lex.rf>a#a-mf920925-079-p2s3w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odnést</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41eeqB</val_frame.rf>
<children>
<LM id="t-mf920925-079-p2s3w14">
<a>
<lex.rf>a#a-mf920925-079-p2s3w14</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p2s3w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kostelík</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>9</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920925-079-p2s2w19</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf920925-079-p2s3w18">
<a>
<lex.rf>a#a-mf920925-079-p2s3w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Křtitel</t_lemma>
<functor>APP</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf920925-079-p2s3w17">
<a>
<lex.rf>a#a-mf920925-079-p2s3w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jan</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf920925-079-p2s3w15">
<a>
<lex.rf>a#a-mf920925-079-p2s3w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svatý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s3w21">
<a>
<lex.rf>a#a-mf920925-079-p2s3w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poberta</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>13</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920925-079-p2s2w16</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf920925-079-p2s3w20">
<a>
<lex.rf>a#a-mf920925-079-p2s3w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>známý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-mf920925-079-p2s3w19">
<a>
<lex.rf>a#a-mf920925-079-p2s3w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosud</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s3w12">
<a>
<lex.rf>a#a-mf920925-079-p2s3w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kde</t_lemma>
<functor>LOC</functor>
<proto_lemma>kde</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.indef</sempos>
<indeftype>relat</indeftype>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_gram.rf>
<LM>t-mf920925-079-p2s3w8</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf920925-079-p2s3w28">
<a>
<lex.rf>a#a-mf920925-079-p2s3w28</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>22</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920925-079-p2s2w13</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf920925-079-p2s3w24">
<a>
<lex.rf>a#a-mf920925-079-p2s3w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>socha</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-mf920925-079-p2s3w25">
<a>
<lex.rf>a#a-mf920925-079-p2s3w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>anděl</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
<LM id="t-mf920925-079-p2s3w23">
<a>
<lex.rf>a#a-mf920925-079-p2s3w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dřevěný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920925-079-p2s3w27">
<a>
<lex.rf>a#a-mf920925-079-p2s3w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kříž</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
<LM id="t-mf920925-079-p2s3w30">
<a>
<lex.rf>a#a-mf920925-079-p2s3w30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>památka</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>23</deepord>
<children>
<LM id="t-mf920925-079-p2s3w29">
<a>
<lex.rf>a#a-mf920925-079-p2s3w29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
<LM id="t-mf920925-079-p2s3w34">
<a>
<lex.rf>a#a-mf920925-079-p2s3w34</lex.rf>
<aux.rf>
<LM>a#a-mf920925-079-p2s3w32</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
<children>
<LM id="t-mf920925-079-p2s3w33">
<a>
<lex.rf>a#a-mf920925-079-p2s3w33</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dvacetitisícový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
</LM>
<LM id="t-mf920925-079-p2s3w31">
<a>
<lex.rf>a#a-mf920925-079-p2s3w31</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>málo</t_lemma>
<functor>EXT</functor>
<proto_lemma>málo</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>sup</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
