<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf920922_067.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>sport</genre>
</meta>
<trees>
<LM id="t-mf920922-067-p1s1">
<atree.rf>a#a-mf920922-067-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p1s1w3">
<a>
<lex.rf>a#a-mf920922-067-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bluf</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-mf920922-067-p1s1w2">
<a>
<lex.rf>a#a-mf920922-067-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bezpečný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-067-p1s1w1">
<a>
<lex.rf>a#a-mf920922-067-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poněkud</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p2s1">
<atree.rf>a#a-mf920922-067-p2s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p2s1w5">
<a>
<lex.rf>a#a-mf920922-067-p2s1w5</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p2s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>myslit_si</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41ckmA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p2s1w1">
<a>
<lex.rf>a#a-mf920922-067-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>co</t_lemma>
<functor>EFF</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>neut</gender>
<number>sg</number>
<indeftype>inter</indeftype>
<person>3</person>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-067-p2s1w4">
<a>
<lex.rf>a#a-mf920922-067-p2s1w4</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p2s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>PAT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_special>segm</coref_special>
</LM>
<LM id="t-mf920922-067-p2s1a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s1C">
<atree.rf>a#a-mf920922-067-p3s1C</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s1w3">
<a>
<lex.rf>a#a-mf920922-067-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bluf</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p1s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-067-p3s1w2">
<a>
<lex.rf>a#a-mf920922-067-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bezpečný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-067-p3s1w1">
<a>
<lex.rf>a#a-mf920922-067-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poněkud</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s1B">
<atree.rf>a#a-mf920922-067-p3s1B</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s1w17">
<a>
<lex.rf>a#a-mf920922-067-p3s1w17</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Dash</t_lemma>
<functor>CONJ</functor>
<deepord>11</deepord>
<children>
<LM id="t-mf920922-067-p3s1w7">
<a>
<lex.rf>a#a-mf920922-067-p3s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosáhnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41afbF</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s1w4">
<a>
<lex.rf>a#a-mf920922-067-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Výbor</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920922-067-p3s1w5">
<a>
<lex.rf>a#a-mf920922-067-p3s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fotbalista</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-067-p3s1w6">
<a>
<lex.rf>a#a-mf920922-067-p3s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sparta</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s1w8">
<a>
<lex.rf>a#a-mf920922-067-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>protest</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-067-p3s1w11">
<a>
<lex.rf>a#a-mf920922-067-p3s1w11</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>gól</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf920922-067-p3s1w10">
<a>
<lex.rf>a#a-mf920922-067-p3s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uznaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf920922-067-p3s1w13">
<a>
<lex.rf>a#a-mf920922-067-p3s1w13</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s1w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>derby</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf920922-067-p3s1w15">
<a>
<lex.rf>a#a-mf920922-067-p3s1w15</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s1w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Slavia</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s1w16">
<a>
<lex.rf>a#a-mf920922-067-p3s1w16</lex.rf>
</a>
<nodetype>dphr</nodetype>
<t_lemma>svého</t_lemma>
<functor>DPHR</functor>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s1w26">
<a>
<lex.rf>a#a-mf920922-067-p3s1w26</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s1w21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>setkat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s1w7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>spec</discourse_type>
<sense_PDTB3>Expansion.Level-of-detail.Arg2-as-detail</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s1w17</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41klgB</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s1w20">
<a>
<lex.rf>a#a-mf920922-067-p3s1w20</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s1w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Mádl</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>12</deepord>
<children>
<LM id="t-mf920922-067-p3s1w19">
<a>
<lex.rf>a#a-mf920922-067-p3s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodčí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s1w22">
<a>
<lex.rf>a#a-mf920922-067-p3s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sparta</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s1w25">
<a>
<lex.rf>a#a-mf920922-067-p3s1w25</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s1w23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>liga</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf920922-067-p3s1w24">
<a>
<lex.rf>a#a-mf920922-067-p3s1w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s1a2">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s2">
<atree.rf>a#a-mf920922-067-p3s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-067-l7A">
<basic-form>trestný bod</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf920922-067-p3s2w12</LM>
<LM>t-mf920922-067-p3s2w13</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-067-p3s2w2">
<a>
<lex.rf>a#a-mf920922-067-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s1w26</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s2w1</LM>
<LM>t-mf920922-067-p3s2w3</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsP</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s2w1">
<a>
<lex.rf>a#a-mf920922-067-p3s2w1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>a</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-067-p3s2w3">
<a>
<lex.rf>a#a-mf920922-067-p3s2w3</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-067-p3s2w4">
<a>
<lex.rf>a#a-mf920922-067-p3s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>možný</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-067-p3s2w9">
<a>
<lex.rf>a#a-mf920922-067-p3s2w9</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s2w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>připsat</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41ixdB</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s2w7">
<a>
<lex.rf>a#a-mf920922-067-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komise</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-067-p3s2w8">
<a>
<lex.rf>a#a-mf920922-067-p3s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodčí</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s2w10">
<a>
<lex.rf>a#a-mf920922-067-p3s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Mádl</t_lemma>
<functor>ADDR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s1w20</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s2w13">
<a>
<lex.rf>a#a-mf920922-067-p3s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bod</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf920922-067-p3s2w12">
<a>
<lex.rf>a#a-mf920922-067-p3s2w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trestný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-mf920922-067-p3s2w11">
<a>
<lex.rf>a#a-mf920922-067-p3s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nějaký</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jaký</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>indef1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s3">
<atree.rf>a#a-mf920922-067-p3s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s3w6">
<a>
<lex.rf>a#a-mf920922-067-p3s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>považovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s1w17</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>1</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s3w5</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41gtiA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s3w4">
<a>
<lex.rf>a#a-mf920922-067-p3s3w4</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s3w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bluf</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-067-p3s3w3">
<a>
<lex.rf>a#a-mf920922-067-p3s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zbytečný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-067-p3s3w2">
<a>
<lex.rf>a#a-mf920922-067-p3s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poněkud</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s3w5">
<a>
<lex.rf>a#a-mf920922-067-p3s3w5</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>ovšem</t_lemma>
<functor>ATT</functor>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-067-p3s3a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p2s1a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s3w7">
<a>
<lex.rf>a#a-mf920922-067-p3s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žádost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf920922-067-p3s3w9">
<a>
<lex.rf>a#a-mf920922-067-p3s3w9</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s3w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sehrání</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41kibA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf920922-067-p3s3w11">
<a>
<lex.rf>a#a-mf920922-067-p3s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>derby</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-067-p3s1w13</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<children>
<LM id="t-mf920922-067-p3s3w10">
<a>
<lex.rf>a#a-mf920922-067-p3s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s4">
<atree.rf>a#a-mf920922-067-p3s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s4w7">
<a>
<lex.rf>a#a-mf920922-067-p3s4w7</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s4w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41lioD</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s4w1">
<a>
<lex.rf>a#a-mf920922-067-p3s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nic</t_lemma>
<functor>ACT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>neut</gender>
<number>sg</number>
<indeftype>negat</indeftype>
<person>3</person>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920922-067-p3s4w2">
<a>
<lex.rf>a#a-mf920922-067-p3s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>takový</t_lemma>
<functor>RSTR</functor>
<proto_lemma>takový</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-067-p3s3w9</target_node.rf>
<type>ANAF</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s4w4">
<a>
<lex.rf>a#a-mf920922-067-p3s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosud</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-067-p3s4w6">
<a>
<lex.rf>a#a-mf920922-067-p3s4w6</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s4w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svět</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-067-p3s4a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s5">
<atree.rf>a#a-mf920922-067-p3s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s5w6">
<a>
<lex.rf>a#a-mf920922-067-p3s5w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s5w4">
<a>
<lex.rf>a#a-mf920922-067-p3s5w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Mach</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-067-p3s5w3">
<a>
<lex.rf>a#a-mf920922-067-p3s5w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pan</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-067-p3s5w1">
<a>
<lex.rf>a#a-mf920922-067-p3s5w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf920922-067-p3s5w2">
<a>
<lex.rf>a#a-mf920922-067-p3s5w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sparta</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s1w22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s5w5">
<a>
<lex.rf>a#a-mf920922-067-p3s5w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-067-p3s3a0</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-mf920922-067-p3s5w14">
<a>
<lex.rf>a#a-mf920922-067-p3s5w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ale</t_lemma>
<functor>ADVS</functor>
<deepord>11</deepord>
<children>
<LM id="t-mf920922-067-p3s5w11">
<a>
<lex.rf>a#a-mf920922-067-p3s5w11</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s5w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>EFF</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s5w10">
<a>
<lex.rf>a#a-mf920922-067-p3s5w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_special>segm</coref_special>
</LM>
<LM id="t-mf920922-067-p3s5w9">
<a>
<lex.rf>a#a-mf920922-067-p3s5w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>BEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s5w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s5w12">
<a>
<lex.rf>a#a-mf920922-067-p3s5w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jasný</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s5w16">
<a>
<lex.rf>a#a-mf920922-067-p3s5w16</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s5w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jít</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s5w11</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s5w14</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41bikAV</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s5w17">
<a>
<lex.rf>a#a-mf920922-067-p3s5w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spíše</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-mf920922-067-p3s5w19">
<a>
<lex.rf>a#a-mf920922-067-p3s5w19</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s5w18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcent</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s3w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-067-p3s5w21">
<a>
<lex.rf>a#a-mf920922-067-p3s5w21</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s5w20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodčí</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-067-p3s1w19</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>t-mf920922-067-p3s2w8</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s5w30">
<a>
<lex.rf>a#a-mf920922-067-p3s5w30</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s5w23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kazit</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s5w16</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>purp</discourse_type>
<sense_PDTB3>Contingency.Purpose.Arg2-as-goal</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-mf920922-067-p3s5w23</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41bkfA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s5w27">
<a>
<lex.rf>a#a-mf920922-067-p3s5w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zápas</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf920922-067-p3s5w26">
<a>
<lex.rf>a#a-mf920922-067-p3s5w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>významný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-mf920922-067-p3s5w25">
<a>
<lex.rf>a#a-mf920922-067-p3s5w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s5w29">
<a>
<lex.rf>a#a-mf920922-067-p3s5w29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chyba</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>20</deepord>
<children>
<LM id="t-mf920922-067-p3s5w28">
<a>
<lex.rf>a#a-mf920922-067-p3s5w28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<coref_gram.rf>
<LM>t-mf920922-067-p3s5a0</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s5a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>21</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s5w21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s5a1">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s6">
<atree.rf>a#a-mf920922-067-p3s6</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s6w6">
<a>
<lex.rf>a#a-mf920922-067-p3s6w6</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>7</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s5w6</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s6w2</LM>
</t-connectors.rf>
</LM>
</discourse>
<children>
<LM id="t-mf920922-067-p3s6w1">
<a>
<lex.rf>a#a-mf920922-067-p3s6w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znát</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41rnfF</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s6w2">
<a>
<lex.rf>a#a-mf920922-067-p3s6w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>však</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-067-p3s6a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-067-p3s3a0</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
</LM>
<LM id="t-mf920922-067-p3s6w5">
<a>
<lex.rf>a#a-mf920922-067-p3s6w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fanoušek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-067-p3s6w3">
<a>
<lex.rf>a#a-mf920922-067-p3s6w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>pl</number>
<person>1</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s5w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s6w4">
<a>
<lex.rf>a#a-mf920922-067-p3s6w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>některý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>indef1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s6w12">
<a>
<lex.rf>a#a-mf920922-067-p3s6w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>věřit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41njsE</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s6w11">
<a>
<lex.rf>a#a-mf920922-067-p3s6w11</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s6w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>derby</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s3w11</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-067-p3s6w10">
<a>
<lex.rf>a#a-mf920922-067-p3s6w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s6w7">
<a>
<lex.rf>a#a-mf920922-067-p3s6w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>anim</gender>
<number>pl</number>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s6w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s6w8">
<a>
<lex.rf>a#a-mf920922-067-p3s6w8</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>už</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s7">
<atree.rf>a#a-mf920922-067-p3s7</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s7w6">
<a>
<lex.rf>a#a-mf920922-067-p3s7w6</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>6</deepord>
<children>
<LM id="t-mf920922-067-p3s7w1">
<a>
<lex.rf>a#a-mf920922-067-p3s7w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dojít</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<val_frame.rf>v#v41zdL</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s7w5">
<a>
<lex.rf>a#a-mf920922-067-p3s7w5</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s7w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jitření</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41bilA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s7a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-067-p3s7w3">
<a>
<lex.rf>a#a-mf920922-067-p3s7w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s6w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s7w4">
<a>
<lex.rf>a#a-mf920922-067-p3s7w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zbytečný</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s7w20">
<a>
<lex.rf>a#a-mf920922-067-p3s7w20</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>15</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s7w1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s7w7</LM>
</t-connectors.rf>
</LM>
</discourse>
<children>
<LM id="t-mf920922-067-p3s7w7">
<a>
<lex.rf>a#a-mf920922-067-p3s7w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>ACT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_gram.rf>
<LM>t-mf920922-067-p3s7w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf920922-067-p3s7w10">
<a>
<lex.rf>a#a-mf920922-067-p3s7w10</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s7w9</LM>
<LM>a#a-mf920922-067-p3s7w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odrazit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41ehuA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s7w13">
<a>
<lex.rf>a#a-mf920922-067-p3s7w13</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s7w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>reakce</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf920922-067-p3s7w12">
<a>
<lex.rf>a#a-mf920922-067-p3s7w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s7w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s7w15">
<a>
<lex.rf>a#a-mf920922-067-p3s7w15</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s7w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlediště</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf920922-067-p3s7w19">
<a>
<lex.rf>a#a-mf920922-067-p3s7w19</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s7w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sudí</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-067-p3s5a0</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf920922-067-p3s7w18">
<a>
<lex.rf>a#a-mf920922-067-p3s7w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příští</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-mf920922-067-p3s7w17">
<a>
<lex.rf>a#a-mf920922-067-p3s7w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>každý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total2</indeftype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s7w21">
<a>
<lex.rf>a#a-mf920922-067-p3s7w21</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s7w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přidělat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s7w10</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s7w20</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41iqcA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s7w22">
<a>
<lex.rf>a#a-mf920922-067-p3s7w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sparta</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s6w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s7w24">
<a>
<lex.rf>a#a-mf920922-067-p3s7w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>starost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-mf920922-067-p3s7w23">
<a>
<lex.rf>a#a-mf920922-067-p3s7w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zbytečný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s8">
<atree.rf>a#a-mf920922-067-p3s8</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-067-l1A">
<basic-form>ve všem všudy</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf920922-067-p3s8w14</LM>
<LM>t-mf920922-067-p3s8w15</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-067-p3s8w2">
<a>
<lex.rf>a#a-mf920922-067-p3s8w2</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-067-p3s8w1">
<a>
<lex.rf>a#a-mf920922-067-p3s8w1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>inu</t_lemma>
<functor>PARTL</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-067-p3s8w7">
<a>
<lex.rf>a#a-mf920922-067-p3s8w7</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>7</deepord>
<children>
<LM id="t-mf920922-067-p3s8w5">
<a>
<lex.rf>a#a-mf920922-067-p3s8w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s8w3">
<a>
<lex.rf>a#a-mf920922-067-p3s8w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vedení</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41nieC</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s8w4">
<a>
<lex.rf>a#a-mf920922-067-p3s8w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sparta</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s7w22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s8w6">
<a>
<lex.rf>a#a-mf920922-067-p3s8w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s8w11">
<a>
<lex.rf>a#a-mf920922-067-p3s8w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čekat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s8w5</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s8w7</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41mtC</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s8w8">
<a>
<lex.rf>a#a-mf920922-067-p3s8w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nikdo</t_lemma>
<functor>ACT</functor>
<proto_lemma>kdo</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>anim</gender>
<number>sg</number>
<indeftype>negat</indeftype>
<person>3</person>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf920922-067-p3s8w10">
<a>
<lex.rf>a#a-mf920922-067-p3s8w10</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s8w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s8w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s8a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-mf920922-067-p3s8w12">
<a>
<lex.rf>a#a-mf920922-067-p3s8w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hned</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-mf920922-067-p3s8w14">
<a>
<lex.rf>a#a-mf920922-067-p3s8w14</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s8w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>LOC</functor>
<proto_lemma>kdo</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.pron.indef</sempos>
<gender>neut</gender>
<number>sg</number>
<indeftype>total1</indeftype>
<person>3</person>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-mf920922-067-p3s8w15">
<a>
<lex.rf>a#a-mf920922-067-p3s8w15</lex.rf>
</a>
<nodetype>dphr</nodetype>
<t_lemma>všudy</t_lemma>
<functor>DPHR</functor>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s8w16">
<a>
<lex.rf>a#a-mf920922-067-p3s8w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>profesionalita</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s9">
<atree.rf>a#a-mf920922-067-p3s9</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-067-l6A">
<basic-form>Zdeněk Nehoda</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf920922-067-p3s9w7</LM>
<LM>t-mf920922-067-p3s9w8</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-067-p3s9w3">
<a>
<lex.rf>a#a-mf920922-067-p3s9w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s8w7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s9w4</LM>
<LM>t-mf920922-067-p3s9w5</LM>
<LM>t-mf920922-067-p3s9w6</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsU</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s9w4">
<a>
<lex.rf>a#a-mf920922-067-p3s9w4</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>však</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-067-p3s9w2">
<a>
<lex.rf>a#a-mf920922-067-p3s9w2</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s9w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výbor</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s9w5">
<a>
<lex.rf>a#a-mf920922-067-p3s9w5</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>přece</t_lemma>
<functor>ATT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-067-p3s9w6">
<a>
<lex.rf>a#a-mf920922-067-p3s9w6</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf920922-067-p3s9w8">
<a>
<lex.rf>a#a-mf920922-067-p3s9w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Nehoda</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf920922-067-p3s9w7">
<a>
<lex.rf>a#a-mf920922-067-p3s9w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Zdeněk</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf920922-067-p3s9w13">
<a>
<lex.rf>a#a-mf920922-067-p3s9w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>protřelý</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>other</type>
<set_id>mf920922-067-p3s9w13</set_id>
</LM>
</quot>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf920922-067-p3s9w10">
<a>
<lex.rf>a#a-mf920922-067-p3s9w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fotbal</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf920922-067-p3s9w11">
<a>
<lex.rf>a#a-mf920922-067-p3s9w11</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>doslova</t_lemma>
<functor>ATT</functor>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s10">
<atree.rf>a#a-mf920922-067-p3s10</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s10w4">
<a>
<lex.rf>a#a-mf920922-067-p3s10w4</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s10w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ovlivnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41ffeA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s10w1">
<a>
<lex.rf>a#a-mf920922-067-p3s10w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>anim</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s9w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s10w2">
<a>
<lex.rf>a#a-mf920922-067-p3s10w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>snad</t_lemma>
<functor>MOD</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-067-p3s10w15">
<a>
<lex.rf>a#a-mf920922-067-p3s10w15</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s10w8</LM>
<LM>a#a-mf920922-067-p3s10w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dostat_se</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41afyI</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s10w11">
<a>
<lex.rf>a#a-mf920922-067-p3s10w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přání</t_lemma>
<functor>ACT</functor>
<quot>
<LM>
<type>other</type>
<set_id>mf920922-067-p3s10w11</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s5w19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41htpD</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s10w9">
<a>
<lex.rf>a#a-mf920922-067-p3s10w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s10w14">
<a>
<lex.rf>a#a-mf920922-067-p3s10w14</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s10w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veřejnost</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf920922-067-p3s10a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-067-p3s11">
<atree.rf>a#a-mf920922-067-p3s11</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-067-p3s11a0">
<a>
<lex.rf>a#a-mf920922-067-p3s10w4</lex.rf>
<aux.rf>
<LM>a#a-mf920922-067-p3s11w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>ovlivnit</t_lemma>
<functor>PRED</functor>
<sentmod>inter</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-067-p3s10w4</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>disjalt</discourse_type>
<sense_PDTB3>Expansion.Disjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-067-p3s11w1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41ffeA</val_frame.rf>
<children>
<LM id="t-mf920922-067-p3s11w1">
<a>
<lex.rf>a#a-mf920922-067-p3s11w1</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>nebo</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-067-p3s11a2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s10w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s11a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-067-p3s10w15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-067-p3s11a3">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf920922-067-p3s11w2">
<a>
<lex.rf>a#a-mf920922-067-p3s11w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>snad</t_lemma>
<functor>MOD</functor>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
