<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf920922_047.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>overview</genre>
</meta>
<trees>
<LM id="t-mf920922-047-p1s1">
<atree.rf>a#a-mf920922-047-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-047-l13A">
<basic-form>kurzovní lístek</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf920922-047-p1s1w1</LM>
<LM>t-mf920922-047-p1s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-047-p1s1w2">
<a>
<lex.rf>a#a-mf920922-047-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lístek</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<discourse_comment>tabulka převedená do textu?</discourse_comment>
<children>
<LM id="t-mf920922-047-p1s1w1">
<a>
<lex.rf>a#a-mf920922-047-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kursovní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p2s1">
<atree.rf>a#a-mf920922-047-p2s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p2s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>2</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-mf920922-047-p2s1w1">
<a>
<lex.rf>a#a-mf920922-047-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>deviza</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-047-p2s1w2">
<a>
<lex.rf>a#a-mf920922-047-p2s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>valuta</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p3s1">
<atree.rf>a#a-mf920922-047-p3s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p3s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>3</deepord>
<children>
<LM id="t-mf920922-047-p3s1w1">
<a>
<lex.rf>a#a-mf920922-047-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>střed</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-047-p3s1w2">
<a>
<lex.rf>a#a-mf920922-047-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nákup</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-047-p3s1w3">
<a>
<lex.rf>a#a-mf920922-047-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodej</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p4s1">
<atree.rf>a#a-mf920922-047-p4s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p4s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-mf920922-047-p4s1w1">
<a>
<lex.rf>a#a-mf920922-047-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-047-p4s1w2">
<a>
<lex.rf>a#a-mf920922-047-p4s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>27.58</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-047-p4s1w3">
<a>
<lex.rf>a#a-mf920922-047-p4s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>26.88</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-047-p4s1w4">
<a>
<lex.rf>a#a-mf920922-047-p4s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>28.28</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p5s1">
<atree.rf>a#a-mf920922-047-p5s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p5s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-mf920922-047-p5s1w1">
<a>
<lex.rf>a#a-mf920922-047-p5s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>marka</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-047-p5s1w2">
<a>
<lex.rf>a#a-mf920922-047-p5s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>18.51</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-047-p5s1w3">
<a>
<lex.rf>a#a-mf920922-047-p5s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>18.05</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-047-p5s1w4">
<a>
<lex.rf>a#a-mf920922-047-p5s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>18.97</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p6s1">
<atree.rf>a#a-mf920922-047-p6s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p6s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-mf920922-047-p6s1w1">
<a>
<lex.rf>a#a-mf920922-047-p6s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>libra</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-047-p6s1w2">
<a>
<lex.rf>a#a-mf920922-047-p6s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>47.07</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-047-p6s1w3">
<a>
<lex.rf>a#a-mf920922-047-p6s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>45.24</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-047-p6s1w4">
<a>
<lex.rf>a#a-mf920922-047-p6s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>48.38</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p7s1">
<atree.rf>a#a-mf920922-047-p7s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p7s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-047-p7s1w1">
<a>
<lex.rf>a#a-mf920922-047-p7s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jen</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920922-047-p7s1w3">
<a>
<lex.rf>a#a-mf920922-047-p7s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sto</t_lemma>
<functor>PAR</functor>
<proto_lemma>sto</proto_lemma>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.quant.def</sempos>
<gender>neut</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p7s1w5">
<a>
<lex.rf>a#a-mf920922-047-p7s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>22.24</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-047-p7s1w6">
<a>
<lex.rf>a#a-mf920922-047-p7s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>21.44</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-047-p7s1w7">
<a>
<lex.rf>a#a-mf920922-047-p7s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>22.76</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p8s1">
<atree.rf>a#a-mf920922-047-p8s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-047-l15A">
<type>object</type>
<tnode.rfs>
<LM>t-mf920922-047-p8s1w1</LM>
<LM>t-mf920922-047-p8s1w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-047-p8s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-047-p8s1w3">
<a>
<lex.rf>a#a-mf920922-047-p8s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>frank</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920922-047-p8s1w1">
<a>
<lex.rf>a#a-mf920922-047-p8s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>švýcarský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p8s1w4">
<a>
<lex.rf>a#a-mf920922-047-p8s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>21.06</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-047-p8s1w5">
<a>
<lex.rf>a#a-mf920922-047-p8s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>20.53</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-047-p8s1w6">
<a>
<lex.rf>a#a-mf920922-047-p8s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>21.59</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p9s1">
<atree.rf>a#a-mf920922-047-p9s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-047-l16A">
<type>object</type>
<tnode.rfs>
<LM>t-mf920922-047-p9s1w1</LM>
<LM>t-mf920922-047-p9s1w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-047-p9s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-047-p9s1w3">
<a>
<lex.rf>a#a-mf920922-047-p9s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>frank</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-047-p9s1w1">
<a>
<lex.rf>a#a-mf920922-047-p9s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>francouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p9s1w4">
<a>
<lex.rf>a#a-mf920922-047-p9s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>5.42</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-047-p9s1w5">
<a>
<lex.rf>a#a-mf920922-047-p9s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>5.23</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-047-p9s1w6">
<a>
<lex.rf>a#a-mf920922-047-p9s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>5.55</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p10s2C">
<atree.rf>a#a-mf920922-047-p10s2C</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p10s2w2">
<a>
<lex.rf>a#a-mf920922-047-p10s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sto</t_lemma>
<functor>PAR</functor>
<proto_lemma>sto</proto_lemma>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.quant.def</sempos>
<gender>neut</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p10s2B">
<atree.rf>a#a-mf920922-047-p10s2B</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p10s2a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>3</deepord>
<children>
<LM id="t-mf920922-047-p10s2w4">
<a>
<lex.rf>a#a-mf920922-047-p10s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>89.78</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-047-p10s2w5">
<a>
<lex.rf>a#a-mf920922-047-p10s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>86.70</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-047-p10s2w6">
<a>
<lex.rf>a#a-mf920922-047-p10s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>91.98</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p12s1">
<atree.rf>a#a-mf920922-047-p12s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p12s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-047-p12s1w1">
<a>
<lex.rf>a#a-mf920922-047-p12s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lira</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920922-047-p12s1w3">
<a>
<lex.rf>a#a-mf920922-047-p12s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tisíc</t_lemma>
<functor>PAR</functor>
<proto_lemma>tisíc</proto_lemma>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p12s1w5">
<a>
<lex.rf>a#a-mf920922-047-p12s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>21.96</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-047-p12s1w6">
<a>
<lex.rf>a#a-mf920922-047-p12s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>21.12</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-047-p12s1w7">
<a>
<lex.rf>a#a-mf920922-047-p12s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>22.56</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-047-p13s1">
<atree.rf>a#a-mf920922-047-p13s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-047-p13s1a0">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-mf920922-047-p13s1w1">
<a>
<lex.rf>a#a-mf920922-047-p13s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šilink</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-047-p13s1w2">
<a>
<lex.rf>a#a-mf920922-047-p13s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.64</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-047-p13s1w3">
<a>
<lex.rf>a#a-mf920922-047-p13s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.58</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-047-p13s1w4">
<a>
<lex.rf>a#a-mf920922-047-p13s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.70</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
