<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0298.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj0298-001-p1s0">
<atree.rf>a#a-wsj0298-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a31">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Du</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0298-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Pont</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s0a30">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>3</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a8">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Hewlett</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj0298-001-p1s0a7">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Packard</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s0a9">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laboratoř</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a10">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Národní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0298-001-p1s0a32">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>11</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a12">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Los</t_lemma>
<functor>FPHR</functor>
<deepord>12</deepord>
</LM>
<LM id="T-wsj0298-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Alamos</t_lemma>
<functor>FPHR</functor>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s0a15">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s0W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podepsat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41friB</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s0a29">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0298-001-p1s0a16">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>smlouva</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a17">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tříletý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
<LM id="T-wsj0298-001-p1s0a19">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s0W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a21">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a20">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>11</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>20</deepord>
</LM>
<LM id="T-wsj0298-001-p1s0a22">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s0a24">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s0W23-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spolupráce</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a26">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W26-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s0W25-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výzkum</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj0298-001-p1s0a27">
<a>
<lex.rf>a#a-wsj0298-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>supravodič</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Du Pont Co., Hewlett-Packard Co. and Los Alamos National Laboratory said they signed a three-year, $11 million agreement to collaborate on superconductor research.</eng_sentence>
</LM>
<LM id="T-wsj0298-001-p1s1">
<atree.rf>a#a-wsj0298-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s1a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s1a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0298-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s0a29</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0298-001-p1s1a5">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>9</deepord>
<children>
<LM id="T-wsj0298-001-p1s1a7">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s1W6-Ta</LM>
<LM>a#a-wsj0298-001-p1s1W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zahrnovat</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41ptxC</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s1a6">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spolupráce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s0a24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0298-001-p1s1a11">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výzkumník</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0298-001-p1s1a10">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>25</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0298-001-p1s1a9">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>málo</t_lemma>
<functor>EXT</functor>
<proto_lemma>málo</proto_lemma>
<gram>
<sempos>adj.quant.grad</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s1a12">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s1W12-Ta</LM>
<LM>a#a-wsj0298-001-p1s1W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaměřit</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0298-001-p1s1a7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<comment>PHASE:2 INTRA_AUTO_SAME-NODES-PDTB_NO-OTHER</comment>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj0298-001-p1s1a5</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41qaxA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s1a28">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s1a6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0298-001-p1s1a31">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s1a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0298-001-p1s1a15">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s1W14-Ta</LM>
</aux.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>řada</t_lemma>
<functor>RHEM</functor>
<deepord>14</deepord>
<children>
<LM id="T-wsj0298-001-p1s1a16">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s1a18">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s1W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vývoj</t_lemma>
<functor>DIR3</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0298-001-p1s1a19">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vrstva</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj0298-001-p1s1a20">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tenký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0298-001-p1s1a21">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>supravodič</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0298-001-p1s1a22">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vysokoteplotní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s1a24">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s1W23-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>využití</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>22</deepord>
<val_frame.rf>v#v41pfkA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s1a30">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>20</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s1a19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0298-001-p1s1a29">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>21</deepord>
</LM>
<LM id="T-wsj0298-001-p1s1a26">
<a>
<lex.rf>a#a-wsj0298-001-p1s1W26-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s1W25-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>elektronika</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The collaboration will include at least 25 researchers and will be aimed primarily at developing thin films of high-temperature superconductors for use in electronics, the companies said.</eng_sentence>
</LM>
<LM id="T-wsj0298-001-p1s2">
<atree.rf>a#a-wsj0298-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W17-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>13</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a4">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>materiál</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a5">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0298-001-p1s2a6">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s2W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>objevit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41dptA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s2a28">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0298-001-p1s2a9">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>4</deepord>
<coref_gram.rf>
<LM>T-wsj0298-001-p1s2a4</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0298-001-p1s2a11">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s2W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TPAR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a12">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>minulý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj0298-001-p1s2a13">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s2a3">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>9</deepord>
<val_frame.rf>v#v41njvL</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s2a14">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>proud</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a15">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>elektrický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s2a17">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s2W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odpor</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s2a18">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0298-001-p1s2a3</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<comment>PHASE:2 INTRA_AUTO_TARGET-NODE-PDTB_COMPATIBLE-SENSE</comment>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj0298-001-p1s2a1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s2a19">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příslib</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a20">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W24-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>20</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a24">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počítač</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a21">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W21-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>17</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a22">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>malý</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0298-001-p1s2a23">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rychlý</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s2a25">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>technologie</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj0298-001-p1s2a26">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>21</deepord>
</LM>
<LM id="T-wsj0298-001-p1s2a27">
<a>
<lex.rf>a#a-wsj0298-001-p1s2W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The materials, discovered during the past three years, conduct electricity without resistance and promise smaller, faster computers and other new technologies.</eng_sentence>
</LM>
<LM id="T-wsj0298-001-p1s3">
<atree.rf>a#a-wsj0298-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s3W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozšířit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41jyyA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s3a2">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a3">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výzkum</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a4">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s3a8">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s3W8-Ta</LM>
<LM>a#a-wsj0298-001-p1s3W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snažit_se</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0298-001-p1s3a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Reason</sense_PDTB3>
<sense1B_PDTB3>Contingency.Cause.Reason</sense1B_PDTB3>
<comment>PHASE:3 TYPECHECKED; INTRA_AUTO_SAME-NODES-PDTB_NO-OTHER</comment>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj0298-001-p1s3W7-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41kwuA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s3a10">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a11">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>americký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s3a12">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W22-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>19</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a40">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>7</deepord>
<coref_gram.rf>
<LM>T-wsj0298-001-p1s3a10</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0298-001-p1s3a13">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozkládat</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>9</deepord>
<val_frame.rf>v#v41jruB</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s3a14">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W14-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>11</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a15">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>riziko</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0298-001-p1s3a16">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>náklad</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj0298-001-p1s3a17">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spojený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a19">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s3W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>využití</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41pfkA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s3a39">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>14</deepord>
</LM>
<LM id="T-wsj0298-001-p1s3a20">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obchodní</t_lemma>
<functor>REG</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
<LM id="T-wsj0298-001-p1s3a21">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>supravodič</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a22">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s3a23">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s3W24-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zhostit_se</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>20</deepord>
<val_frame.rf>v#v41rcyA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s3a25">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výzva</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a26">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>náročný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
</LM>
<LM id="T-wsj0298-001-p1s3a27">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>24</deepord>
<val_frame.rf>v#v41hylC</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s3a29">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>23</deepord>
<coref_gram.rf>
<LM>T-wsj0298-001-p1s3a25</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0298-001-p1s3a34">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W34-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s3W33-Ta</LM>
</aux.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a_to</t_lemma>
<functor>APPS</functor>
<deepord>27</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a30">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konsorcium</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>26</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a31">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zahraniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s3a36">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W35-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>zejména</t_lemma>
<functor>CM</functor>
<deepord>28</deepord>
</LM>
<LM id="T-wsj0298-001-p1s3a41">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>konsorcium</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
<children>
<LM id="T-wsj0298-001-p1s3a37">
<a>
<lex.rf>a#a-wsj0298-001-p1s3W37-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s3W36-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Japonsko</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>30</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Joint-research programs have proliferated as U.S. companies seek to spread the risks and costs of commercializing new superconductors and to meet the challenges posed by foreign consortia, especially in Japan.</eng_sentence>
</LM>
<LM id="T-wsj0298-001-p1s4">
<atree.rf>a#a-wsj0298-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s4a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvyšovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41sdlA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s4a2">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>smlouva</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s0a16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0298-001-p1s4a3">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0298-001-p1s4a5">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s4W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výzkum</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s4a6">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>portfolio</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0298-001-p1s4a7">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rostoucí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0298-001-p1s4a8">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>investice</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0298-001-p1s4a9">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj0298-001-p1s4a14">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>9</deepord>
<children>
<LM id="T-wsj0298-001-p1s4a10">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W10-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Du</t_lemma>
<functor>FPHR</functor>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0298-001-p1s4a11">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W11-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Pont</t_lemma>
<functor>FPHR</functor>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s4a13">
<a>
<lex.rf>a#a-wsj0298-001-p1s4W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s4W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>supravodič</t_lemma>
<functor>DIR3</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The latest research pact bolsters Du Pont's growing portfolio of investments in superconductors.</eng_sentence>
</LM>
<LM id="T-wsj0298-001-p1s5">
<atree.rf>a#a-wsj0298-001-p1s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s5a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podepsat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41friB</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s5a2">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koncern</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s4a9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0298-001-p1s5a3">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0298-001-p1s5a4">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chemický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj0298-001-p1s5a6">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s5W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj0298-001-p1s5a7">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Wilmington</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0298-001-p1s5a9">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s5W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Delawar</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s5a10">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohoda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0298-001-p1s5a12">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s5W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výzkum</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0298-001-p1s5a13">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>supravodič</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s5a15">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s5W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0298-001-p1s5a16">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W20-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>17</deepord>
<children>
<LM id="T-wsj0298-001-p1s5a26">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<deepord>12</deepord>
<children>
<LM id="T-wsj0298-001-p1s5a18">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W16-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Oak</t_lemma>
<functor>FPHR</functor>
<deepord>13</deepord>
</LM>
<LM id="T-wsj0298-001-p1s5a19">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W17-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Ridge</t_lemma>
<functor>FPHR</functor>
<deepord>14</deepord>
</LM>
<LM id="T-wsj0298-001-p1s5a20">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W18-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>National</t_lemma>
<functor>FPHR</functor>
<deepord>15</deepord>
</LM>
<LM id="T-wsj0298-001-p1s5a17">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W19-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Laboratory</t_lemma>
<functor>FPHR</functor>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s5a25">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<deepord>21</deepord>
<children>
<LM id="T-wsj0298-001-p1s5a22">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W21-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Argonne</t_lemma>
<functor>FPHR</functor>
<deepord>18</deepord>
</LM>
<LM id="T-wsj0298-001-p1s5a23">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W22-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>National</t_lemma>
<functor>FPHR</functor>
<deepord>19</deepord>
</LM>
<LM id="T-wsj0298-001-p1s5a21">
<a>
<lex.rf>a#a-wsj0298-001-p1s5W23-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Laboratory</t_lemma>
<functor>FPHR</functor>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The Wilmington, Del., chemicals concern previously signed research superconductor agreements with Oak Ridge National Laboratory and with Argonne National Laboratory.</eng_sentence>
</LM>
<LM id="T-wsj0298-001-p1s6">
<atree.rf>a#a-wsj0298-001-p1s6</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s6a3">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>souhlasit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41kypC</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s6a4">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0298-001-p1s6a2">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s5a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0298-001-p1s6a21">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>3</deepord>
<children>
<LM id="T-wsj0298-001-p1s6a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Du</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0298-001-p1s6a5">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Pont</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s6a7">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s6W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaplacení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0298-001-p1s6a19">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s6a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0298-001-p1s6a9">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0298-001-p1s6a8">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>4.5</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0298-001-p1s6a10">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s6a12">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s6W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>právo</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj0298-001-p1s6a14">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s6W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výzkum</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj0298-001-p1s6a15">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>supravodič</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
<LM id="T-wsj0298-001-p1s6a17">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s6W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>univerzita</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj0298-001-p1s6a18">
<a>
<lex.rf>a#a-wsj0298-001-p1s6W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Houstonský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Last year, Du Pont agreed to pay $4.5 million for rights to superconductor work at the University of Houston.</eng_sentence>
</LM>
<LM id="T-wsj0298-001-p1s7">
<atree.rf>a#a-wsj0298-001-p1s7</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s7a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s7a3">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj0298-001-p1s7a13">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0298-001-p1s7a4">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Hewlett</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0298-001-p1s7a2">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Packard</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s7a5">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výrobce</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0298-001-p1s7a6">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počítač</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj0298-001-p1s7a8">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s7W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0298-001-p1s7a14">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>9</deepord>
<children>
<LM id="T-wsj0298-001-p1s7a10">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W9-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Palo</t_lemma>
<functor>FPHR</functor>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0298-001-p1s7a9">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W10-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Alto</t_lemma>
<functor>FPHR</functor>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s7a12">
<a>
<lex.rf>a#a-wsj0298-001-p1s7W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s7W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kalifornie</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Hewlett-Packard is a Palo Alto, Calif., computer maker.</eng_sentence>
</LM>
<LM id="T-wsj0298-001-p1s8">
<atree.rf>a#a-wsj0298-001-p1s8</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a1">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s8a3">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laboratoř</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0298-001-p1s0a9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0298-001-p1s8a36">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a4">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Los</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a2">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Alamos</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s8a5">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jeden</t_lemma>
<functor>PAT</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a7">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s8W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laboratoř</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a8">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a9">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>národní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a10">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ministerstvo</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a11">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>americký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a12">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>energetika</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s8a13">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>RSTR</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s8a15">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>13</deepord>
<coref_gram.rf>
<LM>T-wsj0298-001-p1s8a7</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0298-001-p1s8a16">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>určený</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a17">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s8W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>centrum</t_lemma>
<functor>COMPL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<compl.rf>
<LM>T-wsj0298-001-p1s8a15</LM>
</compl.rf>
<children>
<LM id="T-wsj0298-001-p1s8a19">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zkušební</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a21">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s8W20-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpora</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a22">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a23">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a24">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W25-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>22</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a25">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průmysl</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a26">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vláda</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s8a28">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W28-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s8W27-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>urychlení</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>25</deepord>
<val_frame.rf>v#v41mugA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s8a34">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>24</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a29">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvedení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>27</deepord>
<val_frame.rf>v#v41ncsA</val_frame.rf>
<children>
<LM id="T-wsj0298-001-p1s8a35">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>26</deepord>
</LM>
<LM id="T-wsj0298-001-p1s8a30">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>supravodič</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
<children>
<LM id="T-wsj0298-001-p1s8a31">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>28</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0298-001-p1s8a33">
<a>
<lex.rf>a#a-wsj0298-001-p1s8W33-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0298-001-p1s8W32-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trh</t_lemma>
<functor>DIR3</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>30</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The Los Alamos laboratory is one of three U.S. Department of Energy national laboratories designed as pilot centers to foster joint industry-government programs to speed the transfer of new superconductors to the marketplace.</eng_sentence>
</LM>
</trees>
</tdata>
