<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0555.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<trees>
<LM id="T-wsj0555-001-p1s0">
<atree.rf>a#a-wsj0555-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj0555-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>firma</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a44">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Waxman</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Industries</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a45">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0555-001-p1s0a31">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W33-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0555-001-p1s0W32-Ta</LM>
<LM>a#a-wsj0555-001-p1s0W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodnout_se</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>26</deepord>
<val_frame.rf>v#v41jqiB</val_frame.rf>
<children>
<LM id="T-wsj0555-001-p1s0a7">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>držitel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a8">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>částka</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a9">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jmenovitý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a20">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a19">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>6542000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0555-001-p1s0a16">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0555-001-p1s0W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dluhopis</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a15">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>RSTR</functor>
<deepord>14</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a47">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>15</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>6</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a48">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Slash</t_lemma>
<functor>OPER</functor>
<is_member>1</is_member>
<deepord>17</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a46">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a13">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>4</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0555-001-p1s0a27">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konvertibilní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a28">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podřadný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a23">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>splatný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a22">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>březen</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a24">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0555-001-p1s0W28-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>15</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj0555-001-p1s0a26">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2007</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0555-001-p1s0a34">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W34-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konvertovat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>28</deepord>
<val_frame.rf>v#v41brqA</val_frame.rf>
<children>
<LM id="T-wsj0555-001-p1s0a43">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>27</deepord>
<coref_gram.rf>
<LM>T-wsj0555-001-p1s0a7</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0555-001-p1s0a35">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W35-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dluh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
<coref_special>segm</coref_special>
</LM>
<LM id="T-wsj0555-001-p1s0a39">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W40-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0555-001-p1s0W36-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>32</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a38">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W38-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>683000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>31</deepord>
<children>
<LM id="T-wsj0555-001-p1s0a37">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W37-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližně</t_lemma>
<functor>EXT</functor>
<proto_lemma>přibližný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>30</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0555-001-p1s0a40">
<a>
<lex.rf>a#a-wsj0555-001-p1s0W39-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obyčejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>33</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Waxman Industries Inc. said holders of $6,542,000 face amount of its 6 1/4% convertible subordinated debentures, due March 15, 2007, have elected to convert the debt into about 683,000 common shares.</eng_sentence>
</LM>
<LM id="T-wsj0555-001-p1s1">
<atree.rf>a#a-wsj0555-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0555-001-p1s1a1">
<a>
<lex.rf>a#a-wsj0555-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0555-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0555-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cena</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0555-001-p1s1a3">
<a>
<lex.rf>a#a-wsj0555-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>převodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0555-001-p1s1a5">
<a>
<lex.rf>a#a-wsj0555-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0555-001-p1s1a4">
<a>
<lex.rf>a#a-wsj0555-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>9.58</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0555-001-p1s1a7">
<a>
<lex.rf>a#a-wsj0555-001-p1s1W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0555-001-p1s1W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The conversion price is $9.58 a share.</eng_sentence>
</LM>
<LM id="T-wsj0555-001-p1s2">
<atree.rf>a#a-wsj0555-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0555-001-p1s2a1">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj0555-001-p1s2a2">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0555-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0555-001-p1s2a5">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0555-001-p1s2W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>EFF</functor>
<proto_lemma>mít</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41chlQ</val_frame.rf>
<children>
<LM id="T-wsj0555-001-p1s2a6">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>držitel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0555-001-p1s2a8">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>PAT</functor>
<deepord>6</deepord>
<children>
<LM id="T-wsj0555-001-p1s2a7">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>52</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0555-001-p1s2a9">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>částka</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0555-001-p1s0a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0555-001-p1s2a10">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jmenovitý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj0555-001-p1s2a11">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dluhopis</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0555-001-p1s0a16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0555-001-p1s2a12">
<a>
<lex.rf>a#a-wsj0555-001-p1s2W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The company said the holders represent 52% of the face amount of the debentures.</eng_sentence>
</LM>
<LM id="T-wsj0555-001-p1s3">
<atree.rf>a#a-wsj0555-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0555-001-p1s3a1">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dodávat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41wzC</val_frame.rf>
<children>
<LM id="T-wsj0555-001-p1s3a2">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>firma</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0555-001-p1s2a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0555-001-p1s3a3">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Waxman</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0555-001-p1s3a4">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>druh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0555-001-p1s3a5">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>různý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0555-001-p1s3a6">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produkt</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0555-001-p1s3a7">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hardwarový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0555-001-p1s3a9">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0555-001-p1s3W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trh</t_lemma>
<functor>DIR3</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0555-001-p1s3a10">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>domácí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0555-001-p1s3a12">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0555-001-p1s3W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>služba</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0555-001-p1s3a13">
<a>
<lex.rf>a#a-wsj0555-001-p1s3W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>servisní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Waxman sells a variety of hardware products for the home repair market.</eng_sentence>
</LM>
</trees>
</tdata>
