<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0316.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj0316-001-p1s0">
<atree.rf>a#a-wsj0316-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a30">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>First</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0316-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Security</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0316-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0316-001-p1s0a6">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s0a9">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s0W9-Ta</LM>
<LM>a#a-wsj0316-001-p1s0W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohodnout_se</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41yeA</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s0a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0316-001-p1s0a26">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0316-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předběžně</t_lemma>
<functor>MANN</functor>
<proto_lemma>předběžný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0316-001-p1s0a13">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s0W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>převzetí</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41intA</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s0a29">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s0a26</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0316-001-p1s0a14">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a31">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>15</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a16">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Deseret</t_lemma>
<functor>FPHR</functor>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0316-001-p1s0a15">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Bancorp</t_lemma>
<functor>FPHR</functor>
<deepord>17</deepord>
</LM>
<LM id="T-wsj0316-001-p1s0a32">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s0a19">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s0W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a21">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s0W20-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a24">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a22">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>18</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj0316-001-p1s0a23">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zhruba</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>21</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s0a25">
<a>
<lex.rf>a#a-wsj0316-001-p1s0W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>First Security Corp. said it tentatively agreed to acquire Deseret Bancorp. for stock valued at about $18 million.</eng_sentence>
</LM>
<LM id="T-wsj0316-001-p1s1">
<atree.rf>a#a-wsj0316-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a1">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyžadovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41pkgA</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podmínka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a3">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>smluvní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s1a6">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s1W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vydat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41nwvH</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s1a7">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s0a29</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0316-001-p1s1a31">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>5</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a9">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>First</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj0316-001-p1s1a8">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Security</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s1a26">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s1W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a27">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>každý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0316-001-p1s1a28">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vlastněný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0316-001-p1s1a29">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s0a14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0316-001-p1s1a30">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Deseret</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s1a16">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>neboli</t_lemma>
<functor>APPS</functor>
<deepord>20</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a10">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a11">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>0.55</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a12">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>asi</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s1a13">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitál</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a14">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>17</deepord>
<coref_gram.rf>
<LM>T-wsj0316-001-p1s1a7</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0316-001-p1s1a15">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akciový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s1a21">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a19">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>550000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a18">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celkem</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>21</deepord>
</LM>
<LM id="T-wsj0316-001-p1s1a20">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zhruba</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s1a22">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s1a14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0316-001-p1s1a32">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>26</deepord>
<children>
<LM id="T-wsj0316-001-p1s1a24">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W29-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>First</t_lemma>
<functor>FPHR</functor>
<deepord>27</deepord>
</LM>
<LM id="T-wsj0316-001-p1s1a23">
<a>
<lex.rf>a#a-wsj0316-001-p1s1W30-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Security</t_lemma>
<functor>FPHR</functor>
<deepord>28</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Terms call for First Security to issue about 0.55 share of its stock for each Deseret share held, or a total of about 550,000 First Security shares.</eng_sentence>
</LM>
<LM id="T-wsj0316-001-p1s2">
<atree.rf>a#a-wsj0316-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0316-001-p1s2a1">
<a>
<lex.rf>a#a-wsj0316-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41chlJ</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s2a8">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s1a22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0316-001-p1s2a3">
<a>
<lex.rf>a#a-wsj0316-001-p1s2W2-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s2W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oběh</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj0316-001-p1s2a6">
<a>
<lex.rf>a#a-wsj0316-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0316-001-p1s2a5">
<a>
<lex.rf>a#a-wsj0316-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>12.3</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0316-001-p1s2a4">
<a>
<lex.rf>a#a-wsj0316-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližně</t_lemma>
<functor>EXT</functor>
<proto_lemma>přibližný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s2a7">
<a>
<lex.rf>a#a-wsj0316-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>It has about 12.3 million shares outstanding.</eng_sentence>
</LM>
<LM id="T-wsj0316-001-p1s3">
<atree.rf>a#a-wsj0316-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a1">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s3a2">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s1a29</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0316-001-p1s3a3">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Deseret</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj0316-001-p1s3a6">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s3W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a7">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>100</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a8">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zhruba</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s3a9">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a11">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s3W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>aktivum</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s3a13">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a14">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mateřský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0316-001-p1s3a15">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>banka</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a31">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>12</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a16">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W16-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Deseret</t_lemma>
<functor>FPHR</functor>
<deepord>13</deepord>
</LM>
<LM id="T-wsj0316-001-p1s3a17">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W17-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Bank</t_lemma>
<functor>FPHR</functor>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s3a19">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>RSTR</functor>
<proto_lemma>mít</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41chlJ</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s3a21">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>15</deepord>
<coref_gram.rf>
<LM>T-wsj0316-001-p1s3a15</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0316-001-p1s3a18">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W23-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>19</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a22">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kancelář</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a23">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>šest</t_lemma>
<functor>RSTR</functor>
<proto_lemma>šest</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>17</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s3a24">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ústředí</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s3a26">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W26-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s3W25-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a32">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>22</deepord>
<children>
<LM id="T-wsj0316-001-p1s3a28">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W27-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Pleasant</t_lemma>
<functor>FPHR</functor>
<deepord>23</deepord>
</LM>
<LM id="T-wsj0316-001-p1s3a27">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W28-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Grove</t_lemma>
<functor>FPHR</functor>
<deepord>24</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s3a30">
<a>
<lex.rf>a#a-wsj0316-001-p1s3W30-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s3W29-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Utah</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Deseret, with about $100 million in assets, is the parent of the Deseret Bank, which has six offices and headquarters at Pleasant Grove, Utah.</eng_sentence>
</LM>
<LM id="T-wsj0316-001-p1s4">
<atree.rf>a#a-wsj0316-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a1">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s4W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rovnat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41jlmB</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s4a2">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cena</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a3">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kupní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s4a8">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>násobek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a5">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1.65</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a6">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>asi</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s4a11">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W12-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>neboli</t_lemma>
<functor>APPS</functor>
<deepord>9</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a9">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a10">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>účetní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s4a13">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>aktivum</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a15">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s4W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pasívum</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s4a17">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s3a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0316-001-p1s4a18">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Deseret</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s4a20">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s4W19-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výše</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a21">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
<LM id="T-wsj0316-001-p1s4a23">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj0316-001-p1s4a22">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>10.7</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0316-001-p1s4a24">
<a>
<lex.rf>a#a-wsj0316-001-p1s4W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The purchase price is equal to about 1.65 times Deseret's roughly $10.7 million book value, or assets less liabilities.</eng_sentence>
</LM>
<LM id="T-wsj0316-001-p1s5">
<atree.rf>a#a-wsj0316-001-p1s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a1">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s5a2">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s2a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0316-001-p1s5a41">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a4">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>First</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0316-001-p1s5a3">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Security</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s5a6">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s5W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sídlo</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a42">
<a>
<aux.rf>
<LM>a#a-wsj0316-001-p1s5W6-Ta</LM>
</aux.rf>
</a>
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>LOC</functor>
<deepord>6</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a8">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W7-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Salt</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj0316-001-p1s5a10">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Lake</t_lemma>
<functor>FPHR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0316-001-p1s5a9">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W9-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>City</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s5a12">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>RSTR</functor>
<proto_lemma>mít</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41chlK</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s5a13">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>10</deepord>
<coref_gram.rf>
<LM>T-wsj0316-001-p1s5a2</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0316-001-p1s5a15">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>miliarda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a14">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>5.4</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj0316-001-p1s5a16">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s5a18">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s5W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>aktivum</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s5a22">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W29-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>25</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a24">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s5W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>EFF</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>18</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s5a23">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohoda</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s0a9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0316-001-p1s5a26">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podmíněný</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a25">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>schválení</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>21</deepord>
<val_frame.rf>v#v41knuA</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s5a38">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s5a23</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0316-001-p1s5a27">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W27-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>23</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a28">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcionář</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
<LM id="T-wsj0316-001-p1s5a29">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>regulátor</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0316-001-p1s5a30">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W30-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s5W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doufat</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>27</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0316-001-p1s5a24</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj0316-001-p1s5a22</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41aiaB</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s5a39">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>26</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s5a13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0316-001-p1s5a33">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W34-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s5W32-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dokončit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>30</deepord>
<val_frame.rf>v#v41ztB</val_frame.rf>
<children>
<LM id="T-wsj0316-001-p1s5a40">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>28</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0316-001-p1s5a39</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0316-001-p1s5a34">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>transakce</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
</LM>
<LM id="T-wsj0316-001-p1s5a36">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W37-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0316-001-p1s5W35-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>32</deepord>
<children>
<LM id="T-wsj0316-001-p1s5a37">
<a>
<lex.rf>a#a-wsj0316-001-p1s5W36-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příští</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>31</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Salt Lake City-based First Security, with $5.4 billion in assets, said the agreement is subject to shareholder and regulatory approval, and that it hopes to complete the transaction early next year.</eng_sentence>
</LM>
</trees>
</tdata>
