<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0993.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj0993-001-p1s0">
<atree.rf>a#a-wsj0993-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a29">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Parker</t_lemma>
<functor>FPHR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0993-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Hannifin</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0993-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj0993-001-p1s0a6">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s0a9">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s0W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>souhlasit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>9</deepord>
<val_frame.rf>v#v41kypC</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s0a28">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0993-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s0W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodej</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a12">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>divize</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a13">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>10</deepord>
<coref_gram.rf>
<LM>T-wsj0993-001-p1s0a28</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0993-001-p1s0a14">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj0993-001-p1s0a16">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s0W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výroba</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a17">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>součástka</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a18">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>automobilový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s0a19">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skupina</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a20">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>investor</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
<LM id="T-wsj0993-001-p1s0a21">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řízený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a22">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>management</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s0a25">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s0W23-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj0993-001-p1s0a24">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>80</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>21</deepord>
</LM>
<LM id="T-wsj0993-001-p1s0a26">
<a>
<lex.rf>a#a-wsj0993-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Parker Hannifin Corp. said it agreed to sell its three automotive parts divisions to a management-led investor group for $80 million.</eng_sentence>
</LM>
<LM id="T-wsj0993-001-p1s1">
<atree.rf>a#a-wsj0993-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0993-001-p1s1a1">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>11</deepord>
<children>
<LM id="T-wsj0993-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řídit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41kegA</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s1a3">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skupina</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s0a19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0993-001-p1s1a4">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skupující</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s1a5">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>7</deepord>
<children>
<LM id="T-wsj0993-001-p1s1a6">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Lederer</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0993-001-p1s1a7">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Paul</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0993-001-p1s1a8">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>R</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s1a10">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0993-001-p1s1a11">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skupina</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0993-001-p1s1a12">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s0a13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0993-001-p1s1a13">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>automobilový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0993-001-p1s1a14">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Parker</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s1a16">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tvořit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>15</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0993-001-p1s1a2</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj0993-001-p1s1a1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41mepB</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s1a17">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s1a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0993-001-p1s1a19">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>člen</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj0993-001-p1s1a18">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>několik</t_lemma>
<functor>RSTR</functor>
<proto_lemma>kolik</proto_lemma>
<gram>
<sempos>adj.quant.indef</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0993-001-p1s1a20">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
<LM id="T-wsj0993-001-p1s1a21">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vedení</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0993-001-p1s1a22">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>divize</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s0a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0993-001-p1s1a23">
<a>
<lex.rf>a#a-wsj0993-001-p1s1W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The buy-out group is headed by Paul R. Lederer, president of Parker's automotive group, and includes several other executives of the three divisions.</eng_sentence>
</LM>
<LM id="T-wsj0993-001-p1s2">
<atree.rf>a#a-wsj0993-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0993-001-p1s2a1">
<a>
<lex.rf>a#a-wsj0993-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s2a2">
<a>
<lex.rf>a#a-wsj0993-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednotka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s1a22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0993-001-p1s2a3">
<a>
<lex.rf>a#a-wsj0993-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s2a5">
<a>
<lex.rf>a#a-wsj0993-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>divize</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0993-001-p1s2a6">
<a>
<lex.rf>a#a-wsj0993-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>7</deepord>
<children>
<LM id="T-wsj0993-001-p1s2a4">
<a>
<lex.rf>a#a-wsj0993-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Edelmann</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0993-001-p1s2a8">
<a>
<lex.rf>a#a-wsj0993-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ideal</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj0993-001-p1s2a9">
<a>
<lex.rf>a#a-wsj0993-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Plews</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The units are the Edelmann, Ideal and Plews divisions.</eng_sentence>
</LM>
<LM id="T-wsj0993-001-p1s3">
<atree.rf>a#a-wsj0993-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0993-001-p1s3a1">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41jsU</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s3a2">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obrat</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0993-001-p1s3a3">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čistý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0993-001-p1s3a5">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s3W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednotka</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s2a5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0993-001-p1s3a6">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s3a8">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s3W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0993-001-p1s3a9">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fiskální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0993-001-p1s3a10">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>končící</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0993-001-p1s3a11">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>červen</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0993-001-p1s3a12">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s3W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>30</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s3a15">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj0993-001-p1s3a14">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>135.6</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj0993-001-p1s3a16">
<a>
<lex.rf>a#a-wsj0993-001-p1s3W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Net sales for the units for the fiscal year ended June 30 were $135.6 million.</eng_sentence>
</LM>
<LM id="T-wsj0993-001-p1s4">
<atree.rf>a#a-wsj0993-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0993-001-p1s4a1">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s4a2">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představitel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0993-001-p1s4a3">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s1a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0993-001-p1s4a4">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Parker</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0993-001-p1s4a7">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s4W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodávat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41hblA</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s4a21">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s1a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0993-001-p1s4a8">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s4a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0993-001-p1s4a9">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednotka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s3a5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0993-001-p1s4a13">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s4W13-Ta</LM>
<LM>a#a-wsj0993-001-p1s4W12-Ta</LM>
<LM>a#a-wsj0993-001-p1s4W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaměřit_se</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>10</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0993-001-p1s4a7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>purp</discourse_type>
<sense_PDTB3>Contingency.Purpose.Arg2-as-goal</sense_PDTB3>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj0993-001-p1s4W12-Ta</LM>
<LM>a#a-wsj0993-001-p1s4W10-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41qayA</val_frame.rf>
<children>
<LM id="T-wsj0993-001-p1s4a22">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0993-001-p1s4a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0993-001-p1s4a16">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0993-001-p1s4W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj0993-001-p1s4a17">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>11</deepord>
<coref_gram.rf>
<LM>T-wsj0993-001-p1s4a22</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0993-001-p1s4a18">
<a>
<lex.rf>a#a-wsj0993-001-p1s4W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Parker officials said the company is selling the units to focus on its other businesses.</eng_sentence>
</LM>
</trees>
</tdata>
