<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj1091.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj1091-001-p1s0">
<atree.rf>a#a-wsj1091-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a1">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oznámit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41fgeB</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s0a31">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a2">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a30">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>4</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a4">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Quickview</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a34">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a5">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Systems</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a3">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s0a9">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s0W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>10</deepord>
<val_frame.rf>v#v41fqjI</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s0a32">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s0a39">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>LOC</functor>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a10">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žaloba</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a12">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s0W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a35">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>16</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a36">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>17</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a14">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Apple</t_lemma>
<functor>FPHR</functor>
<deepord>18</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a15">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Computer</t_lemma>
<functor>FPHR</functor>
<deepord>19</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a13">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s0a37">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s0W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>porušení</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41gjuA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s0a38">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s0a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s0a19">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ochrana</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a20">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>patentový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>21</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s0a22">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W22-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s0W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>část</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a23">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>26</deepord>
<children>
<LM id="T-wsj1091-001-p1s0a24">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>populární</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>24</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a25">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>softwarový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a26">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>HyperCard</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>27</deepord>
</LM>
<LM id="T-wsj1091-001-p1s0a27">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>28</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s0a38</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s0a28">
<a>
<lex.rf>a#a-wsj1091-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Apple</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Quickview Systems Inc. said it filed a lawsuit against Apple Computer Inc., claiming patent infringement in an element of Apple's popular HyperCard software program.</eng_sentence>
</LM>
<LM id="T-wsj1091-001-p1s1">
<atree.rf>a#a-wsj1091-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a1">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohlašovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41hdgB</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s1a2">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žaloba</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s0a10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s1a3">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1091-001-p1s1a4">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a7">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s1W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soud</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a8">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>federální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1091-001-p1s1a9">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a10">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Minneapolis</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s1a14">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s1W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>porušit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41gjvB</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s1a15">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s0a27</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s1a16">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Apple</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s1a17">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>patent</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a18">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s0a32</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s1a19">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Quickview</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s1a20">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>umožňovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41mppA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s1a22">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>15</deepord>
<coref_gram.rf>
<LM>T-wsj1091-001-p1s1a17</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1091-001-p1s1a24">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uživatel</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a25">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počítač</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s1a23">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zobrazovat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>20</deepord>
<val_frame.rf>v#v41rqmA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s1a44">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>17</deepord>
<coref_gram.rf>
<LM>T-wsj1091-001-p1s1a24</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1091-001-p1s1a31">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W29-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s1W27-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obrazovka</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a32">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počítačový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s1a34">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W30-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>pouze</t_lemma>
<functor>RHEM</functor>
<deepord>24</deepord>
</LM>
<LM id="T-wsj1091-001-p1s1a33">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>část</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a35">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pole</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>27</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a36">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W32-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vícenásobný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s1a27">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W35-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s1W34-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>možnost</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>28</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a28">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W36-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vidět</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>29</deepord>
<val_frame.rf>v#v41nlfH</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s1a46">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>21</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s1a44</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s1a37">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W38-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obsah</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>31</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a38">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W37-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>30</deepord>
</LM>
<LM id="T-wsj1091-001-p1s1a39">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W41-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pole</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>34</deepord>
<children>
<LM id="T-wsj1091-001-p1s1a40">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W39-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jakýkoliv</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jaký</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>32</deepord>
</LM>
<LM id="T-wsj1091-001-p1s1a41">
<a>
<lex.rf>a#a-wsj1091-001-p1s1W40-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>určitý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>33</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The suit, filed in Minneapolis federal court, claims that Apple violated a Quickview patent that allows computer users to display ``only portions of multiple fields on a computer screen with the ability to see the entire contents of any given field.''</eng_sentence>
</LM>
<LM id="T-wsj1091-001-p1s2">
<atree.rf>a#a-wsj1091-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1091-001-p1s2a17">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W18-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>16</deepord>
<children>
<LM id="T-wsj1091-001-p1s2a1">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dovolovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41aitA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s2a3">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s0a23</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s2a2">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>HyperCard</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s2a5">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uživatel</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1091-001-p1s2a10">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W11-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>aniž</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="T-wsj1091-001-p1s2a4">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>navrhovat</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41dhaD</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s2a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>4</deepord>
<coref_gram.rf>
<LM>T-wsj1091-001-p1s2a5</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1091-001-p1s2a6">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>aplikace</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj1091-001-p1s2a8">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s2W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počítač</t_lemma>
<functor>BEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1091-001-p1s2a9">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Macintosh</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s2a32">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>CM</functor>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1091-001-p1s2a14">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s2W13-Ta</LM>
<LM>a#a-wsj1091-001-p1s2W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>12</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s2a33">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s2a27</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s2a15">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>programátor</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj1091-001-p1s2a16">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>opravdový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s2a20">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W20-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s2W19-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>distribuovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>17</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1091-001-p1s2a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj1091-001-p1s2a17</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41uwB</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s2a34">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s2a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s2a30">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>19</deepord>
</LM>
<LM id="T-wsj1091-001-p1s2a22">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s2W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počítač</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj1091-001-p1s2a23">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>každý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>20</deepord>
</LM>
<LM id="T-wsj1091-001-p1s2a24">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>21</deepord>
</LM>
<LM id="T-wsj1091-001-p1s2a25">
<a>
<lex.rf>a#a-wsj1091-001-p1s2W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Macintosh</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The HyperCard program allows users to design applications for Macintosh computers without having to be hardcore programmers and is distributed with every Macintosh sold.</eng_sentence>
</LM>
<LM id="T-wsj1091-001-p1s3">
<atree.rf>a#a-wsj1091-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1091-001-p1s3a1">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W11-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ale</t_lemma>
<functor>ADVS</functor>
<deepord>9</deepord>
<children>
<LM id="T-wsj1091-001-p1s3a2">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>1</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s3a3">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s2a34</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s3a4">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jeden</t_lemma>
<functor>PAT</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj1091-001-p1s3a6">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s3W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj1091-001-p1s3a7">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>populární</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1091-001-p1s3a8">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počítačový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1091-001-p1s3a9">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doba</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj1091-001-p1s3a10">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s3a12">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohlásit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1091-001-p1s3a2</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj1091-001-p1s3a1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41hddB</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s3a13">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>analytik</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj1091-001-p1s3a23">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s3W20-Ta</LM>
<LM>a#a-wsj1091-001-p1s3W19-Ta</LM>
<LM>a#a-wsj1091-001-p1s3W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>způsobit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>17</deepord>
<val_frame.rf>v#v41rvuA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s3a17">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žaloba</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s1a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s3a18">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s1a18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s3a19">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Quickview</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s3a21">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s1a15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s3a22">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Apple</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s3a26">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>18</deepord>
</LM>
<LM id="T-wsj1091-001-p1s3a24">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potíž</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj1091-001-p1s3a25">
<a>
<lex.rf>a#a-wsj1091-001-p1s3W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>velký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>It's one of the most popular computer programs of all time, but analysts said the Quickview suit doesn't appear to bode major difficulties for Apple.</eng_sentence>
</LM>
<LM id="T-wsj1091-001-p1s4">
<atree.rf>a#a-wsj1091-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1091-001-p1s4a1">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s4a25">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1091-001-p1s4a2">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>EFF</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s4a27">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1091-001-p1s4a6">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>technologie</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj1091-001-p1s4a7">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zmíněný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s4a5">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s4W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vědět</t_lemma>
<functor>COND</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1091-001-p1s4a2</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>f_cond</discourse_type>
<sense_PDTB3>Contingency.Condition+SpeechAct</sense_PDTB3>
<sense_PDTB3_manual>Contingency.Condition+SpeechAct</sense_PDTB3_manual>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj1091-001-p1s4W4-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41nihC</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s4a31">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s4a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s4a30">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s4a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s4a10">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>technologie</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj1091-001-p1s4a11">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podstatný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1091-001-p1s4a12">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s3a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s4a13">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>HyperCard</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s4a17">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W17-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>16</deepord>
<children>
<LM id="T-wsj1091-001-p1s4a15">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Goodman</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj1091-001-p1s4a16">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Danny</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s4a18">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vývojář</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1091-001-p1s4a19">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s4a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s4a20">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>HyperCard</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s4a22">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W22-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s4W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oblast</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj1091-001-p1s4a29">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>RSTR</functor>
<deepord>21</deepord>
<children>
<LM id="T-wsj1091-001-p1s4a24">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W23-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>San</t_lemma>
<functor>FPHR</functor>
<deepord>22</deepord>
</LM>
<LM id="T-wsj1091-001-p1s4a23">
<a>
<lex.rf>a#a-wsj1091-001-p1s4W24-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Franciska</t_lemma>
<functor>FPHR</functor>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The technology at issue ``is not an underlying technology of HyperCard to my knowledge,'' said Danny Goodman, a San Francisco-area HyperCard program developer.</eng_sentence>
</LM>
<LM id="T-wsj1091-001-p1s5">
<atree.rf>a#a-wsj1091-001-p1s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1091-001-p1s5a2">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>požadovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1091-001-p1s4a2</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>A_I_A</src>
<t-connectors.rf>
<LM>T-wsj1091-001-p1s5a1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41gxnA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s5a3">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žaloba</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s3a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s5a1">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W2-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>nicméně</t_lemma>
<functor>PREC</functor>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1091-001-p1s5a4">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odškodnění</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj1091-001-p1s5a5">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>specifikovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1091-001-p1s5a6">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohlásit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41hddB</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s5a9">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s5W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>6</deepord>
<coref_gram.rf>
<LM>T-wsj1091-001-p1s5a4</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1091-001-p1s5a10">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zástupce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj1091-001-p1s5a11">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>právní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1091-001-p1s5a12">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s3a18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s5a13">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Quickview</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s5a18">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s5W17-Ta</LM>
<LM>a#a-wsj1091-001-p1s5W16-Ta</LM>
<LM>a#a-wsj1091-001-p1s5W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosáhnout</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41afbA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s5a23">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s5a9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s5a19">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj1091-001-p1s5a20">
<a>
<lex.rf>a#a-wsj1091-001-p1s5W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Nonetheless, the suit seeks unspecified damages that an attorney for Quickview claimed could run into the millions of dollars.</eng_sentence>
</LM>
<LM id="T-wsj1091-001-p1s6">
<atree.rf>a#a-wsj1091-001-p1s6</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1091-001-p1s6a1">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohlásit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41hddB</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s6a3">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s3a21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s6a2">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Apple</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1091-001-p1s6a5">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s6W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Cupertino</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj1091-001-p1s6a7">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s6W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kalifornie</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s6a11">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s6W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>EFF</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s6a32">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s6a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s6a12">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přesvědčený</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj1091-001-p1s6a8">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W18-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>16</deepord>
<children>
<LM id="T-wsj1091-001-p1s6a15">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s6W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PAT</functor>
<proto_lemma>mít</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41chlAK</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s6a33">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1091-001-p1s6a16">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>případ</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<coref_special>segm</coref_special>
</LM>
<LM id="T-wsj1091-001-p1s6a17">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>opodstatnění</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj1091-001-p1s6a18">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žádný</t_lemma>
<functor>THO</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj1091-001-p1s6a36">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<deepord>14</deepord>
</LM>
<LM id="T-wsj1091-001-p1s6a35">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s6a20">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W22-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s6W19-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>porušovat</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>20</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1091-001-p1s6a15</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj1091-001-p1s6a8</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41gjxA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s6a34">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>17</deepord>
</LM>
<LM id="T-wsj1091-001-p1s6a21">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>program</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s4a19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s6a22">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>HyperCard</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s6a23">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>požadavek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj1091-001-p1s6a25">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žádný</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>21</deepord>
</LM>
<LM id="T-wsj1091-001-p1s6a26">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>platný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
<LM id="T-wsj1091-001-p1s6a27">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>patent</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj1091-001-p1s6a29">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s5a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s6a30">
<a>
<lex.rf>a#a-wsj1091-001-p1s6W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Quickview</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>In Cupertino, Calif., Apple said that it believes the case has no merit, and that HyperCard does not infringe ``any valid claims'' of the Quickview patents.</eng_sentence>
</LM>
<LM id="T-wsj1091-001-p1s7">
<atree.rf>a#a-wsj1091-001-p1s7</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1091-001-p1s7a1">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41ndjB</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s7a25">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s6a32</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s7a4">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s7W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>10</deepord>
<val_frame.rf>v#v41fqjI</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s7a26">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s7a25</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s7a6">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s7W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soud</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj1091-001-p1s7a7">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>federální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1091-001-p1s7a27">
<a>
<aux.rf>
<LM>a#a-wsj1091-001-p1s7W7-Ta</LM>
</aux.rf>
</a>
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>LOC</functor>
<deepord>6</deepord>
<children>
<LM id="T-wsj1091-001-p1s7a10">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>San</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1091-001-p1s7a9">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W9-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Jose</t_lemma>
<functor>FPHR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1091-001-p1s7a12">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s7W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kalifornie</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s6a7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s7a13">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žaloba</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1091-001-p1s7a14">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vlastní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1091-001-p1s7a15">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s7W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>domáhat_se</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41aazA</val_frame.rf>
<children>
<LM id="T-wsj1091-001-p1s7a17">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>MEANS</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>13</deepord>
<coref_gram.rf>
<LM>T-wsj1091-001-p1s7a13</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1091-001-p1s7a28">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s7a26</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1091-001-p1s7a19">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohlášení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj1091-001-p1s7a29">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>17</deepord>
</LM>
<LM id="T-wsj1091-001-p1s7a20">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>požadavek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj1091-001-p1s7a21">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1091-001-p1s6a29</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1091-001-p1s7a22">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Quickview</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1091-001-p1s7a24">
<a>
<lex.rf>a#a-wsj1091-001-p1s7W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1091-001-p1s7W23-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>platný</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>It said it filed an action of its own in federal court in San Jose, Calif., seeking a declaration that Quickview's claims are invalid.</eng_sentence>
</LM>
</trees>
</tdata>
