<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj1925.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj1925-001-p1s0">
<atree.rf>a#a-wsj1925-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a26">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W31-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1925-001-p1s0W30-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jmenovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>29</deepord>
<val_frame.rf>v#v41biqB</val_frame.rf>
<children>
<LM id="T-wsj1925-001-p1s0a1">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>4</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a2">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Mitchell</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a3">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Charles</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a4">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>S</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s0a7">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>viceprezident</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a9">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>12</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a8">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a40">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>6</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a37">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Homart</t_lemma>
<functor>FPHR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a38">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W9-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Development</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a6">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Co</t_lemma>
<functor>FPHR</functor>
<deepord>10</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a39">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s0a10">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a11">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přidružený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a12">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1925-001-p1s0W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zabývající_se</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a14">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozvoj</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a15">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemovitost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s0a16">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>patřit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>19</deepord>
<val_frame.rf>v#v41fjzB</val_frame.rf>
<children>
<LM id="T-wsj1925-001-p1s0a18">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>18</deepord>
<coref_gram.rf>
<LM>T-wsj1925-001-p1s0a9</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1925-001-p1s0a19">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a44">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>21</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a20">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Sears</t_lemma>
<functor>FPHR</functor>
<deepord>22</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a45">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>,</t_lemma>
<functor>FPHR</functor>
<deepord>23</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a23">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W25-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Roebuck</t_lemma>
<functor>FPHR</functor>
<deepord>24</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a24">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>&amp;</t_lemma>
<functor>FPHR</functor>
<deepord>25</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a22">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Co</t_lemma>
<functor>FPHR</functor>
<deepord>26</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a25">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s0a41">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>28</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a28">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W32-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>30</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a43">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W36-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>35</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a29">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>31</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a42">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>32</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a30">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W34-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Figgie</t_lemma>
<functor>FPHR</functor>
<deepord>33</deepord>
</LM>
<LM id="T-wsj1925-001-p1s0a31">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W35-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Properties</t_lemma>
<functor>FPHR</functor>
<deepord>34</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s0a33">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W37-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednotka</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>36</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a34">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W38-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozvoj</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>37</deepord>
<children>
<LM id="T-wsj1925-001-p1s0a35">
<a>
<lex.rf>a#a-wsj1925-001-p1s0W39-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemovitost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>38</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Charles S. Mitchell, a vice president with Homart Development Co., the real estate development subsidiary of Sears, Roebuck &amp; Co., was named president of Figgie Properties, a real estate development unit.</eng_sentence>
</LM>
<LM id="T-wsj1925-001-p1s1">
<atree.rf>a#a-wsj1925-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1925-001-p1s1a1">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nahradit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41cqbC</val_frame.rf>
<children>
<LM id="T-wsj1925-001-p1s1a12">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1925-001-p1s0a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1925-001-p1s1a2">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kohut</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj1925-001-p1s1a3">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>William</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1925-001-p1s1a4">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rezignovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41jkhA</val_frame.rf>
<children>
<LM id="T-wsj1925-001-p1s1a13">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1925-001-p1s0a28</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1925-001-p1s1a6">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>6</deepord>
<coref_gram.rf>
<LM>T-wsj1925-001-p1s1a2</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1925-001-p1s1a7">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>již</t_lemma>
<functor>RHEM</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1925-001-p1s1a8">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>brzy</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.grad.nneg</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1925-001-p1s1a10">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1925-001-p1s1W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<coref_special>exoph</coref_special>
<children>
<LM id="T-wsj1925-001-p1s1a11">
<a>
<lex.rf>a#a-wsj1925-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>He succeeds William Kohut, who resigned earlier this year.</eng_sentence>
</LM>
<LM id="T-wsj1925-001-p1s2">
<atree.rf>a#a-wsj1925-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a1">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1925-001-p1s2W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jmenovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1925-001-p1s0a26</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>1</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_I_A</src>
<t-connectors.rf>
<LM>T-wsj1925-001-p1s2a4</LM>
</t-connectors.rf>
<is_secondary>1</is_secondary>
</LM>
</discourse>
<val_frame.rf>v#v41biqB</val_frame.rf>
<children>
<LM id="T-wsj1925-001-p1s2a38">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a4">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W2-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1925-001-p1s2W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>RESTR</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1925-001-p1s0a26</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1925-001-p1s2a39">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>6</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a8">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Barkley</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a9">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Richard</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a10">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>A</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s2a5">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovník</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a6">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bývalý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a13">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vedoucí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a14">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>marketing</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a15">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a40">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>12</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a16">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W14-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>FMC</t_lemma>
<functor>FPHR</functor>
<deepord>13</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a17">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W15-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>14</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a18">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W16-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s2a19">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a42">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W24-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>23</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a20">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a41">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>19</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a24">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W21-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Continental</t_lemma>
<functor>FPHR</functor>
<deepord>20</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a25">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W22-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Container</t_lemma>
<functor>FPHR</functor>
<deepord>21</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a23">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W23-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Systems</t_lemma>
<functor>FPHR</functor>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s2a22">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výrobce</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a26">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zařízení</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>27</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a27">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konzervárenský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
<LM id="T-wsj1925-001-p1s2a28">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>strojní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s2a29">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>získat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>31</deepord>
<val_frame.rf>v#v41reiB</val_frame.rf>
<children>
<LM id="T-wsj1925-001-p1s2a31">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>28</deepord>
<coref_gram.rf>
<LM>T-wsj1925-001-p1s2a42</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1925-001-p1s2a32">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1925-001-p1s0a43</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1925-001-p1s2a33">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W32-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Figgie</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>30</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s2a35">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W35-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1925-001-p1s2W34-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konec</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>32</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a36">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W37-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>34</deepord>
<children>
<LM id="T-wsj1925-001-p1s2a37">
<a>
<lex.rf>a#a-wsj1925-001-p1s2W36-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>minulý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>33</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Also, Richard A. Barkley, a former marketing executive with FMC Corp., was appointed president of Continental Container Systems, a producer of can closing machinery that Figgie acquired late last year.</eng_sentence>
</LM>
<LM id="T-wsj1925-001-p1s3">
<atree.rf>a#a-wsj1925-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1925-001-p1s3a1">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj1925-001-p1s3a2">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1925-001-p1s2a32</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1925-001-p1s3a3">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Figgie</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1925-001-p1s3a4">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podnik</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj1925-001-p1s3a5">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1925-001-p1s3W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zabývající_se</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj1925-001-p1s3a7">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výrobek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj1925-001-p1s3a8">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W10-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="T-wsj1925-001-p1s3a9">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>protipožární</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj1925-001-p1s3a11">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>elektronický</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1925-001-p1s3a12">
<a>
<lex.rf>a#a-wsj1925-001-p1s3W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průmyslový</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Figgie is a fire protection, electronics and industrial products concern.</eng_sentence>
</LM>
</trees>
</tdata>
