<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj1062.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj1062-001-p1s0">
<atree.rf>a#a-wsj1062-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s0a23">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>avšak</t_lemma>
<functor>ADVS</functor>
<deepord>19</deepord>
<children>
<LM id="T-wsj1062-001-p1s0a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>požádat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41gxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s0a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dům</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1062-001-p1s0a3">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bílý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s0a4">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kongres</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1062-001-p1s0a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s0W8-Ta</LM>
<LM>a#a-wsj1062-001-p1s0W6-Ta</LM>
<LM>a#a-wsj1062-001-p1s0W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>připojit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41iweB</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s0a35">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s0a4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s0a10">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>9</deepord>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s0a37">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1062-001-p1s0a11">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>navrhovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1062-001-p1s0a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>daň</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj1062-001-p1s0a14">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s0W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1062-001-p1s0a15">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitálový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s0a17">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s0W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>DIR3</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj1062-001-p1s0a18">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konečný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj1062-001-p1s0a19">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj1062-001-p1s0a21">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s0W20-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>17</deepord>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s0a38">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>16</deepord>
</LM>
<LM id="T-wsj1062-001-p1s0a22">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>deficit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s0a25">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s0W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zdát_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>20</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s0a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj1062-001-p1s0a23</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41qxnD</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s0a41">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>21</deepord>
</LM>
<LM id="T-wsj1062-001-p1s0a29">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W33-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s0W28-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přijmout</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>27</deepord>
<val_frame.rf>v#v41isjF</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s0a40">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>22</deepord>
</LM>
<LM id="T-wsj1062-001-p1s0a30">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákonodárce</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj1062-001-p1s0a31">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>myšlenka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj1062-001-p1s0a32">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>24</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s0a33">
<a>
<lex.rf>a#a-wsj1062-001-p1s0W32-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>pravděpodobně</t_lemma>
<functor>MOD</functor>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The White House called on Congress to attach the proposed capital-gains tax cut to its final deficit-reduction bill, but lawmakers seem likely to balk at the idea.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s1">
<atree.rf>a#a-wsj1062-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpořit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41fuiB</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s1a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dům</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s1a3">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bílý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s1a5">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s1W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>začátek</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a6">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíc</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_special>exoph</coref_special>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s1a7">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stažení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41ljhA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s1a45">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj1062-001-p1s1a8">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>opatření</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s0a10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s1a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kontroverzní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1062-001-p1s1a10">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>daňový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s1a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s1W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s0a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s1a13">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s1a18">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s1W17-Ta</LM>
<LM>a#a-wsj1062-001-p1s1W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>schválit</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>15</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s1a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>purp</discourse_type>
<sense_PDTB3>Contingency.Purpose.Arg2-as-goal</sense_PDTB3>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj1062-001-p1s1W15-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41knwB</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s1a17">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kongres</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s0a35</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s1a19">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rychle</t_lemma>
<functor>MANN</functor>
<proto_lemma>rychlý</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
<LM id="T-wsj1062-001-p1s1a20">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a21">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čistý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj1062-001-p1s1a24">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
<LM id="T-wsj1062-001-p1s1a25">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obsahovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>20</deepord>
<val_frame.rf>v#v41dsuA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s1a27">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>19</deepord>
<coref_gram.rf>
<LM>T-wsj1062-001-p1s1a20</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1062-001-p1s1a28">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ustanovení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a29">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W28-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>pouze</t_lemma>
<functor>RHEM</functor>
<deepord>21</deepord>
</LM>
<LM id="T-wsj1062-001-p1s1a30">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>navržený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a31">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>speciálně</t_lemma>
<functor>MANN</functor>
<proto_lemma>speciální</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj1062-001-p1s1a33">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W33-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s1W32-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>účel</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a34">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W35-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozpočet</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>27</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a35">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W34-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>federální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s1a40">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W41-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s1W37-Ta</LM>
<LM>a#a-wsj1062-001-p1s1W36-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>31</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a38">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W39-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Dash</t_lemma>
<functor>CONJ</functor>
<deepord>29</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a39">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W38-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Grammův</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>28</deepord>
</LM>
<LM id="T-wsj1062-001-p1s1a41">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W40-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Rudmanův</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>30</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s1a43">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W44-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s1W42-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozpočet</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>33</deepord>
<children>
<LM id="T-wsj1062-001-p1s1a44">
<a>
<lex.rf>a#a-wsj1062-001-p1s1W43-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyrovnaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>32</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Earlier this month, the White House endorsed stripping the controversial tax measure from the bill so that Congress could pass quickly a ``clean'' bill containing only provisions specifically designed to meet federal budget targets under the Gramm-Rudman act.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s2">
<atree.rf>a#a-wsj1062-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a21">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>20</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s1a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>A_I_A</src>
<t-connectors.rf>
<LM>T-wsj1062-001-p1s2a1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s2a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>avšak</t_lemma>
<functor>PREC</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1062-001-p1s2a4">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nyní</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>teď</proto_lemma>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>2</deepord>
<coref_special>exoph</coref_special>
</LM>
<LM id="T-wsj1062-001-p1s2a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zmeškat</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a21</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Reason</sense_PDTB3>
<src>A_V_A</src>
<t-connectors.rf>
<LM>T-wsj1062-001-p1s2a4</LM>
<LM>T-wsj1062-001-p1s2a5</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41rknA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s2a5">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kdy</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>kdy</proto_lemma>
<gram>
<sempos>adv.pron.indef</sempos>
</gram>
<deepord>3</deepord>
<coref_gram.rf>
<LM>T-wsj1062-001-p1s2a4</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1062-001-p1s2a6">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kongres</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s1a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s2a7">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lhůta</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a8">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stanovený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s2a11">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s2W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>splnění</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>10</deepord>
<val_frame.rf>v#v41lccA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s2a53">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1062-001-p1s2a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cíl</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a15">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s1a40</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s2a14">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W14-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Dash</t_lemma>
<functor>CONJ</functor>
<deepord>13</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a13">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Grammův</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj1062-001-p1s2a16">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Rudmanův</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s2a18">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s2W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozpočet</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a19">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyrovnaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s2a22">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dům</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s1a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s2a23">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bílý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s2a26">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s2W26-Ta</LM>
<LM>a#a-wsj1062-001-p1s2W25-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vracet_se</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>22</deepord>
<val_frame.rf>v#v41npvA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s2a55">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>21</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s2a29">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W30-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s2W28-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>záměr</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a30">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>původní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj1062-001-p1s2a33">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W39-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s2W33-Ta</LM>
<LM>a#a-wsj1062-001-p1s2W32-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát_se</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>30</deepord>
<val_frame.rf>v#v41lioA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s2a35">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W34-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>26</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s1a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s2a57">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>25</deepord>
</LM>
<LM id="T-wsj1062-001-p1s2a36">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W35-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>daň</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>27</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s0a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s2a38">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W38-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s2W36-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a39">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W37-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitálový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>28</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s2a40">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W40-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>součást</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>31</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a41">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W41-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>32</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s1a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s2a42">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W42-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>33</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a46">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W44-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s2W43-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>35</deepord>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s2a59">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>34</deepord>
</LM>
<LM id="T-wsj1062-001-p1s2a47">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W45-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozpočet</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>36</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s2a43">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W52-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>41</deepord>
<val_frame.rf>v#v41gyaA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s2a49">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W48-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s2W47-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>37</deepord>
<coref_gram.rf>
<LM>T-wsj1062-001-p1s2a41</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1062-001-p1s2a50">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W49-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kongres</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>38</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s2a51">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W51-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nadále</t_lemma>
<functor>THL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>40</deepord>
<children>
<LM id="T-wsj1062-001-p1s2a52">
<a>
<lex.rf>a#a-wsj1062-001-p1s2W50-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<deepord>39</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>But now that Congress has missed the legal deadline for meeting the Gramm-Rudman targets, the White House said it has returned to its original view that a capital-gains cut should be part of the deficit-reduction bill, on which Congress continues to work.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s3">
<atree.rf>a#a-wsj1062-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s3a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>15</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s3a23">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1062-001-p1s3a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W11-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_dsp_root>1</is_dsp_root>
<deepord>10</deepord>
<children>
<LM id="T-wsj1062-001-p1s3a28">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a55</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s3a7">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s3W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>COND</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s3a2</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>cond</discourse_type>
<sense_PDTB3>Contingency.Condition.Arg2-as-cond</sense_PDTB3>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj1062-001-p1s3W2-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsU</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s3a25">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1062-001-p1s3a8">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a33</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s3a3">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tak</t_lemma>
<functor>MANN</functor>
<proto_lemma>tak</proto_lemma>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s3a4">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s3W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hledat</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41avoC</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s3a11">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cesta</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj1062-001-p1s3a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jiný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s3a13">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s3W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>usilovat</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s3a4</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj1062-001-p1s3a2</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41mveA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s3a15">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s3W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlasování</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41aviA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s3a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>12</deepord>
</LM>
<LM id="T-wsj1062-001-p1s3a16">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>samostatný</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s3a19">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Fitzwater</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj1062-001-p1s3a20">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mluvčí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1062-001-p1s3a21">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tiskový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s3a22">
<a>
<lex.rf>a#a-wsj1062-001-p1s3W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Marlin</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>``If that doesn't happen, then we press forward on another vehicle and a separate vote,'' said press secretary Marlin Fitzwater.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s4">
<atree.rf>a#a-wsj1062-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s4a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a26</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>1</target_range>
<discourse_type>opp</discourse_type>
<sense_PDTB3>Comparison.Concession.Arg2-as-denier</sense_PDTB3>
<src>A_I_A</src>
<t-connectors.rf>
<LM>T-wsj1062-001-p1s4a3</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41chlBA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s4a20">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1062-001-p1s4a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kapitol</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a50</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s4a3">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>však</t_lemma>
<functor>PREC</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1062-001-p1s4a4">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W3-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>patrně</t_lemma>
<functor>MOD</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1062-001-p1s4a5">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pochopení</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41fyoB</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s4a21">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s4a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s4a6">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dostatečný</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1062-001-p1s4a11">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s4W10-Ta</LM>
<LM>a#a-wsj1062-001-p1s4W8-Ta</LM>
<LM>a#a-wsj1062-001-p1s4W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spojit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>10</deepord>
<val_frame.rf>v#v41lcuA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s4a23">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s4a21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s4a25">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1062-001-p1s4a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W14-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>14</deepord>
<children>
<LM id="T-wsj1062-001-p1s4a13">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj1062-001-p1s4a14">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitálový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s4a15">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a49</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s4a16">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákon</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj1062-001-p1s4a18">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s4W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>18</deepord>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s4a24">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>17</deepord>
</LM>
<LM id="T-wsj1062-001-p1s4a19">
<a>
<lex.rf>a#a-wsj1062-001-p1s4W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>deficit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>On Capitol Hill, though, there doesn't seem to be sufficient sentiment to pair capital gains and the deficit-reduction bill.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s5">
<atree.rf>a#a-wsj1062-001-p1s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>17</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s5a37">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1062-001-p1s5a7">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W6-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>7</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a5">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Archer</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslanec</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a44">
<a>
<aux.rf>
<LM>a#a-wsj1062-001-p1s5W2-Ta</LM>
</aux.rf>
</a>
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>SUBS</functor>
<deepord>3</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a4">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Texas</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s5a6">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>William</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s5a8">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>republikán</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>starý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a10">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>služebně</t_lemma>
<functor>REG</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s5a11">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Výbor</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sněmovní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1062-001-p1s5a14">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s5W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>získávání</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41rejA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s5a38">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s5a11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s5a15">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prostředek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a16">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>finanční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s5a18">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vědět</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
</gram>
<deepord>21</deepord>
<val_frame.rf>v#v41nihC</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s5a40">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>18</deepord>
</LM>
<LM id="T-wsj1062-001-p1s5a39">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s5a7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s5a20">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s5W23-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>najít</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>23</deepord>
<val_frame.rf>v#v41croB</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s5a41">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>20</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s4a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s5a23">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kde</t_lemma>
<functor>LOC</functor>
<proto_lemma>kde</proto_lemma>
<gram>
<sempos>adv.pron.indef</sempos>
</gram>
<deepord>22</deepord>
</LM>
<LM id="T-wsj1062-001-p1s5a25">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlas</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a27">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s5W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpora</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s5a30">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W32-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s5W30-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dostat</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>28</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s5a20</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>purp</discourse_type>
<sense_PDTB3>Contingency.Purpose.Arg2-as-goal</sense_PDTB3>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj1062-001-p1s5W30-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41afvI</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s5a42">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>26</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s5a41</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s5a31">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tam</t_lemma>
<functor>DIR3</functor>
<proto_lemma>tam</proto_lemma>
<gram>
<sempos>adv.pron.def</sempos>
</gram>
<deepord>27</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s4a15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s5a32">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>30</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a35</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s5a43">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>29</deepord>
</LM>
<LM id="T-wsj1062-001-p1s5a33">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W34-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>daň</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>31</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s2a36</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s5a35">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W37-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s5W35-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>33</deepord>
<children>
<LM id="T-wsj1062-001-p1s5a36">
<a>
<lex.rf>a#a-wsj1062-001-p1s5W36-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitálový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>32</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Texas Rep. William Archer, the ranking Republican on the House Ways and Means Committee said, ``I don't see how we have the votes'' to place a capital-gains tax cut there.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s6">
<atree.rf>a#a-wsj1062-001-p1s6</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s6a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vystupňovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s4a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>1</target_range>
<discourse_type>synchr</discourse_type>
<sense_PDTB3>Temporal.Synchronous</sense_PDTB3>
<src>A_I_A</src>
<t-connectors.rf>
<LM>T-wsj1062-001-p1s6a4</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41ozfA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s6a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bush</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1062-001-p1s6a3">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s6a4">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mezitím</t_lemma>
<functor>TPAR</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1062-001-p1s6a5">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lobování</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj1062-001-p1s6a6">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osobní</t_lemma>
<functor>REG</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1062-001-p1s6a8">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s6W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s5a32</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s6a13">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1062-001-p1s6a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>daň</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s5a33</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s6a11">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s6W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj1062-001-p1s6a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s6W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitálový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Meanwhile, President Bush stepped up his personal lobbying for the capital-gains tax cut.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s7">
<atree.rf>a#a-wsj1062-001-p1s7</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s7a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s7a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dům</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s3a28</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s7a3">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bílý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s7a6">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s7W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>plánovat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41fmmA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s7a32">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s7a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s7a7">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uspořádat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41mxmD</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s7a33">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>6</deepord>
<coref_gram.rf>
<LM>T-wsj1062-001-p1s7a32</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1062-001-p1s7a8">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řada</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj1062-001-p1s7a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednání</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>12</deepord>
<val_frame.rf>v#v41bhqA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s7a36">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1062-001-p1s7a34">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s6a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s7a10">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>formální</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1062-001-p1s7a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s7W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dům</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj1062-001-p1s7a13">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bílý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s7a28">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s7W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>demokrat</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj1062-001-p1s7a14">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W15-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>převážně</t_lemma>
<functor>RHEM</functor>
<deepord>15</deepord>
</LM>
<LM id="T-wsj1062-001-p1s7a30">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s7W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Senát</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s7a17">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s7W22-Ta</LM>
<LM>a#a-wsj1062-001-p1s7W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pokusit_se</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>19</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s7a6</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>purp</discourse_type>
<sense_PDTB3>Contingency.Purpose.Arg2-as-goal</sense_PDTB3>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj1062-001-p1s7W21-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41gcbA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s7a37">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s7a33</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s7a19">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přimět</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>21</deepord>
<val_frame.rf>v#v41iubA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s7a38">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>20</deepord>
<coref_gram.rf>
<LM>T-wsj1062-001-p1s7a37</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1062-001-p1s7a20">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákonodárce</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
<LM id="T-wsj1062-001-p1s7a22">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s7W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpora</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj1062-001-p1s7a23">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>25</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s6a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s7a40">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>24</deepord>
</LM>
<LM id="T-wsj1062-001-p1s7a24">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>daň</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>27</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s6a9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1062-001-p1s7a25">
<a>
<lex.rf>a#a-wsj1062-001-p1s7W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The White House said he plans to hold a series of private White House meetings, mostly with Senate Democrats, to try to persuade lawmakers to fall in line behind the tax cut.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s8">
<atree.rf>a#a-wsj1062-001-p1s8</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s8a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W3-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s8W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uskutečnit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41mvqA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s8a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1062-001-p1s8a4">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>setkání</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41klfA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s8a17">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s7a34</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s8a5">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>THO</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1062-001-p1s8a7">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s8W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>demokrat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj1062-001-p1s8a8">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>deset</t_lemma>
<functor>RSTR</functor>
<proto_lemma>deset</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj1062-001-p1s8a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>senátní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1062-001-p1s8a10">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>projevit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>10</deepord>
<val_frame.rf>v#v41hfdC</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s8a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>9</deepord>
<coref_gram.rf>
<LM>T-wsj1062-001-p1s8a7</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1062-001-p1s8a13">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zájem</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj1062-001-p1s8a15">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s8W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s7a23</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s8a18">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>12</deepord>
</LM>
<LM id="T-wsj1062-001-p1s8a16">
<a>
<lex.rf>a#a-wsj1062-001-p1s8W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>daň</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s7a24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The first meeting yesterday was with 10 Senate Democrats who have expressed an interest in cutting the tax.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s9">
<atree.rf>a#a-wsj1062-001-p1s9</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s9a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvádět</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41nccF</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s9a3">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W3-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s9W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>účastník</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1062-001-p1s9a4">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>některý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s9a5">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>senátor</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s8a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s9a11">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s9W10-Ta</LM>
<LM>a#a-wsj1062-001-p1s9W8-Ta</LM>
<LM>a#a-wsj1062-001-p1s9W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>umožnit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41mpoA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s9a10">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s8a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s9a12">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vůdce</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj1062-001-p1s9a13">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>demokratický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1062-001-p1s9a15">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s9W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kongres</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s5a42</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s9a16">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vítězství</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj1062-001-p1s9a19">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W20-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s9W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kompenzovat</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1062-001-p1s9a11</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>purp</discourse_type>
<sense_PDTB3>Contingency.Purpose.Arg2-as-goal</sense_PDTB3>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj1062-001-p1s9W18-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41bohB</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s9a32">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s9a10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s9a20">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>BEN</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s9a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s9a21">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vítězství</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1062-001-p1s9a22">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpořený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj1062-001-p1s9a23">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s9a20</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s9a24">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vlastní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj1062-001-p1s9a26">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s9W25-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spor</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj1062-001-p1s9a27">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kontroverzní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
<LM id="T-wsj1062-001-p1s9a29">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W30-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s9W28-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj1062-001-p1s9a30">
<a>
<lex.rf>a#a-wsj1062-001-p1s9W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitálový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>According to some who attended, the senators argued that the president should give the Democratic leaders in Congress a victory of their own to compensate them for allowing the president to win on the controversial capital-gains issue.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s10">
<atree.rf>a#a-wsj1062-001-p1s10</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s10a11">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s10W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>týkat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41mexA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s10a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>otázka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj1062-001-p1s10a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s10W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>diskutovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41ulA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s10a25">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1062-001-p1s10a24">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1062-001-p1s10a5">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s10W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>4</deepord>
<coref_gram.rf>
<LM>T-wsj1062-001-p1s10a1</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1062-001-p1s10a8">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s10W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kontext</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj1062-001-p1s10a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s10a14">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W16-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>13</deepord>
<children>
<LM id="T-wsj1062-001-p1s10a13">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšení</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>10</deepord>
<val_frame.rf>v#v41sdgA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s10a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1062-001-p1s10a15">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mzda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1062-001-p1s10a16">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>minimální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1062-001-p1s10a17">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšení</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>15</deepord>
<val_frame.rf>v#v41sdgA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s10a28">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>14</deepord>
</LM>
<LM id="T-wsj1062-001-p1s10a18">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výdaj</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj1062-001-p1s10a20">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W20-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s10W19-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>péče</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1062-001-p1s10a22">
<a>
<lex.rf>a#a-wsj1062-001-p1s10W22-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s10W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dítě</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Issues discussed in this context were an increase in the minimum wage and an increase in child-care spending.</eng_sentence>
</LM>
<LM id="T-wsj1062-001-p1s11">
<atree.rf>a#a-wsj1062-001-p1s11</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1062-001-p1s11a1">
<a>
<lex.rf>a#a-wsj1062-001-p1s11W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s11W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyjádřit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41odaA</val_frame.rf>
<children>
<LM id="T-wsj1062-001-p1s11a8">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1062-001-p1s11a2">
<a>
<lex.rf>a#a-wsj1062-001-p1s11W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1062-001-p1s9a32</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1062-001-p1s11a6">
<a>
<lex.rf>a#a-wsj1062-001-p1s11W5-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>prý</t_lemma>
<functor>MOD</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1062-001-p1s11a7">
<a>
<lex.rf>a#a-wsj1062-001-p1s11W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednoznačně</t_lemma>
<functor>MANN</functor>
<proto_lemma>jednoznačný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1062-001-p1s11a9">
<a>
<lex.rf>a#a-wsj1062-001-p1s11W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1062-001-p1s11W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>PAT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>6</deepord>
<coref_special>segm</coref_special>
</LM>
</children>
</LM>
</children>
<eng_sentence>The president was said to have been noncommittal.</eng_sentence>
</LM>
</trees>
</tdata>
