<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj1016.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj1016-001-p1s0">
<atree.rf>a#a-wsj1016-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a1">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oznámit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>12</deepord>
<val_frame.rf>v#v41fgeB</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s0a32">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a2">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skupina</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a3">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>francouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a4">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chemický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a36">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>5</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a41">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Orkem</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a5">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>S</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a37">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a8">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>A</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a38">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s0a11">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s0W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>středa</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a14">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s0W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>učinit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41mgwG</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s0a34">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1016-001-p1s0a15">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nabídka</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a17">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s0W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dozor</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a40">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>22</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a19">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s0W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>LOC</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a39">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>18</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a21">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Coates</t_lemma>
<functor>FPHR</functor>
<deepord>19</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a22">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Brothers</t_lemma>
<functor>FPHR</functor>
<deepord>20</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a20">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>PLC</t_lemma>
<functor>FPHR</functor>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s0a24">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s0W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výrobce</t_lemma>
<functor>LOC</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a25">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>britský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a26">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>26</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a27">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>inkoust</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
<LM id="T-wsj1016-001-p1s0a28">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pryskyřice</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>28</deepord>
<children>
<LM id="T-wsj1016-001-p1s0a29">
<a>
<lex.rf>a#a-wsj1016-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>polyesterový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>French chemicals group, Orkem S.A., said Wednesday it has made a bid for control of Coates Brothers PLC, a British manufacturer of inks and polyester resins.</eng_sentence>
</LM>
<LM id="T-wsj1016-001-p1s1">
<atree.rf>a#a-wsj1016-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1016-001-p1s1a11">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vlastnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41nmxA</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s1a1">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s0a34</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1016-001-p1s1a2">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řízený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1016-001-p1s1a3">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s1a12">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Orkem</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s1a7">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>již</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1016-001-p1s1a9">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>PAT</functor>
<deepord>8</deepord>
<children>
<LM id="T-wsj1016-001-p1s1a8">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>40.6</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1016-001-p1s1a5">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s0a40</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1016-001-p1s1a13">
<a>
<lex.rf>a#a-wsj1016-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Coates</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>State-controlled Orkem already owns 40.6% of Coates.</eng_sentence>
</LM>
<LM id="T-wsj1016-001-p1s2">
<atree.rf>a#a-wsj1016-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1016-001-p1s2a1">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s2a14">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1016-001-p1s2a2">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mluvčí</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1016-001-p1s2a3">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skupina</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s1a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1016-001-p1s2a4">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>francouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s2a8">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s2W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>držet</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41alcI</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s2a9">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>část</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj1016-001-p1s2a10">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zbývající</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s2a7">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W11-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="T-wsj1016-001-p1s2a11">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veřejnost</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1016-001-p1s2a12">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rodina</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1016-001-p1s2a13">
<a>
<lex.rf>a#a-wsj1016-001-p1s2W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obchodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The remainder is held by the public and by family interests, a spokeswoman for the French group said.</eng_sentence>
</LM>
<LM id="T-wsj1016-001-p1s3">
<atree.rf>a#a-wsj1016-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1016-001-p1s3a2">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="T-wsj1016-001-p1s3a4">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s2a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1016-001-p1s3a5">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Orkem</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s3a3">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odmítnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41eedC</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s3a6">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poskytnout</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41glvA</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s3a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1016-001-p1s3a26">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>5</deepord>
<coref_gram.rf>
<LM>T-wsj1016-001-p1s3a4</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1016-001-p1s3a7">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>detail</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj1016-001-p1s3a9">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s3W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nabídka</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s0a15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1016-001-p1s3a10">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>8</deepord>
<coref_gram.rf>
<LM>T-wsj1016-001-p1s3a26</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s3a1">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>12</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj1016-001-p1s3a3</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj1016-001-p1s3a2</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s3a11">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W10-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>pouze</t_lemma>
<functor>RHEM</functor>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1016-001-p1s3a14">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s3W16-Ta</LM>
<LM>a#a-wsj1016-001-p1s3W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41hveA</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s3a28">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s3a10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1016-001-p1s3a15">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nabídka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s3a9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1016-001-p1s3a16">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s3a19">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1016-001-p1s3W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>schválení</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>18</deepord>
<val_frame.rf>v#v41knuA</val_frame.rf>
<children>
<LM id="T-wsj1016-001-p1s3a29">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s3a15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1016-001-p1s3a30">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s3a20</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="T-wsj1016-001-p1s3a20">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rada</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj1016-001-p1s3a21">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>správní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
<LM id="T-wsj1016-001-p1s3a22">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1016-001-p1s1a5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1016-001-p1s3a23">
<a>
<lex.rf>a#a-wsj1016-001-p1s3W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>britský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Orkem declined to give details of its offer, saying only that the bid will be submitted for approval by the board of the British company.</eng_sentence>
</LM>
</trees>
</tdata>
