<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj2410.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj2410-001-p1s0">
<atree.rf>a#a-wsj2410-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a1">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s0a2">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úřad</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a3">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>národní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2410-001-p1s0a4">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>statistický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s0a7">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s0W20-Ta</LM>
<LM>a#a-wsj2410-001-p1s0W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>15</deepord>
<val_frame.rf>v#v41sdiA</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s0a33">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj2410-001-p1s0a8">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přírůstek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a9">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produkt</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a10">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>francouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj2410-001-p1s0a11">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hrubý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj2410-001-p1s0a12">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>domácí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s0a14">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s0W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pololetí</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a15">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>druhý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>dva</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s0a16">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>upravený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a19">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s0W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>inflace</t_lemma>
<functor>DIFF</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s0a24">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s0W22-Ta</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>EFF</functor>
<deepord>17</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a23">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>0.8</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s0a26">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s0W25-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odhad</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a27">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>původní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
<LM id="T-wsj2410-001-p1s0a29">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>RSTR</functor>
<deepord>21</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a28">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>0.7</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s0a31">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W32-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s0W30-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měsíc</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj2410-001-p1s0a32">
<a>
<lex.rf>a#a-wsj2410-001-p1s0W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The inflation-adjusted growth rate for France's gross domestic product for the second quarter was revised upward to 0.8% from the previous three months from the initial estimate of 0.7%, the National Statistics Institute said.</eng_sentence>
</LM>
<LM id="T-wsj2410-001-p1s1">
<atree.rf>a#a-wsj2410-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2410-001-p1s1a1">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohlásit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41hddB</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s1a2">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>orgán</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2410-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2410-001-p1s1a3">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>státní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s1a6">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s1W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ponechat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41gfhE</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s1a7">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úprava</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2410-001-p1s0a7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2410-001-p1s1a8">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s1a9">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přírůstek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj2410-001-p1s1a11">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s1W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>BEN</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2410-001-p1s1a12">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s1a21">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s1W15-Ta</LM>
<LM>a#a-wsj2410-001-p1s1W13-Ta</LM>
<LM>a#a-wsj2410-001-p1s1W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>období</t_lemma>
<functor>CPR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj2410-001-p1s1a22">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předchozí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj2410-001-p1s1a23">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tříměsíční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s1a13">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>změněný</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>adj.denot</sempos>
<negation>neg1</negation>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj2410-001-p1s1a15">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s1W20-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2410-001-p1s1a17">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>RSTR</functor>
<deepord>16</deepord>
<children>
<LM id="T-wsj2410-001-p1s1a16">
<a>
<lex.rf>a#a-wsj2410-001-p1s1W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1.3</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The state agency said the latest revision left the growth rate for the first-quarter compared with the previous three months unchanged at 1.3%.</eng_sentence>
</LM>
<LM id="T-wsj2410-001-p1s2">
<atree.rf>a#a-wsj2410-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2410-001-p1s2a1">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohlásit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41hddB</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s2a2">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úřad</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2410-001-p1s1a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2410-001-p1s2a13">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W22-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s2W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>EFF</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41jsU</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s2a15">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s2W6-Ta</LM>
<LM>a#a-wsj2410-001-p1s2W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pokračovat</t_lemma>
<functor>COND</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2410-001-p1s2a13</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>cond</discourse_type>
<sense_PDTB3>Contingency.Condition.Arg2-as-cond</sense_PDTB3>
<comment>PHASE:2 INTRA_AUTO_TARGET-NODE-PDTB_COMPATIBLE-SENSE</comment>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj2410-001-p1s2W5-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41gbkB</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s2a17">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ekonomika</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2410-001-p1s2a19">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s2W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>růst</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj2410-001-p1s2a22">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s2W11-Ta</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>DIFF</functor>
<deepord>7</deepord>
<children>
<LM id="T-wsj2410-001-p1s2a21">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>0.8</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2410-001-p1s2a7">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s2W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s2a9">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s2W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zbytek</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2410-001-p1s2a10">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<coref_special>exoph</coref_special>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s2a11">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>růst</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj2410-001-p1s2a12">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>HDP</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s2a24">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s2W23-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výše</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2410-001-p1s2a26">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W26-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>RSTR</functor>
<deepord>16</deepord>
<children>
<LM id="T-wsj2410-001-p1s2a25">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>3</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s2a28">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W29-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s2W27-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2410-001-p1s2a10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2410-001-p1s2a29">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
<LM id="T-wsj2410-001-p1s2a30">
<a>
<lex.rf>a#a-wsj2410-001-p1s2W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1989</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>If the economy continues to expand by 0.8% a quarter for the rest of the year, it would leave GDP growth for all of 1989 at 3%, the institute said.</eng_sentence>
</LM>
<LM id="T-wsj2410-001-p1s3">
<atree.rf>a#a-wsj2410-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2410-001-p1s3a1">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W1-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s3W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>1</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s3a3">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2410-001-p1s2a13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2410-001-p1s3a4">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>snížení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41kxkA</val_frame.rf>
<children>
<LM id="T-wsj2410-001-p1s3a13">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2410-001-p1s3a14">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2410-001-p1s2a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2410-001-p1s3a6">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s3W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>růst</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj2410-001-p1s3a8">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>RSTR</functor>
<deepord>7</deepord>
<children>
<LM id="T-wsj2410-001-p1s3a7">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>3.8</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2410-001-p1s3a9">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uváděný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2410-001-p1s3a11">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2410-001-p1s3W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj2410-001-p1s3a12">
<a>
<lex.rf>a#a-wsj2410-001-p1s3W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1988</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>That would be down from the 3.8% rise posted in 1988.</eng_sentence>
</LM>
</trees>
</tdata>
