<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj2071.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj2071-001-p1s0">
<atree.rf>a#a-wsj2071-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a1">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zveřejnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41sbmA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s0a2">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a52">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a4">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>National</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a5">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Semiconductor</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a3">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a6">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s0a9">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s0W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>urovnat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>9</deepord>
<val_frame.rf>v#v41mudA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s0a45">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s0a10">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>proces</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a11">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trvající</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a12">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a13">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtyři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>čtyři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s0a15">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s0W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>porušení</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>15</deepord>
<val_frame.rf>v#v41gjuA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s0a46">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a45</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s0a16">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>patent</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s0a17">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W20-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s0W19-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vést</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>19</deepord>
<val_frame.rf>v#v41njvS</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s0a47">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a46</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s0a20">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>CPHR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>18</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s0a10</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2071-001-p1s0a22">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W22-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s0W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>BEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a53">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>21</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a23">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Linear</t_lemma>
<functor>FPHR</functor>
<deepord>22</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a24">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Technology</t_lemma>
<functor>FPHR</functor>
<deepord>23</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a25">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W25-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>24</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s0a26">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaplatit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>27</deepord>
<val_frame.rf>v#v41qfcB</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s0a28">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>25</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s0a22</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2071-001-p1s0a29">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nakonec</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>26</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a30">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>29</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a31">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>28</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a32">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W32-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>30</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s0a35">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W35-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s0W34-Ta</LM>
<LM>a#a-wsj2071-001-p1s0W33-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>udělení</t_lemma>
<functor>SUBS</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>33</deepord>
<val_frame.rf>v#v41mhtA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s0a50">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>31</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a28</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s0a49">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>32</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a36">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W37-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>licence</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>35</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a37">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W36-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zrušitelný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>34</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a39">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W40-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s0W38-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produkt</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>37</deepord>
<children>
<LM id="T-wsj2071-001-p1s0a40">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W39-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>36</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a41">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W45-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s0W44-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>39</deepord>
<val_frame.rf>v#v41bhrA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s0a44">
<a>
<lex.rf>a#a-wsj2071-001-p1s0W43-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s0W42-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>38</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s0a39</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2071-001-p1s0a55">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>40</deepord>
</LM>
<LM id="T-wsj2071-001-p1s0a54">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>41</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>National Semiconductor Corp. said it settled a four-year-old patent infringement case against Linear Technology Corp. by accepting a $3 million payment from Linear in exchange for granting Linear irrevocable licenses for all products involved.</eng_sentence>
</LM>
<LM id="T-wsj2071-001-p1s1">
<atree.rf>a#a-wsj2071-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2071-001-p1s1a25">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>22</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s1a35">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>přičemž</t_lemma>
<functor>CONJ</functor>
<is_dsp_root>1</is_dsp_root>
<deepord>23</deepord>
<children>
<LM id="T-wsj2071-001-p1s1a1">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s1W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohodnout_se</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a9</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>PDTB3</src>
<a-connectors.rf>
<LM>a#a-wsj2071-001-p1s1W4-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41yeA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s1a2">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a47</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a50</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="T-wsj2071-001-p1s1a3">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oba</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s1a5">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>rovněž</t_lemma>
<functor>RHEM</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2071-001-p1s1a34">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<deepord>5</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s1a2</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2071-001-p1s1a7">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s1W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uspořádání</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41mxkB</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s1a30">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s1a34</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s1a8">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>právo</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj2071-001-p1s1a9">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budoucí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj2071-001-p1s1a10">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vlastnický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s1a12">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s1W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozmezí</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj2071-001-p1s1a13">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2071-001-p1s1a14">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příští</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj2071-001-p1s1a15">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>deset</t_lemma>
<functor>RSTR</functor>
<proto_lemma>deset</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s1a18">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>proběhnout</t_lemma>
<functor>EFF</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>19</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2071-001-p1s1a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj2071-001-p1s1a35</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41gzyD</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s1a19">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uspořádání</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s1a7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41mxkB</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s1a32">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s1a30</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s1a20">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj2071-001-p1s1a36">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s1a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s1a22">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s1W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>arbitráž</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj2071-001-p1s1a23">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>závazný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s1a26">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s1a32</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2071-001-p1s1a27">
<a>
<lex.rf>a#a-wsj2071-001-p1s1W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oba</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The two companies also agreed to settle any future property rights issues over the next 10 years through binding arbitration, both companies said.</eng_sentence>
</LM>
<LM id="T-wsj2071-001-p1s2">
<atree.rf>a#a-wsj2071-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2071-001-p1s2a1">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W3-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s2W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>týkat_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41mexA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s2a2">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednání</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41bhqA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s2a25">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s1a36</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s2a23">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s1a26</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s2a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<deepord>4</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s2a23</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s2a4">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obvod</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2071-001-p1s2a5">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>takzvaný</t_lemma>
<functor>ATT</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2071-001-p1s2a6">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>analogový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj2071-001-p1s2a7">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>integrovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj2071-001-p1s2a8">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nacházet</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41cqnB</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s2a10">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>10</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s2a4</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2071-001-p1s2a11">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uplatnění</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41mrpB</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s2a26">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s2a10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s2a12">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W18-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>18</deepord>
<children>
<LM id="T-wsj2071-001-p1s2a14">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s2W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>elektronika</t_lemma>
<functor>LOC</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj2071-001-p1s2a15">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spotřební</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s2a17">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s2W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průmysl</t_lemma>
<functor>LOC</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj2071-001-p1s2a18">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>automobilový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s2a20">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W22-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s2W19-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vybavení</t_lemma>
<functor>LOC</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj2071-001-p1s2a21">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>elektronický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
<LM id="T-wsj2071-001-p1s2a22">
<a>
<lex.rf>a#a-wsj2071-001-p1s2W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přístrojový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The products are so-called analog integrated circuits that have applications in the consumer electronics, automobile and electronic instrumentation markets.</eng_sentence>
</LM>
<LM id="T-wsj2071-001-p1s3">
<atree.rf>a#a-wsj2071-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a1">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>označit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41ffxA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s3a2">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a50</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2071-001-p1s3a3">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kalifornský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2071-001-p1s3a35">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>3</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a4">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Linear</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj2071-001-p1s3a5">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Technology</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s3a6">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>působící</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a34">
<a>
<aux.rf>
<LM>a#a-wsj2071-001-p1s3W6-Ta</LM>
</aux.rf>
</a>
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>LOC</functor>
<deepord>9</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a8">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Milpitas</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s3a9">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohoda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<coref_special>segm</coref_special>
</LM>
<LM id="T-wsj2071-001-p1s3a14">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s3W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pozitivní</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj2071-001-p1s3a24">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W30-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s3W26-Ta</LM>
<LM>a#a-wsj2071-001-p1s3W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podílet_se</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>22</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2071-001-p1s3a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Reason</sense_PDTB3>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj2071-001-p1s3W15-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41frxA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s3a10">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produkt</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a11">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s3W20-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>17</deepord>
<val_frame.rf>v#v41bhrA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s3a32">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>11</deepord>
</LM>
<LM id="T-wsj2071-001-p1s3a18">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s3W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>14</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s3a10</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2071-001-p1s3a21">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s3W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>patent</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a22">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sporný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s3a36">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<deepord>18</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s3a32</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s3a26">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a27">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dvacet</t_lemma>
<functor>RSTR</functor>
<proto_lemma>dvacet</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a28">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přibližně</t_lemma>
<functor>EXT</functor>
<proto_lemma>přibližný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s3a30">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W33-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s3W31-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obrat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj2071-001-p1s3a31">
<a>
<lex.rf>a#a-wsj2071-001-p1s3W32-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>roční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>23</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Linear Technology, Milpitas, Calif., called the settlement ``positive,'' since products covered by the disputed patents account for about 20% of its annual sales.</eng_sentence>
</LM>
<LM id="T-wsj2071-001-p1s4">
<atree.rf>a#a-wsj2071-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2071-001-p1s4a1">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s4a2">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s3a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2071-001-p1s4a3">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Linear</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s4a21">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W22-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>21</deepord>
<children>
<LM id="T-wsj2071-001-p1s4a34">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s4a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s4a6">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s4W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>splatit</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41lbvA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s4a7">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosud</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj2071-001-p1s4a8">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj2071-001-p1s4a9">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dva</t_lemma>
<functor>RSTR</functor>
<proto_lemma>dva</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s4a10">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s0a47</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2071-001-p1s4a11">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kalifornský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj2071-001-p1s4a12">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celostátní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj2071-001-p1s4a38">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>12</deepord>
<children>
<LM id="T-wsj2071-001-p1s4a14">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W13-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>National</t_lemma>
<functor>FPHR</functor>
<deepord>13</deepord>
</LM>
<LM id="T-wsj2071-001-p1s4a13">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W14-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Semiconductor</t_lemma>
<functor>FPHR</functor>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s4a15">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>působit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41jebB</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s4a17">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>15</deepord>
<coref_gram.rf>
<LM>T-wsj2071-001-p1s4a10</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2071-001-p1s4a39">
<a>
<aux.rf>
<LM>a#a-wsj2071-001-p1s4W18-Ta</LM>
</aux.rf>
</a>
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>LOC</functor>
<deepord>17</deepord>
<children>
<LM id="T-wsj2071-001-p1s4a20">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W19-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Santa</t_lemma>
<functor>FPHR</functor>
<deepord>18</deepord>
</LM>
<LM id="T-wsj2071-001-p1s4a19">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W20-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Claře</t_lemma>
<functor>FPHR</functor>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s4a23">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s4W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>splatit</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>24</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2071-001-p1s4a6</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj2071-001-p1s4a21</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41lbvA</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s4a36">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>20</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s4a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2071-001-p1s4a24">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj2071-001-p1s4a25">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zbývající</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s4a27">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W28-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s4W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>splátka</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>26</deepord>
<children>
<LM id="T-wsj2071-001-p1s4a28">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rovnoměrný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s4a30">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W32-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s4W29-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>29</deepord>
<children>
<LM id="T-wsj2071-001-p1s4a31">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>následující</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>27</deepord>
</LM>
<LM id="T-wsj2071-001-p1s4a32">
<a>
<lex.rf>a#a-wsj2071-001-p1s4W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osm</t_lemma>
<functor>RSTR</functor>
<proto_lemma>osm</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>28</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The electronics concern said it already has paid $2 million of the settlement to National Semiconductor, Santa Clara, Calif., and will pay the remaining $1 million in equal installments over the next eight quarters.</eng_sentence>
</LM>
<LM id="T-wsj2071-001-p1s5">
<atree.rf>a#a-wsj2071-001-p1s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2071-001-p1s5a1">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dodat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>10</deepord>
<val_frame.rf>v#v41wuE</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s5a4">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s5W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>EFF</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<is_dsp_root>1</is_dsp_root>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41chlAI</val_frame.rf>
<children>
<LM id="T-wsj2071-001-p1s5a2">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>platba</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s4a21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2071-001-p1s5a3">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s5a6">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W3-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>patrně</t_lemma>
<functor>MOD</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2071-001-p1s5a15">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj2071-001-p1s5a8">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vliv</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj2071-001-p1s5a10">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2071-001-p1s5W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výsledek</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2071-001-p1s5a11">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>budoucí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj2071-001-p1s5a12">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provozní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2071-001-p1s5a13">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2071-001-p1s4a34</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2071-001-p1s5a14">
<a>
<lex.rf>a#a-wsj2071-001-p1s5W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Linear</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The payments aren't expected to have an impact on coming operating results, Linear added.</eng_sentence>
</LM>
</trees>
</tdata>
