<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj2157.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj2157-001-p1s0">
<atree.rf>a#a-wsj2157-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a1">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vybrat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41nusB</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s0a2">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bush</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a3">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s0a6">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>6</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a4">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Allday</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a5">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Martin</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s0a7">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přítel</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a8">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dlouhodobý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj2157-001-p1s0a10">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s0W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Texas</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s0a13">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s0W13-Ta</LM>
<LM>a#a-wsj2157-001-p1s0W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát_se</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2157-001-p1s0a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>purp</discourse_type>
<sense_PDTB3>Contingency.Purpose.Arg2-as-goal</sense_PDTB3>
<src>A_V_A</src>
<a-connectors.rf>
<LM>a#a-wsj2157-001-p1s0W12-Ta</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41lioA</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s0a23">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s0a6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2157-001-p1s0a15">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a16">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Bracket</t_lemma>
<functor>APPS</functor>
<is_parenthesis>1</is_parenthesis>
<deepord>17</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a17">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komise</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a18">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>federální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj2157-001-p1s0a20">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s0W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>regulace</t_lemma>
<functor>BEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj2157-001-p1s0a21">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>energie</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s0a22">
<a>
<lex.rf>a#a-wsj2157-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>FERC</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>President Bush chose Martin Allday, a longtime friend from Texas, to be chairman of the Federal Energy Regulatory Commission.</eng_sentence>
</LM>
<LM id="T-wsj2157-001-p1s1">
<atree.rf>a#a-wsj2157-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2157-001-p1s1a1">
<a>
<lex.rf>a#a-wsj2157-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nahradit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41cqbC</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s1a2">
<a>
<lex.rf>a#a-wsj2157-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Allday</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s0a23</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2157-001-p1s1a3">
<a>
<lex.rf>a#a-wsj2157-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pan</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s1a5">
<a>
<lex.rf>a#a-wsj2157-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hesse</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj2157-001-p1s1a4">
<a>
<lex.rf>a#a-wsj2157-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Martha</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj2157-001-p1s1a6">
<a>
<lex.rf>a#a-wsj2157-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rezignovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41jkhA</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s1a9">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2157-001-p1s1a8">
<a>
<lex.rf>a#a-wsj2157-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>7</deepord>
<coref_gram.rf>
<LM>T-wsj2157-001-p1s1a5</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Mr. Allday would succeed Martha Hesse, who is resigning.</eng_sentence>
</LM>
<LM id="T-wsj2157-001-p1s2">
<atree.rf>a#a-wsj2157-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a1">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s2a34">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2157-001-p1s2a2">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dům</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a3">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bílý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s2a6">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s2W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odcházet</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>19</deepord>
<val_frame.rf>v#v41ealC</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s2a36">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR1</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj2157-001-p1s2a37">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s1a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2157-001-p1s2a20">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hessová</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a21">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>paní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s2a7">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obchodnice</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a9">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s2W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Chicago</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s2a10">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41gyaF</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s2a12">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>11</deepord>
<coref_gram.rf>
<LM>T-wsj2157-001-p1s2a37</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2157-001-p1s2a14">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s2W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>minulost</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj2157-001-p1s2a16">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s2W17-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>post</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a18">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W21-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>17</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a17">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a22">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>energetika</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s2a23">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>FERC</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s0a16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s2a26">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W26-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s2W25-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>funkce</t_lemma>
<functor>DIR3</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a27">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>viceprezidentka</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a28">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a32">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>24</deepord>
<children>
<LM id="T-wsj2157-001-p1s2a30">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W29-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>First</t_lemma>
<functor>FPHR</functor>
<deepord>23</deepord>
</LM>
<LM id="T-wsj2157-001-p1s2a31">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W30-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Chicago</t_lemma>
<functor>FPHR</functor>
<deepord>25</deepord>
</LM>
<LM id="T-wsj2157-001-p1s2a29">
<a>
<lex.rf>a#a-wsj2157-001-p1s2W31-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The White House said Ms. Hesse, a Chicago businesswoman who previously held posts at the Energy Department and FERC, is leaving to become a vice president of First Chicago Corp.</eng_sentence>
</LM>
<LM id="T-wsj2157-001-p1s3">
<atree.rf>a#a-wsj2157-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2157-001-p1s3a8">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>9</deepord>
<val_frame.rf>v#v41gyaF</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s3a1">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s1a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2157-001-p1s3a2">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Allday</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2157-001-p1s3a3">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poradce</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj2157-001-p1s3a4">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>právní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2157-001-p1s3a6">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s3W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj2157-001-p1s3a7">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Midland</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2157-001-p1s3a11">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s3W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s0a10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2157-001-p1s3a12">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Texas</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s3a13">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s3W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>advokát</t_lemma>
<functor>COMPL</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<compl.rf>
<LM>T-wsj2157-001-p1s3a1</LM>
</compl.rf>
</LM>
<LM id="T-wsj2157-001-p1s3a16">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s3W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ministerstvo</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj2157-001-p1s3a17">
<a>
<lex.rf>a#a-wsj2157-001-p1s3W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vnitro</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Mr. Allday, an attorney in Midland, Texas, has been solicitor at the Interior Department.</eng_sentence>
</LM>
<LM id="T-wsj2157-001-p1s4">
<atree.rf>a#a-wsj2157-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2157-001-p1s4a1">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s4W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>seznámit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41kluB</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s4a21">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s3a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2157-001-p1s4a3">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W2-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s4W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bush</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2157-001-p1s4a6">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s4W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj2157-001-p1s4a7">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>padesátý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>padesát</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj2157-001-p1s4a16">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W16-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="T-wsj2157-001-p1s4a8">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>RSTR</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s4a10">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kdy</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>kdy</proto_lemma>
<gram>
<sempos>adv.pron.indef</sempos>
</gram>
<deepord>6</deepord>
<coref_gram.rf>
<LM>T-wsj2157-001-p1s4a6</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2157-001-p1s4a11">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prezident</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s4a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2157-001-p1s4a12">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>naftař</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj2157-001-p1s4a13">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mladý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj2157-001-p1s4a15">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W15-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s4W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Midland</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s3a6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s4a22">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>být</t_lemma>
<functor>RSTR</functor>
<proto_lemma>být</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2157-001-p1s4a8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj2157-001-p1s4a16</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s4a17">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Allday</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s4a21</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2157-001-p1s4a18">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>právník</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj2157-001-p1s4a19">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>firma</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj2157-001-p1s4a20">
<a>
<lex.rf>a#a-wsj2157-001-p1s4W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>naftařský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>He met Mr. Bush in the 1950s, when the president was a young oil man in Midland and Mr. Allday was a lawyer for an oil firm.</eng_sentence>
</LM>
<LM id="T-wsj2157-001-p1s5">
<atree.rf>a#a-wsj2157-001-p1s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2157-001-p1s5a1">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s5a2">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>FERC</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s2a23</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2157-001-p1s5a3">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komise</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj2157-001-p1s5a4">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pětičlenný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2157-001-p1s5a5">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>regulovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41jhiA</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s5a7">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>5</deepord>
<coref_gram.rf>
<LM>T-wsj2157-001-p1s5a3</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2157-001-p1s5a8">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>miliarda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj2157-001-p1s5a9">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s5a11">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s5W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>transakce</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj2157-001-p1s5a12">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mezistátní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj2157-001-p1s5a13">
<a>
<lex.rf>a#a-wsj2157-001-p1s5W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>velkoobchodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The FERC is a five-member commission that regulates billions of dollars of interstate wholesale energy transactions.</eng_sentence>
</LM>
<LM id="T-wsj2157-001-p1s6">
<atree.rf>a#a-wsj2157-001-p1s6</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2157-001-p1s6a7">
<a>
<lex.rf>a#a-wsj2157-001-p1s6W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s6W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>schválit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2157-001-p1s0a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>MP</src>
<t-connectors.rf>
<LM>T-wsj2157-001-p1s6a6</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41knwB</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s6a2">
<a>
<lex.rf>a#a-wsj2157-001-p1s6W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jmenování</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s0a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41bioA</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s6a9">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s4a11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2157-001-p1s6a3">
<a>
<lex.rf>a#a-wsj2157-001-p1s6W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Allday</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s4a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2157-001-p1s6a10">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>EFF</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj2157-001-p1s6a5">
<a>
<lex.rf>a#a-wsj2157-001-p1s6W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s6W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>funkce</t_lemma>
<functor>DIR3</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s6a6">
<a>
<lex.rf>a#a-wsj2157-001-p1s6W6-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>ještě</t_lemma>
<functor>RHEM</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2157-001-p1s6a8">
<a>
<lex.rf>a#a-wsj2157-001-p1s6W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>senát</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
<eng_sentence>Mr. Allday's appointment is subject to confirmation by the Senate.</eng_sentence>
</LM>
<LM id="T-wsj2157-001-p1s7">
<atree.rf>a#a-wsj2157-001-p1s7</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2157-001-p1s7a1">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s7a12">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2157-001-p1s7a2">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úředník</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj2157-001-p1s7a3">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vrchní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj2157-001-p1s7a4">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>administrativní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s7a7">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2157-001-p1s7W11-Ta</LM>
<LM>a#a-wsj2157-001-p1s7W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>určit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41mtrE</val_frame.rf>
<children>
<LM id="T-wsj2157-001-p1s7a13">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2157-001-p1s7a8">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>datum</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj2157-001-p1s7a9">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odchod</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj2157-001-p1s7a10">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hessová</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2157-001-p1s2a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2157-001-p1s7a11">
<a>
<lex.rf>a#a-wsj2157-001-p1s7W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ještě</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj2157-001-p1s7a14">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Administration officials said a date for Ms. Hesse's departure hasn't been set.</eng_sentence>
</LM>
</trees>
</tdata>
