<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0907.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<trees>
<LM id="T-wsj0907-001-p1s0">
<atree.rf>a#a-wsj0907-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oznámit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41fgeD</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a35">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Chandler</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0907-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Insurance</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0907-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Co</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0907-001-p1s0a6">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s0a7">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předpoklad</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a8">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>8</deepord>
<coref_gram.rf>
<LM>T-wsj0907-001-p1s0a5</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0907-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s0W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ohlásit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41eonA</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s0a34">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0907-001-p1s0a33">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0907-001-p1s0a8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0907-001-p1s0a13">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s0W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a14">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetí</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s0a15">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skok</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a16">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zisk</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a17">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čistý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s0a20">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W20-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s0W18-Ta</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>DIFF</functor>
<deepord>19</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a19">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>97</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s0a25">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>čili</t_lemma>
<functor>APPS</functor>
<deepord>23</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a23">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s0W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>DIR3</functor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a22">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2.8</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>20</deepord>
</LM>
<LM id="T-wsj0907-001-p1s0a24">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s0a28">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W28-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s0W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cent</t_lemma>
<functor>DIR3</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
<children>
<LM id="T-wsj0907-001-p1s0a27">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>51</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>24</deepord>
</LM>
<LM id="T-wsj0907-001-p1s0a30">
<a>
<lex.rf>a#a-wsj0907-001-p1s0W30-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s0W29-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Chandler Insurance Co. said it expects to report third-quarter net income jumped 97% to $2.8 million, or 51 cents a share.</eng_sentence>
</LM>
<LM id="T-wsj0907-001-p1s1">
<atree.rf>a#a-wsj0907-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a1">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41chlAD</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s1a3">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W3-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s1W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a4">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s1a5">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0907-001-p1s1a6">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pojišťovatel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0907-001-p1s0a33</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0907-001-p1s1a7">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0907-001-p1s1a8">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a9">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>automobil</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj0907-001-p1s1a10">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>auto</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a11">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nákladní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s1a12">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příjem</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a16">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>čili</t_lemma>
<functor>APPS</functor>
<deepord>15</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a14">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a13">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1.4</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>12</deepord>
</LM>
<LM id="T-wsj0907-001-p1s1a15">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s1a19">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cent</t_lemma>
<functor>EXT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a18">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>48</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0907-001-p1s1a31">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s1W20-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s1a23">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s1W22-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>základ</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a24">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přepočítaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s1a27">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W27-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s1W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obrat</t_lemma>
<functor>TPAR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a29">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj0907-001-p1s1a28">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>16.5</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>22</deepord>
</LM>
<LM id="T-wsj0907-001-p1s1a30">
<a>
<lex.rf>a#a-wsj0907-001-p1s1W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>In the year-earlier quarter, the automobile and trucking insurer had earnings of $1.4 million, or 48 cents a share on a restated basis, on revenue of $16.5 million.</eng_sentence>
</LM>
<LM id="T-wsj0907-001-p1s2">
<atree.rf>a#a-wsj0907-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0907-001-p1s2a10">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>říci</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41kebA</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s2a2">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>4</deepord>
<children>
<LM id="T-wsj0907-001-p1s2a5">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>LeGere</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj0907-001-p1s2a6">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>W</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0907-001-p1s2a4">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Brent</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s2a1">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>6</deepord>
<children>
<LM id="T-wsj0907-001-p1s2a3">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0907-001-p1s2a8">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0907-001-p1s2a9">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výkonný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s2a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0907-001-p1s2a13">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s2W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhovor</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0907-001-p1s2a16">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s2W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předpokládat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>15</deepord>
<val_frame.rf>v#v41hxpA</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s2a29">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0907-001-p1s2a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0907-001-p1s2a18">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s2W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0907-001-p1s0a13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0907-001-p1s2a19">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslední</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s2a20">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obrat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj0907-001-p1s2a21">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celkový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0907-001-p1s2a23">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W24-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s2W22-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>19</deepord>
<children>
<LM id="T-wsj0907-001-p1s2a24">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>28</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>18</deepord>
</LM>
<LM id="T-wsj0907-001-p1s2a25">
<a>
<lex.rf>a#a-wsj0907-001-p1s2W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>In an interview, W. Brent LeGere, chairman and chief executive officer, said he expects revenue in the latest quarter to total about $28 million.</eng_sentence>
</LM>
<LM id="T-wsj0907-001-p1s3">
<atree.rf>a#a-wsj0907-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0907-001-p1s3a1">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odrážet</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41ehyB</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s3a2">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0907-001-p1s3a3">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příjem</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0907-001-p1s3a5">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s3W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s3a6">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dividenda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0907-001-p1s3a8">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>RSTR</functor>
<deepord>6</deepord>
<children>
<LM id="T-wsj0907-001-p1s3a7">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>25</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s3a10">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s3W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0907-001-p1s3a12">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s3W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>červen</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0907-001-p1s3a13">
<a>
<lex.rf>a#a-wsj0907-001-p1s3W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1989</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The earnings-per-share figures reflect a 25% stock dividend in June 1989.</eng_sentence>
</LM>
<LM id="T-wsj0907-001-p1s4">
<atree.rf>a#a-wsj0907-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0907-001-p1s4a1">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přisoudit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41iyqA</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s4a2">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>LeGere</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0907-001-p1s2a29</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0907-001-p1s4a3">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nárůst</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<coref_special>segm</coref_special>
<children>
<LM id="T-wsj0907-001-p1s4a4">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>příjem</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s4a8">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W11-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>11</deepord>
<children>
<LM id="T-wsj0907-001-p1s4a5">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>růst</t_lemma>
<functor>ADDR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0907-001-p1s4a7">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0907-001-p1s4W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pojištění</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>7</deepord>
<val_frame.rf>v#v41fzxA</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s4a18">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj0907-001-p1s4a9">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přeprava</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0907-001-p1s4a10">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dálkový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0907-001-p1s4a11">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nákladní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0907-001-p1s4a12">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>schopnost</t_lemma>
<functor>ADDR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj0907-001-p1s4a13">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>udržovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41miqE</val_frame.rf>
<children>
<LM id="T-wsj0907-001-p1s4a19">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>13</deepord>
</LM>
<LM id="T-wsj0907-001-p1s4a14">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sazba</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj0907-001-p1s4a15">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pevný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
<LM id="T-wsj0907-001-p1s4a16">
<a>
<lex.rf>a#a-wsj0907-001-p1s4W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pojistný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Mr. LeGere attributed the earnings increase to growth in the company's longhaul trucking insurance lines and the ability to keep premium rates firm.</eng_sentence>
</LM>
</trees>
</tdata>
