<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0246.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj0246-001-p1s0">
<atree.rf>a#a-wsj0246-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a43">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>3</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>AMERICAN</t_lemma>
<functor>FPHR</functor>
<deepord>2</deepord>
</LM>
<LM id="T-wsj0246-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>BRANDS</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0246-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0246-001-p1s0a48">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s0a8">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sídlo</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a49">
<a>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W8-Ta</LM>
</aux.rf>
</a>
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>LOC</functor>
<deepord>8</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W9-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Old</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0246-001-p1s0a10">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Greenwich</t_lemma>
<functor>FPHR</functor>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0246-001-p1s0a13">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W11-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a14">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Connecticut</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s0a17">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosáhnout</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>15</deepord>
<val_frame.rf>v#v41afbA</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s0a45">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0246-001-p1s0a18">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>18</deepord>
<val_frame.rf>v#v41sdgB</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s0a46">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0246-001-p1s0a19">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletní</t_lemma>
<functor>THL</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
<LM id="T-wsj0246-001-p1s0a22">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W22-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W20-Ta</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<t_lemma>#Percnt</t_lemma>
<functor>DIFF</functor>
<deepord>20</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a21">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>11</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s0a24">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W25-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W23-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cent</t_lemma>
<functor>ORIG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a25">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>61</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>21</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s0a28">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W28-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W26-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cent</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a27">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>68</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>23</deepord>
</LM>
<LM id="T-wsj0246-001-p1s0a30">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W30-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W29-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s0a32">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W32-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W31-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>splatnost</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>26</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a33">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W35-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prosinec</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>28</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a34">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W33-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W34-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s0a37">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W37-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W36-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>29</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a38">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W38-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>registrovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>30</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a40">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W42-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W39-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>listopad</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>32</deepord>
<children>
<LM id="T-wsj0246-001-p1s0a41">
<a>
<lex.rf>a#a-wsj0246-001-p1s0W40-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s0W41-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>10</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>31</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>AMERICAN BRANDS Inc., Old Greenwich, Conn., said it increased its quarterly 11% to 68 cents a share from 61 cents, payable Dec. 1 to stock of record Nov. 10.</eng_sentence>
</LM>
<LM id="T-wsj0246-001-p1s1">
<atree.rf>a#a-wsj0246-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0246-001-p1s1a1">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W12-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>11</deepord>
<children>
<LM id="T-wsj0246-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvýšení</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s0a18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41sdgB</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s1a29">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s0a46</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s1a3">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>následovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41dboC</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s1a5">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s1W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oznámení</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41fgcB</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s1a33">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0246-001-p1s1a6">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s0a45</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0246-001-p1s1a8">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s1W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tržba</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj0246-001-p1s1a9">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>silný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj0246-001-p1s1a11">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s1W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrtletí</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0246-001-p1s1a12">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třetí</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s1a13">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odrážet</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>12</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0246-001-p1s1a3</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj0246-001-p1s1a1</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41ehyB</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s1a15">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W20-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s1W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nazvat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>18</deepord>
<val_frame.rf>v#v41diiA</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s1a17">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>co</t_lemma>
<functor>PAT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj0246-001-p1s1a18">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s1a6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0246-001-p1s1a34">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>15</deepord>
<children>
<LM id="T-wsj0246-001-p1s1a20">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>American</t_lemma>
<functor>FPHR</functor>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0246-001-p1s1a19">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Brands</t_lemma>
<functor>FPHR</functor>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s1a23">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tradice</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj0246-001-p1s1a24">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>19</deepord>
<coref_gram.rf>
<LM>T-wsj0246-001-p1s1a18</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0246-001-p1s1a26">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sdílení</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<val_frame.rf>v#v41kglA</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s1a35">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>22</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s1a24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0246-001-p1s1a27">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>růst</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj0246-001-p1s1a28">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výdělek</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s1a22">
<a>
<lex.rf>a#a-wsj0246-001-p1s1W29-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s1W28-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcionář</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The increase follows the company's report of strong earnings for the third quarter, and reflects what American Brands called its ``tradition of sharing earnings growth'' with shareholders.</eng_sentence>
</LM>
<LM id="T-wsj0246-001-p1s2">
<atree.rf>a#a-wsj0246-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0246-001-p1s2a1">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s2a2">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s1a35</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0246-001-p1s2a22">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0246-001-p1s2a4">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>American</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0246-001-p1s2a3">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Brands</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s2a5">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0246-001-p1s2a6">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>orientovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0246-001-p1s2a8">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s2W7-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výrobek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0246-001-p1s2a9">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>spotřební</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s2a11">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s2W10-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaměření</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41qavB</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s2a12">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlavní</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0246-001-p1s2a23">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s2a5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0246-001-p1s2a14">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W17-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>15</deepord>
<children>
<LM id="T-wsj0246-001-p1s2a15">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s2W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tabák</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
</LM>
<LM id="T-wsj0246-001-p1s2a17">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s2W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>destilát</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
<LM id="T-wsj0246-001-p1s2a18">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s2W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pojištění</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>19</deepord>
<val_frame.rf>v#v41fzxA</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s2a21">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0246-001-p1s2a20">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>17</deepord>
</LM>
<LM id="T-wsj0246-001-p1s2a19">
<a>
<lex.rf>a#a-wsj0246-001-p1s2W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>životní</t_lemma>
<functor>REG</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>American Brands is a consumer products company with core businesses in tobacco, distilled spirits and life insurance.</eng_sentence>
</LM>
<LM id="T-wsj0246-001-p1s3">
<atree.rf>a#a-wsj0246-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0246-001-p1s3a1">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41chlJ</val_frame.rf>
<children>
<LM id="T-wsj0246-001-p1s3a3">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s3W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>září</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0246-001-p1s3a4">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W2-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s3W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>30</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s3a6">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0246-001-p1s2a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0246-001-p1s3a14">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>5</deepord>
<children>
<LM id="T-wsj0246-001-p1s3a8">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>American</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj0246-001-p1s3a7">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Brands</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s3a10">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milion</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0246-001-p1s3a9">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>95.2</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>8</deepord>
</LM>
<LM id="T-wsj0246-001-p1s3a11">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0246-001-p1s3a13">
<a>
<lex.rf>a#a-wsj0246-001-p1s3W13-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0246-001-p1s3W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oběh</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
<eng_sentence>As of Sept. 30, American Brands had 95.2 million shares outstanding.</eng_sentence>
</LM>
</trees>
</tdata>
