<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj0680.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj0680-001-p1s0">
<atree.rf>a#a-wsj0680-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s0a1">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>následovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>1</deepord>
<val_frame.rf>v#v41dboB</val_frame.rf>
<children>
<LM id="T-wsj0680-001-p1s0a2">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>seznam</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj0680-001-p1s0a3">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>týdenní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj0680-001-p1s0a4">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0680-001-p1s0a5">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ověřený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj0680-001-p1s0a6">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čistý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0680-001-p1s0a7">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>aktivum</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<children>
<LM id="T-wsj0680-001-p1s0a8">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj0680-001-p1s0a9">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obchodovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj0680-001-p1s0a10">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veřejně</t_lemma>
<functor>MANN</functor>
<proto_lemma>veřejný</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0680-001-p1s0a11">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fond</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj0680-001-p1s0a12">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>investiční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0680-001-p1s0a14">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s0W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oznámení</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41fgcA</val_frame.rf>
<children>
<LM id="T-wsj0680-001-p1s0a20">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0680-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0680-001-p1s0a21">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>15</deepord>
</LM>
<LM id="T-wsj0680-001-p1s0a15">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj0680-001-p1s0a17">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W18-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s0W16-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uzávěrka</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj0680-001-p1s0a18">
<a>
<lex.rf>a#a-wsj0680-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>páteční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Following is a weekly listing of unadited net asset values of publicly traded investment fund shares, reported by the companies as of Friday's close.</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s1">
<atree.rf>a#a-wsj0680-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s1a2">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s1W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj0680-001-p1s0a1</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<comment>PHASE:2 INTER_AUTO_SAME-NODES-PDTB_NO-OTHER</comment>
<src>A_I_A</src>
<t-connectors.rf>
<LM>T-wsj0680-001-p1s1a15</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41ndjB</val_frame.rf>
<children>
<LM id="T-wsj0680-001-p1s1a25">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0680-001-p1s1a4">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W2-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s1W1-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akcie</t_lemma>
<functor>BEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0680-001-p1s1a5">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fond</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0680-001-p1s0a11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj0680-001-p1s1a6">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>každý</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0680-001-p1s1a8">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s1W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poměr</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>5</deepord>
<children>
<LM id="T-wsj0680-001-p1s1a9">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozdíl</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0680-001-p1s1a11">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s1W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>procento</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj0680-001-p1s1a15">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W12-Ta</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>také</t_lemma>
<functor>RHEM</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj0680-001-p1s1a12">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>nebo</t_lemma>
<functor>CONJ</functor>
<deepord>13</deepord>
<children>
<LM id="T-wsj0680-001-p1s1a13">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cena</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj0680-001-p1s1a14">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>závěrečný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj0680-001-p1s1a16">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>katalogový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj0680-001-p1s1a17">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tržní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj0680-001-p1s1a18">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cena</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj0680-001-p1s1a19">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>požadovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>17</deepord>
<val_frame.rf>v#v41gxnA</val_frame.rf>
<children>
<LM id="T-wsj0680-001-p1s1a21">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>16</deepord>
<coref_gram.rf>
<LM>T-wsj0680-001-p1s1a18</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0680-001-p1s1a26">
<a>
<aux.rf>
<LM>a#a-wsj0680-001-p1s1W21-Ta</LM>
<LM>a#a-wsj0680-001-p1s1W22-Ta</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ORIG</functor>
<deepord>18</deepord>
<coref_gram.rf>
<LM>T-wsj0680-001-p1s1a24</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj0680-001-p1s1a24">
<a>
<lex.rf>a#a-wsj0680-001-p1s1W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obchodník</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Also shown is the closing listed market price or a dealer-to-dealer asked price of each fund's shares, with the percentage of difference.</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s2">
<atree.rf>a#a-wsj0680-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s2a1">
<a>
<lex.rf>a#a-wsj0680-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fond</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0680-001-p1s2a2">
<a>
<lex.rf>a#a-wsj0680-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uzavřený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0680-001-p1s2a3">
<a>
<lex.rf>a#a-wsj0680-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dluhopisový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
<eng_sentence>Closed End Bond Funds</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s3">
<atree.rf>a#a-wsj0680-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s3a1">
<a>
<lex.rf>a#a-wsj0680-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fond</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0680-001-p1s3a2">
<a>
<lex.rf>a#a-wsj0680-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>portfolio</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj0680-001-p1s3a3">
<a>
<lex.rf>a#a-wsj0680-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pružný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Flexible Portfolio Funds</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s4">
<atree.rf>a#a-wsj0680-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s4a1">
<a>
<lex.rf>a#a-wsj0680-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fond</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj0680-001-p1s4a2">
<a>
<lex.rf>a#a-wsj0680-001-p1s4W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dluhopis</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj0680-001-p1s4a3">
<a>
<lex.rf>a#a-wsj0680-001-p1s4W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvláštní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj0680-001-p1s4a4">
<a>
<lex.rf>a#a-wsj0680-001-p1s4W4-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>5</deepord>
<children>
<LM id="T-wsj0680-001-p1s4a5">
<a>
<lex.rf>a#a-wsj0680-001-p1s4W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kapitálový</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0680-001-p1s4a6">
<a>
<lex.rf>a#a-wsj0680-001-p1s4W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konvertibilní</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Specialized Equity and Convertible Funds</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s5">
<atree.rf>a#a-wsj0680-001-p1s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s5a5">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0680-001-p1s5a1">
<a>
<lex.rf>a#a-wsj0680-001-p1s5W1-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s5W2-Ta</LM>
</aux.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>a</t_lemma>
<functor>PREC</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0680-001-p1s5a4">
<a>
<lex.rf>a#a-wsj0680-001-p1s5W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s5W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dividenda</t_lemma>
<functor>ACMP</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
<eng_sentence>a - Ex-dividend.</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s6">
<atree.rf>a#a-wsj0680-001-p1s6</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s6a6">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0680-001-p1s6a2">
<a>
<lex.rf>a#a-wsj0680-001-p1s6W1-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s6W2-Ta</LM>
</aux.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>b</t_lemma>
<functor>PREC</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0680-001-p1s6a4">
<a>
<lex.rf>a#a-wsj0680-001-p1s6W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s6W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uzávěrka</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj0680-001-p1s6a5">
<a>
<lex.rf>a#a-wsj0680-001-p1s6W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čtvrteční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>b - As of Thursday's close.</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s7">
<atree.rf>a#a-wsj0680-001-p1s7</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s7a1">
<a>
<lex.rf>a#a-wsj0680-001-p1s7W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>převést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41imqB</val_frame.rf>
<children>
<LM id="T-wsj0680-001-p1s7a3">
<a>
<lex.rf>a#a-wsj0680-001-p1s7W1-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s7W2-Ta</LM>
</aux.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>c</t_lemma>
<functor>PREC</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0680-001-p1s7a9">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0680-001-p1s4a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0680-001-p1s7a8">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj0680-001-p1s7a5">
<a>
<lex.rf>a#a-wsj0680-001-p1s7W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s7W4-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kurs</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj0680-001-p1s7a6">
<a>
<lex.rf>a#a-wsj0680-001-p1s7W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obchodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj0680-001-p1s7a7">
<a>
<lex.rf>a#a-wsj0680-001-p1s7W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rand</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>c - Translated at Commercial Rand exchange rate.</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s8">
<atree.rf>a#a-wsj0680-001-p1s8</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s8a6">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0680-001-p1s8a1">
<a>
<lex.rf>a#a-wsj0680-001-p1s8W1-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s8W2-Ta</LM>
</aux.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>e</t_lemma>
<functor>PREC</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0680-001-p1s8a4">
<a>
<lex.rf>a#a-wsj0680-001-p1s8W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s8W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj0680-001-p1s8a5">
<a>
<lex.rf>a#a-wsj0680-001-p1s8W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kanadský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>e - In Canadian dollars.</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s9">
<atree.rf>a#a-wsj0680-001-p1s9</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s9a6">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj0680-001-p1s9a2">
<a>
<lex.rf>a#a-wsj0680-001-p1s9W1-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s9W2-Ta</LM>
</aux.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>f</t_lemma>
<functor>PREC</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0680-001-p1s9a4">
<a>
<lex.rf>a#a-wsj0680-001-p1s9W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s9W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uzávěrka</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj0680-001-p1s9a5">
<a>
<lex.rf>a#a-wsj0680-001-p1s9W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>středeční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>f - As of Wednesday's close.</eng_sentence>
</LM>
<LM id="T-wsj0680-001-p1s10">
<atree.rf>a#a-wsj0680-001-p1s10</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj0680-001-p1s10a1">
<a>
<lex.rf>a#a-wsj0680-001-p1s10W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41jsBT</val_frame.rf>
<children>
<LM id="T-wsj0680-001-p1s10a8">
<a>
<lex.rf>a#a-wsj0680-001-p1s10W1-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s10W2-Ta</LM>
</aux.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>z</t_lemma>
<functor>PREC</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj0680-001-p1s10a7">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>2</deepord>
</LM>
<LM id="T-wsj0680-001-p1s10a6">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj0680-001-p1s7a9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj0680-001-p1s10a5">
<a>
<lex.rf>a#a-wsj0680-001-p1s10W5-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj0680-001-p1s10W4-Ta</LM>
</aux.rf>
</a>
<nodetype>dphr</nodetype>
<t_lemma>k_dispozici</t_lemma>
<functor>DPHR</functor>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
<eng_sentence>z - Not available.</eng_sentence>
</LM>
</trees>
</tdata>
