<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj1242.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<trees>
<LM id="T-wsj1242-001-p1s0">
<atree.rf>a#a-wsj1242-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a1">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s0a2">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a32">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>2</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a4">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Bausch</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a5">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>&amp;</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a6">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Lomb</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a3">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a33">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s0a10">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s0W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>souhlasit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41kypC</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s0a11">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a12">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1242-001-p1s0a13">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>farmaceutický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a14">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přidružený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s0a16">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s0W15-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dodávání</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41wxA</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s0a34">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s0a11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1242-001-p1s0a17">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kryt</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a18">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kolagenový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a19">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rohovkový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a21">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s0W20-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>operace</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a22">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veterinární</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a23">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chirurgický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>20</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a24">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oko</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s0a25">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednotka</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>23</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a26">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>24</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a35">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>25</deepord>
<children>
<LM id="T-wsj1242-001-p1s0a29">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>International</t_lemma>
<functor>FPHR</functor>
<deepord>26</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a28">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Minerals</t_lemma>
<functor>FPHR</functor>
<deepord>27</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a30">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W29-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>&amp;</t_lemma>
<functor>FPHR</functor>
<deepord>28</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a31">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W30-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Chemical</t_lemma>
<functor>FPHR</functor>
<deepord>29</deepord>
</LM>
<LM id="T-wsj1242-001-p1s0a27">
<a>
<lex.rf>a#a-wsj1242-001-p1s0W31-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>30</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Bausch &amp; Lomb Inc. said its pharmaceuticals subsidiary agreed to supply collagen corneal shields for animal eye surgery to a unit of International Minerals &amp; Chemical Corp.</eng_sentence>
</LM>
<LM id="T-wsj1242-001-p1s1">
<atree.rf>a#a-wsj1242-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1242-001-p1s1a1">
<a>
<lex.rf>a#a-wsj1242-001-p1s1W4-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s1W3-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zveřejnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41sbmB</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s1a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1242-001-p1s1a2">
<a>
<lex.rf>a#a-wsj1242-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podmínka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1242-001-p1s1a3">
<a>
<lex.rf>a#a-wsj1242-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohoda</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<coref_special>segm</coref_special>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s1a5">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
<eng_sentence>Terms weren't disclosed.</eng_sentence>
</LM>
<LM id="T-wsj1242-001-p1s2">
<atree.rf>a#a-wsj1242-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1242-001-p1s2a1">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41hylC</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s2a2">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohoda</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s1a3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1242-001-p1s2a3">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s2a4">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>transakce</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>6</deepord>
<children>
<LM id="T-wsj1242-001-p1s2a5">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>první</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1242-001-p1s2a6">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obchodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1242-001-p1s2a7">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s0a12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1242-001-p1s2a29">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>8</deepord>
<children>
<LM id="T-wsj1242-001-p1s2a9">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Bausch</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1242-001-p1s2a10">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>&amp;</t_lemma>
<functor>FPHR</functor>
<deepord>10</deepord>
</LM>
<LM id="T-wsj1242-001-p1s2a8">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Lomb</t_lemma>
<functor>FPHR</functor>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s2a11">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W16-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s2W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodávat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41hblA</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s2a25">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s0a25</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1242-001-p1s2a14">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kdy</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>kdy</proto_lemma>
<gram>
<sempos>adv.pron.indef</sempos>
</gram>
<deepord>13</deepord>
<coref_gram.rf>
<LM>T-wsj1242-001-p1s2a4</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1242-001-p1s2a15">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s2a7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1242-001-p1s2a16">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tento</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tento</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s2a17">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produkt</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1242-001-p1s2a18">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>péče</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj1242-001-p1s2a20">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W20-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s2W19-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zrak</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s2a22">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W23-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s2W21-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>použití</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
</gram>
<deepord>23</deepord>
<val_frame.rf>v#v41gszA</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s2a28">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>20</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s2a17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1242-001-p1s2a27">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<deepord>21</deepord>
</LM>
<LM id="T-wsj1242-001-p1s2a23">
<a>
<lex.rf>a#a-wsj1242-001-p1s2W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>veterinární</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The agreement marks Bausch &amp; Lomb's first venture selling its eye care products for use by veterinarians.</eng_sentence>
</LM>
<LM id="T-wsj1242-001-p1s3">
<atree.rf>a#a-wsj1242-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1242-001-p1s3a1">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pomáhat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>5</deepord>
<val_frame.rf>v#v41gdxB</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s3a11">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1242-001-p1s3a2">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kryt</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj1242-001-p1s3a3">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kolagenový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1242-001-p1s3a4">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s3a5">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W5-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>urychlovat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41muiA</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s3a12">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<deepord>7</deepord>
<coref_gram.rf>
<LM>T-wsj1242-001-p1s3a2</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj1242-001-p1s3a6">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hojení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>8</deepord>
<children>
<LM id="T-wsj1242-001-p1s3a7">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W7-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rohovka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
<LM id="T-wsj1242-001-p1s3a9">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W9-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s3W8-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>operace</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj1242-001-p1s3a10">
<a>
<lex.rf>a#a-wsj1242-001-p1s3W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oko</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The collagen corneal shield helps speed healing of the cornea after eye surgery.</eng_sentence>
</LM>
<LM id="T-wsj1242-001-p1s4">
<atree.rf>a#a-wsj1242-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1242-001-p1s4a2">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W3-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1242-001-p1s4W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>distribuovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>2</deepord>
<val_frame.rf>v#v41uwA</val_frame.rf>
<children>
<LM id="T-wsj1242-001-p1s4a3">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výrobek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1242-001-p1s4a6">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W10-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s2a25</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1242-001-p1s4a5">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<children>
<LM id="T-wsj1242-001-p1s4a15">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>4</deepord>
<children>
<LM id="T-wsj1242-001-p1s4a12">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Pitman</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1242-001-p1s4a1">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W6-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>-</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj1242-001-p1s4a13">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W7-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Moore</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1242-001-p1s4a14">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1242-001-p1s4a18">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W9-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1242-001-p1s4a7">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W12-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<children>
<LM id="T-wsj1242-001-p1s4a8">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přidružený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>11</deepord>
</LM>
<LM id="T-wsj1242-001-p1s4a9">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1242-001-p1s0a26</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1242-001-p1s4a17">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>14</deepord>
<children>
<LM id="T-wsj1242-001-p1s4a11">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W14-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>International</t_lemma>
<functor>FPHR</functor>
<deepord>15</deepord>
</LM>
<LM id="T-wsj1242-001-p1s4a10">
<a>
<lex.rf>a#a-wsj1242-001-p1s4W15-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Minerals</t_lemma>
<functor>FPHR</functor>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>The product will be distributed by Pitman-Moore Inc., a subsidiary of International Minerals.</eng_sentence>
</LM>
</trees>
</tdata>
