<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj1383.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<trees>
<LM id="T-wsj1383-001-p1s0">
<atree.rf>a#a-wsj1383-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a9">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj1383-001-p1s0a2">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a31">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>3</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a3">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Rhone</t_lemma>
<functor>FPHR</functor>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a1">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>-</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a4">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Poulenc</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a5">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>S</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a32">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W6-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a7">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W7-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>A</t_lemma>
<functor>FPHR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a33">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1383-001-p1s0a11">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W10-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1383-001-p1s0W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Paříž</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj1383-001-p1s0a14">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1383-001-p1s0W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dokončit</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>13</deepord>
<val_frame.rf>v#v41ztB</val_frame.rf>
<children>
<LM id="T-wsj1383-001-p1s0a30">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1383-001-p1s0a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj1383-001-p1s0a15">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koupě</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a16">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provoz</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a17">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>specializovaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>15</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a18">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chemický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a34">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W23-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>23</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a19">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a35">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>20</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a20">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W20-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>RTZ</t_lemma>
<functor>FPHR</functor>
<deepord>19</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a21">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W21-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Corp</t_lemma>
<functor>FPHR</functor>
<deepord>21</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a22">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W22-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1383-001-p1s0a24">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>skupina</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>28</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a25">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W24-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>britský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>24</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a26">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W26-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>26</deepord>
<children>
<LM id="T-wsj1383-001-p1s0a27">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W25-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>důlní</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>25</deepord>
</LM>
<LM id="T-wsj1383-001-p1s0a28">
<a>
<lex.rf>a#a-wsj1383-001-p1s0W27-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>průmyslový</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Rhone-Poulenc S.A., Paris, said it completed the purchase of the specialty chemicals operation of RTZ Corp., a British mining and industrial group.</eng_sentence>
</LM>
<LM id="T-wsj1383-001-p1s1">
<atree.rf>a#a-wsj1383-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1383-001-p1s1a1">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W11-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj1383-001-p1s1a2">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1383-001-p1s0a30</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1383-001-p1s1a4">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>1</deepord>
<children>
<LM id="T-wsj1383-001-p1s1a27">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>3</deepord>
<children>
<LM id="T-wsj1383-001-p1s1a5">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Rhone</t_lemma>
<functor>FPHR</functor>
<deepord>2</deepord>
</LM>
<LM id="T-wsj1383-001-p1s1a29">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>-</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj1383-001-p1s1a3">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Poulenc</t_lemma>
<functor>FPHR</functor>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1383-001-p1s1a7">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>10</deepord>
<children>
<LM id="T-wsj1383-001-p1s1a8">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W7-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="T-wsj1383-001-p1s1a9">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W6-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chemický</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>7</deepord>
</LM>
<LM id="T-wsj1383-001-p1s1a10">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>farmaceutický</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1383-001-p1s1a14">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1383-001-p1s1W13-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>EFF</functor>
<proto_lemma>mít</proto_lemma>
<gram>
<sempos>v</sempos>
</gram>
<deepord>16</deepord>
<val_frame.rf>v#v41chlQ</val_frame.rf>
<children>
<LM id="T-wsj1383-001-p1s1a15">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W14-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1383-001-p1s0a16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj1383-001-p1s1a28">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>14</deepord>
<children>
<LM id="T-wsj1383-001-p1s1a16">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>RTZ</t_lemma>
<functor>FPHR</functor>
<deepord>13</deepord>
</LM>
<LM id="T-wsj1383-001-p1s1a17">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W16-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Chemicals</t_lemma>
<functor>FPHR</functor>
<deepord>15</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj1383-001-p1s1a18">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obrat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>18</deepord>
<children>
<LM id="T-wsj1383-001-p1s1a19">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>roční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>17</deepord>
</LM>
<LM id="T-wsj1383-001-p1s1a21">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W22-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>EXT</functor>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>20</deepord>
<children>
<LM id="T-wsj1383-001-p1s1a22">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W21-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj1383-001-p1s1W20-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>900</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>19</deepord>
</LM>
<LM id="T-wsj1383-001-p1s1a23">
<a>
<lex.rf>a#a-wsj1383-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dolar</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Rhone-Poulenc, a chemical and pharmaceutical company, said RTZ Chemicals has annual sales of about $900 million.</eng_sentence>
</LM>
<LM id="T-wsj1383-001-p1s2">
<atree.rf>a#a-wsj1383-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj1383-001-p1s2a1">
<a>
<lex.rf>a#a-wsj1383-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zveřejnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41sbmB</val_frame.rf>
<children>
<LM id="T-wsj1383-001-p1s2a5">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj1383-001-p1s2a2">
<a>
<lex.rf>a#a-wsj1383-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podmínka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj1383-001-p1s2a3">
<a>
<lex.rf>a#a-wsj1383-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>transakce</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1383-001-p1s0a15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="T-wsj1383-001-p1s2a6">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj1383-001-p1s1a2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
<eng_sentence>It didn't release terms of the transaction.</eng_sentence>
</LM>
</trees>
</tdata>
