<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="wsj2076.cz.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta/>
<trees>
<LM id="T-wsj2076-001-p1s0">
<atree.rf>a#a-wsj2076-001-p1s0</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2076-001-p1s0a1">
<a>
<lex.rf>a#a-wsj2076-001-p1s0W2-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tisk</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj2076-001-p1s0a2">
<a>
<lex.rf>a#a-wsj2076-001-p1s0W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>novinový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>1</deepord>
</LM>
</children>
</LM>
</children>
<eng_sentence>NEWSPAPERS:</eng_sentence>
</LM>
<LM id="T-wsj2076-001-p1s1">
<atree.rf>a#a-wsj2076-001-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a7">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W7-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s1W6-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>8</deepord>
<val_frame.rf>v#v41hbiA</val_frame.rf>
<children>
<LM id="T-wsj2076-001-p1s1a37">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a2">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a36">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>5</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a3">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Media</t_lemma>
<functor>FPHR</functor>
<deepord>3</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a5">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W3-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>General</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a4">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W4-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a39">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2076-001-p1s1a40">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W18-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>15</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a8">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W8-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dva</t_lemma>
<functor>PAT</functor>
<proto_lemma>dva</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a10">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W11-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s1W9-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řetězec</t_lemma>
<functor>DIR1</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>11</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a11">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>10</deepord>
<coref_gram.rf>
<LM>T-wsj2076-001-p1s1a2</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2076-001-p1s1a13">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W14-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s1W12-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pobřeží</t_lemma>
<functor>LOC</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a14">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W13-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>západní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2076-001-p1s1a17">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nabízející</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>14</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a16">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W17-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tisk</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>17</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a18">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W16-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>týdenní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2076-001-p1s1a15">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W24-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<is_member>1</is_member>
<deepord>23</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a42">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<deepord>24</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a21">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W19-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Golden</t_lemma>
<functor>FPHR</functor>
<deepord>18</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a22">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W20-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>West</t_lemma>
<functor>FPHR</functor>
<deepord>19</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a23">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W21-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Publishing</t_lemma>
<functor>FPHR</functor>
<deepord>20</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a20">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W22-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Inc</t_lemma>
<functor>FPHR</functor>
<deepord>21</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a43">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W23-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>22</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2076-001-p1s1a41">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<deepord>25</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a26">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W25-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Highlander</t_lemma>
<functor>FPHR</functor>
<deepord>26</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a25">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W26-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Publications</t_lemma>
<functor>FPHR</functor>
<deepord>27</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2076-001-p1s1a28">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W30-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>produkovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>30</deepord>
<val_frame.rf>v#v41hcjA</val_frame.rf>
<children>
<LM id="T-wsj2076-001-p1s1a29">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W28-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
</gram>
<deepord>28</deepord>
<coref_gram.rf>
<LM>T-wsj2076-001-p1s1a40</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2076-001-p1s1a30">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W29-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celkově</t_lemma>
<functor>MANN</functor>
<proto_lemma>celkový</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>29</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a33">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W34-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>titul</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>35</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a44">
<nodetype>coap</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Separ</t_lemma>
<functor>CONJ</functor>
<deepord>33</deepord>
<children>
<LM id="T-wsj2076-001-p1s1a31">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W31-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>třicet</t_lemma>
<functor>RSTR</functor>
<proto_lemma>třicet</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>31</deepord>
</LM>
<LM id="T-wsj2076-001-p1s1a32">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W32-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jeden</t_lemma>
<functor>RSTR</functor>
<proto_lemma>jeden</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
</gram>
<deepord>32</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2076-001-p1s1a34">
<a>
<lex.rf>a#a-wsj2076-001-p1s1W33-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>novinový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>34</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Media General Inc. intends to sell two of its West Coast weekly newspaper chains, Golden West Publishing Inc. and Highlander Publications, which together comprise 31 papers.</eng_sentence>
</LM>
<LM id="T-wsj2076-001-p1s2">
<atree.rf>a#a-wsj2076-001-p1s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2076-001-p1s2a1">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W3-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>4</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="T-wsj2076-001-p1s2a25">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ACT</functor>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2076-001-p1s1a11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="T-wsj2076-001-p1s2a3">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W1-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Media</t_lemma>
<functor>FPHR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2076-001-p1s2a2">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W2-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>General</t_lemma>
<functor>FPHR</functor>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="T-wsj2076-001-p1s2a6">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W11-Ta</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="T-wsj2076-001-p1s2a24">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2076-001-p1s2a25</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2076-001-p1s2a7">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W6-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s2W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>EFF</functor>
<proto_lemma>mít</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>6</deepord>
<val_frame.rf>v#v41chlCC</val_frame.rf>
<children>
<LM id="T-wsj2076-001-p1s2a9">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W8-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s2W7-Ta</LM>
</aux.rf>
</a>
<nodetype>dphr</nodetype>
<t_lemma>k_dispozici</t_lemma>
<functor>DPHR</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj2076-001-p1s2a10">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W10-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kupec</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>9</deepord>
<children>
<LM id="T-wsj2076-001-p1s2a11">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W9-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potenciální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
</gram>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="T-wsj2076-001-p1s2a12">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W12-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s2W5-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>očekávat</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
</gram>
<deepord>11</deepord>
<discourse>
<LM>
<target_node.rf>T-wsj2076-001-p1s2a7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>A_H_A</src>
<t-connectors.rf>
<LM>T-wsj2076-001-p1s2a6</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41dvcA</val_frame.rf>
<children>
<LM id="T-wsj2076-001-p1s2a15">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W17-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s2W16-Ta</LM>
<LM>a#a-wsj2076-001-p1s2W14-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>realizovat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
</gram>
<deepord>14</deepord>
<val_frame.rf>v#v41jfuB</val_frame.rf>
<children>
<LM id="T-wsj2076-001-p1s2a23">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2076-001-p1s2a24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2076-001-p1s2a16">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W15-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodej</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2076-001-p1s1a7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2076-001-p1s2a19">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W19-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s2W18-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>15</deepord>
<children>
<LM id="T-wsj2076-001-p1s2a20">
<a>
<lex.rf>a#a-wsj2076-001-p1s2W20-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1989</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.quant.def</sempos>
</gram>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Media General said it has had inquiries from potential buyers and expects to complete a sale in 1989.</eng_sentence>
</LM>
<LM id="T-wsj2076-001-p1s3">
<atree.rf>a#a-wsj2076-001-p1s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2076-001-p1s3a1">
<a>
<lex.rf>a#a-wsj2076-001-p1s3W3-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s3W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>projednávat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41hevA</val_frame.rf>
<children>
<LM id="T-wsj2076-001-p1s3a3">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
</gram>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>T-wsj2076-001-p1s2a23</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>T-wsj2076-001-p1s2a10</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
</LM>
<LM id="T-wsj2076-001-p1s3a2">
<a>
<lex.rf>a#a-wsj2076-001-p1s3W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cena</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
</LM>
<LM id="T-wsj2076-001-p1s3a5">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<deepord>4</deepord>
<coref_gram.rf>
<LM>T-wsj2076-001-p1s3a3</LM>
</coref_gram.rf>
</LM>
<LM id="T-wsj2076-001-p1s3a4">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
<eng_sentence>It wouldn't discuss a price.</eng_sentence>
</LM>
<LM id="T-wsj2076-001-p1s4">
<atree.rf>a#a-wsj2076-001-p1s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="T-wsj2076-001-p1s4a1">
<a>
<lex.rf>a#a-wsj2076-001-p1s4W3-Ta</lex.rf>
<aux.rf>
<LM>a#a-wsj2076-001-p1s4W2-Ta</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prodávat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
</gram>
<deepord>3</deepord>
<val_frame.rf>v#v41hblA</val_frame.rf>
<children>
<LM id="T-wsj2076-001-p1s4a9">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<deepord>1</deepord>
</LM>
<LM id="T-wsj2076-001-p1s4a2">
<a>
<lex.rf>a#a-wsj2076-001-p1s4W1-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>řetězec</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>T-wsj2076-001-p1s1a29</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="T-wsj2076-001-p1s4a4">
<a>
<lex.rf>a#a-wsj2076-001-p1s4W4-Ta</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
</gram>
<deepord>4</deepord>
<children>
<LM id="T-wsj2076-001-p1s4a10">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<deepord>5</deepord>
<children>
<LM id="T-wsj2076-001-p1s4a7">
<a>
<lex.rf>a#a-wsj2076-001-p1s4W5-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Lee</t_lemma>
<functor>FPHR</functor>
<deepord>6</deepord>
</LM>
<LM id="T-wsj2076-001-p1s4a6">
<a>
<lex.rf>a#a-wsj2076-001-p1s4W6-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Dirks</t_lemma>
<functor>FPHR</functor>
<deepord>7</deepord>
</LM>
<LM id="T-wsj2076-001-p1s4a8">
<a>
<lex.rf>a#a-wsj2076-001-p1s4W7-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>&amp;</t_lemma>
<functor>FPHR</functor>
<deepord>8</deepord>
</LM>
<LM id="T-wsj2076-001-p1s4a5">
<a>
<lex.rf>a#a-wsj2076-001-p1s4W8-Ta</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Associates</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
<eng_sentence>Lee Dirks &amp; Associates is to sell the chains.</eng_sentence>
</LM>
</trees>
</tdata>
