<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94208_56.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln94208-56-p1s1">
<atree.rf>a#a-ln94208-56-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94208-56-l14A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94208-56-p1s1w3</LM>
<LM>t-ln94208-56-p1s1w4</LM>
<LM>t-ln94208-56-p1s1w5</LM>
<LM>t-ln94208-56-p1s1w6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94208-56-p1s1a1">
<a>
<lex.rf>a#a-ln94208-56-p1s1w2</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Colon</t_lemma>
<functor>CONJ</functor>
<deepord>2</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln94208-56-p1s1w1">
<a>
<lex.rf>a#a-ln94208-56-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČSSD</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94208-56-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<tfa>t</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94208-56-p1s1w6">
<a>
<lex.rf>a#a-ln94208-56-p1s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94208-56-p1s1w8">
<a>
<lex.rf>a#a-ln94208-56-p1s1w8</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p1s1w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>volba</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94208-56-p1s1w4">
<a>
<lex.rf>a#a-ln94208-56-p1s1w4</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>až</t_lemma>
<functor>OPER</functor>
<deepord>7</deepord>
<children>
<LM id="t-ln94208-56-p1s1w3">
<a>
<lex.rf>a#a-ln94208-56-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pět</t_lemma>
<functor>RSTR</functor>
<proto_lemma>pět</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94208-56-p1s1w5">
<a>
<lex.rf>a#a-ln94208-56-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sedm</t_lemma>
<functor>RSTR</functor>
<proto_lemma>sedm</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s1A">
<atree.rf>a#a-ln94208-56-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94208-56-p2s1Aa0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<tfa>t</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln94208-56-p2s1Aw3">
<a>
<lex.rf>a#a-ln94208-56-p2s1Aw3</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s1Aw1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>scéna</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94208-56-p2s1Aw2">
<a>
<lex.rf>a#a-ln94208-56-p2s1Aw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>politický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s1B">
<atree.rf>a#a-ln94208-56-p2s1B</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94208-56-p2s1Bw1">
<a>
<lex.rf>a#a-ln94208-56-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94208-56-p2s1Bw4">
<a>
<lex.rf>a#a-ln94208-56-p2s1Bw4</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<is_parenthesis>1</is_parenthesis>
<deepord>3</deepord>
<children>
<LM id="t-ln94208-56-p2s1Bw3">
<a>
<lex.rf>a#a-ln94208-56-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>em</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>nr</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94208-56-p2s1Bw5">
<a>
<lex.rf>a#a-ln94208-56-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČTK</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s1C">
<atree.rf>a#a-ln94208-56-p2s1C</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94208-56-l16A">
<basic-form>výkonný výbor</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94208-56-p2s1Cw1</LM>
<LM>t-ln94208-56-p2s1Cw2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94208-56-l17A">
<basic-form>komunální volby</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94208-56-p2s1Cw16</LM>
<LM>t-ln94208-56-p2s1Cw17</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94208-56-p2s1Cw10">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw10</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CSQ</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln94208-56-p2s1Cw2">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výbor</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94208-56-p2s1Cw1">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výkonný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94208-56-p2s1Cw3">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČSSD</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s1Cw4">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94208-56-p2s1Cw13</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>reason</discourse_type>
<sense_PDTB3>Contingency.Cause.Result</sense_PDTB3>
<src>pdt30</src>
<t-connectors.rf>
<LM>t-ln94208-56-p2s1Cw11</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s1Ca0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94208-56-p2s1Cw8">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw8</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s1Cw5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zasedání</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41qkhA</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s1Cw6">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_gram.rf>
<LM>t-ln94208-56-p2s1Cw2</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94208-56-p2s1Cw7">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>víkendový</t_lemma>
<functor>TWHEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s1Cw9">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>usnášeníschopný</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s1Cw11">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw11</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>proto</t_lemma>
<functor>CM</functor>
<deepord>11</deepord>
</LM>
<LM id="t-ln94208-56-p2s1Cw13">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw13</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s1Cw12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přijmout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41isjG</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s1Ca1">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln94208-56-p2s1Cw14">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>usnesení</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41mwsA</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s1Ca2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_gram.rf>
<LM>t-ln94208-56-p2s1Cw2</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94208-56-p2s1Cw17">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw17</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s1Cw15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>volba</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p1s1w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94208-56-p2s1Cw16">
<a>
<lex.rf>a#a-ln94208-56-p2s1Cw16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komunální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s2">
<atree.rf>a#a-ln94208-56-p2s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94208-56-p2s2w8">
<a>
<lex.rf>a#a-ln94208-56-p2s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oznámit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41fgeB</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s2w1">
<a>
<lex.rf>a#a-ln94208-56-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jméno</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94208-56-p2s2w2">
<a>
<lex.rf>a#a-ln94208-56-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kandidát</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94208-56-p2s2w4">
<a>
<lex.rf>a#a-ln94208-56-p2s2w4</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praha</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p2s1Bw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s2w6">
<a>
<lex.rf>a#a-ln94208-56-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Zeman</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94208-56-p2s2w5">
<a>
<lex.rf>a#a-ln94208-56-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94208-56-p2s1Cw3</target_node.rf>
<type>P_FUNCT</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94208-56-p2s2w7">
<a>
<lex.rf>a#a-ln94208-56-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zatím</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94208-56-p2s2a1">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s3">
<atree.rf>a#a-ln94208-56-p2s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94208-56-l19A">
<basic-form>sociální demokraté</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94208-56-p2s3w1</LM>
<LM>t-ln94208-56-p2s3w2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94208-56-l20A">
<basic-form>okresní město</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94208-56-p2s3w16</LM>
<LM>t-ln94208-56-p2s3w17</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94208-56-p2s3w13">
<a>
<lex.rf>a#a-ln94208-56-p2s3w13</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln94208-56-p2s3w2">
<a>
<lex.rf>a#a-ln94208-56-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>demokrat</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p2s1Cw3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94208-56-p2s3w1">
<a>
<lex.rf>a#a-ln94208-56-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sociální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s3w5">
<a>
<lex.rf>a#a-ln94208-56-p2s3w5</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>slovo</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94208-56-p2s3w4">
<a>
<lex.rf>a#a-ln94208-56-p2s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p2s2w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s3w8">
<a>
<lex.rf>a#a-ln94208-56-p2s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kandidátka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94208-56-p2s3w7">
<a>
<lex.rf>a#a-ln94208-56-p2s3w7</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s3w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41chlO</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s3w12">
<a>
<lex.rf>a#a-ln94208-56-p2s3w12</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s3w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94208-56-p2s2w4</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln94208-56-p2s3w11">
<a>
<lex.rf>a#a-ln94208-56-p2s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>velký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln94208-56-p2s3w10">
<a>
<lex.rf>a#a-ln94208-56-p2s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s3a0">
<a>
<lex.rf>a#a-ln94208-56-p2s3w7</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s3w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>post</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94208-56-p2s3w7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>MR</src>
<t-connectors.rf>
<LM>t-ln94208-56-p2s3w14</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41chlO</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s3w14">
<a>
<lex.rf>a#a-ln94208-56-p2s3w14</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>dále</t_lemma>
<functor>PREC</functor>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94208-56-p2s3w18">
<a>
<lex.rf>a#a-ln94208-56-p2s3w18</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>15</deepord>
<children>
<LM id="t-ln94208-56-p2s3w17">
<a>
<lex.rf>a#a-ln94208-56-p2s3w17</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s3w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94208-56-p2s3w16">
<a>
<lex.rf>a#a-ln94208-56-p2s3w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>okresní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s3w20">
<a>
<lex.rf>a#a-ln94208-56-p2s3w20</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s3w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obec</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln94208-56-p2s3w19">
<a>
<lex.rf>a#a-ln94208-56-p2s3w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
<LM id="t-ln94208-56-p2s3w23">
<a>
<lex.rf>a#a-ln94208-56-p2s3w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>RSTR</functor>
<proto_lemma>mít</proto_lemma>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<val_frame.rf>v#v41chlO</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s3w22">
<a>
<lex.rf>a#a-ln94208-56-p2s3w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
<coref_gram.rf>
<LM>t-ln94208-56-p2s3w20</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94208-56-p2s3w24">
<a>
<lex.rf>a#a-ln94208-56-p2s3w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<children>
<LM id="t-ln94208-56-p2s3w27">
<a>
<lex.rf>a#a-ln94208-56-p2s3w27</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s3w25</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obyvatel</t_lemma>
<functor>CPR</functor>
<subfunctor>than</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<children>
<LM id="t-ln94208-56-p2s3w26">
<a>
<lex.rf>a#a-ln94208-56-p2s3w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>5000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s4">
<atree.rf>a#a-ln94208-56-p2s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94208-56-l15A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94208-56-p2s4w7</LM>
<LM>t-ln94208-56-p2s4w8</LM>
<LM>t-ln94208-56-p2s4w9</LM>
<LM>t-ln94208-56-p2s4w10</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94208-56-l21A">
<basic-form>předvolební kampaň</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94208-56-p2s4w2</LM>
<LM>t-ln94208-56-p2s4w3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94208-56-p2s4w6">
<a>
<lex.rf>a#a-ln94208-56-p2s4w6</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s4w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>investovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>vol</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41bheA</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s4w5">
<a>
<lex.rf>a#a-ln94208-56-p2s4w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČSSD</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p2s3w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94208-56-p2s4w3">
<a>
<lex.rf>a#a-ln94208-56-p2s4w3</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s4w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kampaň</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94208-56-p2s4w2">
<a>
<lex.rf>a#a-ln94208-56-p2s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předvolební</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s4w10">
<a>
<lex.rf>a#a-ln94208-56-p2s4w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>milión</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p1s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94208-56-p2s4w11">
<a>
<lex.rf>a#a-ln94208-56-p2s4w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94208-56-p2s4w8">
<a>
<lex.rf>a#a-ln94208-56-p2s4w8</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>až</t_lemma>
<functor>OPER</functor>
<deepord>8</deepord>
<children>
<LM id="t-ln94208-56-p2s4w7">
<a>
<lex.rf>a#a-ln94208-56-p2s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>5</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94208-56-p2s4w9">
<a>
<lex.rf>a#a-ln94208-56-p2s4w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>7</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s5">
<atree.rf>a#a-ln94208-56-p2s5</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94208-56-l18A">
<basic-form>komunální volby</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94208-56-p2s5w5</LM>
<LM>t-ln94208-56-p2s5w6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94208-56-p2s5w7">
<a>
<lex.rf>a#a-ln94208-56-p2s5w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>považovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41gtiA</val_frame.rf>
<children>
<LM id="t-ln94208-56-p2s5w3">
<a>
<lex.rf>a#a-ln94208-56-p2s5w3</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s5w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konkurent</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94208-56-p2s5w6">
<a>
<lex.rf>a#a-ln94208-56-p2s5w6</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p2s5w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>volba</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p2s1Cw17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94208-56-p2s5w5">
<a>
<lex.rf>a#a-ln94208-56-p2s5w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komunální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s5w2">
<a>
<lex.rf>a#a-ln94208-56-p2s5w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>velký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>sup</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p2s5a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p2s4w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94208-56-p2s5w8">
<a>
<lex.rf>a#a-ln94208-56-p2s5w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ODS</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p3s1">
<atree.rf>a#a-ln94208-56-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94208-56-l8A">
<type>location</type>
<tnode.rfs>
<LM>t-ln94208-56-p3s1w5</LM>
<LM>t-ln94208-56-p3s1w6</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94208-56-l13A">
<basic-form>Miroslav Kříženecký</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94208-56-p3s1w22</LM>
<LM>t-ln94208-56-p3s1w23</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94208-56-l22A">
<basic-form>obecní volby</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94208-56-p3s1w13</LM>
<LM>t-ln94208-56-p3s1w14</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94208-56-l23A">
<basic-form>vojenský prokurátor</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94208-56-p3s1w17</LM>
<LM>t-ln94208-56-p3s1w18</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94208-56-p3s1w7">
<a>
<lex.rf>a#a-ln94208-56-p3s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zvolit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41sciA</val_frame.rf>
<children>
<LM id="t-ln94208-56-p3s1w2">
<a>
<lex.rf>a#a-ln94208-56-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>konference</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94208-56-p3s1w3">
<a>
<lex.rf>a#a-ln94208-56-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČSSD</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p2s5a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94208-56-p3s1w1">
<a>
<lex.rf>a#a-ln94208-56-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>městský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94208-56-p2s3w12</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94208-56-p3s1w6">
<a>
<lex.rf>a#a-ln94208-56-p3s1w6</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p3s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Budějovice</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p3s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94208-56-p3s1w5">
<a>
<lex.rf>a#a-ln94208-56-p3s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p3s1w11">
<a>
<lex.rf>a#a-ln94208-56-p3s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p3s1w8</LM>
<LM>a#a-ln94208-56-p3s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kandidátka</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94208-56-p2s3w8</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln94208-56-p3s1w10">
<a>
<lex.rf>a#a-ln94208-56-p3s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_gram.rf>
<LM>t-ln94208-56-p3s1w2</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94208-56-p3s1w14">
<a>
<lex.rf>a#a-ln94208-56-p3s1w14</lex.rf>
<aux.rf>
<LM>a#a-ln94208-56-p3s1w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>volba</t_lemma>
<functor>BEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94208-56-p2s5w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94208-56-p3s1w13">
<a>
<lex.rf>a#a-ln94208-56-p3s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obecní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p3s1w23">
<a>
<lex.rf>a#a-ln94208-56-p3s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Kříženecký</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94208-56-p3s1w11</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-ln94208-56-p3s1w22">
<a>
<lex.rf>a#a-ln94208-56-p3s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Miroslav</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln94208-56-p3s1w19">
<a>
<lex.rf>a#a-ln94208-56-p3s1w19</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>17</deepord>
<children>
<LM id="t-ln94208-56-p3s1w18">
<a>
<lex.rf>a#a-ln94208-56-p3s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prokurátor</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94208-56-p3s1w17">
<a>
<lex.rf>a#a-ln94208-56-p3s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vojenský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln94208-56-p3s1w16">
<a>
<lex.rf>a#a-ln94208-56-p3s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlavní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln94208-56-p3s1w15">
<a>
<lex.rf>a#a-ln94208-56-p3s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>někdejší</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94208-56-p3s1w21">
<a>
<lex.rf>a#a-ln94208-56-p3s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>advokát</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln94208-56-p3s1w20">
<a>
<lex.rf>a#a-ln94208-56-p3s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nynější</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
