<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf920922_123.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-mf920922-123-p1s1C">
<atree.rf>a#a-mf920922-123-p1s1C</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-123-p1s1w3">
<a>
<lex.rf>a#a-mf920922-123-p1s1w3</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p1s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozšířit_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41jyyB</val_frame.rf>
<children>
<LM id="t-mf920922-123-p1s1w1">
<a>
<lex.rf>a#a-mf920922-123-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přestřelka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-123-p1s1w4">
<a>
<lex.rf>a#a-mf920922-123-p1s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znovu</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-123-p1s1w7">
<a>
<lex.rf>a#a-mf920922-123-p1s1w7</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p1s1w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>území</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf920922-123-p1s1w6">
<a>
<lex.rf>a#a-mf920922-123-p1s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chorvatský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p1s1B">
<atree.rf>a#a-mf920922-123-p1s1B</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-123-p1s1w8">
<a>
<lex.rf>a#a-mf920922-123-p1s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-mf920922-123-p1s1w9">
<a>
<lex.rf>a#a-mf920922-123-p1s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>delegace</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-123-p1s1w10">
<a>
<lex.rf>a#a-mf920922-123-p1s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>muslim</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf920922-123-p1s1w12">
<a>
<lex.rf>a#a-mf920922-123-p1s1w12</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p1s1w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ženeva</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p2s1A">
<atree.rf>a#a-mf920922-123-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-123-p2s1Aw2">
<a>
<lex.rf>a#a-mf920922-123-p2s1Aw2</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>2</deepord>
<children>
<LM id="t-mf920922-123-p2s1Aw1">
<a>
<lex.rf>a#a-mf920922-123-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Záhřeb</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p1s1w6</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
<LM id="t-mf920922-123-p2s1Aw3">
<a>
<lex.rf>a#a-mf920922-123-p2s1Aw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sarajevo</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p2s1B">
<atree.rf>a#a-mf920922-123-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-123-l5A">
<basic-form>Slavonski Brod</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-mf920922-123-p2s1Bw11</LM>
<LM>t-mf920922-123-p2s1Bw12</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-123-p2s1Bw7">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ostřelovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41faoA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p2s1Bw3">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>armáda</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920922-123-p2s1Bw2">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>federální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-123-p2s1Bw1">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jugoslávský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p2s1Bw4">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-123-p2s1Bw5">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ráno</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p2s1Bw4</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
<LM id="t-mf920922-123-p2s1Bw6">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znovu</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf920922-123-p2s1Bw13">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw13</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>14</deepord>
<children>
<LM id="t-mf920922-123-p2s1Bw10">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>město</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p1s1w6</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
<children>
<LM id="t-mf920922-123-p2s1Bw8">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chorvatský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p1s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p2s1Bw9">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pohraniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-mf920922-123-p2s1Ba0">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-mf920922-123-p2s1Bw11">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw11</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Slavonski</t_lemma>
<functor>FPHR</functor>
<deepord>11</deepord>
</LM>
<LM id="t-mf920922-123-p2s1Bw12">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw12</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Brod</t_lemma>
<functor>FPHR</functor>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p2s1Bw15">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>okolí</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf920922-123-p2s1Bw14">
<a>
<lex.rf>a#a-mf920922-123-p2s1Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>neut</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p2s1Bw10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s1">
<atree.rf>a#a-mf920922-123-p3s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-123-p3s1w3">
<a>
<lex.rf>a#a-mf920922-123-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41jsU</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s1w2">
<a>
<lex.rf>a#a-mf920922-123-p3s1w2</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s1w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sarajevo</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p2s1Aw3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p3s1w5">
<a>
<lex.rf>a#a-mf920922-123-p3s1w5</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>noc</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf920922-123-p3s1w7">
<a>
<lex.rf>a#a-mf920922-123-p3s1w7</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včerejšek</t_lemma>
<functor>TOWH</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p2s1Bw4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s1w9">
<a>
<lex.rf>a#a-mf920922-123-p3s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klid</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-123-p3s1w8">
<a>
<lex.rf>a#a-mf920922-123-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>relativní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s2">
<atree.rf>a#a-mf920922-123-p3s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-123-p3s2w3">
<a>
<lex.rf>a#a-mf920922-123-p3s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s2w2">
<a>
<lex.rf>a#a-mf920922-123-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhlas</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf920922-123-p3s2w1">
<a>
<lex.rf>a#a-mf920922-123-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bosenský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p3s1w2</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s2w9">
<a>
<lex.rf>a#a-mf920922-123-p3s2w9</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s2w8</LM>
<LM>a#a-mf920922-123-p3s2w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaznamenat</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41qurD</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s2w7">
<a>
<lex.rf>a#a-mf920922-123-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přestřelka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf920922-123-p3s2w6">
<a>
<lex.rf>a#a-mf920922-123-p3s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>intenzívní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>acomp</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf920922-123-p3s2w14">
<a>
<lex.rf>a#a-mf920922-123-p3s2w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p3s1w2</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
<children>
<LM id="t-mf920922-123-p3s2w12">
<a>
<lex.rf>a#a-mf920922-123-p3s2w12</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předměstí</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf920922-123-p3s2w13">
<a>
<lex.rf>a#a-mf920922-123-p3s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Stup</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s2a1">
<a>
<lex.rf>a#a-mf920922-123-p3s2w12</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>předměstí</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<children>
<LM id="t-mf920922-123-p3s2w15">
<a>
<lex.rf>a#a-mf920922-123-p3s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Nedarica</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s2w11">
<a>
<lex.rf>a#a-mf920922-123-p3s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>západní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s3">
<atree.rf>a#a-mf920922-123-p3s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-123-l10A">
<basic-form>Bosna a Hercegovina</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-mf920922-123-p3s3w7</LM>
<LM>t-mf920922-123-p3s3w8</LM>
<LM>t-mf920922-123-p3s3w9</LM>
</tnode.rfs>
</LM>
<LM id="s-mf920922-123-l25A">
<basic-form>ústavní rámec</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf920922-123-p3s3w5</LM>
<LM>t-mf920922-123-p3s3w6</LM>
</tnode.rfs>
</LM>
<LM id="s-mf920922-123-l26A">
<basic-form>vládní delegace</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf920922-123-p3s3w27</LM>
<LM>t-mf920922-123-p3s3w28</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-123-p3s3w22">
<a>
<lex.rf>a#a-mf920922-123-p3s3w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zveřejnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<val_frame.rf>v#v41sbmB</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s3w1">
<a>
<lex.rf>a#a-mf920922-123-p3s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p1s1w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-123-p3s3w3">
<a>
<lex.rf>a#a-mf920922-123-p3s3w3</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s3w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vytvoření</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41pemA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s3a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-123-p3s3w6">
<a>
<lex.rf>a#a-mf920922-123-p3s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rámec</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf920922-123-p3s3w5">
<a>
<lex.rf>a#a-mf920922-123-p3s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ústavní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf920922-123-p3s3w4">
<a>
<lex.rf>a#a-mf920922-123-p3s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf920922-123-p3s3w8">
<a>
<lex.rf>a#a-mf920922-123-p3s3w8</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s2w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-123-p3s3w7">
<a>
<lex.rf>a#a-mf920922-123-p3s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bosna</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf920922-123-p3s3w9">
<a>
<lex.rf>a#a-mf920922-123-p3s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hercegovina</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-mf920922-123-p3s3w14">
<a>
<lex.rf>a#a-mf920922-123-p3s3w14</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s3w13</LM>
<LM>a#a-mf920922-123-p3s3w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zůstat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41sadA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s3w11">
<a>
<lex.rf>a#a-mf920922-123-p3s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_gram.rf>
<LM>t-mf920922-123-p3s3w8</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf920922-123-p3s3w20">
<a>
<lex.rf>a#a-mf920922-123-p3s3w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-mf920922-123-p3s3w17">
<a>
<lex.rf>a#a-mf920922-123-p3s3w17</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>ale</t_lemma>
<functor>ADVS</functor>
<deepord>14</deepord>
<children>
<LM id="t-mf920922-123-p3s3w15">
<a>
<lex.rf>a#a-mf920922-123-p3s3w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednotný</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-mf920922-123-p3s3w19">
<a>
<lex.rf>a#a-mf920922-123-p3s3w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>decentralizovaný</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-mf920922-123-p3s3w18">
<a>
<lex.rf>a#a-mf920922-123-p3s3w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>silně</t_lemma>
<functor>EXT</functor>
<proto_lemma>silný</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s3w23">
<a>
<lex.rf>a#a-mf920922-123-p3s3w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s1w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p3s3w25">
<a>
<lex.rf>a#a-mf920922-123-p3s3w25</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s3w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ženeva</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p1s1w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p3s3w28">
<a>
<lex.rf>a#a-mf920922-123-p3s3w28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>delegace</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p1s1w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-123-p3s3w27">
<a>
<lex.rf>a#a-mf920922-123-p3s3w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vládní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
<LM id="t-mf920922-123-p3s3w26">
<a>
<lex.rf>a#a-mf920922-123-p3s3w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>muslimský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p1s1w10</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s4">
<atree.rf>a#a-mf920922-123-p3s4</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-123-p3s4w3">
<a>
<lex.rf>a#a-mf920922-123-p3s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klást</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41bkwA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s4w1">
<a>
<lex.rf>a#a-mf920922-123-p3s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s3w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p3s4w2">
<a>
<lex.rf>a#a-mf920922-123-p3s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_gram.rf>
<LM>t-mf920922-123-p3s4w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf920922-123-p3s4w5">
<a>
<lex.rf>a#a-mf920922-123-p3s4w5</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s4w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cíl</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-123-p3s4w6">
<a>
<lex.rf>a#a-mf920922-123-p3s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vytvoření</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41pemA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s4a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf920922-123-p3s4w13">
<a>
<lex.rf>a#a-mf920922-123-p3s4w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>citation</type>
<set_id>mf920922-123-p3s4w13</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s3w20</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-123-p3s4w11">
<a>
<lex.rf>a#a-mf920922-123-p3s4w11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<quot>
<LM>
<type>citation</type>
<set_id>mf920922-123-p3s4w13</set_id>
</LM>
</quot>
<deepord>10</deepord>
<children>
<LM id="t-mf920922-123-p3s4w8">
<a>
<lex.rf>a#a-mf920922-123-p3s4w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>demokratický</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>citation</type>
<set_id>mf920922-123-p3s4w13</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf920922-123-p3s4w10">
<a>
<lex.rf>a#a-mf920922-123-p3s4w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>laický</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>citation</type>
<set_id>mf920922-123-p3s4w13</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-mf920922-123-p3s4w12">
<a>
<lex.rf>a#a-mf920922-123-p3s4w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>decentralizovaný</t_lemma>
<functor>RSTR</functor>
<quot>
<LM>
<type>citation</type>
<set_id>mf920922-123-p3s4w13</set_id>
</LM>
</quot>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s4w18">
<a>
<lex.rf>a#a-mf920922-123-p3s4w18</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s4w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zaručit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>potential</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41qioA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s4w16">
<a>
<lex.rf>a#a-mf920922-123-p3s4w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_gram.rf>
<LM>t-mf920922-123-p3s4w13</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf920922-123-p3s4w20">
<a>
<lex.rf>a#a-mf920922-123-p3s4w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>národ</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p3s3w26</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-mf920922-123-p3s4w19">
<a>
<lex.rf>a#a-mf920922-123-p3s4w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>všechen</t_lemma>
<functor>RSTR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>adj.pron.indef</sempos>
<indeftype>total1</indeftype>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s4w22">
<a>
<lex.rf>a#a-mf920922-123-p3s4w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>právo</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf920922-123-p3s4w21">
<a>
<lex.rf>a#a-mf920922-123-p3s4w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stejný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s5">
<atree.rf>a#a-mf920922-123-p3s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-123-p3s5w6">
<a>
<lex.rf>a#a-mf920922-123-p3s5w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>reagovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41jfoB</val_frame.rf>
<children>
<LM id="t-mf920922-123-p3s5w2">
<a>
<lex.rf>a#a-mf920922-123-p3s5w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>strana</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p3s4w20</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
<children>
<LM id="t-mf920922-123-p3s5w1">
<a>
<lex.rf>a#a-mf920922-123-p3s5w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>srbský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p3s5w4">
<a>
<lex.rf>a#a-mf920922-123-p3s5w4</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p3s5w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s4w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p3s5w5">
<a>
<lex.rf>a#a-mf920922-123-p3s5w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosud</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-123-p3s5a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p4s1">
<atree.rf>a#a-mf920922-123-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-123-l16A">
<basic-form>Bosna a Hercegovina</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-mf920922-123-p4s1w4</LM>
<LM>t-mf920922-123-p4s1w5</LM>
<LM>t-mf920922-123-p4s1w6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-123-p4s1w8">
<a>
<lex.rf>a#a-mf920922-123-p4s1w8</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s1w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dohodnout_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41yeA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p4s1w2">
<a>
<lex.rf>a#a-mf920922-123-p4s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>strana</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p3s5w2</target_node.rf>
<type>SUB_SET</type>
</LM>
<LM>
<target_node.rf>t-mf920922-123-p3s3w26</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-mf920922-123-p4s1w1">
<a>
<lex.rf>a#a-mf920922-123-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znepřátelený</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf920922-123-p4s1w5">
<a>
<lex.rf>a#a-mf920922-123-p4s1w5</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s3w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-123-p4s1w4">
<a>
<lex.rf>a#a-mf920922-123-p4s1w4</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bosna</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s3w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p4s1w6">
<a>
<lex.rf>a#a-mf920922-123-p4s1w6</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hercegovina</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s3w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p4s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_gram.rf>
<LM>t-mf920922-123-p4s1w2</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf920922-123-p4s1w10">
<a>
<lex.rf>a#a-mf920922-123-p4s1w10</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyhlášení</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41nzdA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p4s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf920922-123-p4s1w12">
<a>
<lex.rf>a#a-mf920922-123-p4s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>týden</t_lemma>
<functor>PAT</functor>
<quot>
<LM>
<type>title</type>
<set_id>mf920922-123-p4s1w12</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf920922-123-p4s1w13">
<a>
<lex.rf>a#a-mf920922-123-p4s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klid</t_lemma>
<functor>APP</functor>
<quot>
<LM>
<type>title</type>
<set_id>mf920922-123-p4s1w12</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-mf920922-123-p4s1w15">
<a>
<lex.rf>a#a-mf920922-123-p4s1w15</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s1w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jméno</t_lemma>
<functor>MANN</functor>
<quot>
<LM>
<type>title</type>
<set_id>mf920922-123-p4s1w12</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-mf920922-123-p4s1w16">
<a>
<lex.rf>a#a-mf920922-123-p4s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dítě</t_lemma>
<functor>APP</functor>
<quot>
<LM>
<type>title</type>
<set_id>mf920922-123-p4s1w12</set_id>
</LM>
</quot>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p4s1w23">
<a>
<lex.rf>a#a-mf920922-123-p4s1w23</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s1w20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zajistit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41pvyA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p4s1w19">
<a>
<lex.rf>a#a-mf920922-123-p4s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_gram.rf>
<LM>t-mf920922-123-p4s1w12</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf920922-123-p4s1w22">
<a>
<lex.rf>a#a-mf920922-123-p4s1w22</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s1w21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>listopad</t_lemma>
<functor>TWHEN</functor>
<subfunctor>begin</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p4s1w19</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
<LM id="t-mf920922-123-p4s1w25">
<a>
<lex.rf>a#a-mf920922-123-p4s1w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dítě</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p4s1w16</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
<children>
<LM id="t-mf920922-123-p4s1w24">
<a>
<lex.rf>a#a-mf920922-123-p4s1w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sarajevský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s1w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p4s1w27">
<a>
<lex.rf>a#a-mf920922-123-p4s1w27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>návrat</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-mf920922-123-p4s1w29">
<a>
<lex.rf>a#a-mf920922-123-p4s1w29</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s1w28</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>škola</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-mf920922-123-p4s1w26">
<a>
<lex.rf>a#a-mf920922-123-p4s1w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poklidný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p4s2">
<atree.rf>a#a-mf920922-123-p4s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf920922-123-l22A">
<basic-form>James Grant</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf920922-123-p4s2w10</LM>
<LM>t-mf920922-123-p4s2w11</LM>
</tnode.rfs>
</LM>
<LM id="s-mf920922-123-l29A">
<type>institution</type>
<tnode.rfs>
<LM>t-mf920922-123-p4s2w6</LM>
<LM>t-mf920922-123-p4s2w7</LM>
<LM>t-mf920922-123-p4s2w8</LM>
<LM>t-mf920922-123-p4s2w9</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf920922-123-p4s2w1">
<a>
<lex.rf>a#a-mf920922-123-p4s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oznámit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41fgeB</val_frame.rf>
<children>
<LM id="t-mf920922-123-p4s2w2">
<a>
<lex.rf>a#a-mf920922-123-p4s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>EFF</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>adj.pron.def.demon</sempos>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p4s1w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p4s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf920922-123-p4s2w4">
<a>
<lex.rf>a#a-mf920922-123-p4s2w4</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ženeva</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p3s3w25</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p4s2w11">
<a>
<lex.rf>a#a-mf920922-123-p4s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Grant</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf920922-123-p4s2w10">
<a>
<lex.rf>a#a-mf920922-123-p4s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>James</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf920922-123-p4s2w5">
<a>
<lex.rf>a#a-mf920922-123-p4s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf920922-123-p4s2w7">
<a>
<lex.rf>a#a-mf920922-123-p4s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fond</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf920922-123-p4s2w8">
<a>
<lex.rf>a#a-mf920922-123-p4s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>OSN</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf920922-123-p4s2w9">
<a>
<lex.rf>a#a-mf920922-123-p4s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>UNICEF</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p4s2w6">
<a>
<lex.rf>a#a-mf920922-123-p4s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Dětský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p4s3">
<atree.rf>a#a-mf920922-123-p4s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf920922-123-p4s3w1">
<a>
<lex.rf>a#a-mf920922-123-p4s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uvést</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41ndjA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p4s3a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p4s2w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p4s3w11">
<a>
<lex.rf>a#a-mf920922-123-p4s3w11</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>8</deepord>
<children>
<LM id="t-mf920922-123-p4s3w5">
<a>
<lex.rf>a#a-mf920922-123-p4s3w5</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s3w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bosna</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf920922-123-p4s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf920922-123-p4s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf920922-123-p4s3w7">
<a>
<lex.rf>a#a-mf920922-123-p4s3w7</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s3w6</LM>
<LM>a#a-mf920922-123-p4s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zabít</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41ppaA</val_frame.rf>
<children>
<LM id="t-mf920922-123-p4s3w10">
<a>
<lex.rf>a#a-mf920922-123-p4s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dítě</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf920922-123-p4s3w9">
<a>
<lex.rf>a#a-mf920922-123-p4s3w9</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s3w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf920922-123-p4s3w16">
<a>
<lex.rf>a#a-mf920922-123-p4s3w16</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s3w15</LM>
<LM>a#a-mf920922-123-p4s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zranit</t_lemma>
<functor>EFF</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<discourse>
<LM>
<target_node.rf>t-mf920922-123-p4s3w7</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-mf920922-123-p4s3w11</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41rwgB</val_frame.rf>
<children>
<LM id="t-mf920922-123-p4s3w14">
<a>
<lex.rf>a#a-mf920922-123-p4s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>pl</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<bridging>
<LM>
<target_node.rf>t-mf920922-123-p4s3w10</target_node.rf>
<type>ANAF</type>
</LM>
</bridging>
<children>
<LM id="t-mf920922-123-p4s3w13">
<a>
<lex.rf>a#a-mf920922-123-p4s3w13</lex.rf>
<aux.rf>
<LM>a#a-mf920922-123-p4s3w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>30000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
