<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf930709_042.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-mf930709-042-p1s1">
<atree.rf>a#a-mf930709-042-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-042-l17B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-042-p1s1w1</LM>
<LM>t-mf930709-042-p1s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-042-p1s1w3">
<a>
<lex.rf>a#a-mf930709-042-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trvat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41mdbA</val_frame.rf>
<children>
<LM id="t-mf930709-042-p1s1w1">
<a>
<lex.rf>a#a-mf930709-042-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>likérka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-042-p1s1w2">
<a>
<lex.rf>a#a-mf930709-042-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Božkov</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p1s1w5">
<a>
<lex.rf>a#a-mf930709-042-p1s1w5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p1s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>známka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-042-p1s1w6">
<a>
<lex.rf>a#a-mf930709-042-p1s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Stock</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s1A">
<atree.rf>a#a-mf930709-042-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-042-p2s1Aw1">
<a>
<lex.rf>a#a-mf930709-042-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Plzeň</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s1B">
<atree.rf>a#a-mf930709-042-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-042-l11B">
<basic-form>Josef Hlinovský</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s1Bw35</LM>
<LM>t-mf930709-042-p2s1Bw36</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-042-l12B">
<basic-form>valná hromada</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s1Bw25</LM>
<LM>t-mf930709-042-p2s1Bw26</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-042-l14B">
<type>number</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s1Bw3</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-042-l15B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s1Bw29</LM>
<LM>t-mf930709-042-p2s1Bw30</LM>
<LM>t-mf930709-042-p2s1Bw32</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-042-l18B">
<basic-form>alkoholický nápoj</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s1Bw7</LM>
<LM>t-mf930709-042-p2s1Bw8</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-042-l19B">
<basic-form>ochranná značka</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s1Bw18</LM>
<LM>t-mf930709-042-p2s1Bw19</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-042-l20B">
<basic-form>akciová společnost</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s1Bw27</LM>
<LM>t-mf930709-042-p2s1Bw28</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-042-p2s1Bw22">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyjádřit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41oczC</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s1Bw1">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obava</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41dmqB</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s1Ba0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_gram.rf>
<LM>t-mf930709-042-p2s1Bw36</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-042-p2s1Bw5">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s1Bw2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pokles</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw6">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výroba</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw9">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw9</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>7</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw8">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nápoj</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw7">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>alkoholický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s1Bw10">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw10</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>mimo_jiné</t_lemma>
<functor>CM</functor>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-042-p2s1Bw13">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fernet</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw12">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>známý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s1Bw3">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw3</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s1Bw4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>30_procentní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf930709-042-p2s1Bw17">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw17</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s1Bw15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ztráta</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw19">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>značka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-042-p1s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-042-p2s1Bw18">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ochranný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-mf930709-042-p2s1Bw20">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Stock</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s1Bw16">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>možný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s1Bw23">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
<LM id="t-mf930709-042-p2s1Bw26">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw26</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s1Bw24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hromada</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw25">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>valný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
<LM id="t-mf930709-042-p2s1Bw28">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>společnost</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-042-p1s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-042-p2s1Bw27">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akciový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
<LM id="t-mf930709-042-p2s1Bw29">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>likérka</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw30">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Plzeň</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw32">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw32</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Božkov</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s1Bw36">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw36</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hlinovský</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw35">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw35</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Josef</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>27</deepord>
</LM>
<LM id="t-mf930709-042-p2s1Bw34">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw34</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>29</deepord>
<children>
<LM id="t-mf930709-042-p2s1Bw33">
<a>
<lex.rf>a#a-mf930709-042-p2s1Bw33</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>fem</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>28</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-042-p2s1Bw28</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s2">
<atree.rf>a#a-mf930709-042-p2s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-042-p2s2w3">
<a>
<lex.rf>a#a-mf930709-042-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>záviset</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41qtaA</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s2w1">
<a>
<lex.rf>a#a-mf930709-042-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zachování</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-042-p2s1Bw17</target_node.rf>
<type>CONTRAST</type>
</LM>
</bridging>
<val_frame.rf>v#v41pujA</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s2w2">
<a>
<lex.rf>a#a-mf930709-042-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>známka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-042-p2s1Bw19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-042-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s2w5">
<a>
<lex.rf>a#a-mf930709-042-p2s2w5</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s2w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rozhodnutí</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41jqjB</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s2a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-042-p2s2w6">
<a>
<lex.rf>a#a-mf930709-042-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vláda</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s3">
<atree.rf>a#a-mf930709-042-p2s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-042-l13B">
<basic-form>valná hromada</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s3w5</LM>
<LM>t-mf930709-042-p2s3w6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-042-p2s3w8">
<a>
<lex.rf>a#a-mf930709-042-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s3w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyplatit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<val_frame.rf>v#v41oonA</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s3w1">
<a>
<lex.rf>a#a-mf930709-042-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dividenda</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-042-p2s3w4">
<a>
<lex.rf>a#a-mf930709-042-p2s3w4</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s3w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jednání</t_lemma>
<functor>CRIT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41bhqA</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s3w6">
<a>
<lex.rf>a#a-mf930709-042-p2s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hromada</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-042-p2s1Bw26</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-042-p2s3w5">
<a>
<lex.rf>a#a-mf930709-042-p2s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>valný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s3a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf930709-042-p2s3a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s3a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-042-p2s3w7">
<a>
<lex.rf>a#a-mf930709-042-p2s3w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>letos</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-042-p2s3a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s4">
<atree.rf>a#a-mf930709-042-p2s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-042-l16B">
<type>number</type>
<tnode.rfs>
<LM>t-mf930709-042-p2s4w5</LM>
<LM>t-mf930709-042-p2s4w6</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-042-p2s4w2">
<a>
<lex.rf>a#a-mf930709-042-p2s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stočit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41lkuB</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s4w1">
<a>
<lex.rf>a#a-mf930709-042-p2s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vloni</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-042-p2s4w3">
<a>
<lex.rf>a#a-mf930709-042-p2s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>likérka</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-042-p2s1Bw33</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-042-p2s4w9">
<a>
<lex.rf>a#a-mf930709-042-p2s4w9</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>APPS</functor>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-042-p2s4w6">
<a>
<lex.rf>a#a-mf930709-042-p2s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tisíc</t_lemma>
<functor>PAT</functor>
<proto_lemma>tisíc</proto_lemma>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>sg</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-042-p2s4w7">
<a>
<lex.rf>a#a-mf930709-042-p2s4w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hl</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-042-p2s4w8">
<a>
<lex.rf>a#a-mf930709-042-p2s4w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lihovina</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-042-p2s1Bw9</target_node.rf>
<type>GEN</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s4w5">
<a>
<lex.rf>a#a-mf930709-042-p2s4w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>124</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf930709-042-p2s4w4">
<a>
<lex.rf>a#a-mf930709-042-p2s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>téměř</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s4w10">
<a>
<lex.rf>a#a-mf930709-042-p2s4w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>sup</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-042-p2s4w13">
<a>
<lex.rf>a#a-mf930709-042-p2s4w13</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s4w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ČR</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-042-p2s2w6</target_node.rf>
<type>FUNCT_P</type>
</LM>
<LM>
<target_node.rf>t-mf930709-042-p2s1Aw1</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
<children>
<LM id="t-mf930709-042-p2s4w12">
<a>
<lex.rf>a#a-mf930709-042-p2s4w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s5">
<atree.rf>a#a-mf930709-042-p2s5</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-042-p2s5w5">
<a>
<lex.rf>a#a-mf930709-042-p2s5w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-mf930709-042-p2s5w3">
<a>
<lex.rf>a#a-mf930709-042-p2s5w3</lex.rf>
<aux.rf>
<LM>a#a-mf930709-042-p2s5w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>CPR</functor>
<subfunctor>wrt</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-042-p2s5w2">
<a>
<lex.rf>a#a-mf930709-042-p2s5w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předchozí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-042-p2s5w4">
<a>
<lex.rf>a#a-mf930709-042-p2s5w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ten</t_lemma>
<functor>ACT</functor>
<proto_lemma>ten</proto_lemma>
<gram>
<sempos>n.pron.def.demon</sempos>
<gender>neut</gender>
<number>sg</number>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-042-p2s4w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-042-p2s5w9">
<a>
<lex.rf>a#a-mf930709-042-p2s5w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nárůst</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-042-p2s5w8">
<a>
<lex.rf>a#a-mf930709-042-p2s5w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dvojnásobný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf930709-042-p2s5w6">
<a>
<lex.rf>a#a-mf930709-042-p2s5w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>EXT</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-mf930709-042-p2s5w7">
<a>
<lex.rf>a#a-mf930709-042-p2s5w7</lex.rf>
</a>
<nodetype>dphr</nodetype>
<t_lemma>než</t_lemma>
<functor>DPHR</functor>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
