<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94207_57.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>sport</genre>
</meta>
<trees>
<LM id="t-ln94207-57-p1s1">
<atree.rf>a#a-ln94207-57-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94207-57-p1s1w3">
<a>
<lex.rf>a#a-ln94207-57-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Serginho</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln94207-57-p1s1w2">
<a>
<lex.rf>a#a-ln94207-57-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trenér</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94207-57-p1s1w1">
<a>
<lex.rf>a#a-ln94207-57-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potrestaný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p2s1A">
<atree.rf>a#a-ln94207-57-p2s1A</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94207-57-l11A">
<basic-form>Rio de Janeiro</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-ln94207-57-p2s1Aw1</LM>
<LM>t-ln94207-57-p2s1Aw2</LM>
<LM>t-ln94207-57-p2s1Aw3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94207-57-p2s1Aa0">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94207-57-p2s1Aw1">
<a>
<lex.rf>a#a-ln94207-57-p2s1Aw1</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Rio</t_lemma>
<functor>FPHR</functor>
<deepord>1</deepord>
</LM>
<LM id="t-ln94207-57-p2s1Aw2">
<a>
<lex.rf>a#a-ln94207-57-p2s1Aw2</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>de</t_lemma>
<functor>FPHR</functor>
<deepord>2</deepord>
</LM>
<LM id="t-ln94207-57-p2s1Aw3">
<a>
<lex.rf>a#a-ln94207-57-p2s1Aw3</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Janeiro</t_lemma>
<functor>FPHR</functor>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p2s1B">
<atree.rf>a#a-ln94207-57-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94207-57-l10A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94207-57-p2s1Bw5</LM>
<LM>t-ln94207-57-p2s1Bw6</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94207-57-l18A">
<basic-form>na lavičce</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94207-57-p2s1Bw10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94207-57-p2s1Ba1">
<a>
<aux.rf>
<LM>a#a-ln94207-57-p2s1Bw8</LM>
</aux.rf>
</a>
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94207-57-p2s1Bw7">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Serginho</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p1s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94207-57-p2s1Bw1">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trenér</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94207-57-p2s1Bw4">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>celek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94207-57-p2s1Bw5">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>FC</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94207-57-p2s1Bw6">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Santos</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p2s1Bw3">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fotbalový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94207-57-p2s1Bw2">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>brazilský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94207-57-p2s1Aa0</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p2s1Ba0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94207-57-p2s1Bw10">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw10</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p2s1Bw9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lavička</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94207-57-p2s1Bw12">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tým</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s1Bw4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94207-57-p2s1Bw11">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_gram.rf>
<LM>t-ln94207-57-p2s1Bw7</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p2s1Bw14">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>den</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94207-57-p2s1Bw13">
<a>
<lex.rf>a#a-ln94207-57-p2s1Bw13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>180</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p2s2">
<atree.rf>a#a-ln94207-57-p2s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94207-57-l15A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94207-57-p2s2w11</LM>
<LM>t-ln94207-57-p2s2w12</LM>
<LM>t-ln94207-57-p2s2w13</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94207-57-p2s2w2">
<a>
<lex.rf>a#a-ln94207-57-p2s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PRED</functor>
<proto_lemma>být</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94207-57-p2s2w1">
<a>
<lex.rf>a#a-ln94207-57-p2s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>důvod</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<secondary_NP_type>reason</secondary_NP_type>
</LM>
<LM id="t-ln94207-57-p2s2w4">
<a>
<lex.rf>a#a-ln94207-57-p2s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>napadení</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41cwgA</val_frame.rf>
<children>
<LM id="t-ln94207-57-p2s2w3">
<a>
<lex.rf>a#a-ln94207-57-p2s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s1Bw11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94207-57-p2s2w5">
<a>
<lex.rf>a#a-ln94207-57-p2s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94207-57-p2s2w7">
<a>
<lex.rf>a#a-ln94207-57-p2s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tým</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94207-57-p2s2w6">
<a>
<lex.rf>a#a-ln94207-57-p2s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soupeř</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p2s2w9">
<a>
<lex.rf>a#a-ln94207-57-p2s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p2s2w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přestávka</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94207-57-p2s2w10">
<a>
<lex.rf>a#a-ln94207-57-p2s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zápas</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94207-57-p2s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_gram.rf>
<LM>t-ln94207-57-p2s2w12</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94207-57-p2s2w12">
<a>
<lex.rf>a#a-ln94207-57-p2s2w12</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Dash</t_lemma>
<functor>CONTRA</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln94207-57-p2s2w11">
<a>
<lex.rf>a#a-ln94207-57-p2s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Santos</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s1Bw12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94207-57-p2s2w13">
<a>
<lex.rf>a#a-ln94207-57-p2s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Guarani</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s2w7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p2s2w16">
<a>
<lex.rf>a#a-ln94207-57-p2s2w16</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Colon</t_lemma>
<functor>OPER</functor>
<is_parenthesis>1</is_parenthesis>
<deepord>15</deepord>
<children>
<LM id="t-ln94207-57-p2s2w15">
<a>
<lex.rf>a#a-ln94207-57-p2s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>0</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln94207-57-p2s2w17">
<a>
<lex.rf>a#a-ln94207-57-p2s2w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>4</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s1">
<atree.rf>a#a-ln94207-57-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94207-57-l7A">
<type>person</type>
<tnode.rfs>
<LM>t-ln94207-57-p3s1w13</LM>
<LM>t-ln94207-57-p3s1w14</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94207-57-l16A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94207-57-p3s1w9</LM>
<LM>t-ln94207-57-p3s1w10</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94207-57-p3s1w17">
<a>
<lex.rf>a#a-ln94207-57-p3s1w17</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln94207-57-p3s1w1">
<a>
<lex.rf>a#a-ln94207-57-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Serginho</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s2w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94207-57-p3s1w4">
<a>
<lex.rf>a#a-ln94207-57-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>startovat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41lijC</val_frame.rf>
<children>
<LM id="t-ln94207-57-p3s1w3">
<a>
<lex.rf>a#a-ln94207-57-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
<coref_gram.rf>
<LM>t-ln94207-57-p3s1w1</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94207-57-p3s1w6">
<a>
<lex.rf>a#a-ln94207-57-p3s1w6</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s1w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dres</t_lemma>
<functor>MANN</functor>
<is_state>1</is_state>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94207-57-p3s1w7">
<a>
<lex.rf>a#a-ln94207-57-p3s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Brazílie</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94207-57-p2s1Bw2</target_node.rf>
<type>REST</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s1w9">
<a>
<lex.rf>a#a-ln94207-57-p3s1w9</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s1w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>MS</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94207-57-p3s1w10">
<a>
<lex.rf>a#a-ln94207-57-p3s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1982</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s1w12">
<a>
<lex.rf>a#a-ln94207-57-p3s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kopnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41bslA</val_frame.rf>
<children>
<LM id="t-ln94207-57-p3s1w14">
<a>
<lex.rf>a#a-ln94207-57-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Giardini</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s2w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94207-57-p3s1w13">
<a>
<lex.rf>a#a-ln94207-57-p3s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>José</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s1w16">
<a>
<lex.rf>a#a-ln94207-57-p3s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s1w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tříslo</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94207-57-p3s1w14</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s1w20">
<a>
<lex.rf>a#a-ln94207-57-p3s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>odůvodnit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<secondary_NP_type>reason</secondary_NP_type>
<discourse>
<LM>
<target_node.rf>t-ln94207-57-p3s1w12</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94207-57-p3s1w17</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41emcA</val_frame.rf>
<children>
<LM id="t-ln94207-57-p3s1w19">
<a>
<lex.rf>a#a-ln94207-57-p3s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>chování</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s2w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41bbpA</val_frame.rf>
<children>
<LM id="t-ln94207-57-p3s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>MANN</functor>
<tfa>t</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln94207-57-p3s1w18">
<a>
<lex.rf>a#a-ln94207-57-p3s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
<coref_gram.rf>
<LM>t-ln94207-57-p3s1w1</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s1w22">
<a>
<lex.rf>a#a-ln94207-57-p3s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poznámka</t_lemma>
<functor>MEANS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln94207-57-p3s1w24">
<a>
<lex.rf>a#a-ln94207-57-p3s1w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Guarani</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s2w13</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94207-57-p3s1w23">
<a>
<lex.rf>a#a-ln94207-57-p3s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ředitel</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p3s1w14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s1w21">
<a>
<lex.rf>a#a-ln94207-57-p3s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rasistický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s2">
<atree.rf>a#a-ln94207-57-p3s2</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94207-57-p3s2w4">
<a>
<lex.rf>a#a-ln94207-57-p3s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41chlAE</val_frame.rf>
<children>
<LM id="t-ln94207-57-p3s2w5">
<a>
<lex.rf>a#a-ln94207-57-p3s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Serginho</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p3s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94207-57-p3s2w6">
<a>
<lex.rf>a#a-ln94207-57-p3s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potíž</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41gqpA</val_frame.rf>
<children>
<LM id="t-ln94207-57-p3s2w3">
<a>
<lex.rf>a#a-ln94207-57-p3s2w3</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přestupek</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94207-57-p3s1w19</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln94207-57-p3s2w2">
<a>
<lex.rf>a#a-ln94207-57-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kázeňský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-ln94207-57-p3s2w5</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s2w7">
<a>
<lex.rf>a#a-ln94207-57-p3s2w7</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>už</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94207-57-p3s2w9">
<a>
<lex.rf>a#a-ln94207-57-p3s2w9</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s2w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hráč</t_lemma>
<functor>COMPL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<compl.rf>
<LM>t-ln94207-57-p3s2w5</LM>
</compl.rf>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s3">
<atree.rf>a#a-ln94207-57-p3s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94207-57-l17A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94207-57-p3s3w13</LM>
<LM>t-ln94207-57-p3s3w14</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94207-57-l19A">
<basic-form>trest stihnout</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94207-57-p3s3w19</LM>
<LM>t-ln94207-57-p3s3w20</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94207-57-p3s3w15">
<a>
<lex.rf>a#a-ln94207-57-p3s3w15</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Comma</t_lemma>
<functor>CONJ</functor>
<deepord>14</deepord>
<children>
<LM id="t-ln94207-57-p3s3w6">
<a>
<lex.rf>a#a-ln94207-57-p3s3w6</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s3w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>počínat_si</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41fpuA</val_frame.rf>
<children>
<LM id="t-ln94207-57-p3s3w2">
<a>
<lex.rf>a#a-ln94207-57-p3s3w2</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s3w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94207-57-p3s3w3">
<a>
<lex.rf>a#a-ln94207-57-p3s3w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1990</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s3a0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p3s2a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94207-57-p3s3w5">
<a>
<lex.rf>a#a-ln94207-57-p3s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>aktivně</t_lemma>
<functor>MANN</functor>
<proto_lemma>aktivní</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94207-57-p3s3w8">
<a>
<lex.rf>a#a-ln94207-57-p3s3w8</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s3w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bitka</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94207-57-p3s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Rcp</t_lemma>
<functor>ADDR</functor>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_gram.rf>
<LM>t-ln94207-57-p3s3w12</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94207-57-p3s3w12">
<a>
<lex.rf>a#a-ln94207-57-p3s3w12</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>10</deepord>
<children>
<LM id="t-ln94207-57-p3s3w10">
<a>
<lex.rf>a#a-ln94207-57-p3s3w10</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s3w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fotbalista</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94207-57-p3s3w11">
<a>
<lex.rf>a#a-ln94207-57-p3s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Santos</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p2s2w11</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s3a2">
<a>
<lex.rf>a#a-ln94207-57-p3s3w10</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s3w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>fotbalista</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94207-57-p3s3w14">
<a>
<lex.rf>a#a-ln94207-57-p3s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Paulo</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94207-57-p3s3w13">
<a>
<lex.rf>a#a-ln94207-57-p3s3w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sao</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94207-57-p3s3w19">
<a>
<lex.rf>a#a-ln94207-57-p3s3w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stihnout</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<val_frame.rf>v#v41ljyA</val_frame.rf>
<children>
<LM id="t-ln94207-57-p3s3w18">
<a>
<lex.rf>a#a-ln94207-57-p3s3w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>15</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94207-57-p3s3a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94207-57-p3s3w20">
<a>
<lex.rf>a#a-ln94207-57-p3s3w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trest</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-ln94207-57-p3s3w17">
<a>
<lex.rf>a#a-ln94207-57-p3s3w17</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s3w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>což</t_lemma>
<functor>CAUS</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_gram.rf>
<LM>t-ln94207-57-p3s3w6</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94207-57-p3s3w23">
<a>
<lex.rf>a#a-ln94207-57-p3s3w23</lex.rf>
<aux.rf>
<LM>a#a-ln94207-57-p3s3w21</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>den</t_lemma>
<functor>THL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln94207-57-p3s3w22">
<a>
<lex.rf>a#a-ln94207-57-p3s3w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>150</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
