<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94206_93.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>collection</genre>
</meta>
<trees>
<LM id="t-ln94206-93-p1s1">
<atree.rf>a#a-ln94206-93-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94206-93-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<tfa>t</tfa>
<deepord>2</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln94206-93-p1s1w1">
<a>
<lex.rf>a#a-ln94206-93-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>co</t_lemma>
<functor>ACT</functor>
<proto_lemma>co</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>neut</gender>
<number>sg</number>
<indeftype>inter</indeftype>
<person>3</person>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94206-93-p1s1w3">
<a>
<lex.rf>a#a-ln94206-93-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kdy</t_lemma>
<functor>TWHEN</functor>
<proto_lemma>kdy</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.indef</sempos>
<indeftype>inter</indeftype>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94206-93-p1s1w5">
<a>
<lex.rf>a#a-ln94206-93-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kde</t_lemma>
<functor>LOC</functor>
<proto_lemma>kde</proto_lemma>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.pron.indef</sempos>
<indeftype>inter</indeftype>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p2s1">
<atree.rf>a#a-ln94206-93-p2s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94206-93-l2A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94206-93-p2s1w1</LM>
<LM>t-ln94206-93-p2s1w2</LM>
<LM>t-ln94206-93-p2s1w3</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l3A">
<type>time</type>
<tnode.rfs>
<LM>t-ln94206-93-p2s1w7</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l4A">
<basic-form>Míčovna Pražského hradu</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-ln94206-93-p2s1w9</LM>
<LM>t-ln94206-93-p2s1w10</LM>
<LM>t-ln94206-93-p2s1w11</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l5A">
<basic-form>festival Pocta katedrále</basic-form>
<type>object</type>
<tnode.rfs>
<LM>t-ln94206-93-p2s1w14</LM>
<LM>t-ln94206-93-p2s1w15</LM>
<LM>t-ln94206-93-p2s1w16</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94206-93-p2s1w4">
<a>
<lex.rf>a#a-ln94206-93-p2s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vystoupit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41oymD</val_frame.rf>
<children>
<LM id="t-ln94206-93-p2s1w3">
<a>
<lex.rf>a#a-ln94206-93-p2s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>orchestr</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94206-93-p2s1w2">
<a>
<lex.rf>a#a-ln94206-93-p2s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>komorní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94206-93-p2s1w1">
<a>
<lex.rf>a#a-ln94206-93-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Talich</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p2s1w5">
<a>
<lex.rf>a#a-ln94206-93-p2s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dnes</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94206-93-p2s1w7">
<a>
<lex.rf>a#a-ln94206-93-p2s1w7</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p2s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>19.30</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94206-93-p2s1w9">
<a>
<lex.rf>a#a-ln94206-93-p2s1w9</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p2s1w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Míčovna</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94206-93-p2s1w11">
<a>
<lex.rf>a#a-ln94206-93-p2s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hrad</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94206-93-p2s1w10">
<a>
<lex.rf>a#a-ln94206-93-p2s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pražský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p2s1w14">
<a>
<lex.rf>a#a-ln94206-93-p2s1w14</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p2s1w13</LM>
<LM>a#a-ln94206-93-p2s1w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>festival</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94206-93-p2s1w15">
<a>
<lex.rf>a#a-ln94206-93-p2s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pocta</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<children>
<LM id="t-ln94206-93-p2s1w16">
<a>
<lex.rf>a#a-ln94206-93-p2s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>katedrála</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94206-93-p2s1w11</target_node.rf>
<type>SET_SUB</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1">
<atree.rf>a#a-ln94206-93-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94206-93-l1A">
<basic-form>dnešní den</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w26</LM>
<LM>t-ln94206-93-p3s1w27</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l6A">
<type>person</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w1</LM>
<LM>t-ln94206-93-p3s1w2</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l7A">
<type>person</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w4</LM>
<LM>t-ln94206-93-p3s1w5</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l8A">
<type>person</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w7</LM>
<LM>t-ln94206-93-p3s1w8</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l9A">
<type>person</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w10</LM>
<LM>t-ln94206-93-p3s1w11</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l12A">
<type>object</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w20</LM>
<LM>t-ln94206-93-p3s1w21</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l13A">
<basic-form>Pražský dům fotografie</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w30</LM>
<LM>t-ln94206-93-p3s1w31</LM>
<LM>t-ln94206-93-p3s1w32</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l14A">
<type>location</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w34</LM>
<LM>t-ln94206-93-p3s1w35</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l15A">
<type>time</type>
<tnode.rfs>
<LM>t-ln94206-93-p3s1w40</LM>
<LM>t-ln94206-93-p3s1w42</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94206-93-p3s1w15">
<a>
<lex.rf>a#a-ln94206-93-p3s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>představit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41hyfB</val_frame.rf>
<children>
<LM id="t-ln94206-93-p3s1w12">
<a>
<lex.rf>a#a-ln94206-93-p3s1w12</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>7</deepord>
<children>
<LM id="t-ln94206-93-p3s1w2">
<a>
<lex.rf>a#a-ln94206-93-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Moucha</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94206-93-p3s1w1">
<a>
<lex.rf>a#a-ln94206-93-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Josef</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1w5">
<a>
<lex.rf>a#a-ln94206-93-p3s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pinkava</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94206-93-p3s1w4">
<a>
<lex.rf>a#a-ln94206-93-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ivan</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1w8">
<a>
<lex.rf>a#a-ln94206-93-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Stano</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94206-93-p3s1w7">
<a>
<lex.rf>a#a-ln94206-93-p3s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tono</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1w11">
<a>
<lex.rf>a#a-ln94206-93-p3s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Stratil</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94206-93-p3s1w10">
<a>
<lex.rf>a#a-ln94206-93-p3s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Václav</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1w13">
<a>
<lex.rf>a#a-ln94206-93-p3s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>další</t_lemma>
<functor>ACT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1w14">
<a>
<lex.rf>a#a-ln94206-93-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_gram.rf>
<LM>t-ln94206-93-p3s1w12</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94206-93-p3s1w17">
<a>
<lex.rf>a#a-ln94206-93-p3s1w17</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p3s1w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výstava</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94206-93-p3s1w21">
<a>
<lex.rf>a#a-ln94206-93-p3s1w21</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p3s1w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>světlo</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln94206-93-p3s1w20">
<a>
<lex.rf>a#a-ln94206-93-p3s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ostrý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1w18">
<a>
<lex.rf>a#a-ln94206-93-p3s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fotografie</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln94206-93-p3s1w37">
<a>
<lex.rf>a#a-ln94206-93-p3s1w37</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>27</deepord>
<children>
<LM id="t-ln94206-93-p3s1w28">
<a>
<lex.rf>a#a-ln94206-93-p3s1w28</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p3s1w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>otevřít</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>res1</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<val_frame.rf>v#v41fdfA</val_frame.rf>
<children>
<LM id="t-ln94206-93-p3s1w23">
<a>
<lex.rf>a#a-ln94206-93-p3s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_gram.rf>
<LM>t-ln94206-93-p3s1w17</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94206-93-p3s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>18</deepord>
</LM>
<LM id="t-ln94206-93-p3s1w27">
<a>
<lex.rf>a#a-ln94206-93-p3s1w27</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p3s1w25</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>den</t_lemma>
<functor>TSIN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94206-93-p2s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94206-93-p3s1w26">
<a>
<lex.rf>a#a-ln94206-93-p3s1w26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dnešní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1w31">
<a>
<lex.rf>a#a-ln94206-93-p3s1w31</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p3s1w29</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dům</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<children>
<LM id="t-ln94206-93-p3s1w32">
<a>
<lex.rf>a#a-ln94206-93-p3s1w32</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fotografie</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
</LM>
<LM id="t-ln94206-93-p3s1w30">
<a>
<lex.rf>a#a-ln94206-93-p3s1w30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pražský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94206-93-p2s1w10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94206-93-p3s1w35">
<a>
<lex.rf>a#a-ln94206-93-p3s1w35</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p3s1w33</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ulice</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94206-93-p3s1w30</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
<children>
<LM id="t-ln94206-93-p3s1w34">
<a>
<lex.rf>a#a-ln94206-93-p3s1w34</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hus</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p3s1w38">
<a>
<lex.rf>a#a-ln94206-93-p3s1w38</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potrvat</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>29</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94206-93-p3s1w28</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94206-93-p3s1w37</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41grlA</val_frame.rf>
<children>
<LM id="t-ln94206-93-p3s1a1">
<a>
<lex.rf>a#a-ln94206-93-p3s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>28</deepord>
<coref_gram.rf>
<LM>t-ln94206-93-p3s1w17</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94206-93-p3s1w42">
<a>
<lex.rf>a#a-ln94206-93-p3s1w42</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p3s1w39</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>září</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>30</deepord>
<children>
<LM id="t-ln94206-93-p3s1w40">
<a>
<lex.rf>a#a-ln94206-93-p3s1w40</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>27</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>31</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p4s1">
<atree.rf>a#a-ln94206-93-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94206-93-l16A">
<type>person</type>
<tnode.rfs>
<LM>t-ln94206-93-p4s1w6</LM>
<LM>t-ln94206-93-p4s1w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94206-93-p4s1w11">
<a>
<lex.rf>a#a-ln94206-93-p4s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p4s1w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vystavit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>res1</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41oxwD</val_frame.rf>
<children>
<LM id="t-ln94206-93-p4s1w4">
<a>
<lex.rf>a#a-ln94206-93-p4s1w4</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>3</deepord>
<children>
<LM id="t-ln94206-93-p4s1w1">
<a>
<lex.rf>a#a-ln94206-93-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obraz</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94206-93-p4s1w3">
<a>
<lex.rf>a#a-ln94206-93-p4s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kresba</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94206-93-p4s1w5">
<a>
<lex.rf>a#a-ln94206-93-p4s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>grafik</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94206-93-p4s1w7">
<a>
<lex.rf>a#a-ln94206-93-p4s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Komárek</t_lemma>
<functor>AUTH</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94206-93-p4s1w6">
<a>
<lex.rf>a#a-ln94206-93-p4s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Vladimír</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p4s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94206-93-p4s1w10">
<a>
<lex.rf>a#a-ln94206-93-p4s1w10</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p4s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dnešek</t_lemma>
<functor>TSIN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94206-93-p3s1w27</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94206-93-p4s1w14">
<a>
<lex.rf>a#a-ln94206-93-p4s1w14</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p4s1w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>centrum</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94206-93-p4s1w15">
<a>
<lex.rf>a#a-ln94206-93-p4s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Chagall</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94206-93-p4s1w13">
<a>
<lex.rf>a#a-ln94206-93-p4s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výtvarný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-ln94206-93-p4s1w17">
<a>
<lex.rf>a#a-ln94206-93-p4s1w17</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p4s1w16</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Ostrava</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p5s1">
<atree.rf>a#a-ln94206-93-p5s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94206-93-l18A">
<basic-form>Valdštejnská zahrada '94</basic-form>
<type>object</type>
<tnode.rfs>
<LM>t-ln94206-93-p5s1w6</LM>
<LM>t-ln94206-93-p5s1w7</LM>
<LM>t-ln94206-93-p5s1w9</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l19A">
<type>location</type>
<tnode.rfs>
<LM>t-ln94206-93-p5s1w15</LM>
<LM>t-ln94206-93-p5s1w16</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94206-93-l20A">
<type>time</type>
<tnode.rfs>
<LM>t-ln94206-93-p5s1w25</LM>
<LM>t-ln94206-93-p5s1w27</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94206-93-p5s1w22">
<a>
<lex.rf>a#a-ln94206-93-p5s1w22</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>17</deepord>
<children>
<LM id="t-ln94206-93-p5s1w1">
<a>
<lex.rf>a#a-ln94206-93-p5s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výstava</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94206-93-p5s1w5">
<a>
<lex.rf>a#a-ln94206-93-p5s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>umělec</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94206-93-p5s1w3">
<a>
<lex.rf>a#a-ln94206-93-p5s1w3</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Dash</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-ln94206-93-p5s1w2">
<a>
<lex.rf>a#a-ln94206-93-p5s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94206-93-p4s1w17</target_node.rf>
<type>PART_WHOLE</type>
</LM>
<LM>
<target_node.rf>t-ln94206-93-p3s1w30</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94206-93-p5s1w4">
<a>
<lex.rf>a#a-ln94206-93-p5s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>slovenský</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p5s1w7">
<a>
<lex.rf>a#a-ln94206-93-p5s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zahrada</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94206-93-p5s1w6">
<a>
<lex.rf>a#a-ln94206-93-p5s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>valdštejnský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94206-93-p5s1w9">
<a>
<lex.rf>a#a-ln94206-93-p5s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>94</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln94206-93-p5s1w11">
<a>
<lex.rf>a#a-ln94206-93-p5s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vstup</t_lemma>
<functor>PAR</functor>
<sentmod>enunc</sentmod>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94206-93-p5s1w13">
<a>
<lex.rf>a#a-ln94206-93-p5s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vchod</t_lemma>
<functor>DIR2</functor>
<subfunctor>basic</subfunctor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94206-93-p5s1w12">
<a>
<lex.rf>a#a-ln94206-93-p5s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hlavní</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94206-93-p5s1w16">
<a>
<lex.rf>a#a-ln94206-93-p5s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p5s1w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ulice</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94206-93-p3s1w30</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
<children>
<LM id="t-ln94206-93-p5s1w15">
<a>
<lex.rf>a#a-ln94206-93-p5s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>letenský</t_lemma>
<functor>RSTR</functor>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p5s1w18">
<a>
<lex.rf>a#a-ln94206-93-p5s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>začínat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41pqyD</val_frame.rf>
<children>
<LM id="t-ln94206-93-p5s1w19">
<a>
<lex.rf>a#a-ln94206-93-p5s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dnes</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-ln94206-93-p5s1w21">
<a>
<lex.rf>a#a-ln94206-93-p5s1w21</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p5s1w20</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Praga</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94206-93-p3s1w30</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94206-93-p5s1w23">
<a>
<lex.rf>a#a-ln94206-93-p5s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>potrvat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<discourse>
<LM>
<target_node.rf>t-ln94206-93-p5s1w18</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>conj</discourse_type>
<sense_PDTB3>Expansion.Conjunction</sense_PDTB3>
<src>pdit10</src>
<t-connectors.rf>
<LM>t-ln94206-93-p5s1w22</LM>
</t-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41grlA</val_frame.rf>
<children>
<LM id="t-ln94206-93-p5s1w27">
<a>
<lex.rf>a#a-ln94206-93-p5s1w27</lex.rf>
<aux.rf>
<LM>a#a-ln94206-93-p5s1w24</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>září</t_lemma>
<functor>TTILL</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-ln94206-93-p5s1w25">
<a>
<lex.rf>a#a-ln94206-93-p5s1w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>30</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
