<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94211_63.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5d.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>news</genre>
</meta>
<trees>
<LM id="t-ln94211-63-p1s1">
<atree.rf>a#a-ln94211-63-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94211-63-p1s1w3">
<a>
<lex.rf>a#a-ln94211-63-p1s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obžalovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41duqA</val_frame.rf>
<children>
<LM id="t-ln94211-63-p1s1w2">
<a>
<lex.rf>a#a-ln94211-63-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>primář</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94211-63-p1s1w1">
<a>
<lex.rf>a#a-ln94211-63-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bývalý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94211-63-p1s1w5">
<a>
<lex.rf>a#a-ln94211-63-p1s1w5</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p1s1w4</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přerušování</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41ihtA</val_frame.rf>
<children>
<LM id="t-ln94211-63-p1s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-ln94211-63-p1s1w2</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94211-63-p1s1w6">
<a>
<lex.rf>a#a-ln94211-63-p1s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>těhotenství</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1A">
<atree.rf>a#a-ln94211-63-p2s1A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94211-63-p2s1Aw1">
<a>
<lex.rf>a#a-ln94211-63-p2s1Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Karviná</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1B">
<atree.rf>a#a-ln94211-63-p2s1B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94211-63-l2A">
<basic-form>Český Těšín</basic-form>
<type>location</type>
<tnode.rfs>
<LM>t-ln94211-63-p2s1Bw9</LM>
<LM>t-ln94211-63-p2s1Bw10</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94211-63-l22A">
<basic-form>MUDr. Petr Š.</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94211-63-p2s1Bw12</LM>
<LM>t-ln94211-63-p2s1Bw14</LM>
<LM>t-ln94211-63-p2s1Bw15</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94211-63-l23A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94211-63-p2s1Bw38</LM>
<LM>t-ln94211-63-p2s1Bw39</LM>
<LM>t-ln94211-63-p2s1Bw41</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94211-63-l28A">
<basic-form>trestný čin nedovoleného přerušení těhotenství</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94211-63-p2s1Bw18</LM>
<LM>t-ln94211-63-p2s1Bw19</LM>
<LM>t-ln94211-63-p2s1Bw20</LM>
<LM>t-ln94211-63-p2s1Bw21</LM>
<LM>t-ln94211-63-p2s1Bw22</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94211-63-l29A">
<basic-form>trestný čin ohrožení devizového hospodářství</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94211-63-p2s1Bw24</LM>
<LM>t-ln94211-63-p2s1Bw25</LM>
<LM>t-ln94211-63-p2s1Bw26</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94211-63-l30A">
<basic-form>neoprávněné užívání cizí věci</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94211-63-p2s1Bw28</LM>
<LM>t-ln94211-63-p2s1Bw29</LM>
<LM>t-ln94211-63-p2s1Bw30</LM>
<LM>t-ln94211-63-p2s1Bw31</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94211-63-l31A">
<basic-form>státní zastupitelství</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94211-63-p2s1Bw35</LM>
<LM>t-ln94211-63-p2s1Bw36</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94211-63-p2s1Bw32">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw32</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>29</deepord>
<val_frame.rf>v#v41fqjI</val_frame.rf>
<children>
<LM id="t-ln94211-63-p2s1Bw1">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obžaloba</t_lemma>
<functor>CPHR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41duoB</val_frame.rf>
<children>
<LM id="t-ln94211-63-p2s1Ba3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#QCor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_gram.rf>
<LM>t-ln94211-63-p2s1Bw36</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94211-63-p2s1Bw15">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw15</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p2s1Bw2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Š</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p1s1a1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94211-63-p2s1Bw14">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Petr</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94211-63-p2s1Bw12">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>MUDr</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94211-63-p2s1Bw4">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>primář</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94211-63-p2s1Bw6">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oddělení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<val_frame.rf>v#v41dxtB</val_frame.rf>
<children>
<LM id="t-ln94211-63-p2s1Bw5">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>gynekologický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln94211-63-p2s1Bw7">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94211-63-p2s1Bw10">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw10</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p2s1Bw8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Těšín</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94211-63-p2s1Bw9">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1Bw3">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bývalý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1Bw11">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>padesátiletý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1Bw19">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw19</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p2s1Bw17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>čin</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94211-63-p1s1w5</target_node.rf>
<type>SUB_SET</type>
</LM>
</bridging>
<children>
<LM id="t-ln94211-63-p2s1Bw18">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>trestný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln94211-63-p2s1Bw27">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw27</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>23</deepord>
<children>
<LM id="t-ln94211-63-p2s1Ba2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln94211-63-p2s1Bw21">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přerušení</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<val_frame.rf>v#v41ihqA</val_frame.rf>
<children>
<LM id="t-ln94211-63-p2s1Bw22">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>těhotenství</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p1s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94211-63-p2s1Bw20">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dovolený</t_lemma>
<functor>MANN</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1Bw24">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ohrožení</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<val_frame.rf>v#v41eqcA</val_frame.rf>
<children>
<LM id="t-ln94211-63-p2s1Bw26">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hospodářství</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<children>
<LM id="t-ln94211-63-p2s1Bw25">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>devizový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1Bw29">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>užívání</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_member>1</is_member>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<val_frame.rf>v#v41nfoA</val_frame.rf>
<children>
<LM id="t-ln94211-63-p2s1Bw31">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw31</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>věc</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>25</deepord>
<children>
<LM id="t-ln94211-63-p2s1Bw30">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw30</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>cizí</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>26</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1Bw28">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oprávněný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg1</negation>
</gram>
<tfa>f</tfa>
<deepord>27</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1Bw33">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw33</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>včera</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>t</tfa>
<deepord>28</deepord>
</LM>
<LM id="t-ln94211-63-p2s1Bw36">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw36</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zastupitelství</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>30</deepord>
<children>
<LM id="t-ln94211-63-p2s1Bw35">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw35</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>státní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>31</deepord>
</LM>
<LM id="t-ln94211-63-p2s1Bw34">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw34</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>karvinský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>32</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p2s1Aw1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p2s1Bw39">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw39</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p2s1Bw37</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soud</t_lemma>
<functor>LOC</functor>
<subfunctor>near</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>33</deepord>
<children>
<LM id="t-ln94211-63-p2s1Bw38">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw38</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>okresní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>34</deepord>
</LM>
<LM id="t-ln94211-63-p2s1Bw41">
<a>
<lex.rf>a#a-ln94211-63-p2s1Bw41</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p2s1Bw40</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Karviná</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>35</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p2s1Bw34</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s1">
<atree.rf>a#a-ln94211-63-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94211-63-l25A">
<basic-form>MUDr. Petr Š.</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94211-63-p3s1w5</LM>
<LM>t-ln94211-63-p3s1w7</LM>
<LM>t-ln94211-63-p3s1w8</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94211-63-p3s1w18">
<a>
<lex.rf>a#a-ln94211-63-p3s1w18</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p3s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přerušit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41ihsC</val_frame.rf>
<children>
<LM id="t-ln94211-63-p3s1w8">
<a>
<lex.rf>a#a-ln94211-63-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Š</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p2s1Bw15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94211-63-p3s1w2">
<a>
<lex.rf>a#a-ln94211-63-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>primář</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94211-63-p3s1w1">
<a>
<lex.rf>a#a-ln94211-63-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bývalý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94211-63-p3s1w4">
<a>
<lex.rf>a#a-ln94211-63-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>oddělení</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p2s1Bw6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41dxtB</val_frame.rf>
<children>
<LM id="t-ln94211-63-p3s1w3">
<a>
<lex.rf>a#a-ln94211-63-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>gynekologický</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s1w5">
<a>
<lex.rf>a#a-ln94211-63-p3s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>MUDr</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94211-63-p3s1w7">
<a>
<lex.rf>a#a-ln94211-63-p3s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Petr</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s1w12">
<a>
<lex.rf>a#a-ln94211-63-p3s1w12</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p3s1w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prosinec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94211-63-p3s1w14">
<a>
<lex.rf>a#a-ln94211-63-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94211-63-p3s1w13">
<a>
<lex.rf>a#a-ln94211-63-p3s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>loňský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s1w17">
<a>
<lex.rf>a#a-ln94211-63-p3s1w17</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p3s1w15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p2s1Bw7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94211-63-p3s1w16">
<a>
<lex.rf>a#a-ln94211-63-p3s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>českotěšínský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p2s1Bw10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s1w19">
<a>
<lex.rf>a#a-ln94211-63-p3s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>těhotenství</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p2s1Bw22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94211-63-p3s1w22">
<a>
<lex.rf>a#a-ln94211-63-p3s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žena</t_lemma>
<functor>BEN</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<children>
<LM id="t-ln94211-63-p3s1w21">
<a>
<lex.rf>a#a-ln94211-63-p3s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osm</t_lemma>
<functor>RSTR</functor>
<proto_lemma>osm</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-ln94211-63-p3s1w20">
<a>
<lex.rf>a#a-ln94211-63-p3s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>asi</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<gram>
<sempos>adv.denot.ngrad.nneg</sempos>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s1w24">
<a>
<lex.rf>a#a-ln94211-63-p3s1w24</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p3s1w23</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Polsko</t_lemma>
<functor>DIR1</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s2">
<atree.rf>a#a-ln94211-63-p3s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94211-63-l13A">
<type>location</type>
<tnode.rfs>
<LM>t-ln94211-63-p3s2w11</LM>
<LM>t-ln94211-63-p3s2w12</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94211-63-p3s2w1">
<a>
<lex.rf>a#a-ln94211-63-p3s2w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lze</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41ccxA</val_frame.rf>
<children>
<LM id="t-ln94211-63-p3s2w2">
<a>
<lex.rf>a#a-ln94211-63-p3s2w2</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>údajně</t_lemma>
<functor>ATT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94211-63-p3s2a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>BEN</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94211-63-p3s2a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94211-63-p3s2w3">
<a>
<lex.rf>a#a-ln94211-63-p3s2w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyloučit</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41oizC</val_frame.rf>
<children>
<LM id="t-ln94211-63-p3s2a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-ln94211-63-p3s2a1</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94211-63-p3s2w18">
<a>
<lex.rf>a#a-ln94211-63-p3s2w18</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p3s2w17</LM>
<LM>a#a-ln94211-63-p3s2w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>PAT</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
<deontmod>poss</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-ln94211-63-p3s2w7">
<a>
<lex.rf>a#a-ln94211-63-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žena</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s1w22</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94211-63-p3s2w6">
<a>
<lex.rf>a#a-ln94211-63-p3s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>polský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s1w24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94211-63-p3s2w13">
<a>
<lex.rf>a#a-ln94211-63-p3s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přijet</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41isaB</val_frame.rf>
<children>
<LM id="t-ln94211-63-p3s2w9">
<a>
<lex.rf>a#a-ln94211-63-p3s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_gram.rf>
<LM>t-ln94211-63-p3s2w7</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94211-63-p3s2w12">
<a>
<lex.rf>a#a-ln94211-63-p3s2w12</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p3s2w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Těšín</t_lemma>
<functor>DIR3</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s1w16</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94211-63-p3s2w11">
<a>
<lex.rf>a#a-ln94211-63-p3s2w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>český</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s2w15">
<a>
<lex.rf>a#a-ln94211-63-p3s2w15</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p3s2w14</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>interrupce</t_lemma>
<functor>INTT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s1w18</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p3s2w19">
<a>
<lex.rf>a#a-ln94211-63-p3s2w19</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln94211-63-p3s2w20">
<a>
<lex.rf>a#a-ln94211-63-p3s2w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodně</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>adj.quant.grad</sempos>
<degcmp>comp</degcmp>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p4s1">
<atree.rf>a#a-ln94211-63-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94211-63-l27A">
<basic-form>MUDr. Petr Š.</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94211-63-p4s1w3</LM>
<LM>t-ln94211-63-p4s1w5</LM>
<LM>t-ln94211-63-p4s1w6</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94211-63-l32A">
<basic-form>pracovní doba</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94211-63-p4s1w10</LM>
<LM>t-ln94211-63-p4s1w11</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94211-63-p4s1w8">
<a>
<lex.rf>a#a-ln94211-63-p4s1w8</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p4s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>provádět</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41hquA</val_frame.rf>
<children>
<LM id="t-ln94211-63-p4s1w6">
<a>
<lex.rf>a#a-ln94211-63-p4s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Š</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s1w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94211-63-p4s1w3">
<a>
<lex.rf>a#a-ln94211-63-p4s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>MUDr</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94211-63-p4s1w5">
<a>
<lex.rf>a#a-ln94211-63-p4s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Petr</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p4s1w1">
<a>
<lex.rf>a#a-ln94211-63-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zákrok</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s2w15</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94211-63-p4s1w11">
<a>
<lex.rf>a#a-ln94211-63-p4s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p4s1w9</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>doba</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94211-63-p4s1w10">
<a>
<lex.rf>a#a-ln94211-63-p4s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pracovní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p4s1w15">
<a>
<lex.rf>a#a-ln94211-63-p4s1w15</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>9</deepord>
<children>
<LM id="t-ln94211-63-p4s1w14">
<a>
<lex.rf>a#a-ln94211-63-p4s1w14</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p4s1w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vědomí</t_lemma>
<functor>ACMP</functor>
<subfunctor>wout</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-ln94211-63-p4s1w16">
<a>
<lex.rf>a#a-ln94211-63-p4s1w16</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p4s1w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>souhlas</t_lemma>
<functor>ACMP</functor>
<subfunctor>wout</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln94211-63-p4s1w17">
<a>
<lex.rf>a#a-ln94211-63-p4s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vedení</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41nieC</val_frame.rf>
<children>
<LM id="t-ln94211-63-p4s1w19">
<a>
<lex.rf>a#a-ln94211-63-p4s1w19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>nemocnice</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s1w17</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94211-63-p4s1w18">
<a>
<lex.rf>a#a-ln94211-63-p4s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>českotěšínský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s2w12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p5s1">
<atree.rf>a#a-ln94211-63-p5s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94211-63-l20A">
<type>time</type>
<tnode.rfs>
<LM>t-ln94211-63-p5s1w5</LM>
<LM>t-ln94211-63-p5s1w7</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94211-63-p5s1w3">
<a>
<lex.rf>a#a-ln94211-63-p5s1w3</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p5s1w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zadržet</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41pseC</val_frame.rf>
<children>
<LM id="t-ln94211-63-p5s1w1">
<a>
<lex.rf>a#a-ln94211-63-p5s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>lékař</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p4s1w6</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94211-63-p5s1w4">
<a>
<lex.rf>a#a-ln94211-63-p5s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>policista</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94211-63-p5s1w7">
<a>
<lex.rf>a#a-ln94211-63-p5s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prosinec</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94211-63-p5s1w9">
<a>
<lex.rf>a#a-ln94211-63-p5s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p3s1w14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-ln94211-63-p5s1w8">
<a>
<lex.rf>a#a-ln94211-63-p5s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>loňský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p5s1w5">
<a>
<lex.rf>a#a-ln94211-63-p5s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>17</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p5s2">
<atree.rf>a#a-ln94211-63-p5s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94211-63-l33A">
<basic-form>zahraniční měna</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94211-63-p5s2w9</LM>
<LM>t-ln94211-63-p5s2w10</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94211-63-l34A">
<basic-form>tuzemská měna</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94211-63-p5s2w7</LM>
<LM>t-ln94211-63-p5s2a3</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94211-63-p5s2w4">
<a>
<lex.rf>a#a-ln94211-63-p5s2w4</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p5s2w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mít</t_lemma>
<functor>PRED</functor>
<proto_lemma>mít</proto_lemma>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>hrt</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41chlO</val_frame.rf>
<children>
<LM id="t-ln94211-63-p5s2w2">
<a>
<lex.rf>a#a-ln94211-63-p5s2w2</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p5s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zadržení</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p5s1w3</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41psdA</val_frame.rf>
<children>
<LM id="t-ln94211-63-p5s2a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-ln94211-63-p5s2a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p5s2a2">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94211-63-p5s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94211-63-p5s2w6">
<a>
<lex.rf>a#a-ln94211-63-p5s2w6</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p5s2w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>LOC</functor>
<subfunctor>near</subfunctor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>5</deepord>
<coref_gram.rf>
<LM>t-ln94211-63-p5s2a2</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94211-63-p5s2w8">
<a>
<lex.rf>a#a-ln94211-63-p5s2w8</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>9</deepord>
<children>
<LM id="t-ln94211-63-p5s2a3">
<a>
<lex.rf>a#a-ln94211-63-p5s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>měna</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94211-63-p5s2w7">
<a>
<lex.rf>a#a-ln94211-63-p5s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tuzemský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p5s2w10">
<a>
<lex.rf>a#a-ln94211-63-p5s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>měna</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94211-63-p5s2w9">
<a>
<lex.rf>a#a-ln94211-63-p5s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zahraniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94211-63-p5s2w12">
<a>
<lex.rf>a#a-ln94211-63-p5s2w12</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p5s2w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hodnota</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94211-63-p5s2w15">
<a>
<lex.rf>a#a-ln94211-63-p5s2w15</lex.rf>
<aux.rf>
<LM>a#a-ln94211-63-p5s2w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>koruna</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-ln94211-63-p5s2w14">
<a>
<lex.rf>a#a-ln94211-63-p5s2w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>300000</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
