<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="ln94202_110.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>collection</genre>
</meta>
<trees>
<LM id="t-ln94202-110-p1s1">
<atree.rf>a#a-ln94202-110-p1s1</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-ln94202-110-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#EmpVerb</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<tfa>t</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-ln94202-110-p1s1w1">
<a>
<lex.rf>a#a-ln94202-110-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>krátce</t_lemma>
<functor>MANN</functor>
<proto_lemma>krátký</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p2s1">
<atree.rf>a#a-ln94202-110-p2s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-110-l1A">
<type>person</type>
<tnode.rfs>
<LM>t-ln94202-110-p2s1w1</LM>
<LM>t-ln94202-110-p2s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-110-p2s1w3">
<a>
<lex.rf>a#a-ln94202-110-p2s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyhrát</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41obaA</val_frame.rf>
<children>
<LM id="t-ln94202-110-p2s1w2">
<a>
<lex.rf>a#a-ln94202-110-p2s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Klimeš</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-110-p2s1w1">
<a>
<lex.rf>a#a-ln94202-110-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Petr</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p2s1w5">
<a>
<lex.rf>a#a-ln94202-110-p2s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>běh</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-ln94202-110-p2s1w4">
<a>
<lex.rf>a#a-ln94202-110-p2s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>silniční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94202-110-p2s1w8">
<a>
<lex.rf>a#a-ln94202-110-p2s1w8</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p2s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Klosterneuburg</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-ln94202-110-p2s1w7">
<a>
<lex.rf>a#a-ln94202-110-p2s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rakouský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-110-p2s1w8</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p3s1">
<atree.rf>a#a-ln94202-110-p3s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-110-l9A">
<basic-form>Héctor Acero Sánchez</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94202-110-p3s1w12</LM>
<LM>t-ln94202-110-p3s1w13</LM>
<LM>t-ln94202-110-p3s1w14</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l16A">
<basic-form>mistr světa</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-110-p3s1w1</LM>
<LM>t-ln94202-110-p3s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-110-p3s1w11">
<a>
<lex.rf>a#a-ln94202-110-p3s1w11</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p3s1w10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát_se</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<val_frame.rf>v#v41lioA</val_frame.rf>
<children>
<LM id="t-ln94202-110-p3s1w1">
<a>
<lex.rf>a#a-ln94202-110-p3s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mistr</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-110-p3s1w2">
<a>
<lex.rf>a#a-ln94202-110-p3s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svět</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-ln94202-110-p3s1w5">
<a>
<lex.rf>a#a-ln94202-110-p3s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>organizace</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-ln94202-110-p3s1w3">
<a>
<lex.rf>a#a-ln94202-110-p3s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>profesionální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-ln94202-110-p3s1w4">
<a>
<lex.rf>a#a-ln94202-110-p3s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>boxerský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-ln94202-110-p3s1w6">
<a>
<lex.rf>a#a-ln94202-110-p3s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>WBC</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p3s1w9">
<a>
<lex.rf>a#a-ln94202-110-p3s1w9</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p3s1w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>váha</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-110-p3s1w8">
<a>
<lex.rf>a#a-ln94202-110-p3s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bantamový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p3s1w14">
<a>
<lex.rf>a#a-ln94202-110-p3s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Sanchez</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-110-p3s1w12">
<a>
<lex.rf>a#a-ln94202-110-p3s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Hector</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94202-110-p3s1w13">
<a>
<lex.rf>a#a-ln94202-110-p3s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Acero</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p3s2">
<atree.rf>a#a-ln94202-110-p3s2</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-110-l10A">
<type>location</type>
<tnode.rfs>
<LM>t-ln94202-110-p3s2w2</LM>
<LM>t-ln94202-110-p3s2w3</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l11A">
<basic-form>Tracy Harris Patterson</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94202-110-p3s2w8</LM>
<LM>t-ln94202-110-p3s2w9</LM>
<LM>t-ln94202-110-p3s2w10</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l12A">
<type>number</type>
<tnode.rfs>
<LM>t-ln94202-110-p3s2w13</LM>
<LM>t-ln94202-110-p3s2w14</LM>
<LM>t-ln94202-110-p3s2w15</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-110-p3s2w4">
<a>
<lex.rf>a#a-ln94202-110-p3s2w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>porazit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41giwB</val_frame.rf>
<children>
<LM id="t-ln94202-110-p3s2w3">
<a>
<lex.rf>a#a-ln94202-110-p3s2w3</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p3s2w1</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>City</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-110-p3s2w2">
<a>
<lex.rf>a#a-ln94202-110-p3s2w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Atlantic</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p3s2a1">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>3</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-110-p3s1w14</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-110-p3s2w10">
<a>
<lex.rf>a#a-ln94202-110-p3s2w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Patterson</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94202-110-p3s2w6">
<a>
<lex.rf>a#a-ln94202-110-p3s2w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>držitel</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-110-p3s2w7">
<a>
<lex.rf>a#a-ln94202-110-p3s2w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>titul</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-110-p3s1w1</target_node.rf>
<type>ANAF</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94202-110-p3s2w5">
<a>
<lex.rf>a#a-ln94202-110-p3s2w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dosavadní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p3s2w8">
<a>
<lex.rf>a#a-ln94202-110-p3s2w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tracy</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94202-110-p3s2w9">
<a>
<lex.rf>a#a-ln94202-110-p3s2w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Harris</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p3s2w12">
<a>
<lex.rf>a#a-ln94202-110-p3s2w12</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p3s2w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bod</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94202-110-p3s2w14">
<a>
<lex.rf>a#a-ln94202-110-p3s2w14</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Colon</t_lemma>
<functor>OPER</functor>
<deepord>12</deepord>
<children>
<LM id="t-ln94202-110-p3s2w13">
<a>
<lex.rf>a#a-ln94202-110-p3s2w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>2</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln94202-110-p3s2w15">
<a>
<lex.rf>a#a-ln94202-110-p3s2w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1</t_lemma>
<functor>EXT</functor>
<subfunctor>nr</subfunctor>
<is_member>1</is_member>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p4s1">
<atree.rf>a#a-ln94202-110-p4s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-110-l6A">
<basic-form>Jake Rodríguez</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94202-110-p4s1w14</LM>
<LM>t-ln94202-110-p4s1w15</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l13A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94202-110-p4s1w6</LM>
<LM>t-ln94202-110-p4s1w7</LM>
<LM>t-ln94202-110-p4s1w8</LM>
<LM>t-ln94202-110-p4s1w9</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l17A">
<basic-form>mistr světa</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-110-p4s1w2</LM>
<LM>t-ln94202-110-p4s1w3</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l19A">
<basic-form>polotěžká váha</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-110-p4s1w4</LM>
<LM>t-ln94202-110-p4s1w5</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-110-p4s1w16">
<a>
<lex.rf>a#a-ln94202-110-p4s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obhájit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
<val_frame.rf>v#v41dojB</val_frame.rf>
<children>
<LM id="t-ln94202-110-p4s1w15">
<a>
<lex.rf>a#a-ln94202-110-p4s1w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Rodriguez</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-110-p4s1w2">
<a>
<lex.rf>a#a-ln94202-110-p4s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mistr</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94202-110-p4s1w1">
<a>
<lex.rf>a#a-ln94202-110-p4s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osmadvacetiletý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-ln94202-110-p4s1w3">
<a>
<lex.rf>a#a-ln94202-110-p4s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svět</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<coref_text>
<LM>
<target_node.rf>t-ln94202-110-p3s1w2</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-ln94202-110-p4s1w5">
<a>
<lex.rf>a#a-ln94202-110-p4s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>váha</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-ln94202-110-p4s1w4">
<a>
<lex.rf>a#a-ln94202-110-p4s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>polotěžký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-ln94202-110-p4s1w10">
<a>
<lex.rf>a#a-ln94202-110-p4s1w10</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Bracket</t_lemma>
<functor>APPS</functor>
<deepord>7</deepord>
<children>
<LM id="t-ln94202-110-p4s1w9">
<a>
<lex.rf>a#a-ln94202-110-p4s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>federace</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-ln94202-110-p4s1w6">
<a>
<lex.rf>a#a-ln94202-110-p4s1w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Mezinárodní</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-ln94202-110-p4s1w7">
<a>
<lex.rf>a#a-ln94202-110-p4s1w7</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>profesionální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
<LM id="t-ln94202-110-p4s1w8">
<a>
<lex.rf>a#a-ln94202-110-p4s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>boxerský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p4s1w11">
<a>
<lex.rf>a#a-ln94202-110-p4s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>IBF</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p4s1w13">
<a>
<lex.rf>a#a-ln94202-110-p4s1w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Američan</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln94202-110-p4s1w14">
<a>
<lex.rf>a#a-ln94202-110-p4s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Jake</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p4s1w18">
<a>
<lex.rf>a#a-ln94202-110-p4s1w18</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p4s1w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bushkill</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
<LM id="t-ln94202-110-p4s1w20">
<a>
<lex.rf>a#a-ln94202-110-p4s1w20</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p4s1w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>stát</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>17</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-110-p4s1w18</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
<children>
<LM id="t-ln94202-110-p4s1w21">
<a>
<lex.rf>a#a-ln94202-110-p4s1w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Pennsylvanie</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p4s1w23">
<a>
<lex.rf>a#a-ln94202-110-p4s1w23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>titul</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-110-p4s1w2</target_node.rf>
<type>ANAF</type>
</LM>
</bridging>
<children>
<LM id="t-ln94202-110-p4s1w22">
<a>
<lex.rf>a#a-ln94202-110-p4s1w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>19</deepord>
<coref_gram.rf>
<LM>t-ln94202-110-p4s1w15</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p5s1">
<atree.rf>a#a-ln94202-110-p5s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-ln94202-110-l8A">
<basic-form>Chris Eubank</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-ln94202-110-p5s1w3</LM>
<LM>t-ln94202-110-p5s1w4</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l14A">
<type>institution</type>
<tnode.rfs>
<LM>t-ln94202-110-p5s1w16</LM>
<LM>t-ln94202-110-p5s1w17</LM>
<LM>t-ln94202-110-p5s1w18</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l15A">
<basic-form>mistr světa</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-110-p5s1w11</LM>
<LM>t-ln94202-110-p5s1w12</LM>
</tnode.rfs>
</LM>
<LM id="s-ln94202-110-l18A">
<basic-form>polotěžká váha</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-ln94202-110-p5s1w14</LM>
<LM>t-ln94202-110-p5s1w15</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-ln94202-110-p5s1w5">
<a>
<lex.rf>a#a-ln94202-110-p5s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obhájit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41dojB</val_frame.rf>
<children>
<LM id="t-ln94202-110-p5s1w4">
<a>
<lex.rf>a#a-ln94202-110-p5s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Eubank</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-ln94202-110-p5s1w2">
<a>
<lex.rf>a#a-ln94202-110-p5s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>boxer</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-ln94202-110-p5s1w1">
<a>
<lex.rf>a#a-ln94202-110-p5s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>britský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p5s1w3">
<a>
<lex.rf>a#a-ln94202-110-p5s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Chris</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p5s1w7">
<a>
<lex.rf>a#a-ln94202-110-p5s1w7</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p5s1w6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Cardiff</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-ln94202-110-p5s1w1</target_node.rf>
<type>WHOLE_PART</type>
</LM>
</bridging>
</LM>
<LM id="t-ln94202-110-p5s1w8">
<a>
<lex.rf>a#a-ln94202-110-p5s1w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podvanácté</t_lemma>
<functor>THO</functor>
<proto_lemma>dvanáct</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>ord</numertype>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-ln94202-110-p5s1w10">
<a>
<lex.rf>a#a-ln94202-110-p5s1w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>titul</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-ln94202-110-p5s1w9">
<a>
<lex.rf>a#a-ln94202-110-p5s1w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>inher</gender>
<number>inher</number>
<person>inher</person>
<politeness>inher</politeness>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_gram.rf>
<LM>t-ln94202-110-p5s1w4</LM>
</coref_gram.rf>
</LM>
<LM id="t-ln94202-110-p5s1w11">
<a>
<lex.rf>a#a-ln94202-110-p5s1w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mistr</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-ln94202-110-p5s1w12">
<a>
<lex.rf>a#a-ln94202-110-p5s1w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svět</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-ln94202-110-p5s1w15">
<a>
<lex.rf>a#a-ln94202-110-p5s1w15</lex.rf>
<aux.rf>
<LM>a#a-ln94202-110-p5s1w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>váha</t_lemma>
<functor>REG</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<children>
<LM id="t-ln94202-110-p5s1w14">
<a>
<lex.rf>a#a-ln94202-110-p5s1w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>polotěžký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
<LM id="t-ln94202-110-p5s1w19">
<a>
<lex.rf>a#a-ln94202-110-p5s1w19</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>#Bracket</t_lemma>
<functor>APPS</functor>
<is_parenthesis>1</is_parenthesis>
<deepord>17</deepord>
<children>
<LM id="t-ln94202-110-p5s1w18">
<a>
<lex.rf>a#a-ln94202-110-p5s1w18</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>organizace</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-ln94202-110-p5s1w16">
<a>
<lex.rf>a#a-ln94202-110-p5s1w16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>světový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-ln94202-110-p5s1w17">
<a>
<lex.rf>a#a-ln94202-110-p5s1w17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>boxerský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
</LM>
</children>
</LM>
<LM id="t-ln94202-110-p5s1w20">
<a>
<lex.rf>a#a-ln94202-110-p5s1w20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>WBO</t_lemma>
<functor>APP</functor>
<is_member>1</is_member>
<is_parenthesis>1</is_parenthesis>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
