<?xml version="1.0" encoding="UTF-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
<head>
<schema href="tdata_c2_schema.xml" />
<references>
<reffile id="a" name="adata" href="mf930709_086.a" />
<reffile id="v" name="vallex" href="pdtvallex-4.5.xml" />
</references>
</head>
<meta>
<annotation_info>
<desc>Manual annotation</desc>
</annotation_info>
<genre>collection</genre>
</meta>
<trees>
<LM id="t-mf930709-086-p1s1">
<atree.rf>a#a-mf930709-086-p1s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-086-l27B">
<basic-form>podpisová akce</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-086-p1s1w1</LM>
<LM>t-mf930709-086-p1s1w2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-086-p1s1w2">
<a>
<lex.rf>a#a-mf930709-086-p1s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>akce</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
<discourse_feature>heading</discourse_feature>
<children>
<LM id="t-mf930709-086-p1s1w1">
<a>
<lex.rf>a#a-mf930709-086-p1s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpisový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-086-p1s1w4">
<a>
<lex.rf>a#a-mf930709-086-p1s1w4</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s1w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>propuštění</t_lemma>
<functor>AIM</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41hlnA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-086-p1s1a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR1</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>4</deepord>
</LM>
<LM id="t-mf930709-086-p1s1w5">
<a>
<lex.rf>a#a-mf930709-086-p1s1w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tyson</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s2A">
<atree.rf>a#a-mf930709-086-p1s2A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-086-p1s2Aw1">
<a>
<lex.rf>a#a-mf930709-086-p1s2Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Indianapolis</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s2B">
<atree.rf>a#a-mf930709-086-p1s2B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-086-l5B">
<basic-form>Mike Tyson</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-086-p1s2Bw5</LM>
<LM>t-mf930709-086-p1s2Bw6</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-086-l9B">
<basic-form>Desirée Washingtonová</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-086-p1s2Bw23</LM>
<LM>t-mf930709-086-p1s2Bw24</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-086-l23B">
<basic-form>královna krásy</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-086-p1s2Bw21</LM>
<LM>t-mf930709-086-p1s2Bw22</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-086-l25B">
<type>number</type>
<tnode.rfs>
<LM>t-mf930709-086-p1s2Bw27</LM>
<LM>t-mf930709-086-p1s2Bw28</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-086-p1s2Bw26">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>shromáždit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<val_frame.rf>v#v41kncA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s2Bw1">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>přítel</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw6">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tyson</t_lemma>
<functor>APP</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s1w5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-086-p1s2Bw5">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Mike</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-086-p1s2Bw4">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>boxer</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw3">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>profesionální</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-086-p1s2Bw2">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>americký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-086-p1s2Aw1</target_node.rf>
<type>PART_WHOLE</type>
</LM>
</bridging>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s2Bw9">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>sedět</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<val_frame.rf>v#v41khtE</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s2Bw8">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_gram.rf>
<LM>t-mf930709-086-p1s2Bw6</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-086-p1s2Bw11">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw11</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s2Bw10</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>rok</t_lemma>
<functor>TSIN</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>9</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw12">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>1992</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.quant.def</sempos>
<gender>nr</gender>
<number>nr</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s2Bw14">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw14</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s2Bw13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vězení</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
</LM>
<LM id="t-mf930709-086-p1s2Bw16">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw16</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s2Bw15</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znásilnění</t_lemma>
<functor>CAUS</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41rmyA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s2Ba0">
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#PersPron</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>nr</gender>
<number>nr</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>12</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s2Bw8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-086-p1s2Bw24">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Washingtonová</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw23">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Desiree</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-mf930709-086-p1s2Bw17">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>uchazečka</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw19">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw19</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s2Bw18</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>titul</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>17</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw21">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>královna</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw22">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>krása</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
</LM>
<LM id="t-mf930709-086-p1s2Bw20">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>černý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s2Bw28">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tisíc</t_lemma>
<functor>PAT</functor>
<proto_lemma>tisíc</proto_lemma>
<gram>
<sempos>n.quant.def</sempos>
<gender>inan</gender>
<number>pl</number>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw29">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw29</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>podpis</t_lemma>
<functor>MAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw31">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw31</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s2Bw30</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žádost</t_lemma>
<functor>DIR3</functor>
<subfunctor>below</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
<children>
<LM id="t-mf930709-086-p1s2Bw34">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw34</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s2Bw32</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>propuštění</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>28</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41hlnA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s2Ba1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>25</deepord>
</LM>
<LM id="t-mf930709-086-p1s2Ba2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Oblfm</t_lemma>
<functor>DIR1</functor>
<subfunctor>nr</subfunctor>
<tfa>t</tfa>
<deepord>26</deepord>
</LM>
<LM id="t-mf930709-086-p1s2Bw33">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw33</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>t</tfa>
<deepord>27</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s2Ba0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s2Bw27">
<a>
<lex.rf>a#a-mf930709-086-p1s2Bw27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tři</t_lemma>
<functor>RSTR</functor>
<proto_lemma>tři</proto_lemma>
<gram>
<sempos>adj.quant.def</sempos>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>29</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s3">
<atree.rf>a#a-mf930709-086-p1s3</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-086-l12B">
<basic-form>Patricia Giffordová</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-086-p1s3w5</LM>
<LM>t-mf930709-086-p1s3w6</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-086-l28B">
<basic-form>mistr světa</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-086-p1s3w10</LM>
<LM>t-mf930709-086-p1s3w11</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-086-p1s3w3">
<a>
<lex.rf>a#a-mf930709-086-p1s3w3</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s3w2</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<val_frame.rf>v#v41hveA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s3w1">
<a>
<lex.rf>a#a-mf930709-086-p1s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dokument</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s2Bw31</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-086-p1s3a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-086-p1s3w6">
<a>
<lex.rf>a#a-mf930709-086-p1s3w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Giffordová</t_lemma>
<functor>ADDR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-086-p1s3w5">
<a>
<lex.rf>a#a-mf930709-086-p1s3w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Patricia</t_lemma>
<functor>RSTR</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-086-p1s3w4">
<a>
<lex.rf>a#a-mf930709-086-p1s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soudkyně</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930709-086-p1s3w12">
<a>
<lex.rf>a#a-mf930709-086-p1s3w12</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>poslat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41gmgC</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s3w8">
<a>
<lex.rf>a#a-mf930709-086-p1s3w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_gram.rf>
<LM>t-mf930709-086-p1s3w6</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-086-p1s3w10">
<a>
<lex.rf>a#a-mf930709-086-p1s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mistr</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s2Bw33</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-086-p1s3w9">
<a>
<lex.rf>a#a-mf930709-086-p1s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>bývalý</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-086-p1s3w11">
<a>
<lex.rf>a#a-mf930709-086-p1s3w11</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>svět</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s3w14">
<a>
<lex.rf>a#a-mf930709-086-p1s3w14</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s3w13</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>mříž</t_lemma>
<functor>DIR3</functor>
<subfunctor>behind</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s4">
<atree.rf>a#a-mf930709-086-p1s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-086-l16B">
<basic-form>Tyson Washingtonovou</basic-form>
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-086-p1s4w13</LM>
<LM>t-mf930709-086-p1s4w14</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-086-p1s4w4">
<a>
<lex.rf>a#a-mf930709-086-p1s4w4</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s4w3</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vystavit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<val_frame.rf>v#v41oxwD</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s4w1">
<a>
<lex.rf>a#a-mf930709-086-p1s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>kopie</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf930709-086-p1s4w2">
<a>
<lex.rf>a#a-mf930709-086-p1s4w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>žádost</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s3w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p1s4a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-086-p1s4w7">
<a>
<lex.rf>a#a-mf930709-086-p1s4w7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s4w5</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výstava</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-086-p1s4w6">
<a>
<lex.rf>a#a-mf930709-086-p1s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tradiční</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
</LM>
<LM id="t-mf930709-086-p1s4w9">
<a>
<lex.rf>a#a-mf930709-086-p1s4w9</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s4w8</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Indianapolis</t_lemma>
<functor>LOC</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-086-p1s4w15">
<a>
<lex.rf>a#a-mf930709-086-p1s4w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>znásilnit</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>11</deepord>
<val_frame.rf>v#v41rmzA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p1s4w13">
<a>
<lex.rf>a#a-mf930709-086-p1s4w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tyson</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s3w10</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-086-p1s4w14">
<a>
<lex.rf>a#a-mf930709-086-p1s4w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Washingtonová</t_lemma>
<functor>PAT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p1s2Bw24</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-086-p1s4w12">
<a>
<lex.rf>a#a-mf930709-086-p1s4w12</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p1s4w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>TPAR</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_gram.rf>
<LM>t-mf930709-086-p1s4w7</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s1">
<atree.rf>a#a-mf930709-086-p2s1</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-086-l29B">
<basic-form>vyšetřující soudce</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-086-p2s1w3</LM>
<LM>t-mf930709-086-p2s1w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-086-p2s1w2">
<a>
<lex.rf>a#a-mf930709-086-p2s1w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyhrožovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<discourse_feature>heading</discourse_feature>
<val_frame.rf>v#v41oboA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s1w1">
<a>
<lex.rf>a#a-mf930709-086-p2s1w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fanoušek</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
</LM>
<LM id="t-mf930709-086-p2s1a0">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
<LM id="t-mf930709-086-p2s1w4">
<a>
<lex.rf>a#a-mf930709-086-p2s1w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soudce</t_lemma>
<functor>ADDR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-086-p2s1w3">
<a>
<lex.rf>a#a-mf930709-086-p2s1w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyšetřující</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s2A">
<atree.rf>a#a-mf930709-086-p2s2A</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-086-p2s2Aw1">
<a>
<lex.rf>a#a-mf930709-086-p2s2Aw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Marseille</t_lemma>
<functor>DENOM</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>n.denot</sempos>
<gender>neut</gender>
<number>nr</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>1</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s2B">
<atree.rf>a#a-mf930709-086-p2s2B</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-086-l26B">
<type>institution</type>
<tnode.rfs>
<LM>t-mf930709-086-p2s2Bw10</LM>
<LM>t-mf930709-086-p2s2Bw11</LM>
<LM>t-mf930709-086-p2s2Bw12</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-086-l30B">
<basic-form>vyšetřující soudce</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-086-p2s2Bw1</LM>
<LM>t-mf930709-086-p2s2Bw2</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-086-p2s2Bw14">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dostat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41afvD</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s2Bw3">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Beffi</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s1w4</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-086-p2s2Bw2">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soudce</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<children>
<LM id="t-mf930709-086-p2s2Bw1">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyšetřující</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s2Bw7">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw7</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p2s2Bw6</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zabývat_se</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<val_frame.rf>v#v41pqjA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s2Bw5">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>ACT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>4</deepord>
<coref_gram.rf>
<LM>t-mf930709-086-p2s2Bw3</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-086-p2s2Bw9">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>aféra</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<children>
<LM id="t-mf930709-086-p2s2Bw8">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>úplatkářský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
<LM id="t-mf930709-086-p2s2Ba0">
<nodetype>list</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Forn</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<tfa>f</tfa>
<deepord>10</deepord>
<children>
<LM id="t-mf930709-086-p2s2Bw10">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw10</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Ol</t_lemma>
<functor>FPHR</functor>
<deepord>8</deepord>
</LM>
<LM id="t-mf930709-086-p2s2Bw11">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw11</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>.</t_lemma>
<functor>FPHR</functor>
<deepord>9</deepord>
</LM>
<LM id="t-mf930709-086-p2s2Bw12">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw12</lex.rf>
</a>
<nodetype>fphr</nodetype>
<t_lemma>Marseille</t_lemma>
<functor>FPHR</functor>
<deepord>11</deepord>
<bridging>
<LM>
<target_node.rf>t-mf930709-086-p2s2Aw1</target_node.rf>
<type>REST</type>
</LM>
</bridging>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s2Bw17">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw17</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>dopis</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<children>
<LM id="t-mf930709-086-p2s2Bw16">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw16</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>výhrůžný</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
</LM>
<LM id="t-mf930709-086-p2s2Bw15">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>několik</t_lemma>
<functor>RSTR</functor>
<proto_lemma>kolik</proto_lemma>
<gram>
<sempos>adj.quant.indef</sempos>
<indeftype>indef1</indeftype>
<numertype>basic</numertype>
</gram>
<tfa>f</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-mf930709-086-p2s2Bw21">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>být</t_lemma>
<functor>RSTR</functor>
<proto_lemma>být</proto_lemma>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<val_frame.rf>v#v41jsM</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s2Bw20">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw20</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>autor</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>17</deepord>
<children>
<LM id="t-mf930709-086-p2s2Bw19">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw19</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>který</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>16</deepord>
<coref_gram.rf>
<LM>t-mf930709-086-p2s2Bw17</LM>
</coref_gram.rf>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s2Bw24">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw24</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p2s2Bw22</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pravděpodobnost</t_lemma>
<functor>ACMP</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<children>
<LM id="t-mf930709-086-p2s2Bw23">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw23</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>velký</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>sup</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>20</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s2Bw25">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fanoušek</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s1w1</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-086-p2s2Bw28">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw28</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>tým</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>23</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s2Bw12</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-086-p2s2Bw26">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw26</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jihofrancouzský</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>22</deepord>
</LM>
<LM id="t-mf930709-086-p2s2Bw27">
<a>
<lex.rf>a#a-mf930709-086-p2s2Bw27</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>fotbalový</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>24</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s3">
<atree.rf>a#a-mf930709-086-p2s3</atree.rf>
<deepord>0</deepord>
<children>
<LM id="t-mf930709-086-p2s3w2">
<a>
<lex.rf>a#a-mf930709-086-p2s3w2</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>obsahovat</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>2</deepord>
<val_frame.rf>v#v41dsuA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s3w1">
<a>
<lex.rf>a#a-mf930709-086-p2s3w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>list</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>1</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s2Bw19</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-086-p2s3w3">
<a>
<lex.rf>a#a-mf930709-086-p2s3w3</lex.rf>
</a>
<nodetype>atom</nodetype>
<t_lemma>i</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>3</deepord>
</LM>
<LM id="t-mf930709-086-p2s3w4">
<a>
<lex.rf>a#a-mf930709-086-p2s3w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>hrozba</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>pl</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-086-p2s3w8">
<a>
<lex.rf>a#a-mf930709-086-p2s3w8</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p2s3w6</LM>
<LM>a#a-mf930709-086-p2s3w7</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zabít</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>6</deepord>
<val_frame.rf>v#v41ppaA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s3a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>5</deepord>
</LM>
<LM id="t-mf930709-086-p2s3w10">
<a>
<lex.rf>a#a-mf930709-086-p2s3w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>manželka</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>8</deepord>
<children>
<LM id="t-mf930709-086-p2s3w9">
<a>
<lex.rf>a#a-mf930709-086-p2s3w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soudcův</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>7</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s2Bw5</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s3w15">
<a>
<lex.rf>a#a-mf930709-086-p2s3w15</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p2s3w13</LM>
<LM>a#a-mf930709-086-p2s3w12</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>ukončit</t_lemma>
<functor>COND</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>post</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>pas</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<discourse>
<LM>
<target_node.rf>t-mf930709-086-p2s3w8</target_node.rf>
<type>discourse</type>
<start_range>0</start_range>
<target_range>0</target_range>
<discourse_type>cond</discourse_type>
<sense_PDTB3>Contingency.Negative-condition.Arg2-as-negCond</sense_PDTB3>
<src>pdit10</src>
<a-connectors.rf>
<LM>a#a-mf930709-086-p2s3w12</LM>
</a-connectors.rf>
</LM>
</discourse>
<val_frame.rf>v#v41mmnB</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s3w14">
<a>
<lex.rf>a#a-mf930709-086-p2s3w14</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyšetřování</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot.neg</sempos>
<gender>neut</gender>
<number>sg</number>
<typgroup>single</typgroup>
<negation>neg0</negation>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s2Bw7</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<val_frame.rf>v#v41panA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s3a4">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
<LM id="t-mf930709-086-p2s3a3">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>PAT</functor>
<tfa>t</tfa>
<deepord>10</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s3a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>12</deepord>
</LM>
<LM id="t-mf930709-086-p2s3a0">
<nodetype>atom</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Neg</t_lemma>
<functor>RHEM</functor>
<tfa>f</tfa>
<deepord>13</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s4">
<atree.rf>a#a-mf930709-086-p2s4</atree.rf>
<deepord>0</deepord>
<mwes>
<LM id="s-mf930709-086-l22B">
<type>person</type>
<tnode.rfs>
<LM>t-mf930709-086-p2s4w5</LM>
<LM>t-mf930709-086-p2s4w6</LM>
</tnode.rfs>
</LM>
<LM id="s-mf930709-086-l32A">
<basic-form>předseda klubu</basic-form>
<type>lexeme</type>
<tnode.rfs>
<LM>t-mf930709-086-p2s4w3</LM>
<LM>t-mf930709-086-p2s4w4</LM>
</tnode.rfs>
</LM>
</mwes>
<children>
<LM id="t-mf930709-086-p2s4w15">
<a>
<lex.rf>a#a-mf930709-086-p2s4w15</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>prohlásit</t_lemma>
<functor>PRED</functor>
<sentmod>enunc</sentmod>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>13</deepord>
<val_frame.rf>v#v41hddB</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s4w6">
<a>
<lex.rf>a#a-mf930709-086-p2s4w6</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Tapie</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>c</tfa>
<deepord>1</deepord>
<children>
<LM id="t-mf930709-086-p2s4w2">
<a>
<lex.rf>a#a-mf930709-086-p2s4w2</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>4</deepord>
<children>
<LM id="t-mf930709-086-p2s4w1">
<a>
<lex.rf>a#a-mf930709-086-p2s4w1</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>majitel</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>3</deepord>
<children>
<LM id="t-mf930709-086-p2s4a0">
<a>
<lex.rf>a#a-mf930709-086-p2s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<is_generated>1</is_generated>
<t_lemma>klub</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>2</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s4w3">
<a>
<lex.rf>a#a-mf930709-086-p2s4w3</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>předseda</t_lemma>
<functor>RSTR</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>5</deepord>
<children>
<LM id="t-mf930709-086-p2s4w4">
<a>
<lex.rf>a#a-mf930709-086-p2s4w4</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klub</t_lemma>
<functor>APP</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>6</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s2Bw28</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-086-p2s4w5">
<a>
<lex.rf>a#a-mf930709-086-p2s4w5</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Bernard</t_lemma>
<functor>ID</functor>
<sentmod>enunc</sentmod>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>7</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s4w13">
<a>
<lex.rf>a#a-mf930709-086-p2s4w13</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>vyslýchat</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>ant</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>12</deepord>
<val_frame.rf>v#v41owwA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s4w8">
<a>
<lex.rf>a#a-mf930709-086-p2s4w8</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jenž</t_lemma>
<functor>PAT</functor>
<proto_lemma>který</proto_lemma>
<gram>
<sempos>n.pron.indef</sempos>
<gender>inher</gender>
<number>inher</number>
<indeftype>relat</indeftype>
<person>inher</person>
</gram>
<tfa>t</tfa>
<deepord>8</deepord>
<coref_gram.rf>
<LM>t-mf930709-086-p2s4w6</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-086-p2s4w10">
<a>
<lex.rf>a#a-mf930709-086-p2s4w10</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>Beffi</t_lemma>
<functor>ACT</functor>
<is_name_of_person>1</is_name_of_person>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>10</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s3w9</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-086-p2s4w9">
<a>
<lex.rf>a#a-mf930709-086-p2s4w9</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>soudce</t_lemma>
<functor>RSTR</functor>
<gram>
<sempos>n.denot</sempos>
<gender>anim</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>9</deepord>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s4w12">
<a>
<lex.rf>a#a-mf930709-086-p2s4w12</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p2s4w11</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>středa</t_lemma>
<functor>TWHEN</functor>
<subfunctor>basic</subfunctor>
<gram>
<sempos>n.denot</sempos>
<gender>fem</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>t</tfa>
<deepord>11</deepord>
</LM>
</children>
</LM>
</children>
</LM>
<LM id="t-mf930709-086-p2s4w18">
<a>
<lex.rf>a#a-mf930709-086-p2s4w18</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p2s4w17</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>jít</t_lemma>
<functor>EFF</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>sim</tense>
<aspect>proc</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>asserted</factmod>
</gram>
<tfa>f</tfa>
<deepord>14</deepord>
<val_frame.rf>v#v41bikAV</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s4w20">
<a>
<lex.rf>a#a-mf930709-086-p2s4w20</lex.rf>
<aux.rf>
<LM>a#a-mf930709-086-p2s4w19</LM>
</aux.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>pokus</t_lemma>
<functor>ACT</functor>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>16</deepord>
<children>
<LM id="t-mf930709-086-p2s4a1">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Gen</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>15</deepord>
</LM>
<LM id="t-mf930709-086-p2s4w21">
<a>
<lex.rf>a#a-mf930709-086-p2s4w21</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>zničit</t_lemma>
<functor>PAT</functor>
<gram>
<sempos>v</sempos>
<deontmod>decl</deontmod>
<tense>nil</tense>
<aspect>cpl</aspect>
<iterativeness>it0</iterativeness>
<diatgram>act</diatgram>
<factmod>nil</factmod>
</gram>
<tfa>f</tfa>
<deepord>18</deepord>
<val_frame.rf>v#v41rpnA</val_frame.rf>
<children>
<LM id="t-mf930709-086-p2s4a2">
<nodetype>qcomplex</nodetype>
<is_generated>1</is_generated>
<t_lemma>#Cor</t_lemma>
<functor>ACT</functor>
<tfa>t</tfa>
<deepord>17</deepord>
<coref_gram.rf>
<LM>t-mf930709-086-p2s4a1</LM>
</coref_gram.rf>
</LM>
<LM id="t-mf930709-086-p2s4w23">
<a>
<lex.rf>a#a-mf930709-086-p2s4w23</lex.rf>
</a>
<nodetype>coap</nodetype>
<t_lemma>a</t_lemma>
<functor>CONJ</functor>
<deepord>20</deepord>
<children>
<LM id="t-mf930709-086-p2s4w22">
<a>
<lex.rf>a#a-mf930709-086-p2s4w22</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>klub</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.denot</sempos>
<gender>inan</gender>
<number>sg</number>
<typgroup>single</typgroup>
</gram>
<tfa>f</tfa>
<deepord>19</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s4a0</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
</LM>
<LM id="t-mf930709-086-p2s4w24">
<a>
<lex.rf>a#a-mf930709-086-p2s4w24</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>#PersPron</t_lemma>
<functor>PAT</functor>
<is_member>1</is_member>
<gram>
<sempos>n.pron.def.pers</sempos>
<gender>anim</gender>
<number>sg</number>
<person>3</person>
<politeness>basic</politeness>
</gram>
<tfa>f</tfa>
<deepord>21</deepord>
<coref_text>
<LM>
<target_node.rf>t-mf930709-086-p2s4w8</target_node.rf>
<type>SPEC</type>
</LM>
</coref_text>
<children>
<LM id="t-mf930709-086-p2s4w25">
<a>
<lex.rf>a#a-mf930709-086-p2s4w25</lex.rf>
</a>
<nodetype>complex</nodetype>
<t_lemma>osobně</t_lemma>
<functor>MANN</functor>
<proto_lemma>osobní</proto_lemma>
<gram>
<sempos>adj.denot</sempos>
<degcmp>pos</degcmp>
<negation>neg0</negation>
</gram>
<tfa>f</tfa>
<deepord>22</deepord>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</children>
</LM>
</trees>
</tdata>
